/**
 * SEED DE SERVIÇOS - SECRETARIA DE SEGURANÇA PÚBLICA
 * Total: 6 serviços
 */

import { ServiceDefinition } from './types';

export const publicSafetyServices: ServiceDefinition[] = [
  {
    name: 'Registro de Ocorrência',
    description: 'Registro de boletim de ocorrência',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'COM_DADOS',
    moduleType: 'REGISTRO_OCORRENCIA',
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Comprovante de Residência'],
    estimatedDays: 1,
    priority: 5,
    category: 'Ocorrências',
    icon: 'Siren',
    color: '#dc2626',
    formSchema: {
      type: 'object',
      citizenFields: [
        'nome',
        'cpf',
        'rg',
        'dataNascimento',
        'email',
        'telefone',
        'telefoneSecundario',
        'cep',
        'logradouro',
        'numero',
        'complemento',
        'bairro',
        'nomeMae',
        'estadoCivil',
        'profissao',
        'rendaFamiliar'
      ],
      properties: {
        // Campos do Cidadão
        nome: { type: 'string', title: 'Nome Completo', minLength: 3, maxLength: 200 },
        cpf: { type: 'string', title: 'CPF', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
        rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
        dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
        email: { type: 'string', format: 'email', title: 'E-mail' },
        telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
        telefoneSecundario: { type: 'string', title: 'Telefone Secundário (opcional)', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
        cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
        logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
        numero: { type: 'string', title: 'Número', maxLength: 10 },
        complemento: { type: 'string', title: 'Complemento (opcional)', maxLength: 100 },
        bairro: { type: 'string', title: 'Bairro/Comunidade', minLength: 2, maxLength: 100 },
        nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
        estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
        profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
        rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },

        // Campos Customizados do Serviço
        pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
        tipoOcorrencia: { type: 'string', title: 'Tipo de Ocorrência', enum: ['Furto', 'Roubo', 'Ameaça', 'Perturbação', 'Acidente', 'Outro'] },
        dataOcorrencia: { type: 'string', format: 'date', title: 'Data da Ocorrência' },
        horaOcorrencia: { type: 'string', title: 'Hora da Ocorrência', pattern: '^([01]\\d|2[0-3]):([0-5]\\d)$' },
        localOcorrencia: { type: 'string', title: 'Local da Ocorrência', maxLength: 300 },
        descricao: { type: 'string', title: 'Descrição dos Fatos', minLength: 50, maxLength: 2000, widget: 'textarea' },
        observacoes: { type: 'string', title: 'Observações', maxLength: 500, widget: 'textarea' }
      },
      required: [
        'nome', 'cpf', 'rg', 'dataNascimento', 'email', 'telefone',
        'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'estadoCivil', 'profissao', 'rendaFamiliar',
        'tipoOcorrencia', 'dataOcorrencia', 'horaOcorrencia', 'localOcorrencia', 'descricao'
      ]
    }
  },
  {
    name: 'Solicitação de Patrulhamento',
    description: 'Solicitação de ronda policial',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'COM_DADOS',
    moduleType: 'PATROLHAMENTO',
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF'],
    estimatedDays: 2,
    priority: 4,
    category: 'Patrulhamento',
    icon: 'Shield',
    color: '#b91c1c',
    formSchema: {
      type: 'object',
      citizenFields: [
        'nome',
        'cpf',
        'rg',
        'dataNascimento',
        'email',
        'telefone',
        'telefoneSecundario',
        'cep',
        'logradouro',
        'numero',
        'complemento',
        'bairro',
        'nomeMae',
        'estadoCivil',
        'profissao',
        'rendaFamiliar'
      ],
      properties: {
        // Campos do Cidadão
        nome: { type: 'string', title: 'Nome Completo', minLength: 3, maxLength: 200 },
        cpf: { type: 'string', title: 'CPF', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
        rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
        dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
        email: { type: 'string', format: 'email', title: 'E-mail' },
        telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
        telefoneSecundario: { type: 'string', title: 'Telefone Secundário (opcional)', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
        cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
        logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
        numero: { type: 'string', title: 'Número', maxLength: 10 },
        complemento: { type: 'string', title: 'Complemento (opcional)', maxLength: 100 },
        bairro: { type: 'string', title: 'Bairro/Comunidade', minLength: 2, maxLength: 100 },
        nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
        estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
        profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
        rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },

        // Campos Customizados do Serviço
        pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
        motivo: { type: 'string', title: 'Motivo do Patrulhamento', minLength: 20, maxLength: 1000, widget: 'textarea' },
        periodo: { type: 'string', title: 'Período Solicitado', maxLength: 200 },
        observacoes: { type: 'string', title: 'Observações', maxLength: 500, widget: 'textarea' }
      },
      required: [
        'nome', 'cpf', 'rg', 'dataNascimento', 'email', 'telefone',
        'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'estadoCivil', 'profissao', 'rendaFamiliar',
        'motivo', 'periodo'
      ]
    }
  },
  {
    name: 'Mapa de Criminalidade',
    description: 'Consulta de estatísticas de segurança',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: false,
    estimatedDays: null,
    priority: 1,
    category: 'Informativo',
    icon: 'ChartBar',
    color: '#94a3b8',
  },
  {
    name: 'Certidão de Antecedentes',
    description: 'Emissão de certidão de antecedentes criminais',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: true,
    requiredDocuments: ['CPF', 'RG'],
    estimatedDays: 3,
    priority: 2,
    category: 'Certidões',
    icon: 'FileText',
    color: '#dc2626',
  },
  {
    name: 'Declaração de Perda de Documentos',
    description: 'Emissão de declaração de perda',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: true,
    requiredDocuments: ['CPF', 'RG', 'BO'],
    estimatedDays: 3,
    priority: 2,
    category: 'Declarações',
    icon: 'FileCheck',
    color: '#dc2626',
  },
  {
    name: 'Autorização para Evento com Segurança',
    description: 'Autorização para eventos com policiamento',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'COM_DADOS',
    moduleType: 'AUTORIZACAO_EVENTO_SEG',
    requiresDocuments: true,
    requiredDocuments: ['Projeto', 'Seguro', 'Autorizações'],
    estimatedDays: 15,
    priority: 4,
    category: 'Autorizações',
    icon: 'Users',
    color: '#991b1b',
    formSchema: {
      type: 'object',
      citizenFields: [
        'nome',
        'cpf',
        'rg',
        'dataNascimento',
        'email',
        'telefone',
        'telefoneSecundario',
        'cep',
        'logradouro',
        'numero',
        'complemento',
        'bairro',
        'nomeMae',
        'estadoCivil',
        'profissao',
        'rendaFamiliar'
      ],
      properties: {
        // Campos do Cidadão
        nome: { type: 'string', title: 'Nome Completo', minLength: 3, maxLength: 200 },
        cpf: { type: 'string', title: 'CPF', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
        rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
        dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
        email: { type: 'string', format: 'email', title: 'E-mail' },
        telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
        telefoneSecundario: { type: 'string', title: 'Telefone Secundário (opcional)', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
        cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
        logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
        numero: { type: 'string', title: 'Número', maxLength: 10 },
        complemento: { type: 'string', title: 'Complemento (opcional)', maxLength: 100 },
        bairro: { type: 'string', title: 'Bairro/Comunidade', minLength: 2, maxLength: 100 },
        nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
        estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
        profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
        rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },

        // Campos Customizados do Serviço
        pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
        nomeEvento: { type: 'string', title: 'Nome do Evento', maxLength: 200 },
        publicoEstimado: { type: 'number', title: 'Público Estimado', minimum: 1 },
        dataEvento: { type: 'string', format: 'date', title: 'Data do Evento' },
        observacoes: { type: 'string', title: 'Observações', maxLength: 500, widget: 'textarea' }
      },
      required: [
        'nome', 'cpf', 'rg', 'dataNascimento', 'email', 'telefone',
        'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'estadoCivil', 'profissao', 'rendaFamiliar',
        'nomeEvento', 'publicoEstimado', 'dataEvento'
      ]
    }
  },
  {
      name: 'Atendimentos - Segurança Pública',
      description: 'Registro geral de atendimentos em segurança',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'COM_DADOS',
      moduleType: 'ATENDIMENTOS_SEGURANCA',
      requiresDocuments: false,
      estimatedDays: 1,
      priority: 3,
      category: 'Atendimento',
      icon: 'Shield',
      color: '#dc2626',
      formSchema: {
        type: 'object',
        citizenFields: [
          'nome',
          'cpf',
          'rg',
          'dataNascimento',
          'email',
          'telefone',
          'telefoneSecundario',
          'cep',
          'logradouro',
          'numero',
          'complemento',
          'bairro',
          'pontoReferencia',
          'nomeMae',
          'estadoCivil',
          'profissao',
          'rendaFamiliar'
        ],
        properties: {
          nome: { type: 'string', title: 'Nome Completo', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          tipoAtendimento: { type: 'string', title: 'Tipo de Atendimento', enum: ['Consulta', 'Denúncia', 'Solicitação', 'Orientação', 'Outro'] },
          assunto: { type: 'string', title: 'Assunto', maxLength: 200 },
          descricao: { type: 'string', title: 'Descrição do Atendimento', minLength: 20, maxLength: 1000 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'tipoAtendimento', 'assunto', 'descricao'],
      },
    },
  {
      name: 'Registro de Ocorrência (BO)',
      description: 'Registro de boletim de ocorrência',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'COM_DADOS',
      moduleType: 'REGISTRO_OCORRENCIA',
      requiresDocuments: true,
      requiredDocuments: ['RG', 'CPF'],
      estimatedDays: 1,
      priority: 5,
      category: 'Ocorrência',
      icon: 'FileWarning',
      color: '#b91c1c',
      formSchema: {
        type: 'object',
        properties: {
          nome: { type: 'string', title: 'Nome Completo', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          tipoOcorrencia: { type: 'string', title: 'Tipo de Ocorrência', enum: ['Furto', 'Roubo', 'Lesão Corporal', 'Ameaça', 'Dano ao Patrimônio', 'Perturbação do Sossego', 'Acidente de Trânsito', 'Desaparecimento', 'Outro'] },
          dataOcorrencia: { type: 'string', format: 'date-time', title: 'Data e Hora da Ocorrência' },
          localOcorrencia: { type: 'string', title: 'Local da Ocorrência', maxLength: 300 },
          relatoOcorrencia: { type: 'string', title: 'Relato Detalhado da Ocorrência', minLength: 50, maxLength: 2000 },
          testemunhas: { type: 'string', title: 'Testemunhas (nomes e contatos)', maxLength: 500 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'tipoOcorrencia', 'dataOcorrencia', 'localOcorrencia', 'relatoOcorrencia'],
      },
    },
  {
      name: 'Solicitação de Ronda Policial',
      description: 'Solicitação de patrulhamento em área específica',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'COM_DADOS',
      moduleType: 'SOLICITACAO_RONDA',
      requiresDocuments: false,
      estimatedDays: 2,
      priority: 4,
      category: 'Ronda',
      icon: 'Car',
      color: '#991b1b',
      formSchema: {
        type: 'object',
        citizenFields: [
          'nome',
          'cpf',
          'rg',
          'dataNascimento',
          'email',
          'telefone',
          'telefoneSecundario',
          'cep',
          'logradouro',
          'numero',
          'complemento',
          'bairro',
          'pontoReferencia',
          'nomeMae',
          'estadoCivil',
          'profissao',
          'rendaFamiliar'
        ],
        properties: {
          nome: { type: 'string', title: 'Nome Completo', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          enderecoRonda: { type: 'string', title: 'Endereço da Área para Ronda', maxLength: 300 },
          motivoSolicitacao: { type: 'string', title: 'Motivo da Solicitação', enum: ['Aumento de Criminalidade', 'Ponto de Drogas', 'Perturbação do Sossego', 'Vandalismo', 'Outro'] },
          periodoPreferencial: { type: 'string', title: 'Período Preferencial', enum: ['Manhã', 'Tarde', 'Noite', 'Madrugada', 'Indiferente'] },
          justificativa: { type: 'string', title: 'Justificativa Detalhada', minLength: 30, maxLength: 1000 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'enderecoRonda', 'motivoSolicitacao', 'justificativa'],
      },
    },
  {
      name: 'Solicitação de Câmera de Segurança',
      description: 'Solicitação de instalação de câmera de monitoramento',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'COM_DADOS',
      moduleType: 'SOLICITACAO_CAMERA_SEGURANCA',
      requiresDocuments: true,
      requiredDocuments: ['Justificativa', 'Abaixo-assinado', 'Fotos do Local'],
      estimatedDays: 30,
      priority: 4,
      category: 'Câmeras',
      icon: 'Camera',
      color: '#7f1d1d',
      formSchema: {
        type: 'object',
        citizenFields: [
          'nome',
          'cpf',
          'rg',
          'dataNascimento',
          'email',
          'telefone',
          'telefoneSecundario',
          'cep',
          'logradouro',
          'numero',
          'complemento',
          'bairro',
          'pontoReferencia',
          'nomeMae',
          'estadoCivil',
          'profissao',
          'rendaFamiliar'
        ],
        properties: {
          nome: { type: 'string', title: 'Nome Completo do Solicitante', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          localInstalacao: { type: 'string', title: 'Local Sugerido para Instalação', maxLength: 300 },
          motivoInstalacao: { type: 'string', title: 'Motivo da Solicitação', enum: ['Furtos Frequentes', 'Vandalismo', 'Tráfico de Drogas', 'Proteção de Equipamento Público', 'Outro'] },
          numeroAssinaturas: { type: 'integer', title: 'Número de Assinaturas Coletadas', minimum: 1 },
          justificativa: { type: 'string', title: 'Justificativa Detalhada', minLength: 50, maxLength: 1000 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'localInstalacao', 'motivoInstalacao', 'numeroAssinaturas', 'justificativa'],
      },
    },
  {
      name: 'Denúncia Anônima (Disque Denúncia)',
      description: 'Registro de denúncias anônimas',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'COM_DADOS',
      moduleType: 'DENUNCIA_ANONIMA',
      requiresDocuments: false,
      estimatedDays: 1,
      priority: 5,
      category: 'Denúncia',
      icon: 'AlertCircle',
      color: '#ef4444',
      formSchema: {
        type: 'object',
        citizenFields: [
          'nome',
          'cpf',
          'rg',
          'dataNascimento',
          'email',
          'telefone',
          'telefoneSecundario',
          'cep',
          'logradouro',
          'numero',
          'complemento',
          'bairro',
          'pontoReferencia',
          'nomeMae',
          'estadoCivil',
          'profissao',
          'rendaFamiliar'
        ],
        properties: {
          nome: { type: 'string', title: 'Nome Completo (opcional para denúncia anônima)', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF (opcional)', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          tipoDenuncia: { type: 'string', title: 'Tipo de Denúncia', enum: ['Tráfico de Drogas', 'Roubo/Furto', 'Violência Doméstica', 'Corrupção', 'Maus-tratos', 'Porte Ilegal de Arma', 'Outro'] },
          localDenuncia: { type: 'string', title: 'Local da Denúncia', maxLength: 300 },
          relatoDenuncia: { type: 'string', title: 'Relato Detalhado da Denúncia', minLength: 30, maxLength: 2000 },
          denunciaAnonima: { type: 'boolean', title: 'Deseja fazer a denúncia de forma anônima?' },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'tipoDenuncia', 'localDenuncia', 'relatoDenuncia'],
      },
    },
  {
      name: 'Cadastro de Ponto Crítico',
      description: 'Registro de áreas de risco e vulnerabilidade',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'COM_DADOS',
      moduleType: 'CADASTRO_PONTO_CRITICO',
      requiresDocuments: false,
      estimatedDays: 5,
      priority: 4,
      category: 'Mapeamento',
      icon: 'MapPin',
      color: '#f87171',
      formSchema: {
        type: 'object',
        citizenFields: [
          'nome',
          'cpf',
          'rg',
          'dataNascimento',
          'email',
          'telefone',
          'telefoneSecundario',
          'cep',
          'logradouro',
          'numero',
          'complemento',
          'bairro',
          'pontoReferencia',
          'nomeMae',
          'estadoCivil',
          'profissao',
          'rendaFamiliar'
        ],
        properties: {
          nome: { type: 'string', title: 'Nome Completo do Informante', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          localPontoCritico: { type: 'string', title: 'Local do Ponto Crítico', maxLength: 300 },
          tipoPontoCritico: { type: 'string', title: 'Tipo de Ponto Crítico', enum: ['Alta Criminalidade', 'Tráfico de Drogas', 'Ponto de Prostituição', 'Vandalismo', 'Aglomeração de Pessoas', 'Outro'] },
          descricaoSituacao: { type: 'string', title: 'Descrição da Situação', minLength: 30, maxLength: 1000 },
          nivelGravidade: { type: 'string', title: 'Nível de Gravidade', enum: ['Baixo', 'Médio', 'Alto', 'Crítico'] },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'localPontoCritico', 'tipoPontoCritico', 'descricaoSituacao', 'nivelGravidade'],
      },
    },
  {
      name: 'Alerta de Segurança',
      description: 'Registro de avisos e alertas de segurança',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'COM_DADOS',
      moduleType: 'ALERTA_SEGURANCA',
      requiresDocuments: false,
      estimatedDays: 1,
      priority: 5,
      category: 'Alerta',
      icon: 'Bell',
      color: '#fca5a5',
      formSchema: {
        type: 'object',
        citizenFields: [
          'nome',
          'cpf',
          'rg',
          'dataNascimento',
          'email',
          'telefone',
          'telefoneSecundario',
          'cep',
          'logradouro',
          'numero',
          'complemento',
          'bairro',
          'pontoReferencia',
          'nomeMae',
          'estadoCivil',
          'profissao',
          'rendaFamiliar'
        ],
        properties: {
          nome: { type: 'string', title: 'Nome Completo', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          tipoAlerta: { type: 'string', title: 'Tipo de Alerta', enum: ['Suspeito Circulando', 'Veículo Suspeito', 'Situação de Risco', 'Evento de Segurança', 'Outro'] },
          localAlerta: { type: 'string', title: 'Local do Alerta', maxLength: 300 },
          descricaoAlerta: { type: 'string', title: 'Descrição do Alerta', minLength: 20, maxLength: 1000 },
          urgencia: { type: 'string', title: 'Nível de Urgência', enum: ['Baixa', 'Média', 'Alta', 'Emergencial'] },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'tipoAlerta', 'localAlerta', 'descricaoAlerta', 'urgencia'],
      },
    },
  {
      name: 'Registro de Patrulha',
      description: 'Registro de patrulhamento realizado',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'COM_DADOS',
      moduleType: 'REGISTRO_PATRULHA',
      requiresDocuments: false,
      estimatedDays: 1,
      priority: 3,
      category: 'Patrulha',
      icon: 'Route',
      color: '#dc2626',
      formSchema: {
        type: 'object',
        citizenFields: [
          'nome',
          'cpf',
          'rg',
          'dataNascimento',
          'email',
          'telefone',
          'telefoneSecundario',
          'cep',
          'logradouro',
          'numero',
          'complemento',
          'bairro',
          'pontoReferencia',
          'nomeMae',
          'estadoCivil',
          'profissao',
          'rendaFamiliar'
        ],
        properties: {
          nome: { type: 'string', title: 'Nome Completo do Agente', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF do Agente', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          dataPatrulha: { type: 'string', format: 'date-time', title: 'Data e Hora da Patrulha' },
          tipoPatrulha: { type: 'string', title: 'Tipo de Patrulha', enum: ['Ronda Preventiva', 'Ronda Escolar', 'Operação Específica', 'Atendimento a Ocorrência', 'Patrulha Comunitária'] },
          localPatrulhado: { type: 'string', title: 'Local Patrulhado', maxLength: 300 },
          viaturaCodigo: { type: 'string', title: 'Código da Viatura', maxLength: 50 },
          relato: { type: 'string', title: 'Relato da Patrulha', minLength: 20, maxLength: 1000 },
          ocorrenciasRegistradas: { type: 'string', title: 'Ocorrências Registradas', maxLength: 500 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'dataPatrulha', 'tipoPatrulha', 'localPatrulhado', 'viaturaCodigo', 'relato'],
      },
    },
  {
      name: 'Gestão da Guarda Municipal',
      description: 'Administração de escala de serviço e viaturas',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'COM_DADOS',
      moduleType: 'GESTAO_GUARDA_MUNICIPAL',
      requiresDocuments: false,
      estimatedDays: null,
      priority: 2,
      category: 'Gestão Interna',
      icon: 'Users',
      color: '#64748b',
      formSchema: {
        type: 'object',
        citizenFields: [
          'nome',
          'cpf',
          'rg',
          'dataNascimento',
          'email',
          'telefone',
          'telefoneSecundario',
          'cep',
          'logradouro',
          'numero',
          'complemento',
          'bairro',
          'pontoReferencia',
          'nomeMae',
          'estadoCivil',
          'profissao',
          'rendaFamiliar'
        ],
        properties: {
          nome: { type: 'string', title: 'Nome Completo do Responsável', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          tipoGestao: { type: 'string', title: 'Tipo de Gestão', enum: ['Cadastro de Agente', 'Escala de Serviço', 'Gestão de Viatura', 'Controle de Equipamento', 'Outro'] },
          descricao: { type: 'string', title: 'Descrição', minLength: 20, maxLength: 1000 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'tipoGestao', 'descricao'],
      },
    },
  {
      name: 'Gestão de Vigilância (Central de Operações)',
      description: 'Administração de câmeras e central de monitoramento',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'COM_DADOS',
      moduleType: 'GESTAO_VIGILANCIA',
      requiresDocuments: false,
      estimatedDays: null,
      priority: 2,
      category: 'Gestão Interna',
      icon: 'Monitor',
      color: '#64748b',
      formSchema: {
        type: 'object',
        citizenFields: [
          'nome',
          'cpf',
          'rg',
          'dataNascimento',
          'email',
          'telefone',
          'telefoneSecundario',
          'cep',
          'logradouro',
          'numero',
          'complemento',
          'bairro',
          'pontoReferencia',
          'nomeMae',
          'estadoCivil',
          'profissao',
          'rendaFamiliar'
        ],
        properties: {
          nome: { type: 'string', title: 'Nome Completo do Operador', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          tipoOperacao: { type: 'string', title: 'Tipo de Operação', enum: ['Cadastro de Câmera', 'Manutenção de Câmera', 'Análise de Imagens', 'Registro de Ocorrência Visual', 'Outro'] },
          descricaoOperacao: { type: 'string', title: 'Descrição da Operação', minLength: 20, maxLength: 1000 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'tipoOperacao', 'descricaoOperacao'],
      },
    },
  {
      name: 'Estatísticas de Segurança',
      description: 'Consulta a análises e estatísticas regionais',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: false,
      estimatedDays: null,
      priority: 1,
      category: 'Informativo',
      icon: 'BarChart',
      color: '#94a3b8',
    },
  {
      name: 'Certidão de Antecedentes Criminais',
      description: 'Emissão de certidão de antecedentes da guarda municipal',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: true,
      requiredDocuments: ['CPF', 'RG', 'Comprovante de Endereço'],
      estimatedDays: 5,
      priority: 3,
      category: 'Certidões',
      icon: 'FileText',
      color: '#dc2626',
    },
  {
      name: 'Certidão de Ocorrência Policial',
      description: 'Emissão de certidão de registro de ocorrência',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: true,
      requiredDocuments: ['CPF', 'RG', 'Número da Ocorrência'],
      estimatedDays: 3,
      priority: 3,
      category: 'Certidões',
      icon: 'FileText',
      color: '#dc2626',
    },
  {
      name: 'Declaração de Comparecimento a Delegacia',
      description: 'Emissão de declaração de comparecimento para registro',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: true,
      requiredDocuments: ['CPF', 'RG'],
      estimatedDays: 1,
      priority: 2,
      category: 'Declarações',
      icon: 'FileCheck',
      color: '#dc2626',
    },
  {
      name: 'Atestado de Bons Antecedentes',
      description: 'Emissão de atestado de bons antecedentes municipais',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: true,
      requiredDocuments: ['CPF', 'RG', 'Comprovante de Residência'],
      estimatedDays: 7,
      priority: 3,
      category: 'Atestados',
      icon: 'CheckCircle',
      color: '#dc2626',
    },
  {
      name: 'Laudo de Vistoria de Segurança',
      description: 'Emissão de laudo de vistoria de segurança de estabelecimento',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: true,
      requiredDocuments: ['CPF', 'RG', 'Alvará de Funcionamento', 'CNPJ'],
      estimatedDays: 15,
      priority: 3,
      category: 'Laudos',
      icon: 'ClipboardCheck',
      color: '#dc2626',
    },
  {
      name: 'Autorização para Evento com Aglomeração',
      description: 'Emissão de autorização de segurança para eventos',
      departmentCode: 'SEGURANCA_PUBLICA',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: true,
      requiredDocuments: ['CPF', 'RG', 'Projeto do Evento', 'Plano de Segurança'],
      estimatedDays: 20,
      priority: 4,
      category: 'Autorizações',
      icon: 'Shield',
      color: '#dc2626',
    }
];
