/**
 * SEED DE SERVIÇOS - SECRETARIA DE OBRAS PÚBLICAS
 * Total: 8 serviços
 */

import { ServiceDefinition } from './types';

export const publicWorksServices: ServiceDefinition[] = [
  {
    name: 'Aprovação de Projeto de Construção',
    description: 'Aprovação de projetos de construção',
    departmentCode: 'OBRAS_PUBLICAS',
    serviceType: 'COM_DADOS',
    moduleType: 'APROVACAO_PROJETO',
    requiresDocuments: true,
    requiredDocuments: ['Projeto Arquitetônico', 'ART', 'Matrícula'],
    estimatedDays: 45,
    priority: 5,
    category: 'Aprovação',
    icon: 'Blueprint',
    color: '#7c3aed',
    formSchema: {
      citizenFields: [
        'citizen_name',
        'citizen_cpf',
        'citizen_rg',
        'citizen_birthDate',
        'citizen_email',
        'citizen_phone',
        'citizen_phoneSecondary',
        'citizen_zipCode',
        'citizen_address',
        'citizen_addressNumber',
        'citizen_addressComplement',
        'citizen_neighborhood',
        'citizen_motherName',
        'citizen_maritalStatus',
        'citizen_occupation',
        'citizen_familyIncome'
      ],
      fields: [
        {
          id: 'pontoReferencia',
          label: 'Ponto de Referência',
          type: 'text',
          maxLength: 200,
          required: false
        },
        {
          id: 'areaConstruir',
          label: 'Área a Construir (m²)',
          type: 'number',
          minimum: 1,
          required: true
        },
        {
          id: 'tipoObra',
          label: 'Tipo de Obra',
          type: 'select',
          options: ['Residencial', 'Comercial', 'Industrial', 'Misto'],
          required: true
        },
        {
          id: 'pavimentos',
          label: 'Número de Pavimentos',
          type: 'number',
          minimum: 1,
          required: true
        },
        {
          id: 'observacoes',
          label: 'Observações',
          type: 'textarea',
          maxLength: 500,
          required: false
        }
      ]
    }
  },
  {
    name: 'Alvará de Construção',
    description: 'Emissão de alvará de construção',
    departmentCode: 'OBRAS_PUBLICAS',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: true,
    requiredDocuments: ['Projeto Aprovado', 'ART', 'Taxas Pagas'],
    estimatedDays: 5,
    priority: 3,
    category: 'Alvarás',
    icon: 'FileCheck',
    color: '#7c3aed',
  },
  {
    name: 'Habite-se',
    description: 'Emissão de habite-se',
    departmentCode: 'OBRAS_PUBLICAS',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: true,
    requiredDocuments: ['Vistoria', 'Projeto', 'Certidões'],
    estimatedDays: 15,
    priority: 4,
    category: 'Conclusão',
    icon: 'Home',
    color: '#7c3aed',
  },
  {
    name: 'Certidão de Numeração Predial',
    description: 'Emissão de certidão de numeração',
    departmentCode: 'OBRAS_PUBLICAS',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: true,
    requiredDocuments: ['CPF', 'RG', 'Endereço'],
    estimatedDays: 7,
    priority: 2,
    category: 'Certidões',
    icon: 'FileText',
    color: '#7c3aed',
  },
  {
    name: 'Laudo de Vistoria Técnica',
    description: 'Emissão de laudo de vistoria',
    departmentCode: 'OBRAS_PUBLICAS',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: true,
    requiredDocuments: ['CPF', 'RG', 'Endereço do Imóvel'],
    estimatedDays: 20,
    priority: 4,
    category: 'Laudos',
    icon: 'ClipboardCheck',
    color: '#7c3aed',
  },
  {
    name: 'Autorização para Demolição',
    description: 'Autorização para demolição de imóvel',
    departmentCode: 'OBRAS_PUBLICAS',
    serviceType: 'COM_DADOS',
    moduleType: 'AUTORIZACAO_DEMOLICAO',
    requiresDocuments: true,
    requiredDocuments: ['Projeto', 'Laudo Estrutural', 'Anuência Vizinhos'],
    estimatedDays: 30,
    priority: 5,
    category: 'Autorizações',
    icon: 'Hammer',
    color: '#6d28d9',
    formSchema: {
      citizenFields: [
        'citizen_name',
        'citizen_cpf',
        'citizen_rg',
        'citizen_birthDate',
        'citizen_email',
        'citizen_phone',
        'citizen_phoneSecondary',
        'citizen_zipCode',
        'citizen_address',
        'citizen_addressNumber',
        'citizen_addressComplement',
        'citizen_neighborhood',
        'citizen_motherName',
        'citizen_maritalStatus',
        'citizen_occupation',
        'citizen_familyIncome'
      ],
      fields: [
        {
          id: 'pontoReferencia',
          label: 'Ponto de Referência',
          type: 'text',
          maxLength: 200,
          required: false
        },
        {
          id: 'motivoDemolicao',
          label: 'Motivo da Demolição',
          type: 'textarea',
          minLength: 20,
          maxLength: 1000,
          required: true
        },
        {
          id: 'areaDemolir',
          label: 'Área a Demolir (m²)',
          type: 'number',
          minimum: 1,
          required: true
        },
        {
          id: 'observacoes',
          label: 'Observações',
          type: 'textarea',
          maxLength: 500,
          required: false
        }
      ]
    }
  },
  {
    name: 'Plano Diretor',
    description: 'Consulta ao plano diretor municipal',
    departmentCode: 'OBRAS_PUBLICAS',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: false,
    estimatedDays: null,
    priority: 1,
    category: 'Informativo',
    icon: 'Map',
    color: '#94a3b8',
  },
  {
    name: 'Gestão de Obras Públicas',
    description: 'Controle interno de obras em andamento',
    departmentCode: 'OBRAS_PUBLICAS',
    serviceType: 'COM_DADOS',
    moduleType: 'GESTAO_OBRAS',
    requiresDocuments: false,
    estimatedDays: null,
    priority: 3,
    category: 'Gestão Interna',
    icon: 'Wrench',
    color: '#6b7280',
    formSchema: {
      citizenFields: [],
      fields: [
        {
          id: 'nomeObra',
          label: 'Nome da Obra',
          type: 'text',
          minLength: 3,
          maxLength: 200,
          required: true
        },
        {
          id: 'localizacao',
          label: 'Localização',
          type: 'text',
          maxLength: 300,
          required: true
        },
        {
          id: 'orcamento',
          label: 'Orçamento',
          type: 'number',
          minimum: 0,
          required: true
        },
        {
          id: 'prazo',
          label: 'Prazo (dias)',
          type: 'number',
          minimum: 1,
          required: true
        },
        {
          id: 'status',
          label: 'Status',
          type: 'select',
          options: ['Planejamento', 'Em Execução', 'Paralisada', 'Concluída'],
          required: true
        },
        {
          id: 'observacoes',
          label: 'Observações',
          type: 'textarea',
          maxLength: 500,
          required: false
        }
      ]
    }
  },
  {
      name: 'Atendimentos - Obras Públicas',
      description: 'Registro geral de atendimentos na área de obras',
      departmentCode: 'OBRAS_PUBLICAS',
      serviceType: 'COM_DADOS',
      moduleType: 'ATENDIMENTOS_OBRAS',
      requiresDocuments: false,
      estimatedDays: 1,
      priority: 3,
      category: 'Atendimento',
      icon: 'HardHat',
      color: '#f59e0b',
      formSchema: {
        type: 'object',
        properties: {
          nome: { type: 'string', title: 'Nome Completo', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$' },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$' },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$' },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          motivoAtendimento: { type: 'string', title: 'Motivo do Atendimento', enum: ['Solicitação de Reparo', 'Vistoria Técnica', 'Informações sobre Obras', 'Reclamação', 'Outro'] },
          descricaoAtendimento: { type: 'string', title: 'Descrição do Atendimento', minLength: 10, maxLength: 1000 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 }
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'motivoAtendimento', 'descricaoAtendimento']
      }
    },
  {
      name: 'Solicitação de Reparo de Via',
      description: 'Solicitação de tapa-buraco e pavimentação',
      departmentCode: 'OBRAS_PUBLICAS',
      serviceType: 'COM_DADOS',
      moduleType: 'SOLICITACAO_REPARO_VIA',
      requiresDocuments: false,
      estimatedDays: 15,
      priority: 4,
      category: 'Manutenção',
      icon: 'Construction',
      color: '#ea580c',
      formSchema: {
        type: 'object',
        citizenFields: [
          'nome',
          'cpf',
          'rg',
          'dataNascimento',
          'email',
          'telefone',
          'telefoneSecundario',
          'cep',
          'logradouro',
          'numero',
          'complemento',
          'bairro',
          'pontoReferencia',
          'nomeMae',
          'estadoCivil',
          'profissao',
          'rendaFamiliar'
        ],
        properties: {
          nome: { type: 'string', title: 'Nome Completo', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$' },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$' },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$' },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          enderecoProblema: { type: 'string', title: 'Endereço do Problema', minLength: 10, maxLength: 300 },
          tipoProblema: { type: 'string', title: 'Tipo de Problema', enum: ['Buraco', 'Afundamento', 'Rachadura', 'Pavimentação Danificada', 'Valeta', 'Outro'] },
          descricaoProblema: { type: 'string', title: 'Descrição do Problema', minLength: 20, maxLength: 1000 },
          tamanhoEstimado: { type: 'string', title: 'Tamanho Estimado', enum: ['Pequeno (até 1m)', 'Médio (1-3m)', 'Grande (mais de 3m)'] },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 }
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'enderecoProblema', 'tipoProblema', 'descricaoProblema']
      }
    },
  {
      name: 'Vistoria Técnica de Obras',
      description: 'Solicitação de inspeção técnica em obras',
      departmentCode: 'OBRAS_PUBLICAS',
      serviceType: 'COM_DADOS',
      moduleType: 'VISTORIA_TECNICA_OBRAS',
      requiresDocuments: true,
      requiredDocuments: ['Projeto', 'Documentação do Imóvel'],
      estimatedDays: 10,
      priority: 3,
      category: 'Vistoria',
      icon: 'ClipboardCheck',
      color: '#f97316',
      formSchema: {
        type: 'object',
        citizenFields: [
          'nome',
          'cpf',
          'rg',
          'dataNascimento',
          'email',
          'telefone',
          'telefoneSecundario',
          'cep',
          'logradouro',
          'numero',
          'complemento',
          'bairro',
          'pontoReferencia',
          'nomeMae',
          'estadoCivil',
          'profissao',
          'rendaFamiliar'
        ],
        properties: {
          nome: { type: 'string', title: 'Nome Completo do Solicitante', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF do Solicitante', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG do Solicitante', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$' },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$' },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$' },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          enderecoObra: { type: 'string', title: 'Endereço da Obra', minLength: 10, maxLength: 300 },
          tipoVistoria: { type: 'string', title: 'Tipo de Vistoria', enum: ['Estrutural', 'Elétrica', 'Hidráulica', 'Pavimentação', 'Geral', 'Outro'] },
          motivoVistoria: { type: 'string', title: 'Motivo da Vistoria', minLength: 30, maxLength: 1000 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 }
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'enderecoObra', 'tipoVistoria', 'motivoVistoria']
      }
    },
  {
      name: 'Cadastro de Obra Pública',
      description: 'Registro de obras públicas no município',
      departmentCode: 'OBRAS_PUBLICAS',
      serviceType: 'COM_DADOS',
      moduleType: 'CADASTRO_OBRA_PUBLICA',
      requiresDocuments: true,
      requiredDocuments: ['Projeto', 'Orçamento', 'Cronograma'],
      estimatedDays: 7,
      priority: 3,
      category: 'Cadastro',
      icon: 'Building2',
      color: '#fb923c',
      formSchema: {
        type: 'object',
        citizenFields: [
          'nome',
          'cpf',
          'rg',
          'dataNascimento',
          'email',
          'telefone',
          'telefoneSecundario',
          'cep',
          'logradouro',
          'numero',
          'complemento',
          'bairro',
          'pontoReferencia',
          'nomeMae',
          'estadoCivil',
          'profissao',
          'rendaFamiliar'
        ],
        properties: {
          nome: { type: 'string', title: 'Nome Completo do Responsável', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF do Responsável', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG do Responsável', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$' },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$' },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$' },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          nomeObra: { type: 'string', title: 'Nome da Obra', minLength: 3, maxLength: 200 },
          tipoObra: { type: 'string', title: 'Tipo de Obra', enum: ['Pavimentação', 'Edificação', 'Saneamento', 'Drenagem', 'Ponte/Viaduto', 'Praça/Parque', 'Outro'] },
          enderecoObra: { type: 'string', title: 'Endereço da Obra', minLength: 10, maxLength: 300 },
          descricaoObra: { type: 'string', title: 'Descrição da Obra', minLength: 50, maxLength: 1000 },
          dataInicio: { type: 'string', format: 'date', title: 'Data de Início Prevista' },
          dataTermino: { type: 'string', format: 'date', title: 'Data de Término Prevista' },
          valorOrcado: { type: 'number', title: 'Valor Orçado (R$)', minimum: 0 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 }
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'nomeObra', 'tipoObra', 'enderecoObra', 'descricaoObra', 'dataInicio', 'dataTermino']
      }
    },
  {
      name: 'Inspeção de Obra',
      description: 'Inspeção de andamento de obras públicas',
      departmentCode: 'OBRAS_PUBLICAS',
      serviceType: 'COM_DADOS',
      moduleType: 'INSPECAO_OBRA',
      requiresDocuments: false,
      estimatedDays: 5,
      priority: 3,
      category: 'Inspeção',
      icon: 'Eye',
      color: '#fdba74',
      formSchema: {
        type: 'object',
        citizenFields: [
          'nome',
          'cpf',
          'rg',
          'dataNascimento',
          'email',
          'telefone',
          'telefoneSecundario',
          'cep',
          'logradouro',
          'numero',
          'complemento',
          'bairro',
          'pontoReferencia',
          'nomeMae',
          'estadoCivil',
          'profissao',
          'rendaFamiliar'
        ],
        properties: {
          nome: { type: 'string', title: 'Nome Completo do Fiscal', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF do Fiscal', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG do Fiscal', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$' },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$' },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$' },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          nomeObra: { type: 'string', title: 'Nome da Obra Inspecionada', maxLength: 200 },
          dataInspecao: { type: 'string', format: 'date', title: 'Data da Inspeção' },
          percentualConcluido: { type: 'integer', title: 'Percentual Concluído (%)', minimum: 0, maximum: 100 },
          situacaoObra: { type: 'string', title: 'Situação da Obra', enum: ['No Prazo', 'Atrasada', 'Paralisada', 'Concluída'] },
          relatoInspecao: { type: 'string', title: 'Relato da Inspeção', minLength: 30, maxLength: 1000 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 }
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'nomeObra', 'dataInspecao', 'situacaoObra', 'relatoInspecao']
      }
    },
  {
      name: 'Acompanhamento de Obras',
      description: 'Consulta ao progresso de obras públicas',
      departmentCode: 'OBRAS_PUBLICAS',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: false,
      estimatedDays: null,
      priority: 1,
      category: 'Informativo',
      icon: 'Info',
      color: '#94a3b8',
    },
  {
      name: 'Mapa de Obras',
      description: 'Visualização geoespacial de obras no município',
      departmentCode: 'OBRAS_PUBLICAS',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: false,
      estimatedDays: null,
      priority: 1,
      category: 'Informativo',
      icon: 'Map',
      color: '#94a3b8',
    },
  {name: 'Certidão de Obra Pública', description: 'Certidão oficial de obra pública realizada', departmentCode: 'OBRAS_PUBLICAS', serviceType: 'SEM_DADOS', moduleType: null, requiresDocuments: true, requiredDocuments: ['CNPJ/CPF'], estimatedDays: 7, priority: 3, category: 'Certidões', icon: 'FileText', color: '#f59e0b'},
  {name: 'Declaração de Manutenção Realizada', description: 'Declaração de manutenção em via pública', departmentCode: 'OBRAS_PUBLICAS', serviceType: 'SEM_DADOS', moduleType: null, requiresDocuments: true, requiredDocuments: ['CPF', 'Comprovante de Endereço'], estimatedDays: 5, priority: 3, category: 'Certidões', icon: 'FileCheck', color: '#10b981'},
  {name: 'Atestado de Vistoria de Obras', description: 'Atestado de vistoria técnica realizada', departmentCode: 'OBRAS_PUBLICAS', serviceType: 'SEM_DADOS', moduleType: null, requiresDocuments: true, requiredDocuments: ['CPF', 'Documentos do Imóvel'], estimatedDays: 7, priority: 4, category: 'Certidões', icon: 'ClipboardCheck', color: '#3b82f6'},
  {name: 'Guia de Ocupação de Via', description: 'Autorização para ocupação temporária de via', departmentCode: 'OBRAS_PUBLICAS', serviceType: 'SEM_DADOS', moduleType: null, requiresDocuments: true, requiredDocuments: ['CNPJ/CPF', 'Projeto'], estimatedDays: 10, priority: 4, category: 'Documentos', icon: 'Construction', color: '#ef4444'},
  {name: 'Consulta de Status de Obra', description: 'Consulta do andamento de obras públicas', departmentCode: 'OBRAS_PUBLICAS', serviceType: 'SEM_DADOS', moduleType: null, requiresDocuments: true, requiredDocuments: ['CPF'], estimatedDays: 1, priority: 2, category: 'Consultas', icon: 'Search', color: '#8b5cf6'},
  {name: 'Segunda Via de Documentos de Obras', description: 'Reemissão de documentos relacionados a obras', departmentCode: 'OBRAS_PUBLICAS', serviceType: 'SEM_DADOS', moduleType: null, requiresDocuments: true, requiredDocuments: ['CPF', 'Protocolo Original'], estimatedDays: 5, priority: 2, category: 'Documentos', icon: 'Copy', color: '#6b7280'}
];
