/**
 * SEED DE SERVIÇOS - SECRETARIA DE ESPORTES
 * Total: 9 serviços
 */

import { ServiceDefinition } from './types';

export const sportsServices: ServiceDefinition[] = [
  {
    name: 'Inscrição em Modalidades Esportivas',
    description: 'Inscrição em aulas de esporte',
    departmentCode: 'ESPORTES',
    serviceType: 'COM_DADOS',
    moduleType: 'INSCRICAO_MODALIDADE',
    requiresDocuments: true,
    requiredDocuments: ['Atestado Médico', 'RG', 'Comprovante de Residência'],
    estimatedDays: 5,
    priority: 3,
    category: 'Inscrições',
    icon: 'Trophy',
    color: '#f59e0b',
    formSchema: {
      citizenFields: [
        'citizen_name',
        'citizen_cpf',
        'citizen_rg',
        'citizen_birthdate',
        'citizen_email',
        'citizen_phone',
        'citizen_phonesecondary',
        'citizen_zipcode',
        'citizen_address',
        'citizen_addressnumber',
        'citizen_addresscomplement',
        'citizen_neighborhood',
        'citizen_mothername',
        'citizen_maritalstatus',
        'citizen_occupation',
        'citizen_familyincome'
      ],
      fields: [
        {
          id: 'pontoReferencia',
          label: 'Ponto de Referência',
          type: 'text',
          maxLength: 200,
          required: false
        },
        {
          id: 'modalidade',
          label: 'Modalidade Esportiva',
          type: 'select',
          options: ['Futebol', 'Vôlei', 'Basquete', 'Natação', 'Judô', 'Karatê', 'Atletismo', 'Outro'],
          required: true
        },
        {
          id: 'nivel',
          label: 'Nível',
          type: 'select',
          options: ['Iniciante', 'Intermediário', 'Avançado'],
          required: true
        },
        {
          id: 'turnoPreferencial',
          label: 'Turno Preferencial',
          type: 'select',
          options: ['Manhã', 'Tarde', 'Noite', 'Qualquer'],
          required: true
        },
        {
          id: 'observacoes',
          label: 'Observações',
          type: 'textarea',
          maxLength: 500,
          required: false
        }
      ]
    }
  },
  {
    name: 'Aluguel de Quadras',
    description: 'Reserva de quadras esportivas',
    departmentCode: 'ESPORTES',
    serviceType: 'COM_DADOS',
    moduleType: 'ALUGUEL_QUADRA',
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF'],
    estimatedDays: 1,
    priority: 3,
    category: 'Reservas',
    icon: 'CalendarCheck',
    color: '#d97706',
    formSchema: {
      citizenFields: [
        'citizen_name',
        'citizen_cpf',
        'citizen_rg',
        'citizen_birthdate',
        'citizen_email',
        'citizen_phone',
        'citizen_phonesecondary',
        'citizen_zipcode',
        'citizen_address',
        'citizen_addressnumber',
        'citizen_addresscomplement',
        'citizen_neighborhood',
        'citizen_mothername',
        'citizen_maritalstatus',
        'citizen_occupation',
        'citizen_familyincome'
      ],
      fields: [
        {
          id: 'pontoReferencia',
          label: 'Ponto de Referência',
          type: 'text',
          maxLength: 200,
          required: false
        },
        {
          id: 'local',
          label: 'Local da Quadra',
          type: 'text',
          minLength: 3,
          maxLength: 200,
          required: true
        },
        {
          id: 'dataReserva',
          label: 'Data da Reserva',
          type: 'date',
          required: true
        },
        {
          id: 'horarioInicio',
          label: 'Horário de Início',
          type: 'text',
          pattern: '^([01]\\d|2[0-3]):([0-5]\\d)$',
          required: true
        },
        {
          id: 'duracao',
          label: 'Duração (horas)',
          type: 'number',
          minimum: 1,
          maximum: 4,
          required: true
        },
        {
          id: 'observacoes',
          label: 'Observações',
          type: 'textarea',
          maxLength: 500,
          required: false
        }
      ]
    }
  },
  {
    name: 'Agenda de Eventos Esportivos',
    description: 'Consulta de competições e torneios',
    departmentCode: 'ESPORTES',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: false,
    estimatedDays: null,
    priority: 1,
    category: 'Informativo',
    icon: 'Calendar',
    color: '#94a3b8',
  },
  {
    name: 'Certidão de Participação Esportiva',
    description: 'Emissão de certidão de participação',
    departmentCode: 'ESPORTES',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: true,
    requiredDocuments: ['CPF', 'RG', 'Nome do Evento'],
    estimatedDays: 5,
    priority: 2,
    category: 'Certidões',
    icon: 'FileText',
    color: '#f59e0b',
  },
  {
    name: 'Declaração de Atleta',
    description: 'Emissão de declaração de atleta',
    departmentCode: 'ESPORTES',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: true,
    requiredDocuments: ['CPF', 'RG', 'Comprovante de Inscrição'],
    estimatedDays: 5,
    priority: 2,
    category: 'Declarações',
    icon: 'FileCheck',
    color: '#f59e0b',
  },
  {
    name: 'Atestado de Aptidão Física',
    description: 'Emissão de atestado para prática esportiva',
    departmentCode: 'ESPORTES',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: true,
    requiredDocuments: ['CPF', 'RG', 'Atestado Médico'],
    estimatedDays: 3,
    priority: 2,
    category: 'Atestados',
    icon: 'CheckCircle',
    color: '#f59e0b',
  },
  {
    name: 'Laudo Técnico de Instalação',
    description: 'Emissão de laudo de instalações esportivas',
    departmentCode: 'ESPORTES',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: true,
    requiredDocuments: ['CPF', 'RG', 'Localização'],
    estimatedDays: 15,
    priority: 3,
    category: 'Laudos',
    icon: 'ClipboardCheck',
    color: '#f59e0b',
  },
  {
    name: 'Autorização para Torneio',
    description: 'Autorização para realização de torneios',
    departmentCode: 'ESPORTES',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: true,
    requiredDocuments: ['CPF', 'RG', 'Regulamento'],
    estimatedDays: 10,
    priority: 3,
    category: 'Autorizações',
    icon: 'Shield',
    color: '#f59e0b',
  },
  {
    name: 'Inscrição em Torneios',
    description: 'Inscrição de equipes em torneios municipais',
    departmentCode: 'ESPORTES',
    serviceType: 'COM_DADOS',
    moduleType: 'INSCRICAO_EQUIPE_TORNEIO',
    requiresDocuments: true,
    requiredDocuments: ['Lista de Atletas', 'Regulamento Assinado'],
    estimatedDays: 7,
    priority: 4,
    category: 'Torneios',
    icon: 'Medal',
    color: '#f97316',
    formSchema: {
      citizenFields: [
          'citizen_name',
          'citizen_cpf',
          'citizen_rg',
          'citizen_birthdate',
          'citizen_email',
          'citizen_phone',
          'citizen_phonesecondary',
          'citizen_zipcode',
          'citizen_address',
          'citizen_addressnumber',
          'citizen_addresscomplement',
          'citizen_neighborhood',
          'citizen_mothername',
          'citizen_maritalstatus',
          'citizen_occupation',
          'citizen_familyincome'
        ],
      fields: [
        {
          id: 'pontoReferencia',
          label: 'Ponto de Referência',
          type: 'text',
          maxLength: 200,
          required: false
        },
        {
          id: 'nomeEquipe',
          label: 'Nome da Equipe',
          type: 'text',
          minLength: 3,
          maxLength: 200,
          required: true
        },
        {
          id: 'modalidade',
          label: 'Modalidade',
          type: 'select',
          options: ['Futebol', 'Futsal', 'Vôlei', 'Basquete', 'Handebol', 'Outro'],
          required: true
        },
        {
          id: 'categoria',
          label: 'Categoria',
          type: 'select',
          options: ['Infantil', 'Juvenil', 'Adulto', 'Master', 'Feminino', 'Misto'],
          required: true
        },
        {
          id: 'atletas',
          label: 'Lista de Atletas',
          type: 'array',
          items: {
            type: 'object',
            properties: {
            },
            required: ['nome', 'cpf']
          },
          minItems: 5,
          required: true
        },
        {
          id: 'observacoes',
          label: 'Observações',
          type: 'textarea',
          maxLength: 500,
          required: false
        }
      ]
    }
  },
  {
      name: 'Atendimentos - Esportes',
      description: 'Registro geral de atendimentos na área esportiva',
      departmentCode: 'ESPORTES',
      serviceType: 'COM_DADOS',
      moduleType: 'ATENDIMENTOS_ESPORTES',
      requiresDocuments: false,
      estimatedDays: 1,
      priority: 3,
      category: 'Atendimento',
      icon: 'Trophy',
      color: '#f59e0b',
      formSchema: {
        type: 'object',
          citizenFields: [
            'citizen_name',
            'citizen_cpf',
            'citizen_rg',
            'citizen_birthdate',
            'citizen_email',
            'citizen_phone',
            'citizen_phonesecondary',
            'citizen_zipcode',
            'citizen_address',
            'citizen_addressnumber',
            'citizen_addresscomplement',
            'citizen_neighborhood',
            'citizen_mothername',
            'citizen_maritalstatus',
            'citizen_occupation',
            'citizen_familyincome'
          ],
        properties: {
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          motivoAtendimento: { type: 'string', title: 'Motivo do Atendimento', enum: ['Informações Gerais', 'Inscrição em Escolinha', 'Reserva de Espaço', 'Inscrição em Competição', 'Cadastro de Atleta', 'Cadastro de Equipe', 'Reclamação', 'Sugestão', 'Outro'] },
          descricaoAtendimento: { type: 'string', title: 'Descrição do Atendimento', minLength: 10, maxLength: 1000 },
          modalidadeInteresse: { type: 'string', title: 'Modalidade de Interesse', enum: ['Futebol', 'Futsal', 'Vôlei', 'Basquete', 'Handebol', 'Natação', 'Atletismo', 'Judô', 'Karatê', 'Capoeira', 'Tênis', 'Tênis de Mesa', 'Ginástica', 'Outro'] },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 }
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'motivoAtendimento', 'descricaoAtendimento']
      }
    },
  {
      name: 'Inscrição em Escolinha Esportiva',
      description: 'Inscrição em escolinhas de futebol, vôlei, basquete, etc',
      departmentCode: 'ESPORTES',
      serviceType: 'COM_DADOS',
      moduleType: 'INSCRICAO_ESCOLINHA',
      requiresDocuments: true,
      requiredDocuments: ['Certidão de Nascimento', 'Atestado Médico', 'Comprovante de Endereço'],
      estimatedDays: 5,
      priority: 4,
      category: 'Escolinhas',
      icon: 'Users',
      color: '#ea580c',
      formSchema: {
        type: 'object',
        citizenFields: [
            'citizen_name',
            'citizen_cpf',
            'citizen_rg',
            'citizen_birthdate',
            'citizen_email',
            'citizen_phone',
            'citizen_phonesecondary',
            'citizen_zipcode',
            'citizen_address',
            'citizen_addressnumber',
            'citizen_addresscomplement',
            'citizen_neighborhood',
            'citizen_mothername',
            'citizen_maritalstatus',
            'citizen_occupation',
            'citizen_familyincome'
          ],
        properties: {
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeAluno: { type: 'string', title: 'Nome Completo do Aluno', minLength: 3, maxLength: 200 },
          cpfAluno: { type: 'string', title: 'CPF do Aluno', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          dataNascimentoAluno: { type: 'string', format: 'date', title: 'Data de Nascimento do Aluno' },
          idadeAluno: { type: 'integer', title: 'Idade do Aluno', minimum: 4, maximum: 17 },
          sexoAluno: { type: 'string', title: 'Sexo do Aluno', enum: ['Masculino', 'Feminino'] },
          modalidadeEscolinha: { type: 'string', title: 'Modalidade da Escolinha', enum: ['Futebol', 'Futsal', 'Vôlei', 'Basquete', 'Handebol', 'Natação', 'Atletismo', 'Judô', 'Karatê', 'Capoeira', 'Tênis', 'Ginástica'] },
          unidadeEscolinha: { type: 'string', title: 'Unidade/Local da Escolinha', maxLength: 200 },
          turnoPreferencia: { type: 'string', title: 'Turno de Preferência', enum: ['Manhã', 'Tarde', 'Noite'] },
          necessidadesEspeciais: { type: 'string', title: 'Necessidades Especiais', maxLength: 500 },
          experienciaAnterior: { type: 'string', title: 'Experiência Anterior', enum: ['Sim', 'Não'] },
          objetivoInscricao: { type: 'string', title: 'Objetivo da Inscrição', enum: ['Recreação', 'Competição', 'Saúde/Condicionamento', 'Socialização'] },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 }
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'nomeAluno', 'cpfAluno', 'dataNascimentoAluno', 'idadeAluno', 'sexoAluno', 'modalidadeEscolinha', 'turnoPreferencia']
      },
    linkedCitizensConfig: {
      enabled: true,
      links: [{
        linkType: 'STUDENT',
        role: 'BENEFICIARY',
        label: 'Aluno/Participante',
        description: 'Selecione o aluno que participará da escolinha esportiva',
        required: true,
        mapFromLegacyFields: {
          name: 'nomeAluno',
          cpf: 'cpfAluno',
          birthDate: 'dataNascimentoAluno'
        },
        contextFields: [
          { id: 'idadeAluno', sourceField: 'idadeAluno' },
          { id: 'sexoAluno', sourceField: 'sexoAluno' },
          { id: 'modalidadeEscolinha', sourceField: 'modalidadeEscolinha' },
          { id: 'unidadeEscolinha', sourceField: 'unidadeEscolinha' },
          { id: 'turnoPreferencia', sourceField: 'turnoPreferencia' },
          { id: 'necessidadesEspeciais', sourceField: 'necessidadesEspeciais' },
          { id: 'experienciaAnterior', sourceField: 'experienciaAnterior' },
          { id: 'objetivoInscricao', sourceField: 'objetivoInscricao' }
        ],
        expectedRelationships: ['SON', 'DAUGHTER', 'GRANDSON', 'GRANDDAUGHTER']
      }]
    }
  },
  {
      name: 'Cadastro de Atleta',
      description: 'Cadastro de atletas federados no município',
      departmentCode: 'ESPORTES',
      serviceType: 'COM_DADOS',
      moduleType: 'CADASTRO_ATLETA',
      requiresDocuments: true,
      requiredDocuments: ['RG', 'CPF', 'Atestado Médico', 'Comprovante de Federação'],
      estimatedDays: 7,
      priority: 3,
      category: 'Cadastro',
      icon: 'User',
      color: '#f97316',
      formSchema: {
        type: 'object',
        citizenFields: [
            'citizen_name',
            'citizen_cpf',
            'citizen_rg',
            'citizen_birthdate',
            'citizen_email',
            'citizen_phone',
            'citizen_phonesecondary',
            'citizen_zipcode',
            'citizen_address',
            'citizen_addressnumber',
            'citizen_addresscomplement',
            'citizen_neighborhood',
            'citizen_mothername',
            'citizen_maritalstatus',
            'citizen_occupation',
            'citizen_familyincome'
          ],
        properties: {
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          modalidade: { type: 'string', title: 'Modalidade Principal', enum: ['Futebol', 'Futsal', 'Vôlei', 'Basquete', 'Handebol', 'Natação', 'Atletismo', 'Judô', 'Karatê', 'Capoeira', 'Tênis', 'Tênis de Mesa', 'Ginástica', 'Outro'] },
          posicao: { type: 'string', title: 'Posição/Categoria', maxLength: 100 },
          altura: { type: 'number', title: 'Altura (cm)', minimum: 100, maximum: 250 },
          peso: { type: 'number', title: 'Peso (kg)', minimum: 30, maximum: 200 },
          categoriaIdade: { type: 'string', title: 'Categoria de Idade', enum: ['Sub-11', 'Sub-13', 'Sub-15', 'Sub-17', 'Sub-20', 'Adulto', 'Master'] },
          numeroFederacao: { type: 'string', title: 'Número da Federação', maxLength: 50 },
          federacaoVinculada: { type: 'string', title: 'Federação Vinculada', maxLength: 200 },
          equipeAtual: { type: 'string', title: 'Equipe Atual', maxLength: 200 },
          tempoExperiencia: { type: 'string', title: 'Tempo de Experiência', enum: ['Menos de 1 ano', '1-3 anos', '3-5 anos', '5-10 anos', 'Mais de 10 anos'] },
          objetivoAtleta: { type: 'string', title: 'Objetivo como Atleta', enum: ['Competição Municipal', 'Competição Estadual', 'Competição Nacional', 'Profissionalização', 'Recreação'] },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 }
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'modalidade', 'categoriaIdade', 'numeroFederacao', 'federacaoVinculada']
      }
    },
  {
      name: 'Reserva de Espaço Esportivo',
      description: 'Agendamento de quadras, ginásios e campos',
      departmentCode: 'ESPORTES',
      serviceType: 'COM_DADOS',
      moduleType: 'RESERVA_ESPACO_ESPORTIVO',
      requiresDocuments: true,
      requiredDocuments: ['RG', 'CPF', 'Termo de Responsabilidade'],
      estimatedDays: 3,
      priority: 3,
      category: 'Reserva',
      icon: 'Building',
      color: '#fb923c',
      formSchema: {
        type: 'object',
        citizenFields: [
            'citizen_name',
            'citizen_cpf',
            'citizen_rg',
            'citizen_birthdate',
            'citizen_email',
            'citizen_phone',
            'citizen_phonesecondary',
            'citizen_zipcode',
            'citizen_address',
            'citizen_addressnumber',
            'citizen_addresscomplement',
            'citizen_neighborhood',
            'citizen_mothername',
            'citizen_maritalstatus',
            'citizen_occupation',
            'citizen_familyincome'
          ],
        properties: {
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          tipoEspaco: { type: 'string', title: 'Tipo de Espaço', enum: ['Quadra Poliesportiva', 'Campo de Futebol', 'Ginásio', 'Piscina', 'Quadra de Tênis', 'Pista de Atletismo', 'Outro'] },
          nomeEspaco: { type: 'string', title: 'Nome do Espaço', maxLength: 200 },
          dataReserva: { type: 'string', format: 'date', title: 'Data da Reserva' },
          horarioInicio: { type: 'string', title: 'Horário de Início', pattern: '^([01]?[0-9]|2[0-3]):[0-5][0-9]$' },
          horarioFim: { type: 'string', title: 'Horário de Término', pattern: '^([01]?[0-9]|2[0-3]):[0-5][0-9]$' },
          finalidadeUso: { type: 'string', title: 'Finalidade do Uso', enum: ['Treino Esportivo', 'Competição', 'Evento', 'Recreação', 'Aula', 'Outro'] },
          modalidadePraticada: { type: 'string', title: 'Modalidade a ser Praticada', maxLength: 100 },
          numeroParticipantes: { type: 'integer', title: 'Número de Participantes', minimum: 1 },
          nomeGrupoEquipe: { type: 'string', title: 'Nome do Grupo/Equipe', maxLength: 200 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 }
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'tipoEspaco', 'nomeEspaco', 'dataReserva', 'horarioInicio', 'horarioFim', 'finalidadeUso', 'numeroParticipantes']
      }
    },
  {
      name: 'Inscrição em Competição',
      description: 'Inscrição em campeonatos e competições municipais',
      departmentCode: 'ESPORTES',
      serviceType: 'COM_DADOS',
      moduleType: 'INSCRICAO_COMPETICAO',
      requiresDocuments: true,
      requiredDocuments: ['Fichas dos Atletas', 'Atestados Médicos', 'Comprovante de Pagamento'],
      estimatedDays: 10,
      priority: 4,
      category: 'Competições',
      icon: 'Medal',
      color: '#facc15',
      formSchema: {
        type: 'object',
        citizenFields: [
            'citizen_name',
            'citizen_cpf',
            'citizen_rg',
            'citizen_birthdate',
            'citizen_email',
            'citizen_phone',
            'citizen_phonesecondary',
            'citizen_zipcode',
            'citizen_address',
            'citizen_addressnumber',
            'citizen_addresscomplement',
            'citizen_neighborhood',
            'citizen_mothername',
            'citizen_maritalstatus',
            'citizen_occupation',
            'citizen_familyincome'
          ],
        properties: {
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeCompeticao: { type: 'string', title: 'Nome da Competição', maxLength: 200 },
          modalidade: { type: 'string', title: 'Modalidade', enum: ['Futebol', 'Futsal', 'Vôlei', 'Basquete', 'Handebol', 'Natação', 'Atletismo', 'Judô', 'Karatê', 'Tênis', 'Tênis de Mesa', 'Outro'] },
          categoria: { type: 'string', title: 'Categoria', enum: ['Sub-11', 'Sub-13', 'Sub-15', 'Sub-17', 'Sub-20', 'Adulto', 'Master', 'Livre'] },
          tipoInscricao: { type: 'string', title: 'Tipo de Inscrição', enum: ['Individual', 'Equipe'] },
          nomeEquipe: { type: 'string', title: 'Nome da Equipe (se aplicável)', maxLength: 200 },
          numeroAtletas: { type: 'integer', title: 'Número de Atletas', minimum: 1 },
          nomeTecnico: { type: 'string', title: 'Nome do Técnico', maxLength: 200 },
          cpfTecnico: { type: 'string', title: 'CPF do Técnico', pattern: '^\\d{11}$' },
          telefoneTecnico: { type: 'string', title: 'Telefone do Técnico', pattern: '^\\d{10,11}$' },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 }
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'nomeCompeticao', 'modalidade', 'categoria', 'tipoInscricao', 'numeroAtletas']
      }
    },
  {
      name: 'Cadastro de Equipe Esportiva',
      description: 'Cadastro de equipes municipais',
      departmentCode: 'ESPORTES',
      serviceType: 'COM_DADOS',
      moduleType: 'CADASTRO_EQUIPE_ESPORTIVA',
      requiresDocuments: true,
      requiredDocuments: ['Fichas dos Atletas', 'Documentação do Técnico', 'Regimento'],
      estimatedDays: 7,
      priority: 3,
      category: 'Cadastro',
      icon: 'Users',
      color: '#eab308',
      formSchema: {
        type: 'object',
        citizenFields: [
            'citizen_name',
            'citizen_cpf',
            'citizen_rg',
            'citizen_birthdate',
            'citizen_email',
            'citizen_phone',
            'citizen_phonesecondary',
            'citizen_zipcode',
            'citizen_address',
            'citizen_addressnumber',
            'citizen_addresscomplement',
            'citizen_neighborhood',
            'citizen_mothername',
            'citizen_maritalstatus',
            'citizen_occupation',
            'citizen_familyincome'
          ],
        properties: {
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeEquipe: { type: 'string', title: 'Nome da Equipe', minLength: 3, maxLength: 200 },
          modalidade: { type: 'string', title: 'Modalidade', enum: ['Futebol', 'Futsal', 'Vôlei', 'Basquete', 'Handebol', 'Natação', 'Atletismo', 'Outro'] },
          categoria: { type: 'string', title: 'Categoria', enum: ['Sub-11', 'Sub-13', 'Sub-15', 'Sub-17', 'Sub-20', 'Adulto', 'Master', 'Livre'] },
          anoFundacao: { type: 'integer', title: 'Ano de Fundação', minimum: 1900, maximum: 2100 },
          numeroAtletas: { type: 'integer', title: 'Número de Atletas', minimum: 5 },
          nomeTecnico: { type: 'string', title: 'Nome do Técnico Principal', minLength: 3, maxLength: 200 },
          cpfTecnico: { type: 'string', title: 'CPF do Técnico', pattern: '^\\d{11}$' },
          telefoneTecnico: { type: 'string', title: 'Telefone do Técnico', pattern: '^\\d{10,11}$' },
          crefTecnico: { type: 'string', title: 'CREF do Técnico', maxLength: 20 },
          localTreino: { type: 'string', title: 'Local de Treino', maxLength: 200 },
          diasTreino: { type: 'string', title: 'Dias de Treino', maxLength: 200 },
          horarioTreino: { type: 'string', title: 'Horário de Treino', maxLength: 100 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 }
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'nomeEquipe', 'modalidade', 'categoria', 'numeroAtletas', 'nomeTecnico', 'cpfTecnico', 'telefoneTecnico']
      }
    },
  {
      name: 'Inscrição em Torneio',
      description: 'Inscrição de equipes em torneios esportivos',
      departmentCode: 'ESPORTES',
      serviceType: 'COM_DADOS',
      moduleType: 'INSCRICAO_TORNEIO',
      requiresDocuments: true,
      requiredDocuments: ['Súmula da Equipe', 'Comprovante de Pagamento'],
      estimatedDays: 5,
      priority: 3,
      category: 'Torneios',
      icon: 'Trophy',
      color: '#ca8a04',
      formSchema: {
        type: 'object',
        citizenFields: [
            'citizen_name',
            'citizen_cpf',
            'citizen_rg',
            'citizen_birthdate',
            'citizen_email',
            'citizen_phone',
            'citizen_phonesecondary',
            'citizen_zipcode',
            'citizen_address',
            'citizen_addressnumber',
            'citizen_addresscomplement',
            'citizen_neighborhood',
            'citizen_mothername',
            'citizen_maritalstatus',
            'citizen_occupation',
            'citizen_familyincome'
          ],
        properties: {
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeTorneio: { type: 'string', title: 'Nome do Torneio', maxLength: 200 },
          modalidade: { type: 'string', title: 'Modalidade', enum: ['Futebol', 'Futsal', 'Vôlei', 'Basquete', 'Handebol', 'Outro'] },
          categoria: { type: 'string', title: 'Categoria', enum: ['Sub-11', 'Sub-13', 'Sub-15', 'Sub-17', 'Sub-20', 'Adulto', 'Master', 'Livre'] },
          nomeEquipe: { type: 'string', title: 'Nome da Equipe', minLength: 3, maxLength: 200 },
          numeroAtletas: { type: 'integer', title: 'Número de Atletas Inscritos', minimum: 5 },
          nomeTecnico: { type: 'string', title: 'Nome do Técnico', minLength: 3, maxLength: 200 },
          telefoneTecnico: { type: 'string', title: 'Telefone do Técnico', pattern: '^\\d{10,11}$' },
          uniformePrincipal: { type: 'string', title: 'Cor do Uniforme Principal', maxLength: 100 },
          uniformeReserva: { type: 'string', title: 'Cor do Uniforme Reserva', maxLength: 100 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 }
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'nomeTorneio', 'modalidade', 'categoria', 'nomeEquipe', 'numeroAtletas', 'nomeTecnico', 'telefoneTecnico']
      }
    },
  {
      name: 'Cadastro de Modalidade Esportiva',
      description: 'Cadastro de novas modalidades esportivas no município',
      departmentCode: 'ESPORTES',
      serviceType: 'COM_DADOS',
      moduleType: 'CADASTRO_MODALIDADE',
      requiresDocuments: true,
      requiredDocuments: ['Regras da Modalidade', 'Documentação do Instrutor'],
      estimatedDays: 15,
      priority: 2,
      category: 'Cadastro',
      icon: 'Plus',
      color: '#a16207',
      formSchema: {
        type: 'object',
        citizenFields: [
            'citizen_name',
            'citizen_cpf',
            'citizen_rg',
            'citizen_birthdate',
            'citizen_email',
            'citizen_phone',
            'citizen_phonesecondary',
            'citizen_zipcode',
            'citizen_address',
            'citizen_addressnumber',
            'citizen_addresscomplement',
            'citizen_neighborhood',
            'citizen_mothername',
            'citizen_maritalstatus',
            'citizen_occupation',
            'citizen_familyincome'
          ],
        properties: {
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeModalidade: { type: 'string', title: 'Nome da Modalidade', minLength: 3, maxLength: 200 },
          tipoModalidade: { type: 'string', title: 'Tipo de Modalidade', enum: ['Coletiva', 'Individual', 'Combate', 'Aquática', 'Radical', 'Adaptada', 'Outro'] },
          descricaoModalidade: { type: 'string', title: 'Descrição da Modalidade', minLength: 50, maxLength: 1000 },
          objetivosModalidade: { type: 'string', title: 'Objetivos da Modalidade', minLength: 30, maxLength: 500 },
          publicoAlvo: { type: 'string', title: 'Público-Alvo', enum: ['Infantil', 'Juvenil', 'Adulto', 'Idoso', 'Todos'] },
          numeroMinimoParticipantes: { type: 'integer', title: 'Número Mínimo de Participantes', minimum: 1 },
          nomeInstrutor: { type: 'string', title: 'Nome do Instrutor/Professor', minLength: 3, maxLength: 200 },
          cpfInstrutor: { type: 'string', title: 'CPF do Instrutor', pattern: '^\\d{11}$' },
          crefInstrutor: { type: 'string', title: 'CREF do Instrutor', maxLength: 20 },
          telefoneInstrutor: { type: 'string', title: 'Telefone do Instrutor', pattern: '^\\d{10,11}$' },
          materialNecessario: { type: 'string', title: 'Material Necessário', maxLength: 500 },
          espacoNecessario: { type: 'string', title: 'Espaço Necessário', maxLength: 300 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 }
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'nomeModalidade', 'tipoModalidade', 'descricaoModalidade', 'objetivosModalidade', 'publicoAlvo', 'nomeInstrutor', 'cpfInstrutor']
      }
    },
  {
      name: 'Certidão de Atleta Municipal',
      description: 'Certidão comprovando condição de atleta municipal',
      departmentCode: 'ESPORTES',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: true,
      requiredDocuments: ['CPF', 'RG', 'Atestado Médico'],
      estimatedDays: 5,
      priority: 3,
      category: 'Certidões',
      icon: 'FileText',
      color: '#f59e0b'
    },
  {
      name: 'Declaração de Participação em Competição',
      description: 'Declaração de participação em competições esportivas municipais',
      departmentCode: 'ESPORTES',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: true,
      requiredDocuments: ['CPF', 'Comprovante de Inscrição'],
      estimatedDays: 3,
      priority: 3,
      category: 'Certidões',
      icon: 'Trophy',
      color: '#fbbf24'
    },
  {
      name: 'Atestado de Inscrição em Escolinha',
      description: 'Atestado de inscrição em escolinhas esportivas',
      departmentCode: 'ESPORTES',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: true,
      requiredDocuments: ['CPF do Responsável', 'RG do Atleta'],
      estimatedDays: 2,
      priority: 3,
      category: 'Certidões',
      icon: 'Users',
      color: '#10b981'
    },
  {
      name: 'Comprovante de Reserva de Quadra',
      description: 'Comprovante de reserva de espaço esportivo',
      departmentCode: 'ESPORTES',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: true,
      requiredDocuments: ['CPF'],
      estimatedDays: 1,
      priority: 4,
      category: 'Documentos',
      icon: 'Calendar',
      color: '#3b82f6'
    },
  {
      name: 'Segunda Via de Carteira de Atleta',
      description: 'Reemissão de carteira de atleta municipal',
      departmentCode: 'ESPORTES',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: true,
      requiredDocuments: ['CPF', 'RG', 'Foto 3x4'],
      estimatedDays: 5,
      priority: 2,
      category: 'Documentos',
      icon: 'Copy',
      color: '#6b7280'
    },
  {
      name: 'Consulta de Calendário Esportivo',
      description: 'Consulta oficial do calendário de eventos esportivos',
      departmentCode: 'ESPORTES',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: true,
      requiredDocuments: ['CPF'],
      estimatedDays: 1,
      priority: 2,
      category: 'Consultas',
      icon: 'Search',
      color: '#8b5cf6'
    }
];
