/**
 * SEED DE SERVIÇOS - SECRETARIA DE PLANEJAMENTO URBANO
 * Total: 9 serviços
 */

import { ServiceDefinition } from './types';

export const urbanPlanningServices: ServiceDefinition[] = [
  {
    name: 'Plano Diretor',
    description: 'Consulta e informações sobre o Plano Diretor Municipal',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: false,
    estimatedDays: null,
    priority: 2,
    category: 'Informações',
    icon: 'Map',
    color: '#6366f1',
  },
  {
    name: 'Zoneamento Urbano',
    description: 'Consulta de zoneamento e uso do solo',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: false,
    estimatedDays: null,
    priority: 3,
    category: 'Informações',
    icon: 'MapPin',
    color: '#8b5cf6',
  },
  {
    name: 'Certidão de Zoneamento',
    description: 'Emissão de certidão de zoneamento de imóvel',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: true,
    requiredDocuments: ['CPF', 'RG', 'Matrícula do Imóvel ou Endereço Completo'],
    estimatedDays: 7,
    priority: 4,
    category: 'Certidões',
    icon: 'FileText',
    color: '#f59e0b',
  },
  {
    name: 'Certidão de Uso do Solo',
    description: 'Certidão de uso e ocupação do solo',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: true,
    requiredDocuments: ['CPF', 'RG', 'Matrícula do Imóvel'],
    estimatedDays: 7,
    priority: 4,
    category: 'Certidões',
    icon: 'FileCheck',
    color: '#f59e0b',
  },
  {
    name: 'Declaração de Conformidade Urbanística',
    description: 'Declaração de que o imóvel está em conformidade com as normas urbanísticas',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: true,
    requiredDocuments: ['CPF', 'RG', 'CNPJ (se empresa)', 'Matrícula do Imóvel', 'Projeto Aprovado'],
    estimatedDays: 10,
    priority: 4,
    category: 'Declarações',
    icon: 'CheckCircle',
    color: '#10b981',
  },
  {
    name: 'Laudo de Vistoria Urbanística',
    description: 'Laudo técnico de vistoria urbanística de imóvel',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: true,
    requiredDocuments: ['CPF', 'RG', 'Matrícula do Imóvel', 'Comprovante de Propriedade'],
    estimatedDays: 15,
    priority: 4,
    category: 'Laudos',
    icon: 'ClipboardCheck',
    color: '#3b82f6',
  },
  {
    name: 'Autorização de Parcelamento do Solo',
    description: 'Autorização para parcelamento de terreno',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'COM_DADOS',
    moduleType: 'PARCELAMENTO_SOLO',
    requiresDocuments: true,
    requiredDocuments: ['CPF', 'RG', 'CNPJ (se empresa)', 'Matrícula do Imóvel', 'Projeto de Parcelamento', 'ART do Responsável Técnico'],
    estimatedDays: 30,
    priority: 5,
    category: 'Autorizações',
    icon: 'Grid',
    color: '#ec4899',
    formSchema: {
      citizenFields: [
        'citizen_name',
        'citizen_cpf',
        'citizen_rg',
        'citizen_birthDate',
        'citizen_email',
        'citizen_phone',
        'citizen_phoneSecondary',
        'citizen_zipCode',
        'citizen_address',
        'citizen_addressNumber',
        'citizen_addressComplement',
        'citizen_neighborhood',
        'citizen_motherName',
        'citizen_maritalStatus',
        'citizen_occupation',
        'citizen_familyIncome'
      ],
      fields: [
        {
          id: 'pontoReferencia',
          label: 'Ponto de Referência',
          type: 'text',
          maxLength: 200,
          required: false
        },
        {
          id: 'tipoSolicitante',
          label: 'Tipo de Solicitante',
          type: 'select',
          options: ['Pessoa Física', 'Pessoa Jurídica'],
          required: true
        },
        {
          id: 'cnpj',
          label: 'CNPJ (se pessoa jurídica)',
          type: 'text',
          pattern: '^\\d{14}$',
          minLength: 14,
          maxLength: 14,
          required: false
        },
        {
          id: 'razaoSocial',
          label: 'Razão Social (se pessoa jurídica)',
          type: 'text',
          minLength: 3,
          maxLength: 200,
          required: false
        },
        {
          id: 'matriculaImovel',
          label: 'Matrícula do Imóvel',
          type: 'text',
          minLength: 3,
          maxLength: 50,
          required: true
        },
        {
          id: 'enderecoImovel',
          label: 'Endereço Completo do Imóvel',
          type: 'text',
          minLength: 10,
          maxLength: 300,
          required: true
        },
        {
          id: 'areaTotal',
          label: 'Área Total do Terreno (m²)',
          type: 'number',
          minimum: 1,
          required: true
        },
        {
          id: 'tipoParcelamento',
          label: 'Tipo de Parcelamento',
          type: 'select',
          options: ['Loteamento', 'Desmembramento', 'Remembramento'],
          required: true
        },
        {
          id: 'numeroLotes',
          label: 'Número de Lotes Previsto',
          type: 'number',
          minimum: 1,
          required: true
        },
        {
          id: 'nomeResponsavelTecnico',
          label: 'Nome do Responsável Técnico',
          type: 'text',
          minLength: 3,
          maxLength: 200,
          required: true
        },
        {
          id: 'creaResponsavel',
          label: 'CREA do Responsável Técnico',
          type: 'text',
          maxLength: 20,
          required: true
        },
        {
          id: 'numeroART',
          label: 'Número da ART',
          type: 'text',
          maxLength: 50,
          required: true
        },
        {
          id: 'descricaoProjeto',
          label: 'Descrição do Projeto',
          type: 'textarea',
          minLength: 50,
          maxLength: 2000,
          required: true
        },
        {
          id: 'observacoes',
          label: 'Observações',
          type: 'textarea',
          maxLength: 1000,
          required: false
        }
      ]
    }
  },
  {
    name: 'Consulta de Viabilidade Urbanística',
    description: 'Consulta de viabilidade para empreendimentos',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'COM_DADOS',
    moduleType: 'VIABILIDADE_URBANISTICA',
    requiresDocuments: true,
    requiredDocuments: ['CPF', 'RG', 'Matrícula do Imóvel', 'Memorial Descritivo'],
    estimatedDays: 15,
    priority: 4,
    category: 'Consultas',
    icon: 'Search',
    color: '#06b6d4',
    formSchema: {
      citizenFields: [
        'citizen_name',
        'citizen_cpf',
        'citizen_rg',
        'citizen_birthDate',
        'citizen_email',
        'citizen_phone',
        'citizen_phoneSecondary',
        'citizen_zipCode',
        'citizen_address',
        'citizen_addressNumber',
        'citizen_addressComplement',
        'citizen_neighborhood',
        'citizen_motherName',
        'citizen_maritalStatus',
        'citizen_occupation',
        'citizen_familyIncome'
      ],
      fields: [
        {
          id: 'pontoReferencia',
          label: 'Ponto de Referência',
          type: 'text',
          maxLength: 200,
          required: false
        },
        {
          id: 'tipoEmpreendimento',
          label: 'Tipo de Empreendimento',
          type: 'select',
          options: ['Residencial', 'Comercial', 'Industrial', 'Misto', 'Institucional'],
          required: true
        },
        {
          id: 'matriculaImovel',
          label: 'Matrícula do Imóvel',
          type: 'text',
          minLength: 3,
          maxLength: 50,
          required: true
        },
        {
          id: 'enderecoImovel',
          label: 'Endereço do Imóvel',
          type: 'text',
          minLength: 10,
          maxLength: 300,
          required: true
        },
        {
          id: 'areaTerreno',
          label: 'Área do Terreno (m²)',
          type: 'number',
          minimum: 1,
          required: true
        },
        {
          id: 'areaConstruir',
          label: 'Área a Construir (m²)',
          type: 'number',
          minimum: 1,
          required: true
        },
        {
          id: 'descricaoEmpreendimento',
          label: 'Descrição do Empreendimento',
          type: 'textarea',
          minLength: 20,
          maxLength: 1000,
          required: true
        },
        {
          id: 'observacoes',
          label: 'Observações',
          type: 'textarea',
          maxLength: 500,
          required: false
        }
      ]
    }
  },
  {
    name: 'Mapa de Zoneamento',
    description: 'Consulta ao mapa de zoneamento urbano do município',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'SEM_DADOS',
    moduleType: null,
    requiresDocuments: false,
    estimatedDays: null,
    priority: 2,
    category: 'Mapas',
    icon: 'Map',
    color: '#14b8a6',
  },
  {
      name: 'Atendimentos - Planejamento Urbano',
      description: 'Registro geral de atendimentos em planejamento',
      departmentCode: 'PLANEJAMENTO_URBANO',
      serviceType: 'COM_DADOS',
      moduleType: 'ATENDIMENTOS_PLANEJAMENTO',
      requiresDocuments: false,
      estimatedDays: 1,
      priority: 3,
      category: 'Atendimento',
      icon: 'Map',
      color: '#6366f1',
      formSchema: {
        type: 'object',
        properties: {
          nome: { type: 'string', title: 'Nome Completo', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          tipoAtendimento: { type: 'string', title: 'Tipo de Atendimento', enum: ['Consulta', 'Informação', 'Solicitação', 'Reclamação', 'Outro'] },
          assunto: { type: 'string', title: 'Assunto', maxLength: 200 },
          descricao: { type: 'string', title: 'Descrição do Atendimento', minLength: 20, maxLength: 1000 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'tipoAtendimento', 'assunto', 'descricao'],
      },
    },
  {
      name: 'Aprovação de Projeto Arquitetônico',
      description: 'Aprovação de projetos de construção e reforma',
      departmentCode: 'PLANEJAMENTO_URBANO',
      serviceType: 'COM_DADOS',
      moduleType: 'APROVACAO_PROJETO',
      requiresDocuments: true,
      requiredDocuments: ['Projeto Arquitetônico', 'ART', 'Documentação do Imóvel'],
      estimatedDays: 30,
      priority: 5,
      category: 'Aprovação',
      icon: 'FileCheck',
      color: '#4f46e5',
      formSchema: {
        type: 'object',
        properties: {
          nome: { type: 'string', title: 'Nome Completo do Proprietário', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF do Proprietário', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          enderecoObra: { type: 'string', title: 'Endereço Completo da Obra', maxLength: 300 },
          tipoProjeto: { type: 'string', title: 'Tipo de Projeto', enum: ['Construção Nova', 'Reforma', 'Ampliação', 'Regularização', 'Demolição'] },
          areaTerreno: { type: 'number', title: 'Área do Terreno (m²)', minimum: 1 },
          areaConstruir: { type: 'number', title: 'Área a Construir (m²)', minimum: 1 },
          numeroMatricula: { type: 'string', title: 'Número da Matrícula do Imóvel', maxLength: 50 },
          nomeResponsavelTecnico: { type: 'string', title: 'Nome do Responsável Técnico', maxLength: 200 },
          creaResponsavel: { type: 'string', title: 'CREA do Responsável Técnico', maxLength: 50 },
          numeroART: { type: 'string', title: 'Número da ART', maxLength: 50 },
          descricaoProjeto: { type: 'string', title: 'Descrição do Projeto', minLength: 50, maxLength: 1000 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'enderecoObra', 'tipoProjeto', 'areaTerreno', 'areaConstruir', 'numeroMatricula', 'nomeResponsavelTecnico', 'creaResponsavel', 'numeroART', 'descricaoProjeto'],
      },
    },
  {
      name: 'Alvará de Construção',
      description: 'Solicitação de licença para construção',
      departmentCode: 'PLANEJAMENTO_URBANO',
      serviceType: 'COM_DADOS',
      moduleType: 'ALVARA_CONSTRUCAO',
      requiresDocuments: true,
      requiredDocuments: ['Projeto Aprovado', 'Matrícula do Imóvel', 'ART'],
      estimatedDays: 20,
      priority: 5,
      category: 'Alvará',
      icon: 'Building',
      color: '#4338ca',
      formSchema: {
        type: 'object',
        properties: {
          nome: { type: 'string', title: 'Nome Completo do Proprietário', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF do Proprietário', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          enderecoObra: { type: 'string', title: 'Endereço Completo da Obra', maxLength: 300 },
          numeroMatricula: { type: 'string', title: 'Número da Matrícula do Imóvel', maxLength: 50 },
          numeroProjetoAprovado: { type: 'string', title: 'Número do Projeto Aprovado', maxLength: 50 },
          dataAprovacaoProjeto: { type: 'string', format: 'date', title: 'Data de Aprovação do Projeto' },
          areaTotal: { type: 'number', title: 'Área Total da Construção (m²)', minimum: 1 },
          numeroPavimentos: { type: 'integer', title: 'Número de Pavimentos', minimum: 1, maximum: 50 },
          nomeResponsavelObra: { type: 'string', title: 'Nome do Responsável pela Obra', maxLength: 200 },
          creaResponsavel: { type: 'string', title: 'CREA do Responsável', maxLength: 50 },
          numeroART: { type: 'string', title: 'Número da ART de Execução', maxLength: 50 },
          prazoObra: { type: 'integer', title: 'Prazo Estimado da Obra (meses)', minimum: 1, maximum: 120 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'enderecoObra', 'numeroMatricula', 'numeroProjetoAprovado', 'dataAprovacaoProjeto', 'areaTotal', 'numeroPavimentos', 'nomeResponsavelObra', 'creaResponsavel', 'numeroART'],
      },
    },
  {
      name: 'Alvará de Funcionamento',
      description: 'Licença comercial para estabelecimentos',
      departmentCode: 'PLANEJAMENTO_URBANO',
      serviceType: 'COM_DADOS',
      moduleType: 'ALVARA_FUNCIONAMENTO',
      requiresDocuments: true,
      requiredDocuments: ['CNPJ', 'Contrato Social', 'Laudo Técnico', 'Comprovante de Endereço'],
      estimatedDays: 15,
      priority: 5,
      category: 'Alvará',
      icon: 'Store',
      color: '#3730a3',
      formSchema: {
        type: 'object',
        properties: {
          nome: { type: 'string', title: 'Nome Completo do Responsável', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF do Responsável', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          razaoSocial: { type: 'string', title: 'Razão Social da Empresa', maxLength: 200 },
          nomeFantasia: { type: 'string', title: 'Nome Fantasia', maxLength: 200 },
          cnpj: { type: 'string', title: 'CNPJ', pattern: '^\\d{14}$', minLength: 14, maxLength: 14 },
          inscricaoEstadual: { type: 'string', title: 'Inscrição Estadual', maxLength: 50 },
          enderecoEstabelecimento: { type: 'string', title: 'Endereço Completo do Estabelecimento', maxLength: 300 },
          areaEstabelecimento: { type: 'number', title: 'Área do Estabelecimento (m²)', minimum: 1 },
          ramoAtividade: { type: 'string', title: 'Ramo de Atividade', maxLength: 200 },
          numeroFuncionarios: { type: 'integer', title: 'Número de Funcionários', minimum: 0 },
          horarioFuncionamento: { type: 'string', title: 'Horário de Funcionamento', maxLength: 100 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'razaoSocial', 'nomeFantasia', 'cnpj', 'enderecoEstabelecimento', 'areaEstabelecimento', 'ramoAtividade', 'numeroFuncionarios', 'horarioFuncionamento'],
      },
    },
  {
      name: 'Solicitação de Certidão Municipal',
      description: 'Emissão de certidões municipais',
      departmentCode: 'PLANEJAMENTO_URBANO',
      serviceType: 'COM_DADOS',
      moduleType: 'SOLICITACAO_CERTIDAO',
      requiresDocuments: true,
      requiredDocuments: ['RG', 'CPF', 'Documentação do Imóvel'],
      estimatedDays: 5,
      priority: 3,
      category: 'Certidão',
      icon: 'FileText',
      color: '#312e81',
      formSchema: {
        type: 'object',
        properties: {
          nome: { type: 'string', title: 'Nome Completo', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          tipoCertidao: { type: 'string', title: 'Tipo de Certidão', enum: ['Certidão de Uso do Solo', 'Certidão de Valor Venal', 'Certidão de Zoneamento', 'Certidão Negativa de Débitos', 'Certidão de Regularidade de Obra', 'Outra'] },
          finalidade: { type: 'string', title: 'Finalidade da Certidão', maxLength: 200 },
          enderecoImovel: { type: 'string', title: 'Endereço do Imóvel (se aplicável)', maxLength: 300 },
          inscricaoImobiliaria: { type: 'string', title: 'Inscrição Imobiliária', maxLength: 50 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'tipoCertidao', 'finalidade'],
      },
    },
  {
      name: 'Denúncia de Construção Irregular',
      description: 'Registro de denúncias de obras irregulares',
      departmentCode: 'PLANEJAMENTO_URBANO',
      serviceType: 'COM_DADOS',
      moduleType: 'DENUNCIA_CONSTRUCAO_IRREGULAR',
      requiresDocuments: false,
      estimatedDays: 10,
      priority: 4,
      category: 'Denúncia',
      icon: 'AlertTriangle',
      color: '#dc2626',
      formSchema: {
        type: 'object',
        properties: {
          nome: { type: 'string', title: 'Nome Completo do Denunciante', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF do Denunciante', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          enderecoObraIrregular: { type: 'string', title: 'Endereço da Obra Irregular', maxLength: 300 },
          tipoIrregularidade: { type: 'string', title: 'Tipo de Irregularidade', enum: ['Construção sem Licença', 'Ampliação Irregular', 'Obra em Área de Preservação', 'Desrespeito ao Projeto Aprovado', 'Invasão de Via Pública', 'Outra'] },
          descricaoDenuncia: { type: 'string', title: 'Descrição Detalhada da Denúncia', minLength: 30, maxLength: 1000 },
          denunciaAnonima: { type: 'boolean', title: 'Deseja fazer a denúncia de forma anônima?' },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'enderecoObraIrregular', 'tipoIrregularidade', 'descricaoDenuncia'],
      },
    },
  {
      name: 'Cadastro de Loteamento',
      description: 'Registro e aprovação de loteamentos',
      departmentCode: 'PLANEJAMENTO_URBANO',
      serviceType: 'COM_DADOS',
      moduleType: 'CADASTRO_LOTEAMENTO',
      requiresDocuments: true,
      requiredDocuments: ['Projeto de Loteamento', 'Matrícula', 'Estudos Técnicos', 'ART'],
      estimatedDays: 90,
      priority: 5,
      category: 'Loteamento',
      icon: 'Grid3x3',
      color: '#6366f1',
      formSchema: {
        type: 'object',
        properties: {
          nome: { type: 'string', title: 'Nome Completo do Responsável', minLength: 3, maxLength: 200 },
          cpf: { type: 'string', title: 'CPF do Responsável', pattern: '^\\d{11}$', minLength: 11, maxLength: 11 },
          rg: { type: 'string', title: 'RG', minLength: 5, maxLength: 20 },
          dataNascimento: { type: 'string', format: 'date', title: 'Data de Nascimento' },
          email: { type: 'string', format: 'email', title: 'E-mail' },
          telefone: { type: 'string', title: 'Telefone Principal', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          telefoneSecundario: { type: 'string', title: 'Telefone Secundário', pattern: '^\\d{10,11}$', minLength: 10, maxLength: 11 },
          cep: { type: 'string', title: 'CEP', pattern: '^\\d{8}$', minLength: 8, maxLength: 8 },
          logradouro: { type: 'string', title: 'Rua/Avenida', minLength: 3, maxLength: 200 },
          numero: { type: 'string', title: 'Número', maxLength: 10 },
          complemento: { type: 'string', title: 'Complemento', maxLength: 100 },
          bairro: { type: 'string', title: 'Bairro', minLength: 2, maxLength: 100 },
          pontoReferencia: { type: 'string', title: 'Ponto de Referência', maxLength: 200 },
          nomeMae: { type: 'string', title: 'Nome da Mãe', minLength: 3, maxLength: 200 },
          estadoCivil: { type: 'string', title: 'Estado Civil', enum: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
          profissao: { type: 'string', title: 'Profissão/Ocupação', maxLength: 100 },
          rendaFamiliar: { type: 'string', title: 'Faixa de Renda Familiar', enum: ['Até 1 salário mínimo', '1 a 2 salários mínimos', '2 a 3 salários mínimos', '3 a 5 salários mínimos', 'Acima de 5 salários mínimos'] },
          nomeLoteamento: { type: 'string', title: 'Nome do Loteamento', maxLength: 200 },
          enderecoGleba: { type: 'string', title: 'Endereço da Gleba', maxLength: 300 },
          areaTotal: { type: 'number', title: 'Área Total da Gleba (m²)', minimum: 1000 },
          numeroLotes: { type: 'integer', title: 'Número de Lotes', minimum: 1 },
          areaLotesPadrao: { type: 'number', title: 'Área Padrão dos Lotes (m²)', minimum: 1 },
          numeroMatricula: { type: 'string', title: 'Número da Matrícula da Gleba', maxLength: 50 },
          nomeResponsavelTecnico: { type: 'string', title: 'Nome do Responsável Técnico', maxLength: 200 },
          creaResponsavel: { type: 'string', title: 'CREA do Responsável', maxLength: 50 },
          numeroART: { type: 'string', title: 'Número da ART', maxLength: 50 },
          infraestrutura: { type: 'string', title: 'Infraestrutura Prevista', maxLength: 500 },
          observacoes: { type: 'string', title: 'Observações', maxLength: 500 },
        },
        required: ['nome', 'cpf', 'dataNascimento', 'email', 'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'nomeMae', 'nomeLoteamento', 'enderecoGleba', 'areaTotal', 'numeroLotes', 'areaLotesPadrao', 'numeroMatricula', 'nomeResponsavelTecnico', 'creaResponsavel', 'numeroART'],
      },
    },
  {
      name: 'Consultas Públicas (Plano Diretor)',
      description: 'Participação em audiências e consultas públicas',
      departmentCode: 'PLANEJAMENTO_URBANO',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: false,
      estimatedDays: null,
      priority: 1,
      category: 'Informativo',
      icon: 'Users',
      color: '#94a3b8',
    },
  {
      name: 'Mapa Urbano (Zoneamento)',
      description: 'Consulta ao mapa de zoneamento e uso do solo',
      departmentCode: 'PLANEJAMENTO_URBANO',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: false,
      estimatedDays: null,
      priority: 1,
      category: 'Informativo',
      icon: 'Map',
      color: '#94a3b8',
    },
  {
      name: 'Certidão de Viabilidade de Construção',
      description: 'Emissão de certidão atestando viabilidade de construção',
      departmentCode: 'PLANEJAMENTO_URBANO',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: true,
      requiredDocuments: ['CPF', 'RG', 'Matrícula do Imóvel', 'Planta de Situação'],
      estimatedDays: 10,
      priority: 3,
      category: 'Certidões',
      icon: 'FileText',
      color: '#6366f1',
    },
  {
      name: 'Atestado de Regularidade de Obra',
      description: 'Emissão de atestado confirmando regularidade da obra',
      departmentCode: 'PLANEJAMENTO_URBANO',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: true,
      requiredDocuments: ['CPF', 'RG', 'Alvará de Construção', 'ART'],
      estimatedDays: 15,
      priority: 3,
      category: 'Atestados',
      icon: 'CheckCircle',
      color: '#6366f1',
    },
  {
      name: 'Laudo de Vistoria Técnica',
      description: 'Emissão de laudo técnico de vistoria de imóvel',
      departmentCode: 'PLANEJAMENTO_URBANO',
      serviceType: 'SEM_DADOS',
      moduleType: null,
      requiresDocuments: true,
      requiredDocuments: ['CPF', 'RG', 'Comprovante de Propriedade', 'ART do Responsável'],
      estimatedDays: 15,
      priority: 3,
      category: 'Laudos',
      icon: 'ClipboardCheck',
      color: '#6366f1',
    }
];
