import { ServiceSuggestion, ServiceType, ServiceSubtype } from './types';

export const administracaoSuggestions: ServiceSuggestion[] = [
  {
    id: 'protocolo-documento',
    name: 'Protocolo de Documento',
    description: 'Abertura de protocolo para entrega de documentos oficiais',
    icon: 'FileInput',
    category: 'Protocolo',
    estimatedDays: 1,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'tipo_documento', type: 'select', label: 'Tipo de Documento', required: true },
      { name: 'destinatario', type: 'select', label: 'Setor Destinatário', required: true },
      { name: 'assunto', type: 'textarea', label: 'Assunto', required: true },
      { name: 'urgente', type: 'checkbox', label: 'Documento Urgente', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'consulta-protocolo',
    name: 'Consulta de Protocolo',
    description: 'Consulte o andamento de protocolos abertos',
    icon: 'Search',
    category: 'Protocolo',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_protocolo', type: 'text', label: 'Número do Protocolo', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'ADMINISTRACAO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'declaracao-funcional',
    name: 'Declaração Funcional',
    description: 'Solicite declaração funcional ou de tempo de serviço',
    icon: 'FileText',
    category: 'Recursos Humanos',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_declaracao', type: 'select', label: 'Tipo de Declaração', required: true },
      { name: 'matricula', type: 'text', label: 'Matrícula', required: true },
      { name: 'finalidade', type: 'textarea', label: 'Finalidade', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'ferias-servidor',
    name: 'Agendamento de Férias',
    description: 'Agende o período de férias para servidores públicos',
    icon: 'Calendar',
    category: 'Recursos Humanos',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'matricula', type: 'text', label: 'Matrícula', required: true },
      { name: 'data_inicio', type: 'date', label: 'Data de Início', required: true },
      { name: 'quantidade_dias', type: 'number', label: 'Quantidade de Dias', required: true },
      { name: 'abono_pecuniario', type: 'checkbox', label: 'Solicitar Abono Pecuniário', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'contracheque-servidor',
    name: 'Segunda Via de Contracheque',
    description: 'Emita segunda via de contracheque',
    icon: 'Receipt',
    category: 'Recursos Humanos',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'matricula', type: 'text', label: 'Matrícula', required: true },
      { name: 'mes_referencia', type: 'select', label: 'Mês de Referência', required: true },
      { name: 'ano_referencia', type: 'select', label: 'Ano de Referência', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'ADMINISTRACAO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'patrimonio-cadastro',
    name: 'Cadastro de Bem Patrimonial',
    description: 'Registre novos bens no patrimônio público',
    icon: 'Package',
    category: 'Patrimônio',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'descricao_bem', type: 'text', label: 'Descrição do Bem', required: true },
      { name: 'tipo_bem', type: 'select', label: 'Tipo de Bem', required: true },
      { name: 'valor_aquisicao', type: 'number', label: 'Valor de Aquisição', required: true },
      { name: 'data_aquisicao', type: 'date', label: 'Data de Aquisição', required: true },
      { name: 'localizacao', type: 'text', label: 'Localização Física', required: true },
      { name: 'estado_conservacao', type: 'select', label: 'Estado de Conservação', required: true },
      { name: 'numero_nota_fiscal', type: 'text', label: 'Número da Nota Fiscal', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'patrimonio-transferencia',
    name: 'Transferência de Bem Patrimonial',
    description: 'Solicite transferência de bem entre setores',
    icon: 'ArrowRightLeft',
    category: 'Patrimônio',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_patrimonio', type: 'text', label: 'Número do Patrimônio', required: true },
      { name: 'setor_origem', type: 'select', label: 'Setor de Origem', required: true },
      { name: 'setor_destino', type: 'select', label: 'Setor de Destino', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'patrimonio-baixa',
    name: 'Baixa de Bem Patrimonial',
    description: 'Solicite baixa de bem patrimonial inservível',
    icon: 'Trash2',
    category: 'Patrimônio',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'numero_patrimonio', type: 'text', label: 'Número do Patrimônio', required: true },
      { name: 'motivo_baixa', type: 'select', label: 'Motivo da Baixa', required: true },
      { name: 'descricao_estado', type: 'textarea', label: 'Descrição do Estado Atual', required: true },
      { name: 'valor_residual', type: 'number', label: 'Valor Residual', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 2,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'almoxarifado-requisicao',
    name: 'Requisição de Material',
    description: 'Solicite materiais do almoxarifado',
    icon: 'ClipboardList',
    category: 'Almoxarifado',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'setor_solicitante', type: 'select', label: 'Setor Solicitante', required: true },
      { name: 'descricao_material', type: 'textarea', label: 'Descrição do Material', required: true },
      { name: 'quantidade', type: 'number', label: 'Quantidade', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
      { name: 'urgente', type: 'checkbox', label: 'Requisição Urgente', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'almoxarifado-consulta-estoque',
    name: 'Consulta de Estoque',
    description: 'Consulte disponibilidade de materiais no almoxarifado',
    icon: 'Search',
    category: 'Almoxarifado',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'codigo_material', type: 'text', label: 'Código do Material', required: false },
      { name: 'descricao', type: 'text', label: 'Descrição', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'ADMINISTRACAO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'veiculo-agendamento',
    name: 'Agendamento de Veículo Oficial',
    description: 'Agende o uso de veículo oficial',
    icon: 'Car',
    category: 'Frotas',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'data_uso', type: 'date', label: 'Data do Uso', required: true },
      { name: 'hora_inicio', type: 'text', label: 'Hora de Início', required: true },
      { name: 'hora_fim', type: 'text', label: 'Hora de Término', required: true },
      { name: 'tipo_veiculo', type: 'select', label: 'Tipo de Veículo', required: true },
      { name: 'destino', type: 'text', label: 'Destino', required: true },
      { name: 'finalidade', type: 'textarea', label: 'Finalidade', required: true },
      { name: 'motorista_proprio', type: 'checkbox', label: 'Possui Motorista Próprio', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'veiculo-manutencao',
    name: 'Solicitação de Manutenção de Veículo',
    description: 'Solicite manutenção preventiva ou corretiva de veículo oficial',
    icon: 'Wrench',
    category: 'Frotas',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'tipo_manutencao', type: 'select', label: 'Tipo de Manutenção', required: true },
      { name: 'descricao_problema', type: 'textarea', label: 'Descrição do Problema', required: true },
      { name: 'quilometragem', type: 'number', label: 'Quilometragem Atual', required: true },
      { name: 'urgente', type: 'checkbox', label: 'Manutenção Urgente', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'veiculo-abastecimento',
    name: 'Registro de Abastecimento',
    description: 'Registre abastecimento de veículo oficial',
    icon: 'Fuel',
    category: 'Frotas',
    estimatedDays: 1,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'data_abastecimento', type: 'date', label: 'Data do Abastecimento', required: true },
      { name: 'quantidade_litros', type: 'number', label: 'Quantidade (Litros)', required: true },
      { name: 'valor_total', type: 'number', label: 'Valor Total', required: true },
      { name: 'posto', type: 'text', label: 'Posto de Combustível', required: true },
      { name: 'quilometragem', type: 'number', label: 'Quilometragem', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 4,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'licitacao-consulta',
    name: 'Consulta de Licitações',
    description: 'Consulte licitações em andamento ou encerradas',
    icon: 'FileSearch',
    category: 'Licitações',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_licitacao', type: 'text', label: 'Número da Licitação', required: false },
      { name: 'modalidade', type: 'select', label: 'Modalidade', required: false },
      { name: 'status', type: 'select', label: 'Status', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'ADMINISTRACAO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'licitacao-edital',
    name: 'Solicitação de Edital',
    description: 'Solicite cópia de edital de licitação',
    icon: 'Download',
    category: 'Licitações',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_licitacao', type: 'text', label: 'Número da Licitação', required: true },
      { name: 'formato', type: 'select', label: 'Formato', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'licitacao-habilitacao',
    name: 'Habilitação de Fornecedor',
    description: 'Habilite-se como fornecedor em processos licitatórios',
    icon: 'UserCheck',
    category: 'Licitações',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'razao_social', type: 'text', label: 'Razão Social', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'ramo_atividade', type: 'text', label: 'Ramo de Atividade', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'endereco_completo', type: 'textarea', label: 'Endereço Completo', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'contrato-consulta',
    name: 'Consulta de Contratos',
    description: 'Consulte contratos administrativos vigentes',
    icon: 'FileText',
    category: 'Contratos',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_contrato', type: 'text', label: 'Número do Contrato', required: false },
      { name: 'contratada', type: 'text', label: 'Empresa Contratada', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'ADMINISTRACAO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'contrato-aditivo',
    name: 'Solicitação de Aditivo Contratual',
    description: 'Solicite termo aditivo de contrato',
    icon: 'FilePlus',
    category: 'Contratos',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'numero_contrato', type: 'text', label: 'Número do Contrato', required: true },
      { name: 'tipo_aditivo', type: 'select', label: 'Tipo de Aditivo', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
      { name: 'valor_acrescimo', type: 'number', label: 'Valor do Acréscimo', required: false },
      { name: 'prazo_adicional', type: 'number', label: 'Prazo Adicional (dias)', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 2,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'ouvidoria-manifestacao',
    name: 'Registro de Manifestação',
    description: 'Registre elogio, sugestão, reclamação ou denúncia',
    icon: 'MessageSquare',
    category: 'Ouvidoria',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_manifestacao', type: 'select', label: 'Tipo de Manifestação', required: true },
      { name: 'orgao_relacionado', type: 'select', label: 'Órgão Relacionado', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição Detalhada', required: true },
      { name: 'anonimo', type: 'checkbox', label: 'Manifestação Anônima', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'ouvidoria-acompanhamento',
    name: 'Acompanhamento de Manifestação',
    description: 'Acompanhe o andamento da sua manifestação',
    icon: 'Eye',
    category: 'Ouvidoria',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_protocolo', type: 'text', label: 'Número do Protocolo', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'ADMINISTRACAO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'estagio-inscricao',
    name: 'Inscrição para Estágio',
    description: 'Inscreva-se em programa de estágio na administração pública',
    icon: 'GraduationCap',
    category: 'Recursos Humanos',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'area_interesse', type: 'select', label: 'Área de Interesse', required: true },
      { name: 'curso', type: 'text', label: 'Curso', required: true },
      { name: 'instituicao_ensino', type: 'text', label: 'Instituição de Ensino', required: true },
      { name: 'periodo_curso', type: 'text', label: 'Período do Curso', required: true },
      { name: 'turno_disponivel', type: 'select', label: 'Turno Disponível', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'concurso-consulta',
    name: 'Consulta de Concursos Públicos',
    description: 'Consulte editais de concursos públicos',
    icon: 'Users',
    category: 'Recursos Humanos',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'cargo', type: 'text', label: 'Cargo', required: false },
      { name: 'status', type: 'select', label: 'Status', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'ADMINISTRACAO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'ponto-eletronico-ajuste',
    name: 'Solicitação de Ajuste de Ponto',
    description: 'Solicite correção de registro de ponto eletrônico',
    icon: 'Clock',
    category: 'Recursos Humanos',
    estimatedDays: 7,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'matricula', type: 'text', label: 'Matrícula', required: true },
      { name: 'data_ajuste', type: 'date', label: 'Data do Ajuste', required: true },
      { name: 'tipo_ajuste', type: 'select', label: 'Tipo de Ajuste', required: true },
      { name: 'horario_correto', type: 'text', label: 'Horário Correto', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'licenca-servidor',
    name: 'Solicitação de Licença',
    description: 'Solicite licença médica, maternidade ou outras',
    icon: 'Calendar',
    category: 'Recursos Humanos',
    estimatedDays: 5,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'matricula', type: 'text', label: 'Matrícula', required: true },
      { name: 'tipo_licenca', type: 'select', label: 'Tipo de Licença', required: true },
      { name: 'data_inicio', type: 'date', label: 'Data de Início', required: true },
      { name: 'data_fim', type: 'date', label: 'Data de Término', required: true },
      { name: 'observacoes', type: 'textarea', label: 'Observações', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'progressao-funcional',
    name: 'Solicitação de Progressão Funcional',
    description: 'Solicite progressão ou promoção funcional',
    icon: 'TrendingUp',
    category: 'Recursos Humanos',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'matricula', type: 'text', label: 'Matrícula', required: true },
      { name: 'tipo_progressao', type: 'select', label: 'Tipo de Progressão', required: true },
      { name: 'tempo_servico', type: 'number', label: 'Tempo de Serviço (anos)', required: true },
      { name: 'qualificacoes', type: 'textarea', label: 'Qualificações/Cursos', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 2,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'capacitacao-inscricao',
    name: 'Inscrição em Curso de Capacitação',
    description: 'Inscreva-se em cursos de capacitação para servidores',
    icon: 'BookOpen',
    category: 'Recursos Humanos',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'matricula', type: 'text', label: 'Matrícula', required: true },
      { name: 'curso', type: 'select', label: 'Curso', required: true },
      { name: 'turma', type: 'select', label: 'Turma', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'processo-administrativo',
    name: 'Abertura de Processo Administrativo',
    description: 'Abra processo administrativo disciplinar ou apuratório',
    icon: 'AlertTriangle',
    category: 'Protocolo',
    estimatedDays: 60,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'tipo_processo', type: 'select', label: 'Tipo de Processo', required: true },
      { name: 'servidor_envolvido', type: 'text', label: 'Servidor Envolvido', required: false },
      { name: 'relato_fatos', type: 'textarea', label: 'Relato dos Fatos', required: true },
      { name: 'data_ocorrencia', type: 'date', label: 'Data da Ocorrência', required: true },
      { name: 'testemunhas', type: 'textarea', label: 'Testemunhas', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 2,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'aposentadoria-requerimento',
    name: 'Requerimento de Aposentadoria',
    description: 'Solicite processo de aposentadoria',
    icon: 'Home',
    category: 'Recursos Humanos',
    estimatedDays: 90,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'matricula', type: 'text', label: 'Matrícula', required: true },
      { name: 'tipo_aposentadoria', type: 'select', label: 'Tipo de Aposentadoria', required: true },
      { name: 'tempo_contribuicao', type: 'number', label: 'Tempo de Contribuição (anos)', required: true },
      { name: 'data_nascimento', type: 'date', label: 'Data de Nascimento', required: true },
      { name: 'data_admissao', type: 'date', label: 'Data de Admissão', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 2,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'beneficio-servidor',
    name: 'Solicitação de Benefício',
    description: 'Solicite auxílio-alimentação, transporte ou outros benefícios',
    icon: 'Gift',
    category: 'Recursos Humanos',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'matricula', type: 'text', label: 'Matrícula', required: true },
      { name: 'tipo_beneficio', type: 'select', label: 'Tipo de Benefício', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'seguro-veiculo',
    name: 'Acionamento de Seguro de Veículo',
    description: 'Acione seguro de veículo oficial em caso de sinistro',
    icon: 'Shield',
    category: 'Frotas',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'tipo_sinistro', type: 'select', label: 'Tipo de Sinistro', required: true },
      { name: 'data_ocorrencia', type: 'date', label: 'Data da Ocorrência', required: true },
      { name: 'descricao_sinistro', type: 'textarea', label: 'Descrição do Sinistro', required: true },
      { name: 'boletim_ocorrencia', type: 'text', label: 'Número do B.O.', required: false },
      { name: 'terceiros_envolvidos', type: 'checkbox', label: 'Há Terceiros Envolvidos', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 2,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'diarias-viagem',
    name: 'Solicitação de Diárias de Viagem',
    description: 'Solicite diárias para viagens a serviço',
    icon: 'Plane',
    category: 'Recursos Humanos',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'matricula', type: 'text', label: 'Matrícula', required: true },
      { name: 'destino', type: 'text', label: 'Destino', required: true },
      { name: 'data_inicio', type: 'date', label: 'Data de Início', required: true },
      { name: 'data_fim', type: 'date', label: 'Data de Término', required: true },
      { name: 'finalidade', type: 'textarea', label: 'Finalidade da Viagem', required: true },
      { name: 'quantidade_diarias', type: 'number', label: 'Quantidade de Diárias', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'central-atendimento',
    name: 'Agendamento na Central de Atendimento',
    description: 'Agende atendimento presencial em departamentos administrativos',
    icon: 'CalendarCheck',
    category: 'Protocolo',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'departamento', type: 'select', label: 'Departamento', required: true },
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
      { name: 'horario_preferencia', type: 'select', label: 'Horário de Preferência', required: true },
      { name: 'assunto', type: 'textarea', label: 'Assunto', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'certidao-tempo-servico',
    name: 'Certidão de Tempo de Serviço',
    description: 'Emita certidão de tempo de serviço público',
    icon: 'FileText',
    category: 'Recursos Humanos',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'matricula', type: 'text', label: 'Matrícula', required: true },
      { name: 'finalidade', type: 'select', label: 'Finalidade', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'adicional-noturno',
    name: 'Solicitação de Adicional Noturno',
    description: 'Solicite reconhecimento de horas trabalhadas no período noturno',
    icon: 'Moon',
    category: 'Recursos Humanos',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'matricula', type: 'text', label: 'Matrícula', required: true },
      { name: 'mes_referencia', type: 'select', label: 'Mês de Referência', required: true },
      { name: 'total_horas_noturnas', type: 'number', label: 'Total de Horas Noturnas', required: true },
      { name: 'setor_trabalho', type: 'text', label: 'Setor de Trabalho', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'inventario-patrimonio',
    name: 'Participação em Inventário Patrimonial',
    description: 'Registre participação em comissão de inventário',
    icon: 'ClipboardCheck',
    category: 'Patrimônio',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'setor_responsavel', type: 'select', label: 'Setor Responsável', required: true },
      { name: 'data_inicio', type: 'date', label: 'Data de Início', required: true },
      { name: 'observacoes', type: 'textarea', label: 'Observações', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 2,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'ata-registro-precos',
    name: 'Consulta de Ata de Registro de Preços',
    description: 'Consulte atas de registro de preços vigentes',
    icon: 'FileSpreadsheet',
    category: 'Licitações',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_ata', type: 'text', label: 'Número da Ata', required: false },
      { name: 'tipo_material', type: 'text', label: 'Tipo de Material/Serviço', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'ADMINISTRACAO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'credenciamento-fornecedor',
    name: 'Credenciamento de Fornecedor',
    description: 'Credenciamento para fornecimento de bens e serviços',
    icon: 'Building',
    category: 'Licitações',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'razao_social', type: 'text', label: 'Razão Social', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'tipo_fornecimento', type: 'select', label: 'Tipo de Fornecimento', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco', type: 'textarea', label: 'Endereço Completo', required: true },
      { name: 'produtos_servicos', type: 'textarea', label: 'Produtos/Serviços Oferecidos', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'desistencia-licitacao',
    name: 'Desistência de Licitação',
    description: 'Registre desistência de participação em processo licitatório',
    icon: 'XCircle',
    category: 'Licitações',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_licitacao', type: 'text', label: 'Número da Licitação', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'motivo_desistencia', type: 'textarea', label: 'Motivo da Desistência', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'recurso-licitacao',
    name: 'Interposição de Recurso em Licitação',
    description: 'Interponha recurso administrativo em processo licitatório',
    icon: 'Scale',
    category: 'Licitações',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'numero_licitacao', type: 'text', label: 'Número da Licitação', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'fase_recurso', type: 'select', label: 'Fase do Recurso', required: true },
      { name: 'fundamentacao', type: 'textarea', label: 'Fundamentação do Recurso', required: true },
      { name: 'pedido', type: 'textarea', label: 'Pedido', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 2,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'atualizacao-cadastro-servidor',
    name: 'Atualização de Dados Cadastrais',
    description: 'Atualize seus dados cadastrais como servidor',
    icon: 'UserCog',
    category: 'Recursos Humanos',
    estimatedDays: 5,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'matricula', type: 'text', label: 'Matrícula', required: true },
      { name: 'tipo_atualizacao', type: 'select', label: 'Tipo de Atualização', required: true },
      { name: 'dados_novos', type: 'textarea', label: 'Dados Atualizados', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'malote-correspondencia',
    name: 'Envio de Correspondência Oficial',
    description: 'Envie correspondência através do malote oficial',
    icon: 'Mail',
    category: 'Protocolo',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'setor_remetente', type: 'select', label: 'Setor Remetente', required: true },
      { name: 'destinatario', type: 'text', label: 'Destinatário', required: true },
      { name: 'endereco_destino', type: 'textarea', label: 'Endereço de Destino', required: true },
      { name: 'tipo_correspondencia', type: 'select', label: 'Tipo de Correspondência', required: true },
      { name: 'urgente', type: 'checkbox', label: 'Correspondência Urgente', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'cessao-servidor',
    name: 'Solicitação de Cessão de Servidor',
    description: 'Solicite cessão de servidor para outro órgão',
    icon: 'UserMinus',
    category: 'Recursos Humanos',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'matricula', type: 'text', label: 'Matrícula', required: true },
      { name: 'orgao_destino', type: 'text', label: 'Órgão de Destino', required: true },
      { name: 'tipo_cessao', type: 'select', label: 'Tipo de Cessão', required: true },
      { name: 'prazo_cessao', type: 'number', label: 'Prazo da Cessão (meses)', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'ADMINISTRACAO',
    priority: 2,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'acesso-informacao',
    name: 'Solicitação de Informação Pública',
    description: 'Solicite acesso a informações públicas (LAI)',
    icon: 'Info',
    category: 'Ouvidoria',
    estimatedDays: 20,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'informacao_solicitada', type: 'textarea', label: 'Informação Solicitada', required: true },
      { name: 'orgao_relacionado', type: 'select', label: 'Órgão Relacionado', required: false },
      { name: 'formato_resposta', type: 'select', label: 'Formato de Resposta', required: true },
      { name: 'anonimo', type: 'checkbox', label: 'Solicitação Anônima', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'recurso-manifestacao',
    name: 'Recurso de Manifestação',
    description: 'Interponha recurso contra resposta da ouvidoria',
    icon: 'MessageSquarePlus',
    category: 'Ouvidoria',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_protocolo', type: 'text', label: 'Número do Protocolo', required: true },
      { name: 'motivo_recurso', type: 'textarea', label: 'Motivo do Recurso', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'ADMINISTRACAO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'pesquisa-satisfacao',
    name: 'Pesquisa de Satisfação',
    description: 'Responda pesquisa de satisfação sobre serviços administrativos',
    icon: 'Star',
    category: 'Ouvidoria',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'servico_avaliado', type: 'select', label: 'Serviço Avaliado', required: true },
      { name: 'nota_atendimento', type: 'number', label: 'Nota de Atendimento (0-10)', required: true },
      { name: 'comentarios', type: 'textarea', label: 'Comentários', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'ADMINISTRACAO',
    priority: 4,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
];
