import { ServiceSuggestion, ServiceType, ServiceSubtype } from './types';

export const defesaCivilSuggestions: ServiceSuggestion[] = [
  {
    id: 'alerta-emergencia',
    name: 'Acionamento de Emergência',
    description: 'Acione a Defesa Civil em situações de emergência',
    icon: 'AlertTriangle',
    category: 'Emergências',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_emergencia', type: 'select', label: 'Tipo de Emergência', required: true },
      { name: 'endereco_ocorrencia', type: 'text', label: 'Endereço da Ocorrência', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição da Situação', required: true },
      { name: 'pessoas_risco', type: 'checkbox', label: 'Há Pessoas em Risco', required: false },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 5,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'cadastro-area-risco',
    name: 'Cadastro de Área de Risco',
    description: 'Cadastre áreas de risco na sua região',
    icon: 'MapPin',
    category: 'Cadastro de Áreas de Risco',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_risco', type: 'select', label: 'Tipo de Risco', required: true },
      { name: 'descricao_detalhada', type: 'textarea', label: 'Descrição Detalhada', required: true },
      { name: 'quantidade_moradias', type: 'number', label: 'Quantidade de Moradias Afetadas', required: false },
      { name: 'historico_ocorrencias', type: 'textarea', label: 'Histórico de Ocorrências', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 4,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'vistoria-imovel',
    name: 'Solicitação de Vistoria',
    description: 'Solicite vistoria técnica em imóvel',
    icon: 'ClipboardCheck',
    category: 'Prevenção',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco_imovel', type: 'text', label: 'Endereço do Imóvel', required: true },
      { name: 'motivo_vistoria', type: 'select', label: 'Motivo da Vistoria', required: true },
      { name: 'descricao_problema', type: 'textarea', label: 'Descrição do Problema', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'laudo-tecnico',
    name: 'Solicitação de Laudo Técnico',
    description: 'Solicite laudo técnico de vistoria realizada',
    icon: 'FileText',
    category: 'Prevenção',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_vistoria', type: 'text', label: 'Número da Vistoria', required: true },
      { name: 'finalidade', type: 'select', label: 'Finalidade do Laudo', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'cadastro-voluntario',
    name: 'Cadastro de Voluntário',
    description: 'Cadastre-se como voluntário da Defesa Civil',
    icon: 'Users',
    category: 'Voluntariado',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'area_atuacao', type: 'select', label: 'Área de Atuação', required: true },
      { name: 'experiencia_previa', type: 'textarea', label: 'Experiência Prévia', required: false },
      { name: 'disponibilidade', type: 'select', label: 'Disponibilidade', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'formacao', type: 'text', label: 'Formação', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'curso-capacitacao',
    name: 'Inscrição em Curso de Capacitação',
    description: 'Inscreva-se em cursos de capacitação em Defesa Civil',
    icon: 'GraduationCap',
    category: 'Capacitação',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'curso', type: 'select', label: 'Curso', required: true },
      { name: 'turma', type: 'select', label: 'Turma', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'doacao-desastre',
    name: 'Registro de Doação',
    description: 'Registre doação para vítimas de desastres',
    icon: 'Heart',
    category: 'Doações',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_doacao', type: 'select', label: 'Tipo de Doação', required: true },
      { name: 'descricao_itens', type: 'textarea', label: 'Descrição dos Itens', required: true },
      { name: 'quantidade', type: 'text', label: 'Quantidade', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
      { name: 'endereco_coleta', type: 'text', label: 'Endereço para Coleta', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'abrigo-temporario',
    name: 'Solicitação de Abrigo Temporário',
    description: 'Solicite vaga em abrigo temporário',
    icon: 'Home',
    category: 'Emergências',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'quantidade_pessoas', type: 'number', label: 'Quantidade de Pessoas', required: true },
      { name: 'motivo', type: 'select', label: 'Motivo da Solicitação', required: true },
      { name: 'necessidades_especiais', type: 'textarea', label: 'Necessidades Especiais', required: false },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 5,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'auxilio-reconstrucao',
    name: 'Solicitação de Auxílio para Reconstrução',
    description: 'Solicite auxílio para reconstrução de imóvel afetado',
    icon: 'Hammer',
    category: 'Emergências',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'endereco_imovel', type: 'text', label: 'Endereço do Imóvel', required: true },
      { name: 'tipo_desastre', type: 'select', label: 'Tipo de Desastre', required: true },
      { name: 'data_ocorrencia', type: 'date', label: 'Data da Ocorrência', required: true },
      { name: 'danos_estruturais', type: 'textarea', label: 'Descrição dos Danos', required: true },
      { name: 'numero_moradores', type: 'number', label: 'Número de Moradores', required: true },
      { name: 'renda_familiar', type: 'number', label: 'Renda Familiar', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 4,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'monitoramento-chuvas',
    name: 'Consulta de Monitoramento de Chuvas',
    description: 'Consulte dados de monitoramento pluviométrico',
    icon: 'CloudRain',
    category: 'Alerta',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'regiao', type: 'select', label: 'Região', required: false },
      { name: 'periodo', type: 'select', label: 'Período', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DEFESA_CIVIL',
    priority: 4,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'plano-contingencia',
    name: 'Consulta de Plano de Contingência',
    description: 'Consulte planos de contingência municipais',
    icon: 'BookOpen',
    category: 'Prevenção',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_desastre', type: 'select', label: 'Tipo de Desastre', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'alerta-sms',
    name: 'Cadastro para Alertas SMS',
    description: 'Cadastre-se para receber alertas de emergência por SMS',
    icon: 'Bell',
    category: 'Alerta',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'telefone', type: 'tel', label: 'Telefone Celular', required: true },
      { name: 'regiao_interesse', type: 'select', label: 'Região de Interesse', required: true },
      { name: 'tipos_alerta', type: 'select', label: 'Tipos de Alerta', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'denuncia-construcao-irregular',
    name: 'Denúncia de Construção Irregular',
    description: 'Denuncie construções irregulares em áreas de risco',
    icon: 'AlertOctagon',
    category: 'Prevenção',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_irregularidade', type: 'select', label: 'Tipo de Irregularidade', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'anonimo', type: 'checkbox', label: 'Denúncia Anônima', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'kit-emergencia',
    name: 'Solicitação de Kit de Emergência',
    description: 'Solicite kit de emergência para famílias em situação de risco',
    icon: 'Package',
    category: 'Emergências',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'quantidade_pessoas', type: 'number', label: 'Quantidade de Pessoas', required: true },
      { name: 'tipo_situacao', type: 'select', label: 'Tipo de Situação', required: true },
      { name: 'endereco_entrega', type: 'text', label: 'Endereço para Entrega', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
      { name: 'necessidades_especificas', type: 'textarea', label: 'Necessidades Específicas', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DEFESA_CIVIL',
    priority: 4,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'ocorrencia-alagamento',
    name: 'Registro de Alagamento',
    description: 'Registre ocorrência de alagamento',
    icon: 'Droplet',
    category: 'Emergências',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'nivel_agua', type: 'select', label: 'Nível da Água', required: true },
      { name: 'imoveis_afetados', type: 'number', label: 'Imóveis Afetados', required: false },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 5,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'ocorrencia-deslizamento',
    name: 'Registro de Deslizamento',
    description: 'Registre ocorrência de deslizamento de terra',
    icon: 'Mountain',
    category: 'Emergências',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'extensao_area', type: 'text', label: 'Extensão da Área Afetada', required: true },
      { name: 'moradias_risco', type: 'number', label: 'Moradias em Risco', required: false },
      { name: 'vitimas', type: 'checkbox', label: 'Há Vítimas', required: false },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 5,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'remocao-preventiva',
    name: 'Solicitação de Remoção Preventiva',
    description: 'Solicite remoção preventiva de famílias em área de risco',
    icon: 'Truck',
    category: 'Emergências',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'quantidade_familias', type: 'number', label: 'Quantidade de Famílias', required: true },
      { name: 'total_pessoas', type: 'number', label: 'Total de Pessoas', required: true },
      { name: 'tipo_risco', type: 'select', label: 'Tipo de Risco', required: true },
      { name: 'urgencia', type: 'select', label: 'Nível de Urgência', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 5,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'mapa-risco',
    name: 'Consulta de Mapa de Risco',
    description: 'Consulte mapas de áreas de risco do município',
    icon: 'Map',
    category: 'Prevenção',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'regiao', type: 'select', label: 'Região', required: false },
      { name: 'tipo_risco', type: 'select', label: 'Tipo de Risco', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DEFESA_CIVIL',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'palestra-preventiva',
    name: 'Solicitação de Palestra Preventiva',
    description: 'Solicite palestra sobre prevenção de desastres',
    icon: 'Presentation',
    category: 'Capacitação',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'instituicao', type: 'text', label: 'Instituição', required: true },
      { name: 'tema', type: 'select', label: 'Tema', required: true },
      { name: 'publico_estimado', type: 'number', label: 'Público Estimado', required: true },
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
      { name: 'local', type: 'text', label: 'Local', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'simulado-evacuacao',
    name: 'Solicitação de Simulado de Evacuação',
    description: 'Solicite realização de simulado de evacuação',
    icon: 'PersonStanding',
    category: 'Capacitação',
    estimatedDays: 20,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'local', type: 'text', label: 'Local', required: true },
      { name: 'tipo_edificacao', type: 'select', label: 'Tipo de Edificação', required: true },
      { name: 'numero_pessoas', type: 'number', label: 'Número de Pessoas', required: true },
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'equipamento-protecao',
    name: 'Empréstimo de Equipamento de Proteção',
    description: 'Solicite empréstimo de equipamentos de proteção',
    icon: 'Shield',
    category: 'Voluntariado',
    estimatedDays: 5,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'tipo_equipamento', type: 'select', label: 'Tipo de Equipamento', required: true },
      { name: 'quantidade', type: 'number', label: 'Quantidade', required: true },
      { name: 'finalidade', type: 'textarea', label: 'Finalidade', required: true },
      { name: 'data_inicio', type: 'date', label: 'Data de Início', required: true },
      { name: 'data_devolucao', type: 'date', label: 'Data de Devolução', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'apoio-animais',
    name: 'Resgate de Animais em Área de Risco',
    description: 'Solicite resgate de animais em situação de emergência',
    icon: 'PawPrint',
    category: 'Emergências',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_animal', type: 'select', label: 'Tipo de Animal', required: true },
      { name: 'quantidade_animais', type: 'number', label: 'Quantidade de Animais', required: true },
      { name: 'situacao', type: 'textarea', label: 'Descrição da Situação', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DEFESA_CIVIL',
    priority: 4,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'certificado-voluntario',
    name: 'Solicitação de Certificado de Voluntário',
    description: 'Solicite certificado de participação em ações voluntárias',
    icon: 'Award',
    category: 'Voluntariado',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'periodo_atuacao', type: 'text', label: 'Período de Atuação', required: true },
      { name: 'atividades_realizadas', type: 'textarea', label: 'Atividades Realizadas', required: true },
      { name: 'finalidade', type: 'select', label: 'Finalidade', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'escala-plantao',
    name: 'Consulta de Escala de Plantão',
    description: 'Consulte escala de plantão da Defesa Civil',
    icon: 'Calendar',
    category: 'Alerta',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'periodo', type: 'select', label: 'Período', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DEFESA_CIVIL',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'ocorrencia-incendio',
    name: 'Registro de Incêndio',
    description: 'Registre ocorrência de incêndio',
    icon: 'Flame',
    category: 'Emergências',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_incendio', type: 'select', label: 'Tipo de Incêndio', required: true },
      { name: 'extensao', type: 'select', label: 'Extensão do Incêndio', required: true },
      { name: 'vitimas', type: 'checkbox', label: 'Há Vítimas', required: false },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 5,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'auxilio-lona',
    name: 'Solicitação de Lona para Cobertura',
    description: 'Solicite lona para cobertura emergencial de imóvel',
    icon: 'Tent',
    category: 'Emergências',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'motivo', type: 'select', label: 'Motivo', required: true },
      { name: 'area_afetada', type: 'text', label: 'Área Afetada (m²)', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DEFESA_CIVIL',
    priority: 4,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'analise-solo',
    name: 'Solicitação de Análise de Solo',
    description: 'Solicite análise técnica de estabilidade do solo',
    icon: 'Microscope',
    category: 'Prevenção',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'motivo_analise', type: 'select', label: 'Motivo da Análise', required: true },
      { name: 'descricao_area', type: 'textarea', label: 'Descrição da Área', required: true },
      { name: 'historico_problemas', type: 'textarea', label: 'Histórico de Problemas', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'desobstrucao-drenagem',
    name: 'Solicitação de Desobstrução de Drenagem',
    description: 'Solicite desobstrução de sistema de drenagem',
    icon: 'Waves',
    category: 'Prevenção',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_obstrucao', type: 'select', label: 'Tipo de Obstrução', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'urgente', type: 'checkbox', label: 'Situação Urgente', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DEFESA_CIVIL',
    priority: 4,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'relatorio-ocorrencia',
    name: 'Solicitação de Relatório de Ocorrência',
    description: 'Solicite relatório de ocorrência atendida',
    icon: 'FileBarChart',
    category: 'Emergências',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_ocorrencia', type: 'text', label: 'Número da Ocorrência', required: true },
      { name: 'finalidade', type: 'select', label: 'Finalidade', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'ponto-apoio',
    name: 'Cadastro de Ponto de Apoio',
    description: 'Cadastre local como ponto de apoio em emergências',
    icon: 'MapPinned',
    category: 'Voluntariado',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_estabelecimento', type: 'text', label: 'Nome do Estabelecimento', required: true },
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'capacidade', type: 'number', label: 'Capacidade de Pessoas', required: true },
      { name: 'recursos_disponiveis', type: 'textarea', label: 'Recursos Disponíveis', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'ocorrencia-vendaval',
    name: 'Registro de Vendaval',
    description: 'Registre ocorrência de vendaval ou tempestade',
    icon: 'Wind',
    category: 'Emergências',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_dano', type: 'select', label: 'Tipo de Dano', required: true },
      { name: 'imoveis_afetados', type: 'number', label: 'Imóveis Afetados', required: false },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 5,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'queda-arvore',
    name: 'Registro de Queda de Árvore',
    description: 'Registre queda de árvore em via pública',
    icon: 'Trees',
    category: 'Emergências',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'obstrui_via', type: 'checkbox', label: 'Obstrui a Via', required: false },
      { name: 'risco_fiacao', type: 'checkbox', label: 'Há Risco de Fiação Elétrica', required: false },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DEFESA_CIVIL',
    priority: 5,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'boletim-climatico',
    name: 'Consulta de Boletim Climático',
    description: 'Consulte boletins climáticos e previsões',
    icon: 'Cloud',
    category: 'Alerta',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'periodo', type: 'select', label: 'Período', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DEFESA_CIVIL',
    priority: 4,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'declaracao-desastre',
    name: 'Solicitação de Declaração de Situação de Emergência',
    description: 'Solicite declaração oficial de situação de emergência ou calamidade',
    icon: 'FileWarning',
    category: 'Emergências',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'tipo_desastre', type: 'select', label: 'Tipo de Desastre', required: true },
      { name: 'area_afetada', type: 'text', label: 'Área Afetada', required: true },
      { name: 'data_ocorrencia', type: 'date', label: 'Data da Ocorrência', required: true },
      { name: 'familias_afetadas', type: 'number', label: 'Famílias Afetadas', required: true },
      { name: 'danos_materiais', type: 'textarea', label: 'Descrição dos Danos', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 4,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'estacao-meteorologica',
    name: 'Dados de Estação Meteorológica',
    description: 'Consulte dados de estações meteorológicas municipais',
    icon: 'Gauge',
    category: 'Alerta',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'estacao', type: 'select', label: 'Estação', required: false },
      { name: 'periodo', type: 'select', label: 'Período', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DEFESA_CIVIL',
    priority: 4,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'nucleo-comunitario',
    name: 'Cadastro de NUDEC (Núcleo Comunitário)',
    description: 'Cadastre ou registre Núcleo Comunitário de Defesa Civil',
    icon: 'Users2',
    category: 'Voluntariado',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_nucleo', type: 'text', label: 'Nome do Núcleo', required: true },
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'coordenador', type: 'text', label: 'Nome do Coordenador', required: true },
      { name: 'telefone_coordenador', type: 'tel', label: 'Telefone do Coordenador', required: true },
      { name: 'area_atuacao', type: 'textarea', label: 'Área de Atuação', required: true },
      { name: 'numero_voluntarios', type: 'number', label: 'Número de Voluntários', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'plano-fuga',
    name: 'Elaboração de Plano de Fuga',
    description: 'Solicite auxílio para elaboração de plano de fuga familiar',
    icon: 'Route',
    category: 'Prevenção',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_risco', type: 'select', label: 'Tipo de Risco', required: true },
      { name: 'numero_moradores', type: 'number', label: 'Número de Moradores', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'historico-desastres',
    name: 'Consulta de Histórico de Desastres',
    description: 'Consulte histórico de desastres do município',
    icon: 'History',
    category: 'Prevenção',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_desastre', type: 'select', label: 'Tipo de Desastre', required: false },
      { name: 'periodo_inicio', type: 'date', label: 'Período Início', required: false },
      { name: 'periodo_fim', type: 'date', label: 'Período Fim', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'recursos-federais',
    name: 'Consulta de Recursos Federais Recebidos',
    description: 'Consulte recursos federais recebidos para recuperação de desastres',
    icon: 'DollarSign',
    category: 'Emergências',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'ano', type: 'select', label: 'Ano', required: false },
      { name: 'tipo_desastre', type: 'select', label: 'Tipo de Desastre', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'radiocomunicacao',
    name: 'Solicitação de Rádio Comunicador',
    description: 'Solicite empréstimo de rádio comunicador para voluntários',
    icon: 'Radio',
    category: 'Voluntariado',
    estimatedDays: 5,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'finalidade', type: 'textarea', label: 'Finalidade', required: true },
      { name: 'periodo_uso', type: 'text', label: 'Período de Uso', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'autorizacao-evento',
    name: 'Autorização para Evento em Área de Risco',
    description: 'Solicite autorização para evento em área classificada como risco',
    icon: 'CheckCircle',
    category: 'Prevenção',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'tipo_evento', type: 'text', label: 'Tipo de Evento', required: true },
      { name: 'local', type: 'text', label: 'Local', required: true },
      { name: 'data_evento', type: 'date', label: 'Data do Evento', required: true },
      { name: 'publico_esperado', type: 'number', label: 'Público Esperado', required: true },
      { name: 'medidas_seguranca', type: 'textarea', label: 'Medidas de Segurança', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DEFESA_CIVIL',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
];
