import { ServiceSuggestion, ServiceType, ServiceSubtype } from './types';

export const desenvolvimentoEconomicoSuggestions: ServiceSuggestion[] = [
  {
    id: 'microcredito-solicitacao',
    name: 'Solicitação de Microcrédito',
    description: 'Solicite microcrédito para empreendedores',
    icon: 'Coins',
    category: 'Microcrédito',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'valor_solicitado', type: 'number', label: 'Valor Solicitado', required: true },
      { name: 'finalidade', type: 'textarea', label: 'Finalidade do Crédito', required: true },
      { name: 'ramo_atividade', type: 'select', label: 'Ramo de Atividade', required: true },
      { name: 'tempo_atuacao', type: 'number', label: 'Tempo de Atuação (meses)', required: true },
      { name: 'faturamento_mensal', type: 'number', label: 'Faturamento Mensal', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'mei-formalizacao',
    name: 'Orientação para Formalização MEI',
    description: 'Receba orientação para se tornar Microempreendedor Individual',
    icon: 'UserCheck',
    category: 'Empreendedorismo',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'atividade_pretendida', type: 'text', label: 'Atividade Pretendida', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'cadastro-empreendedor',
    name: 'Cadastro de Empreendedor Local',
    description: 'Cadastre-se no banco de empreendedores do município',
    icon: 'Briefcase',
    category: 'Empreendedorismo',
    estimatedDays: 7,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_negocio', type: 'text', label: 'Nome do Negócio', required: true },
      { name: 'ramo_atividade', type: 'select', label: 'Ramo de Atividade', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'descricao_produtos_servicos', type: 'textarea', label: 'Produtos/Serviços', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'curso-empreendedorismo',
    name: 'Inscrição em Curso de Empreendedorismo',
    description: 'Inscreva-se em cursos gratuitos de empreendedorismo',
    icon: 'GraduationCap',
    category: 'Qualificação',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'curso', type: 'select', label: 'Curso', required: true },
      { name: 'turma', type: 'select', label: 'Turma', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'feira-empreendedor',
    name: 'Inscrição em Feira de Empreendedores',
    description: 'Inscreva-se para participar de feiras e eventos',
    icon: 'Store',
    category: 'Feiras',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_negocio', type: 'text', label: 'Nome do Negócio', required: true },
      { name: 'tipo_produto', type: 'select', label: 'Tipo de Produto', required: true },
      { name: 'espaco_necessario', type: 'select', label: 'Espaço Necessário', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'licenca-ambulante',
    name: 'Solicitação de Licença de Comércio Ambulante',
    description: 'Solicite autorização para comércio ambulante',
    icon: 'ShoppingCart',
    category: 'Feiras',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'tipo_comercio', type: 'select', label: 'Tipo de Comércio', required: true },
      { name: 'produtos', type: 'textarea', label: 'Produtos Comercializados', required: true },
      { name: 'locais_pretendidos', type: 'textarea', label: 'Locais Pretendidos', required: true },
      { name: 'dias_semana', type: 'select', label: 'Dias da Semana', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'consulta-vagas-emprego',
    name: 'Consulta de Vagas de Emprego',
    description: 'Consulte vagas disponíveis no banco de empregos',
    icon: 'Search',
    category: 'Emprego',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'area_atuacao', type: 'select', label: 'Área de Atuação', required: false },
      { name: 'nivel_escolaridade', type: 'select', label: 'Escolaridade', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'cadastro-trabalhador',
    name: 'Cadastro de Trabalhador',
    description: 'Cadastre-se no banco de candidatos a vagas',
    icon: 'UserPlus',
    category: 'Emprego',
    estimatedDays: 5,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'area_interesse', type: 'select', label: 'Área de Interesse', required: true },
      { name: 'escolaridade', type: 'select', label: 'Escolaridade', required: true },
      { name: 'experiencia', type: 'textarea', label: 'Experiência Profissional', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'disponibilidade', type: 'select', label: 'Disponibilidade', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'qualificacao-profissional',
    name: 'Inscrição em Curso de Qualificação',
    description: 'Inscreva-se em cursos de qualificação profissional',
    icon: 'Award',
    category: 'Qualificação',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'curso', type: 'select', label: 'Curso', required: true },
      { name: 'turno_preferencia', type: 'select', label: 'Turno de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'sala-empreendedor',
    name: 'Agendamento na Sala do Empreendedor',
    description: 'Agende atendimento na Sala do Empreendedor',
    icon: 'CalendarCheck',
    category: 'Empreendedorismo',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'assunto', type: 'select', label: 'Assunto', required: true },
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
      { name: 'horario_preferencia', type: 'select', label: 'Horário de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'economia-solidaria',
    name: 'Cadastro de Iniciativa de Economia Solidária',
    description: 'Cadastre cooperativa ou associação de economia solidária',
    icon: 'Users',
    category: 'Economia Solidária',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_iniciativa', type: 'text', label: 'Nome da Iniciativa', required: true },
      { name: 'tipo_organizacao', type: 'select', label: 'Tipo de Organização', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: false },
      { name: 'ramo_atividade', type: 'select', label: 'Ramo de Atividade', required: true },
      { name: 'numero_associados', type: 'number', label: 'Número de Associados', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'certificado-artesao',
    name: 'Solicitação de Carteira de Artesão',
    description: 'Solicite carteira de identificação de artesão',
    icon: 'Palette',
    category: 'Feiras',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'especialidade', type: 'select', label: 'Especialidade', required: true },
      { name: 'tempo_atividade', type: 'number', label: 'Tempo de Atividade (anos)', required: true },
      { name: 'descricao_produtos', type: 'textarea', label: 'Descrição dos Produtos', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'box-mercado',
    name: 'Solicitação de Box em Mercado Municipal',
    description: 'Solicite locação de box em mercado municipal',
    icon: 'Building',
    category: 'Mercados',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'mercado', type: 'select', label: 'Mercado', required: true },
      { name: 'tipo_comercio', type: 'select', label: 'Tipo de Comércio', required: true },
      { name: 'produtos', type: 'textarea', label: 'Produtos a Comercializar', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'experiencia', type: 'textarea', label: 'Experiência no Ramo', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'consulta-mercados',
    name: 'Consulta de Mercados Municipais',
    description: 'Consulte informações sobre mercados municipais',
    icon: 'Info',
    category: 'Mercados',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'mercado', type: 'select', label: 'Mercado', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'plano-negocios',
    name: 'Assessoria para Plano de Negócios',
    description: 'Receba assessoria para elaboração de plano de negócios',
    icon: 'FileText',
    category: 'Empreendedorismo',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_negocio', type: 'text', label: 'Tipo de Negócio', required: true },
      { name: 'estagio_negocio', type: 'select', label: 'Estágio do Negócio', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'registro-marca',
    name: 'Orientação para Registro de Marca',
    description: 'Receba orientação sobre registro de marca no INPI',
    icon: 'Copyright',
    category: 'Empreendedorismo',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_marca', type: 'text', label: 'Nome da Marca', required: true },
      { name: 'tipo_produto_servico', type: 'text', label: 'Produto/Serviço', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'incubadora-empresas',
    name: 'Inscrição em Incubadora de Empresas',
    description: 'Inscreva seu negócio em programa de incubação',
    icon: 'Rocket',
    category: 'Empreendedorismo',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_startup', type: 'text', label: 'Nome da Startup', required: true },
      { name: 'area_atuacao', type: 'select', label: 'Área de Atuação', required: true },
      { name: 'descricao_negocio', type: 'textarea', label: 'Descrição do Negócio', required: true },
      { name: 'estagio_desenvolvimento', type: 'select', label: 'Estágio de Desenvolvimento', required: true },
      { name: 'numero_socios', type: 'number', label: 'Número de Sócios', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'eventos-negocios',
    name: 'Consulta de Eventos de Negócios',
    description: 'Consulte agenda de eventos, palestras e workshops',
    icon: 'Calendar',
    category: 'Empreendedorismo',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_evento', type: 'select', label: 'Tipo de Evento', required: false },
      { name: 'periodo', type: 'select', label: 'Período', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'compras-governamentais',
    name: 'Orientação sobre Compras Governamentais',
    description: 'Receba orientação para vender para o governo',
    icon: 'ShoppingBag',
    category: 'Empreendedorismo',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_produto_servico', type: 'text', label: 'Produto/Serviço', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'credito-rural',
    name: 'Orientação sobre Crédito Rural',
    description: 'Receba orientação sobre linhas de crédito rural',
    icon: 'Tractor',
    category: 'Microcrédito',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_atividade', type: 'select', label: 'Tipo de Atividade', required: true },
      { name: 'area_producao', type: 'number', label: 'Área de Produção (hectares)', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'turismo-negocio',
    name: 'Cadastro de Negócio Turístico',
    description: 'Cadastre seu negócio ligado ao turismo',
    icon: 'Palmtree',
    category: 'Empreendedorismo',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_negocio', type: 'text', label: 'Nome do Negócio', required: true },
      { name: 'tipo_servico', type: 'select', label: 'Tipo de Serviço', required: true },
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'mentoria-empresarial',
    name: 'Solicitação de Mentoria Empresarial',
    description: 'Solicite mentoria com empresários experientes',
    icon: 'Users2',
    category: 'Empreendedorismo',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'area_negocio', type: 'select', label: 'Área do Negócio', required: true },
      { name: 'desafios', type: 'textarea', label: 'Principais Desafios', required: true },
      { name: 'tempo_atuacao', type: 'number', label: 'Tempo de Atuação (meses)', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'analise-credito',
    name: 'Consulta de Análise de Crédito',
    description: 'Consulte status da análise de crédito solicitada',
    icon: 'FileSearch',
    category: 'Microcrédito',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_protocolo', type: 'text', label: 'Número do Protocolo', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'selo-produto-local',
    name: 'Solicitação de Selo de Produto Local',
    description: 'Solicite certificação de produto local',
    icon: 'BadgeCheck',
    category: 'Empreendedorismo',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_produto', type: 'text', label: 'Nome do Produto', required: true },
      { name: 'tipo_produto', type: 'select', label: 'Tipo de Produto', required: true },
      { name: 'producao_local', type: 'textarea', label: 'Comprovação de Produção Local', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'exportacao-orientacao',
    name: 'Orientação para Exportação',
    description: 'Receba orientação sobre exportação de produtos',
    icon: 'Globe',
    category: 'Empreendedorismo',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'produto', type: 'text', label: 'Produto', required: true },
      { name: 'pais_destino', type: 'text', label: 'País de Destino', required: false },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'networking-empresarial',
    name: 'Inscrição em Eventos de Networking',
    description: 'Inscreva-se em eventos de networking empresarial',
    icon: 'Network',
    category: 'Empreendedorismo',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'evento', type: 'select', label: 'Evento', required: true },
      { name: 'area_atuacao', type: 'select', label: 'Área de Atuação', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'estudo-viabilidade',
    name: 'Solicitação de Estudo de Viabilidade',
    description: 'Solicite estudo de viabilidade econômica',
    icon: 'TrendingUp',
    category: 'Empreendedorismo',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_negocio', type: 'text', label: 'Tipo de Negócio', required: true },
      { name: 'investimento_previsto', type: 'number', label: 'Investimento Previsto', required: true },
      { name: 'localizacao', type: 'text', label: 'Localização Pretendida', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'coworking-inscricao',
    name: 'Inscrição em Espaço de Coworking',
    description: 'Inscreva-se para utilizar espaço de coworking público',
    icon: 'Laptop',
    category: 'Empreendedorismo',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_atividade', type: 'text', label: 'Tipo de Atividade', required: true },
      { name: 'periodo_uso', type: 'select', label: 'Período de Uso', required: true },
      { name: 'horario_preferencia', type: 'select', label: 'Horário de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'balcao-emprego',
    name: 'Agendamento no Balcão de Empregos',
    description: 'Agende atendimento no balcão de empregos',
    icon: 'CalendarClock',
    category: 'Emprego',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
      { name: 'horario_preferencia', type: 'select', label: 'Horário de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'certificado-curso',
    name: 'Solicitação de Certificado de Curso',
    description: 'Solicite certificado de curso realizado',
    icon: 'FileBadge',
    category: 'Qualificação',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_curso', type: 'select', label: 'Nome do Curso', required: true },
      { name: 'turma', type: 'text', label: 'Turma', required: true },
      { name: 'ano_conclusao', type: 'select', label: 'Ano de Conclusão', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'consultoria-digital',
    name: 'Consultoria em Marketing Digital',
    description: 'Receba consultoria sobre marketing digital para seu negócio',
    icon: 'Smartphone',
    category: 'Empreendedorismo',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_negocio', type: 'text', label: 'Nome do Negócio', required: true },
      { name: 'tipo_produto_servico', type: 'text', label: 'Produto/Serviço', required: true },
      { name: 'redes_sociais_atuais', type: 'textarea', label: 'Redes Sociais Atuais', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'rodada-negocios',
    name: 'Inscrição em Rodada de Negócios',
    description: 'Inscreva-se em rodada de negócios setorial',
    icon: 'Handshake',
    category: 'Empreendedorismo',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'empresa', type: 'text', label: 'Nome da Empresa', required: true },
      { name: 'setor', type: 'select', label: 'Setor', required: true },
      { name: 'produtos_servicos', type: 'textarea', label: 'Produtos/Serviços', required: true },
      { name: 'interesse_comercial', type: 'select', label: 'Interesse Comercial', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'regularizacao-debitos',
    name: 'Orientação para Regularização de Débitos',
    description: 'Receba orientação sobre regularização de débitos empresariais',
    icon: 'FileWarning',
    category: 'Empreendedorismo',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'tipo_debito', type: 'select', label: 'Tipo de Débito', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'programa-primeiro-emprego',
    name: 'Inscrição no Programa Primeiro Emprego',
    description: 'Inscreva-se no programa de primeiro emprego',
    icon: 'UserCircle',
    category: 'Emprego',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'area_interesse', type: 'select', label: 'Área de Interesse', required: true },
      { name: 'escolaridade', type: 'select', label: 'Escolaridade', required: true },
      { name: 'cursos_complementares', type: 'textarea', label: 'Cursos Complementares', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'cadastro-fornecedor-local',
    name: 'Cadastro de Fornecedor Local',
    description: 'Cadastre-se como fornecedor de produtos/serviços locais',
    icon: 'Truck',
    category: 'Empreendedorismo',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'razao_social', type: 'text', label: 'Razão Social', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'categoria_fornecimento', type: 'select', label: 'Categoria de Fornecimento', required: true },
      { name: 'produtos_servicos', type: 'textarea', label: 'Produtos/Serviços Oferecidos', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'dados-economicos',
    name: 'Consulta de Dados Econômicos Municipais',
    description: 'Consulte dados e indicadores econômicos do município',
    icon: 'BarChart',
    category: 'Empreendedorismo',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_dado', type: 'select', label: 'Tipo de Dado', required: false },
      { name: 'periodo', type: 'select', label: 'Período', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'programa-jovem-aprendiz',
    name: 'Cadastro no Programa Jovem Aprendiz',
    description: 'Cadastre-se no programa jovem aprendiz',
    icon: 'School',
    category: 'Emprego',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'data_nascimento', type: 'date', label: 'Data de Nascimento', required: true },
      { name: 'escolaridade', type: 'select', label: 'Escolaridade', required: true },
      { name: 'area_interesse', type: 'select', label: 'Área de Interesse', required: true },
      { name: 'turno_disponivel', type: 'select', label: 'Turno Disponível', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'pesquisa-mercado',
    name: 'Solicitação de Pesquisa de Mercado',
    description: 'Solicite pesquisa de mercado para seu negócio',
    icon: 'Search',
    category: 'Empreendedorismo',
    estimatedDays: 45,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'produto_servico', type: 'text', label: 'Produto/Serviço', required: true },
      { name: 'objetivo_pesquisa', type: 'textarea', label: 'Objetivo da Pesquisa', required: true },
      { name: 'publico_alvo', type: 'text', label: 'Público-Alvo', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 2,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'alvara-provisorio',
    name: 'Orientação sobre Alvará Provisório',
    description: 'Receba orientação sobre alvará provisório de funcionamento',
    icon: 'FileCheck',
    category: 'Empreendedorismo',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_atividade', type: 'text', label: 'Tipo de Atividade', required: true },
      { name: 'endereco_estabelecimento', type: 'text', label: 'Endereço do Estabelecimento', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'programa-capacitacao-mulheres',
    name: 'Programa de Capacitação para Mulheres Empreendedoras',
    description: 'Inscreva-se em programa de capacitação para mulheres empreendedoras',
    icon: 'Heart',
    category: 'Qualificação',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_negocio', type: 'text', label: 'Tipo de Negócio', required: true },
      { name: 'estagio_negocio', type: 'select', label: 'Estágio do Negócio', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'hub-inovacao',
    name: 'Inscrição no Hub de Inovação',
    description: 'Inscreva seu projeto inovador no hub de inovação municipal',
    icon: 'Lightbulb',
    category: 'Empreendedorismo',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_projeto', type: 'text', label: 'Nome do Projeto', required: true },
      { name: 'area_inovacao', type: 'select', label: 'Área de Inovação', required: true },
      { name: 'descricao_projeto', type: 'textarea', label: 'Descrição do Projeto', required: true },
      { name: 'estagio_desenvolvimento', type: 'select', label: 'Estágio de Desenvolvimento', required: true },
      { name: 'equipe', type: 'number', label: 'Número de Pessoas na Equipe', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'DESENVOLVIMENTO_ECONOMICO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
];
