import { ServiceSuggestion, ServiceType, ServiceSubtype } from './types';

export const financasSuggestions: ServiceSuggestion[] = [
  {
    id: 'certidao-negativa-debitos',
    name: 'Certidão Negativa de Débitos',
    description: 'Emissão de certidão negativa de débitos tributários',
    icon: 'FileCheck',
    category: 'Certidões',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'finalidade', type: 'select', label: 'Finalidade', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'certidao-positiva-debitos',
    name: 'Certidão Positiva com Efeito Negativo',
    description: 'Emissão de certidão positiva com efeito de negativa',
    icon: 'FileText',
    category: 'Certidões',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'finalidade', type: 'select', label: 'Finalidade', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'consulta-iptu',
    name: 'Consulta de IPTU',
    description: 'Consulte débitos e guias de IPTU',
    icon: 'Home',
    category: 'IPTU',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'inscricao_imovel', type: 'text', label: 'Inscrição do Imóvel', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 5,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'segunda-via-iptu',
    name: 'Segunda Via de IPTU',
    description: 'Emita segunda via de carnê de IPTU',
    icon: 'Download',
    category: 'IPTU',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'inscricao_imovel', type: 'text', label: 'Inscrição do Imóvel', required: true },
      { name: 'ano_exercicio', type: 'select', label: 'Ano do Exercício', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 5,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'parcelamento-iptu',
    name: 'Parcelamento de IPTU',
    description: 'Solicite parcelamento de débitos de IPTU',
    icon: 'CreditCard',
    category: 'IPTU',
    estimatedDays: 7,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'inscricao_imovel', type: 'text', label: 'Inscrição do Imóvel', required: true },
      { name: 'valor_total', type: 'number', label: 'Valor Total do Débito', required: true },
      { name: 'numero_parcelas', type: 'select', label: 'Número de Parcelas', required: true },
      { name: 'renda_familiar', type: 'number', label: 'Renda Familiar', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.PAGAMENTO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'isencao-iptu-idoso',
    name: 'Isenção de IPTU para Idoso',
    description: 'Solicite isenção de IPTU para pessoa idosa',
    icon: 'UserCheck',
    category: 'Isenções',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'inscricao_imovel', type: 'text', label: 'Inscrição do Imóvel', required: true },
      { name: 'data_nascimento', type: 'date', label: 'Data de Nascimento', required: true },
      { name: 'renda_familiar', type: 'number', label: 'Renda Familiar', required: true },
      { name: 'unico_imovel', type: 'checkbox', label: 'Único Imóvel', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'isencao-iptu-baixa-renda',
    name: 'Isenção de IPTU para Baixa Renda',
    description: 'Solicite isenção de IPTU por baixa renda',
    icon: 'DollarSign',
    category: 'Isenções',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'inscricao_imovel', type: 'text', label: 'Inscrição do Imóvel', required: true },
      { name: 'renda_familiar', type: 'number', label: 'Renda Familiar', required: true },
      { name: 'numero_moradores', type: 'number', label: 'Número de Moradores', required: true },
      { name: 'programa_social', type: 'checkbox', label: 'Inscrito em Programa Social', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'consulta-iss',
    name: 'Consulta de ISS',
    description: 'Consulte débitos de ISS',
    icon: 'Building',
    category: 'ISS',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'declaracao-iss',
    name: 'Declaração Mensal de ISS',
    description: 'Envie declaração mensal de ISS',
    icon: 'FileSpreadsheet',
    category: 'ISS',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'mes_referencia', type: 'select', label: 'Mês de Referência', required: true },
      { name: 'ano_referencia', type: 'select', label: 'Ano de Referência', required: true },
      { name: 'valor_servicos', type: 'number', label: 'Valor dos Serviços', required: true },
      { name: 'deducoes', type: 'number', label: 'Deduções', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'parcelamento-iss',
    name: 'Parcelamento de ISS',
    description: 'Solicite parcelamento de débitos de ISS',
    icon: 'CalendarDays',
    category: 'ISS',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'valor_total', type: 'number', label: 'Valor Total do Débito', required: true },
      { name: 'numero_parcelas', type: 'select', label: 'Número de Parcelas', required: true },
      { name: 'faturamento_mensal', type: 'number', label: 'Faturamento Mensal', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.PAGAMENTO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'alvara-funcionamento',
    name: 'Consulta de Taxa de Alvará',
    description: 'Consulte valor da taxa de alvará de funcionamento',
    icon: 'Store',
    category: 'Taxas',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'taxa-fiscalizacao',
    name: 'Pagamento de Taxa de Fiscalização',
    description: 'Gere guia de pagamento de taxa de fiscalização',
    icon: 'Receipt',
    category: 'Taxas',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'tipo_taxa', type: 'select', label: 'Tipo de Taxa', required: true },
      { name: 'ano_exercicio', type: 'select', label: 'Ano do Exercício', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.PAGAMENTO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'divida-ativa',
    name: 'Consulta de Dívida Ativa',
    description: 'Consulte débitos inscritos em dívida ativa',
    icon: 'FileWarning',
    category: 'Dívida Ativa',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'parcelamento-divida-ativa',
    name: 'Parcelamento de Dívida Ativa',
    description: 'Solicite parcelamento de débitos em dívida ativa',
    icon: 'HandCoins',
    category: 'Dívida Ativa',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'valor_total', type: 'number', label: 'Valor Total do Débito', required: true },
      { name: 'numero_parcelas', type: 'select', label: 'Número de Parcelas', required: true },
      { name: 'renda_mensal', type: 'number', label: 'Renda Mensal', required: true },
      { name: 'entrada', type: 'number', label: 'Valor da Entrada', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.PAGAMENTO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'nota-fiscal-eletronica',
    name: 'Cadastro para Nota Fiscal Eletrônica',
    description: 'Cadastre-se para emitir nota fiscal eletrônica',
    icon: 'FileDigit',
    category: 'Notas Fiscais',
    estimatedDays: 7,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'razao_social', type: 'text', label: 'Razão Social', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'consulta-nota-fiscal',
    name: 'Consulta de Nota Fiscal',
    description: 'Consulte notas fiscais emitidas',
    icon: 'Search',
    category: 'Notas Fiscais',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_nota', type: 'text', label: 'Número da Nota', required: false },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: false },
      { name: 'periodo_inicio', type: 'date', label: 'Período Início', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'revisao-iptu',
    name: 'Solicitação de Revisão de IPTU',
    description: 'Solicite revisão de valor venal do imóvel',
    icon: 'Calculator',
    category: 'IPTU',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'inscricao_imovel', type: 'text', label: 'Inscrição do Imóvel', required: true },
      { name: 'motivo_revisao', type: 'select', label: 'Motivo da Revisão', required: true },
      { name: 'descricao_motivo', type: 'textarea', label: 'Descrição Detalhada', required: true },
      { name: 'valor_atual', type: 'number', label: 'Valor Atual', required: true },
      { name: 'valor_pretendido', type: 'number', label: 'Valor Pretendido', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'itbi-calculo',
    name: 'Cálculo de ITBI',
    description: 'Calcule o valor do ITBI para transferência de imóvel',
    icon: 'Calculator',
    category: 'ITBI',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'valor_transacao', type: 'number', label: 'Valor da Transação', required: true },
      { name: 'tipo_imovel', type: 'select', label: 'Tipo de Imóvel', required: true },
      { name: 'primeira_compra', type: 'checkbox', label: 'Primeira Compra', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'itbi-pagamento',
    name: 'Pagamento de ITBI',
    description: 'Gere guia de pagamento de ITBI',
    icon: 'CreditCard',
    category: 'ITBI',
    estimatedDays: 3,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'inscricao_imovel', type: 'text', label: 'Inscrição do Imóvel', required: true },
      { name: 'valor_transacao', type: 'number', label: 'Valor da Transação', required: true },
      { name: 'comprador_cpf_cnpj', type: 'text', label: 'CPF/CNPJ Comprador', required: true },
      { name: 'vendedor_cpf_cnpj', type: 'text', label: 'CPF/CNPJ Vendedor', required: true },
      { name: 'data_transacao', type: 'date', label: 'Data da Transação', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.PAGAMENTO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'restituicao-tributos',
    name: 'Solicitação de Restituição de Tributos',
    description: 'Solicite restituição de valores pagos indevidamente',
    icon: 'RefreshCw',
    category: 'Tributos',
    estimatedDays: 45,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'tipo_tributo', type: 'select', label: 'Tipo de Tributo', required: true },
      { name: 'valor_restituicao', type: 'number', label: 'Valor da Restituição', required: true },
      { name: 'motivo', type: 'textarea', label: 'Motivo da Solicitação', required: true },
      { name: 'ano_exercicio', type: 'select', label: 'Ano do Exercício', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'compensacao-tributos',
    name: 'Solicitação de Compensação Tributária',
    description: 'Solicite compensação de créditos tributários',
    icon: 'ArrowLeftRight',
    category: 'Tributos',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'tributo_credito', type: 'select', label: 'Tributo do Crédito', required: true },
      { name: 'tributo_debito', type: 'select', label: 'Tributo do Débito', required: true },
      { name: 'valor_compensacao', type: 'number', label: 'Valor da Compensação', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'certidao-valor-venal',
    name: 'Certidão de Valor Venal',
    description: 'Emita certidão de valor venal do imóvel',
    icon: 'FileText',
    category: 'Certidões',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'inscricao_imovel', type: 'text', label: 'Inscrição do Imóvel', required: true },
      { name: 'finalidade', type: 'select', label: 'Finalidade', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'recurso-auto-infracao',
    name: 'Recurso de Auto de Infração',
    description: 'Interponha recurso contra auto de infração tributária',
    icon: 'Scale',
    category: 'Tributos',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'numero_auto', type: 'text', label: 'Número do Auto de Infração', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'fundamentacao', type: 'textarea', label: 'Fundamentação do Recurso', required: true },
      { name: 'pedido', type: 'textarea', label: 'Pedido', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'atualizacao-cadastral',
    name: 'Atualização Cadastral de Imóvel',
    description: 'Atualize dados cadastrais do imóvel',
    icon: 'Edit',
    category: 'IPTU',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'inscricao_imovel', type: 'text', label: 'Inscrição do Imóvel', required: true },
      { name: 'tipo_alteracao', type: 'select', label: 'Tipo de Alteração', required: true },
      { name: 'dados_novos', type: 'textarea', label: 'Dados Atualizados', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'cadastro-imovel-novo',
    name: 'Cadastro de Imóvel Novo',
    description: 'Cadastre imóvel novo no sistema tributário',
    icon: 'PlusCircle',
    category: 'IPTU',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'endereco_completo', type: 'text', label: 'Endereço Completo', required: true },
      { name: 'area_terreno', type: 'number', label: 'Área do Terreno (m²)', required: true },
      { name: 'area_construida', type: 'number', label: 'Área Construída (m²)', required: true },
      { name: 'tipo_construcao', type: 'select', label: 'Tipo de Construção', required: true },
      { name: 'proprietario_cpf_cnpj', type: 'text', label: 'CPF/CNPJ Proprietário', required: true },
      { name: 'matricula_imovel', type: 'text', label: 'Matrícula do Imóvel', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'baixa-imovel',
    name: 'Baixa de Imóvel Demolido',
    description: 'Solicite baixa de imóvel demolido',
    icon: 'Trash2',
    category: 'IPTU',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'inscricao_imovel', type: 'text', label: 'Inscrição do Imóvel', required: true },
      { name: 'data_demolicao', type: 'date', label: 'Data da Demolição', required: true },
      { name: 'motivo_demolicao', type: 'textarea', label: 'Motivo da Demolição', required: true },
      { name: 'alvara_demolicao', type: 'text', label: 'Número do Alvará de Demolição', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 2,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'refis-municipal',
    name: 'Adesão ao REFIS Municipal',
    description: 'Adira ao programa de refinanciamento fiscal municipal',
    icon: 'FileSignature',
    category: 'Dívida Ativa',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'debitos_incluir', type: 'textarea', label: 'Débitos a Incluir', required: true },
      { name: 'valor_total', type: 'number', label: 'Valor Total dos Débitos', required: true },
      { name: 'numero_parcelas', type: 'select', label: 'Número de Parcelas', required: true },
      { name: 'renda_mensal', type: 'number', label: 'Renda Mensal', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.PAGAMENTO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'certidao-quitacao',
    name: 'Certidão de Quitação de IPTU',
    description: 'Emita certidão de quitação de IPTU',
    icon: 'CheckCircle',
    category: 'Certidões',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'inscricao_imovel', type: 'text', label: 'Inscrição do Imóvel', required: true },
      { name: 'anos_quitacao', type: 'text', label: 'Anos de Quitação', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'consulta-parcelamento',
    name: 'Consulta de Parcelamento',
    description: 'Consulte situação de parcelamentos ativos',
    icon: 'ListChecks',
    category: 'Tributos',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'numero_parcelamento', type: 'text', label: 'Número do Parcelamento', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'reparcelamento',
    name: 'Reparcelamento de Débitos',
    description: 'Solicite reparcelamento de débitos',
    icon: 'RotateCcw',
    category: 'Tributos',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'numero_parcelamento_anterior', type: 'text', label: 'Número do Parcelamento Anterior', required: true },
      { name: 'saldo_devedor', type: 'number', label: 'Saldo Devedor', required: true },
      { name: 'numero_parcelas', type: 'select', label: 'Número de Parcelas', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.PAGAMENTO,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'isencao-taxa-alvara',
    name: 'Isenção de Taxa de Alvará',
    description: 'Solicite isenção de taxa de alvará',
    icon: 'BadgeCheck',
    category: 'Isenções',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'tipo_atividade', type: 'select', label: 'Tipo de Atividade', required: true },
      { name: 'enquadramento_legal', type: 'select', label: 'Enquadramento Legal', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'desmembramento-iptu',
    name: 'Desmembramento de IPTU',
    description: 'Solicite desmembramento de inscrição de IPTU',
    icon: 'Split',
    category: 'IPTU',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'inscricao_original', type: 'text', label: 'Inscrição Original', required: true },
      { name: 'quantidade_lotes', type: 'number', label: 'Quantidade de Lotes', required: true },
      { name: 'descricao_lotes', type: 'textarea', label: 'Descrição dos Lotes', required: true },
      { name: 'matricula_imovel', type: 'text', label: 'Matrícula do Imóvel', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 2,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'unificacao-iptu',
    name: 'Unificação de IPTU',
    description: 'Solicite unificação de inscrições de IPTU',
    icon: 'Combine',
    category: 'IPTU',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'inscricoes_unificar', type: 'textarea', label: 'Inscrições a Unificar', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
      { name: 'matricula_unificada', type: 'text', label: 'Matrícula Unificada', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 2,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'codigo-tributario',
    name: 'Consulta ao Código Tributário',
    description: 'Consulte o código tributário municipal',
    icon: 'BookOpen',
    category: 'Tributos',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'assunto', type: 'select', label: 'Assunto', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'planta-valores',
    name: 'Consulta à Planta de Valores',
    description: 'Consulte a planta genérica de valores',
    icon: 'Map',
    category: 'IPTU',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'bairro', type: 'select', label: 'Bairro', required: false },
      { name: 'logradouro', type: 'text', label: 'Logradouro', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'credito-tributario',
    name: 'Reconhecimento de Crédito Tributário',
    description: 'Solicite reconhecimento de crédito tributário',
    icon: 'BadgeDollarSign',
    category: 'Tributos',
    estimatedDays: 45,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'tipo_credito', type: 'select', label: 'Tipo de Crédito', required: true },
      { name: 'valor_credito', type: 'number', label: 'Valor do Crédito', required: true },
      { name: 'origem_credito', type: 'textarea', label: 'Origem do Crédito', required: true },
      { name: 'documentacao_comprobatoria', type: 'textarea', label: 'Documentação Comprobatória', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'declaracao-imunidade',
    name: 'Declaração de Imunidade Tributária',
    description: 'Solicite reconhecimento de imunidade tributária',
    icon: 'Shield',
    category: 'Isenções',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'tipo_entidade', type: 'select', label: 'Tipo de Entidade', required: true },
      { name: 'fundamento_legal', type: 'textarea', label: 'Fundamento Legal', required: true },
      { name: 'inscricao_imovel', type: 'text', label: 'Inscrição do Imóvel', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'certidao-objeto-social',
    name: 'Certidão de Objeto Social',
    description: 'Emita certidão de objeto social para fins tributários',
    icon: 'FileBarChart',
    category: 'Certidões',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'finalidade', type: 'select', label: 'Finalidade', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'protocolo-processo-fiscal',
    name: 'Abertura de Processo Fiscal',
    description: 'Abra processo administrativo fiscal',
    icon: 'FolderPlus',
    category: 'Tributos',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'tipo_processo', type: 'select', label: 'Tipo de Processo', required: true },
      { name: 'assunto', type: 'textarea', label: 'Assunto', required: true },
      { name: 'pedido', type: 'textarea', label: 'Pedido', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'consulta-processo-fiscal',
    name: 'Consulta de Processo Fiscal',
    description: 'Consulte andamento de processo fiscal',
    icon: 'FolderSearch',
    category: 'Tributos',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_processo', type: 'text', label: 'Número do Processo', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'consulta-incentivos-fiscais',
    name: 'Consulta de Incentivos Fiscais',
    description: 'Consulte programas de incentivos fiscais disponíveis',
    icon: 'Gift',
    category: 'Isenções',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'setor_atividade', type: 'select', label: 'Setor de Atividade', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'FINANCAS',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'adesao-incentivo-fiscal',
    name: 'Adesão a Programa de Incentivo Fiscal',
    description: 'Solicite adesão a programa de incentivo fiscal',
    icon: 'TrendingUp',
    category: 'Isenções',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'programa', type: 'select', label: 'Programa de Incentivo', required: true },
      { name: 'ramo_atividade', type: 'select', label: 'Ramo de Atividade', required: true },
      { name: 'numero_empregos', type: 'number', label: 'Número de Empregos Gerados', required: true },
      { name: 'investimento_previsto', type: 'number', label: 'Investimento Previsto', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'orientacao-tributaria',
    name: 'Agendamento de Orientação Tributária',
    description: 'Agende atendimento para orientação tributária',
    icon: 'CalendarCheck',
    category: 'Tributos',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'assunto', type: 'select', label: 'Assunto', required: true },
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
      { name: 'horario_preferencia', type: 'select', label: 'Horário de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'FINANCAS',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
];
