import { ServiceSuggestion } from './types';

export const meioambienteSuggestions: ServiceSuggestion[] = [
  {
    id: 'licenca-ambiental-simplificada',
    name: 'Licença Ambiental Simplificada',
    description: 'Licenciamento ambiental para atividades de baixo impacto',
    icon: 'FileCheck',
    category: 'Licenciamento',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_requerente', type: 'text', label: 'Nome do Requerente', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'tipo_atividade', type: 'select', label: 'Tipo de Atividade', required: true },
      { name: 'area_atividade', type: 'number', label: 'Área da Atividade (m²)', required: true },
      { name: 'endereco_atividade', type: 'text', label: 'Endereço da Atividade', required: true },
      { name: 'descricao_atividade', type: 'textarea', label: 'Descrição da Atividade', required: true },
    ]
  },
  {
    id: 'poda-arvore-via-publica',
    name: 'Solicitação de Poda de Árvore',
    description: 'Poda de árvores em vias públicas ou calçadas',
    icon: 'TreeDeciduous',
    category: 'Arborização',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_arvore', type: 'text', label: 'Endereço da Árvore', required: true },
      { name: 'motivo_poda', type: 'select', label: 'Motivo da Poda', required: true },
      { name: 'tipo_arvore', type: 'text', label: 'Tipo/Espécie da Árvore (se souber)', required: false },
      { name: 'descricao_situacao', type: 'textarea', label: 'Descrição da Situação', required: true },
    ]
  },
  {
    id: 'denuncia-ambiental',
    name: 'Denúncia Ambiental',
    description: 'Denuncie crimes e infrações ambientais',
    icon: 'AlertTriangle',
    category: 'Fiscalização',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_denunciante', type: 'text', label: 'Nome do Denunciante (opcional)', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone para Contato', required: true },
      { name: 'tipo_denuncia', type: 'select', label: 'Tipo de Infração', required: true },
      { name: 'local_ocorrencia', type: 'text', label: 'Local da Ocorrência', required: true },
      { name: 'data_ocorrencia', type: 'date', label: 'Data da Ocorrência', required: true },
      { name: 'descricao_denuncia', type: 'textarea', label: 'Descrição Detalhada', required: true },
      { name: 'possui_fotos', type: 'select', label: 'Possui Fotos/Vídeos?', required: false },
    ]
  },
  {
    id: 'coleta-seletiva-cadastro',
    name: 'Cadastro em Coleta Seletiva',
    description: 'Participe do programa de coleta seletiva do município',
    icon: 'Recycle',
    category: 'Reciclagem',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_completo', type: 'text', label: 'Nome Completo', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_residencia', type: 'text', label: 'Endereço Residencial', required: true },
      { name: 'tipo_residencia', type: 'select', label: 'Tipo de Residência', required: true },
      { name: 'num_moradores', type: 'number', label: 'Número de Moradores', required: true },
      { name: 'interesse_compostagem', type: 'select', label: 'Interesse em Compostagem', required: false },
    ]
  },
  {
    id: 'destinacao-residuo-construcao',
    name: 'Descarte de Resíduos da Construção Civil',
    description: 'Autorização para descarte de entulho e resíduos de obras',
    icon: 'Trash2',
    category: 'Resíduos',
    estimatedDays: 7,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_responsavel', type: 'text', label: 'Nome do Responsável', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'tipo_residuo', type: 'select', label: 'Tipo de Resíduo', required: true },
      { name: 'volume_estimado', type: 'number', label: 'Volume Estimado (m³)', required: true },
      { name: 'endereco_origem', type: 'text', label: 'Endereço de Origem', required: true },
      { name: 'possui_transporte', type: 'select', label: 'Possui Transporte Próprio?', required: true },
    ]
  },
  {
    id: 'plantio-arvore-calçada',
    name: 'Plantio de Árvore em Calçada',
    description: 'Solicitação de plantio de árvore em frente à residência',
    icon: 'TreePine',
    category: 'Arborização',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_plantio', type: 'text', label: 'Endereço para Plantio', required: true },
      { name: 'largura_calcada', type: 'number', label: 'Largura da Calçada (metros)', required: true },
      { name: 'possui_fiacao', type: 'select', label: 'Possui Fiação Aérea?', required: true },
      { name: 'preferencia_especie', type: 'text', label: 'Preferência de Espécie (se houver)', required: false },
    ]
  },
  {
    id: 'autorizacao-queimada-controlada',
    name: 'Autorização para Queimada Controlada',
    description: 'Licença para queimada controlada em área rural',
    icon: 'Flame',
    category: 'Autorização',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_proprietario', type: 'text', label: 'Nome do Proprietário', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'area_propriedade', type: 'number', label: 'Área da Propriedade (hectares)', required: true },
      { name: 'area_queima', type: 'number', label: 'Área para Queima (hectares)', required: true },
      { name: 'finalidade_queima', type: 'select', label: 'Finalidade da Queima', required: true },
      { name: 'data_pretendida', type: 'date', label: 'Data Pretendida', required: true },
      { name: 'medidas_seguranca', type: 'textarea', label: 'Medidas de Segurança', required: true },
    ]
  },
  {
    id: 'recuperacao-nascente',
    name: 'Programa de Recuperação de Nascentes',
    description: 'Adesão ao programa municipal de recuperação de nascentes',
    icon: 'Droplet',
    category: 'Conservação',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_proprietario', type: 'text', label: 'Nome do Proprietário', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'area_propriedade', type: 'number', label: 'Área da Propriedade (hectares)', required: true },
      { name: 'num_nascentes', type: 'number', label: 'Número de Nascentes', required: true },
      { name: 'estado_nascentes', type: 'select', label: 'Estado das Nascentes', required: true },
      { name: 'possui_app_preservada', type: 'select', label: 'Possui APP Preservada?', required: true },
      { name: 'observacoes', type: 'textarea', label: 'Observações', required: false },
    ]
  },
  {
    id: 'compostagem-domestica',
    name: 'Kit de Compostagem Doméstica',
    description: 'Solicitação de kit para compostagem doméstica',
    icon: 'Leaf',
    category: 'Sustentabilidade',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_completo', type: 'text', label: 'Nome Completo', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_entrega', type: 'text', label: 'Endereço para Entrega', required: true },
      { name: 'tipo_residencia', type: 'select', label: 'Tipo de Residência', required: true },
      { name: 'tem_quintal', type: 'select', label: 'Possui Quintal?', required: true },
      { name: 'experiencia_compostagem', type: 'select', label: 'Experiência com Compostagem', required: false },
    ]
  },
  {
    id: 'palestra-educacao-ambiental',
    name: 'Palestra de Educação Ambiental',
    description: 'Solicitação de palestra em escola ou comunidade',
    icon: 'BookOpen',
    category: 'Educação',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'instituicao', type: 'text', label: 'Instituição/Escola', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'tema_interesse', type: 'select', label: 'Tema de Interesse', required: true },
      { name: 'publico_alvo', type: 'select', label: 'Público-Alvo', required: true },
      { name: 'num_participantes', type: 'number', label: 'Número de Participantes', required: true },
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
    ]
  },
  {
    id: 'remocao-arvore',
    name: 'Autorização para Remoção de Árvore',
    description: 'Solicitação de autorização para remoção de árvore',
    icon: 'TreeDeciduous',
    category: 'Arborização',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_arvore', type: 'text', label: 'Endereço da Árvore', required: true },
      { name: 'especie_arvore', type: 'text', label: 'Espécie da Árvore', required: true },
      { name: 'dap', type: 'number', label: 'DAP - Diâmetro (cm)', required: false },
      { name: 'motivo_remocao', type: 'select', label: 'Motivo da Remoção', required: true },
      { name: 'laudo_tecnico', type: 'select', label: 'Possui Laudo Técnico?', required: false },
    ]
  },
  {
    id: 'fiscalizacao-barulho',
    name: 'Denúncia de Poluição Sonora',
    description: 'Denúncia de poluição sonora e excesso de barulho',
    icon: 'Volume2',
    category: 'Fiscalização',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_denunciante', type: 'text', label: 'Nome (opcional)', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_ocorrencia', type: 'text', label: 'Endereço da Ocorrência', required: true },
      { name: 'tipo_estabelecimento', type: 'select', label: 'Tipo de Estabelecimento', required: true },
      { name: 'horario_barulho', type: 'text', label: 'Horário do Barulho', required: true },
      { name: 'frequencia', type: 'select', label: 'Frequência', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
    ]
  },
  {
    id: 'outorga-uso-agua',
    name: 'Outorga de Uso de Água',
    description: 'Solicitação de outorga para uso de recursos hídricos',
    icon: 'Droplet',
    category: 'Recursos Hídricos',
    estimatedDays: 45,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_requerente', type: 'text', label: 'Nome do Requerente', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'tipo_captacao', type: 'select', label: 'Tipo de Captação', required: true },
      { name: 'finalidade_uso', type: 'select', label: 'Finalidade do Uso', required: true },
      { name: 'vazao_pretendida', type: 'number', label: 'Vazão Pretendida (m³/h)', required: true },
      { name: 'corpo_hidrico', type: 'text', label: 'Corpo Hídrico', required: true },
    ]
  },
  {
    id: 'licenca-poco-artesiano',
    name: 'Licença para Perfuração de Poço Artesiano',
    description: 'Autorização para perfuração de poço artesiano',
    icon: 'CircleDot',
    category: 'Recursos Hídricos',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_proprietario', type: 'text', label: 'Nome do Proprietário', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_perfuracao', type: 'text', label: 'Endereço da Perfuração', required: true },
      { name: 'finalidade_uso', type: 'select', label: 'Finalidade do Uso', required: true },
      { name: 'profundidade_estimada', type: 'number', label: 'Profundidade Estimada (metros)', required: true },
      { name: 'empresa_perfuradora', type: 'text', label: 'Empresa Perfuradora', required: true },
    ]
  },
  {
    id: 'area-preservacao-permanente',
    name: 'Averbação de APP',
    description: 'Averbação de Área de Preservação Permanente',
    icon: 'Shield',
    category: 'Conservação',
    estimatedDays: 60,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_proprietario', type: 'text', label: 'Nome do Proprietário', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'area_propriedade', type: 'number', label: 'Área Total da Propriedade (hectares)', required: true },
      { name: 'area_app', type: 'number', label: 'Área de APP (hectares)', required: true },
      { name: 'tipo_app', type: 'select', label: 'Tipo de APP', required: true },
      { name: 'possui_geo', type: 'select', label: 'Possui Georreferenciamento?', required: true },
    ]
  },
  {
    id: 'reserva-legal',
    name: 'Averbação de Reserva Legal',
    description: 'Averbação de Reserva Legal em propriedade rural',
    icon: 'Map',
    category: 'Conservação',
    estimatedDays: 60,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_proprietario', type: 'text', label: 'Nome do Proprietário', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'area_propriedade', type: 'number', label: 'Área Total (hectares)', required: true },
      { name: 'area_reserva', type: 'number', label: 'Área de Reserva Legal (hectares)', required: true },
      { name: 'percentual_reserva', type: 'number', label: 'Percentual de Reserva (%)', required: true },
      { name: 'car_registrado', type: 'select', label: 'CAR Registrado?', required: true },
    ]
  },
  {
    id: 'ecoponto-cadastro',
    name: 'Cadastro de Ecoponto Comunitário',
    description: 'Solicitação de instalação de ecoponto no bairro',
    icon: 'MapPin',
    category: 'Reciclagem',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'bairro', type: 'text', label: 'Bairro', required: true },
      { name: 'local_sugerido', type: 'text', label: 'Local Sugerido', required: true },
      { name: 'num_familias_beneficiadas', type: 'number', label: 'Famílias Beneficiadas (estimativa)', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ]
  },
  {
    id: 'descarte-oleo-usado',
    name: 'Descarte de Óleo de Cozinha Usado',
    description: 'Pontos de coleta de óleo de cozinha usado',
    icon: 'Droplet',
    category: 'Reciclagem',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_completo', type: 'text', label: 'Nome Completo', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'bairro', type: 'text', label: 'Bairro', required: true },
      { name: 'quantidade_estimada', type: 'select', label: 'Quantidade Estimada', required: true },
      { name: 'frequencia_descarte', type: 'select', label: 'Frequência de Descarte', required: true },
    ]
  },
  {
    id: 'coleta-eletronicos',
    name: 'Coleta de Lixo Eletrônico',
    description: 'Agendamento de coleta de lixo eletrônico',
    icon: 'Monitor',
    category: 'Resíduos',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_completo', type: 'text', label: 'Nome Completo', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_coleta', type: 'text', label: 'Endereço para Coleta', required: true },
      { name: 'tipo_equipamento', type: 'select', label: 'Tipo de Equipamento', required: true },
      { name: 'quantidade_itens', type: 'number', label: 'Quantidade de Itens', required: true },
      { name: 'descricao_itens', type: 'textarea', label: 'Descrição dos Itens', required: true },
    ]
  },
  {
    id: 'horta-comunitaria',
    name: 'Adesão à Horta Comunitária',
    description: 'Cadastro em projeto de horta comunitária',
    icon: 'Sprout',
    category: 'Sustentabilidade',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_completo', type: 'text', label: 'Nome Completo', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'bairro', type: 'text', label: 'Bairro', required: true },
      { name: 'experiencia_cultivo', type: 'select', label: 'Experiência com Cultivo', required: false },
      { name: 'disponibilidade_horas', type: 'number', label: 'Disponibilidade (horas/semana)', required: true },
      { name: 'interesse_organico', type: 'select', label: 'Interesse em Cultivo Orgânico', required: true },
    ]
  },
  {
    id: 'inspecao-ambiental',
    name: 'Solicitação de Inspeção Ambiental',
    description: 'Solicitar vistoria técnica ambiental em propriedade',
    icon: 'ClipboardCheck',
    category: 'Fiscalização',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_inspecao', type: 'text', label: 'Endereço para Inspeção', required: true },
      { name: 'motivo_inspecao', type: 'select', label: 'Motivo da Inspeção', required: true },
      { name: 'descricao_solicitacao', type: 'textarea', label: 'Descrição da Solicitação', required: true },
    ]
  },
  {
    id: 'fauna-silvestre',
    name: 'Resgata de Fauna Silvestre',
    description: 'Solicitação de resgate de animal silvestre',
    icon: 'Bird',
    category: 'Fauna',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_animal', type: 'text', label: 'Localização do Animal', required: true },
      { name: 'tipo_animal', type: 'select', label: 'Tipo de Animal', required: true },
      { name: 'condicao_animal', type: 'select', label: 'Condição do Animal', required: true },
      { name: 'situacao_urgente', type: 'select', label: 'Situação Urgente?', required: true },
      { name: 'descricao_situacao', type: 'textarea', label: 'Descrição da Situação', required: true },
    ]
  },
  {
    id: 'dedetizacao-publica',
    name: 'Dedetização em Área Pública',
    description: 'Solicitação de dedetização em terreno público',
    icon: 'Bug',
    category: 'Controle Ambiental',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_local', type: 'text', label: 'Endereço do Local', required: true },
      { name: 'tipo_praga', type: 'select', label: 'Tipo de Praga', required: true },
      { name: 'nivel_infestacao', type: 'select', label: 'Nível de Infestação', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
    ]
  },
  {
    id: 'capina-terreno',
    name: 'Capina em Terreno Baldio',
    description: 'Solicitação de capina em terreno baldio público',
    icon: 'Scissors',
    category: 'Manutenção',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_terreno', type: 'text', label: 'Endereço do Terreno', required: true },
      { name: 'area_estimada', type: 'number', label: 'Área Estimada (m²)', required: false },
      { name: 'situacao_terreno', type: 'select', label: 'Situação do Terreno', required: true },
      { name: 'risco_saude', type: 'select', label: 'Representa Risco à Saúde?', required: true },
    ]
  },
  {
    id: 'certificado-dispensa-licenca',
    name: 'Certificado de Dispensa de Licença',
    description: 'Solicitação de certificado para atividades dispensadas',
    icon: 'FileText',
    category: 'Licenciamento',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_requerente', type: 'text', label: 'Nome do Requerente', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'tipo_atividade', type: 'select', label: 'Tipo de Atividade', required: true },
      { name: 'endereco_atividade', type: 'text', label: 'Endereço da Atividade', required: true },
      { name: 'descricao_atividade', type: 'textarea', label: 'Descrição da Atividade', required: true },
    ]
  },
  {
    id: 'mudas-nativas',
    name: 'Doação de Mudas Nativas',
    description: 'Solicitação de mudas de árvores nativas',
    icon: 'Leaf',
    category: 'Arborização',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_plantio', type: 'text', label: 'Endereço do Plantio', required: true },
      { name: 'quantidade_mudas', type: 'number', label: 'Quantidade de Mudas', required: true },
      { name: 'tipo_area', type: 'select', label: 'Tipo de Área', required: true },
      { name: 'finalidade', type: 'select', label: 'Finalidade', required: true },
    ]
  },
  {
    id: 'parque-visita-monitorada',
    name: 'Visita Monitorada a Parque Ambiental',
    description: 'Agendamento de visita educativa a parque municipal',
    icon: 'Trees',
    category: 'Educação',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_responsavel', type: 'text', label: 'Nome do Responsável', required: true },
      { name: 'instituicao', type: 'text', label: 'Instituição/Escola', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'num_visitantes', type: 'number', label: 'Número de Visitantes', required: true },
      { name: 'faixa_etaria', type: 'select', label: 'Faixa Etária', required: true },
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
    ]
  },
  {
    id: 'analise-agua-poco',
    name: 'Análise de Água de Poço',
    description: 'Solicitação de análise de qualidade da água',
    icon: 'TestTube',
    category: 'Recursos Hídricos',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_poco', type: 'text', label: 'Endereço do Poço', required: true },
      { name: 'tipo_poco', type: 'select', label: 'Tipo de Poço', required: true },
      { name: 'finalidade_agua', type: 'select', label: 'Finalidade da Água', required: true },
      { name: 'tipo_analise', type: 'select', label: 'Tipo de Análise', required: true },
    ]
  },
  {
    id: 'viveiro-municipal',
    name: 'Cadastro no Viveiro Municipal',
    description: 'Cadastro para retirada de mudas no viveiro',
    icon: 'Sprout',
    category: 'Arborização',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_completo', type: 'text', label: 'Nome Completo', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'finalidade_mudas', type: 'select', label: 'Finalidade das Mudas', required: true },
      { name: 'area_plantio', type: 'number', label: 'Área de Plantio (m²)', required: true },
    ]
  },
  {
    id: 'car-cadastro-rural',
    name: 'CAR - Cadastro Ambiental Rural',
    description: 'Orientação e registro no Cadastro Ambiental Rural',
    icon: 'FileCheck',
    category: 'Regularização',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_proprietario', type: 'text', label: 'Nome do Proprietário', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'nome_propriedade', type: 'text', label: 'Nome da Propriedade', required: true },
      { name: 'area_total', type: 'number', label: 'Área Total (hectares)', required: true },
      { name: 'possui_matricula', type: 'select', label: 'Possui Matrícula do Imóvel?', required: true },
      { name: 'possui_geo', type: 'select', label: 'Possui Georreferenciamento?', required: true },
    ]
  },
  {
    id: 'curso-agente-ambiental',
    name: 'Curso de Agente Ambiental Voluntário',
    description: 'Inscrição em curso de formação de agentes ambientais',
    icon: 'GraduationCap',
    category: 'Educação',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_completo', type: 'text', label: 'Nome Completo', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'escolaridade', type: 'select', label: 'Escolaridade', required: true },
      { name: 'area_interesse', type: 'select', label: 'Área de Interesse', required: true },
      { name: 'disponibilidade', type: 'textarea', label: 'Disponibilidade', required: true },
    ]
  },
  {
    id: 'termos-compromisso-ambiental',
    name: 'Termo de Compromisso Ambiental',
    description: 'Assinatura de termo para regularização ambiental',
    icon: 'FileSignature',
    category: 'Regularização',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_responsavel', type: 'text', label: 'Nome do Responsável', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'tipo_atividade', type: 'select', label: 'Tipo de Atividade', required: true },
      { name: 'area_atividade', type: 'number', label: 'Área da Atividade (hectares)', required: true },
      { name: 'compromissos', type: 'textarea', label: 'Compromissos a Serem Assumidos', required: true },
    ]
  },
  {
    id: 'denuncia-maus-tratos-animais',
    name: 'Denúncia de Maus-Tratos a Animais',
    description: 'Denuncie maus-tratos a animais domésticos ou silvestres',
    icon: 'Heart',
    category: 'Fauna',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_denunciante', type: 'text', label: 'Nome (opcional)', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'local_ocorrencia', type: 'text', label: 'Local da Ocorrência', required: true },
      { name: 'tipo_animal', type: 'select', label: 'Tipo de Animal', required: true },
      { name: 'tipo_maus_tratos', type: 'select', label: 'Tipo de Maus-Tratos', required: true },
      { name: 'data_ocorrencia', type: 'date', label: 'Data da Ocorrência', required: true },
      { name: 'descricao_detalhada', type: 'textarea', label: 'Descrição Detalhada', required: true },
    ]
  },
  {
    id: 'recuperacao-area-degradada',
    name: 'Projeto de Recuperação de Área Degradada',
    description: 'Aprovação de projeto de recuperação ambiental',
    icon: 'RefreshCw',
    category: 'Conservação',
    estimatedDays: 45,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_responsavel', type: 'text', label: 'Nome do Responsável', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'area_degradada', type: 'number', label: 'Área Degradada (hectares)', required: true },
      { name: 'tipo_degradacao', type: 'select', label: 'Tipo de Degradação', required: true },
      { name: 'metodologia', type: 'textarea', label: 'Metodologia de Recuperação', required: true },
      { name: 'prazo_execucao', type: 'number', label: 'Prazo de Execução (meses)', required: true },
    ]
  },
  {
    id: 'fiscalizacao-postura-animal',
    name: 'Fiscalização de Criação de Animais',
    description: 'Denúncia de criação irregular de animais em área urbana',
    icon: 'AlertTriangle',
    category: 'Fiscalização',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_denunciante', type: 'text', label: 'Nome (opcional)', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_ocorrencia', type: 'text', label: 'Endereço da Ocorrência', required: true },
      { name: 'tipo_animal', type: 'select', label: 'Tipo de Animal', required: true },
      { name: 'quantidade_estimada', type: 'number', label: 'Quantidade Estimada', required: false },
      { name: 'problemas_causados', type: 'textarea', label: 'Problemas Causados', required: true },
    ]
  },
  {
    id: 'energia-solar-orientacao',
    name: 'Orientação para Energia Solar',
    description: 'Consultoria sobre instalação de energia solar',
    icon: 'Sun',
    category: 'Sustentabilidade',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_interessado', type: 'text', label: 'Nome do Interessado', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'tipo_imovel', type: 'select', label: 'Tipo de Imóvel', required: true },
      { name: 'consumo_medio', type: 'number', label: 'Consumo Médio Mensal (kWh)', required: true },
      { name: 'area_telhado', type: 'number', label: 'Área Disponível no Telhado (m²)', required: false },
      { name: 'objetivo', type: 'select', label: 'Objetivo', required: true },
    ]
  },
  {
    id: 'compensacao-ambiental',
    name: 'Projeto de Compensação Ambiental',
    description: 'Apresentação de projeto de compensação ambiental',
    icon: 'Scale',
    category: 'Licenciamento',
    estimatedDays: 60,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_empresa', type: 'text', label: 'Nome da Empresa', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'tipo_empreendimento', type: 'select', label: 'Tipo de Empreendimento', required: true },
      { name: 'area_impactada', type: 'number', label: 'Área Impactada (hectares)', required: true },
      { name: 'tipo_compensacao', type: 'select', label: 'Tipo de Compensação', required: true },
      { name: 'area_compensacao', type: 'number', label: 'Área de Compensação (hectares)', required: true },
    ]
  },
  {
    id: 'autorizacao-manejo-fauna',
    name: 'Autorização de Manejo de Fauna',
    description: 'Autorização para manejo de fauna silvestre',
    icon: 'Bird',
    category: 'Fauna',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_responsavel', type: 'text', label: 'Nome do Responsável Técnico', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'registro_profissional', type: 'text', label: 'Registro Profissional', required: true },
      { name: 'especies_alvo', type: 'textarea', label: 'Espécies-Alvo', required: true },
      { name: 'tipo_manejo', type: 'select', label: 'Tipo de Manejo', required: true },
      { name: 'area_manejo', type: 'number', label: 'Área de Manejo (hectares)', required: true },
    ]
  },
  {
    id: 'monitoramento-qualidade-ar',
    name: 'Solicitação de Monitoramento de Qualidade do Ar',
    description: 'Solicitação de análise da qualidade do ar',
    icon: 'Wind',
    category: 'Controle Ambiental',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'endereco_monitoramento', type: 'text', label: 'Endereço para Monitoramento', required: true },
      { name: 'motivo_solicitacao', type: 'select', label: 'Motivo da Solicitação', required: true },
      { name: 'fonte_suspeita', type: 'text', label: 'Fonte Suspeita de Poluição', required: false },
      { name: 'descricao_problema', type: 'textarea', label: 'Descrição do Problema', required: true },
    ]
  },
  {
    id: 'licenca-supressao-vegetal',
    name: 'Licença de Supressão Vegetal',
    description: 'Autorização para supressão de vegetação nativa',
    icon: 'TreeDeciduous',
    category: 'Licenciamento',
    estimatedDays: 45,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_requerente', type: 'text', label: 'Nome do Requerente', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'area_supressao', type: 'number', label: 'Área de Supressão (hectares)', required: true },
      { name: 'tipo_vegetacao', type: 'select', label: 'Tipo de Vegetação', required: true },
      { name: 'finalidade_supressao', type: 'select', label: 'Finalidade da Supressão', required: true },
      { name: 'possui_inventario', type: 'select', label: 'Possui Inventário Florestal?', required: true },
    ]
  },
  {
    id: 'certificado-regularidade-ambiental',
    name: 'Certificado de Regularidade Ambiental',
    description: 'Emissão de certificado de regularidade ambiental',
    icon: 'Award',
    category: 'Regularização',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_requerente', type: 'text', label: 'Nome do Requerente', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'tipo_atividade', type: 'select', label: 'Tipo de Atividade', required: true },
      { name: 'possui_licencas', type: 'select', label: 'Possui Todas as Licenças?', required: true },
      { name: 'finalidade_certificado', type: 'select', label: 'Finalidade do Certificado', required: true },
    ]
  },
  {
    id: 'programa-arboriza-cidade',
    name: 'Programa Arboriza Cidade',
    description: 'Adesão ao programa municipal de arborização',
    icon: 'Trees',
    category: 'Arborização',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_participante', type: 'text', label: 'Nome do Participante', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'bairro', type: 'text', label: 'Bairro', required: true },
      { name: 'tipo_participacao', type: 'select', label: 'Tipo de Participação', required: true },
      { name: 'disponibilidade_horario', type: 'select', label: 'Disponibilidade de Horário', required: true },
      { name: 'experiencia_plantio', type: 'select', label: 'Experiência com Plantio', required: false },
    ]
  },
  {
    id: 'relatorio-impacto-ambiental',
    name: 'Protocolo de Relatório de Impacto Ambiental',
    description: 'Protocolar RIMA para análise técnica',
    icon: 'FileBarChart',
    category: 'Licenciamento',
    estimatedDays: 90,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_empresa', type: 'text', label: 'Nome da Empresa', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'responsavel_tecnico', type: 'text', label: 'Responsável Técnico', required: true },
      { name: 'tipo_empreendimento', type: 'select', label: 'Tipo de Empreendimento', required: true },
      { name: 'area_influencia', type: 'number', label: 'Área de Influência (km²)', required: true },
      { name: 'possui_eia', type: 'select', label: 'Possui EIA Elaborado?', required: true },
    ]
  },
  {
    id: 'oficina-reciclagem-artesanato',
    name: 'Oficina de Reciclagem e Artesanato',
    description: 'Inscrição em oficina de reaproveitamento de materiais',
    icon: 'Recycle',
    category: 'Educação',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_participante', type: 'text', label: 'Nome do Participante', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'idade', type: 'number', label: 'Idade', required: true },
      { name: 'tipo_oficina', type: 'select', label: 'Tipo de Oficina', required: true },
      { name: 'turno_preferencia', type: 'select', label: 'Turno de Preferência', required: true },
      { name: 'experiencia_artesanato', type: 'select', label: 'Experiência com Artesanato', required: false },
    ]
  },
  {
    id: 'selo-verde-empresa',
    name: 'Selo Verde Empresarial',
    description: 'Certificação ambiental para empresas sustentáveis',
    icon: 'Award',
    category: 'Sustentabilidade',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_empresa', type: 'text', label: 'Nome da Empresa', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'ramo_atividade', type: 'select', label: 'Ramo de Atividade', required: true },
      { name: 'num_funcionarios', type: 'number', label: 'Número de Funcionários', required: true },
      { name: 'praticas_sustentaveis', type: 'textarea', label: 'Práticas Sustentáveis Adotadas', required: true },
      { name: 'gestao_residuos', type: 'select', label: 'Possui Gestão de Resíduos?', required: true },
    ]
  },
  {
    id: 'projeto-reflorestamento',
    name: 'Projeto de Reflorestamento',
    description: 'Aprovação de projeto de reflorestamento com nativas',
    icon: 'TreePine',
    category: 'Conservação',
    estimatedDays: 45,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_responsavel', type: 'text', label: 'Nome do Responsável', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'area_reflorestamento', type: 'number', label: 'Área de Reflorestamento (hectares)', required: true },
      { name: 'especies_nativas', type: 'textarea', label: 'Espécies Nativas Propostas', required: true },
      { name: 'densidade_plantio', type: 'number', label: 'Densidade de Plantio (mudas/hectare)', required: true },
      { name: 'cronograma_execucao', type: 'textarea', label: 'Cronograma de Execução', required: true },
    ]
  }
];
