import { ServiceSuggestion, ServiceType, ServiceSubtype } from './types';

export const mobilidadeUrbanaSuggestions: ServiceSuggestion[] = [
  {
    id: 'cartao-transporte-publico',
    name: 'Solicitação de Cartão de Transporte',
    description: 'Solicite cartão para uso no transporte público',
    icon: 'CreditCard',
    category: 'Transporte Público',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'tipo_cartao', type: 'select', label: 'Tipo de Cartão', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 4,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'passe-livre-estudante',
    name: 'Passe Livre Estudantil',
    description: 'Solicite passe livre para estudantes',
    icon: 'GraduationCap',
    category: 'Passe Livre',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'instituicao_ensino', type: 'text', label: 'Instituição de Ensino', required: true },
      { name: 'curso', type: 'text', label: 'Curso', required: true },
      { name: 'periodo', type: 'select', label: 'Período', required: true },
      { name: 'turno', type: 'select', label: 'Turno', required: true },
      { name: 'endereco_residencia', type: 'text', label: 'Endereço de Residência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'passe-livre-idoso',
    name: 'Passe Livre para Idoso',
    description: 'Solicite gratuidade no transporte para idosos',
    icon: 'Heart',
    category: 'Passe Livre',
    estimatedDays: 7,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'data_nascimento', type: 'date', label: 'Data de Nascimento', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 4,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'passe-livre-pcd',
    name: 'Passe Livre para Pessoa com Deficiência',
    description: 'Solicite gratuidade no transporte para PcD',
    icon: 'Accessibility',
    category: 'Passe Livre',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'tipo_deficiencia', type: 'select', label: 'Tipo de Deficiência', required: true },
      { name: 'laudo_medico', type: 'checkbox', label: 'Possui Laudo Médico', required: true },
      { name: 'necessita_acompanhante', type: 'checkbox', label: 'Necessita Acompanhante', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 4,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'consulta-linhas-onibus',
    name: 'Consulta de Linhas de Ônibus',
    description: 'Consulte linhas e horários de ônibus',
    icon: 'Bus',
    category: 'Transporte Público',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_linha', type: 'text', label: 'Número da Linha', required: false },
      { name: 'origem', type: 'text', label: 'Origem', required: false },
      { name: 'destino', type: 'text', label: 'Destino', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 5,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'reclamacao-onibus',
    name: 'Reclamação sobre Transporte Público',
    description: 'Registre reclamação sobre o transporte público',
    icon: 'MessageSquareWarning',
    category: 'Transporte Público',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_linha', type: 'text', label: 'Número da Linha', required: true },
      { name: 'tipo_reclamacao', type: 'select', label: 'Tipo de Reclamação', required: true },
      { name: 'data_hora', type: 'date', label: 'Data e Hora', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 4,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'sugestao-nova-linha',
    name: 'Sugestão de Nova Linha de Ônibus',
    description: 'Sugira criação de nova linha de transporte',
    icon: 'MapPin',
    category: 'Transporte Público',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'origem', type: 'text', label: 'Origem', required: true },
      { name: 'destino', type: 'text', label: 'Destino', required: true },
      { name: 'pontos_intermediarios', type: 'textarea', label: 'Pontos Intermediários', required: false },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
      { name: 'demanda_estimada', type: 'select', label: 'Demanda Estimada', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'ponto-onibus-instalacao',
    name: 'Solicitação de Ponto de Ônibus',
    description: 'Solicite instalação de ponto de ônibus',
    icon: 'MapPinned',
    category: 'Transporte Público',
    estimatedDays: 45,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'linhas_passam', type: 'text', label: 'Linhas que Passam', required: true },
      { name: 'tipo_ponto', type: 'select', label: 'Tipo de Ponto', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'ponto-onibus-manutencao',
    name: 'Solicitação de Manutenção de Ponto',
    description: 'Solicite reparo em ponto de ônibus',
    icon: 'Wrench',
    category: 'Transporte Público',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_problema', type: 'select', label: 'Tipo de Problema', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 4,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'ciclovia-solicitacao',
    name: 'Solicitação de Ciclovia',
    description: 'Solicite implantação de ciclovia',
    icon: 'Bike',
    category: 'Ciclovia',
    estimatedDays: 90,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'via_solicitada', type: 'text', label: 'Via Solicitada', required: true },
      { name: 'extensao_estimada', type: 'text', label: 'Extensão Estimada', required: false },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
      { name: 'demanda_ciclistas', type: 'select', label: 'Demanda de Ciclistas', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'ciclovia-manutencao',
    name: 'Manutenção de Ciclovia',
    description: 'Solicite reparo em ciclovia',
    icon: 'Construction',
    category: 'Ciclovia',
    estimatedDays: 20,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_problema', type: 'select', label: 'Tipo de Problema', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'mapa-ciclovias',
    name: 'Consulta de Mapa de Ciclovias',
    description: 'Consulte mapa de ciclovias da cidade',
    icon: 'Map',
    category: 'Ciclovia',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'regiao', type: 'select', label: 'Região', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'calcada-acessivel',
    name: 'Solicitação de Calçada Acessível',
    description: 'Solicite adequação de calçada para acessibilidade',
    icon: 'Accessibility',
    category: 'Calçadas',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_problema', type: 'select', label: 'Tipo de Problema', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'calcada-irregularidade',
    name: 'Denúncia de Calçada Irregular',
    description: 'Denuncie irregularidades em calçadas',
    icon: 'AlertOctagon',
    category: 'Calçadas',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_irregularidade', type: 'select', label: 'Tipo de Irregularidade', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'proprietario_responsavel', type: 'checkbox', label: 'Conhece Proprietário Responsável', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'rampa-acessibilidade',
    name: 'Solicitação de Rampa de Acessibilidade',
    description: 'Solicite instalação de rampa para acessibilidade',
    icon: 'ArrowDownToLine',
    category: 'Acessibilidade',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_local', type: 'select', label: 'Tipo de Local', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'integracao-modal',
    name: 'Consulta de Integração Modal',
    description: 'Consulte informações sobre integração de transportes',
    icon: 'Repeat',
    category: 'Integração Modal',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_transporte', type: 'select', label: 'Tipo de Transporte', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'terminal-integracao',
    name: 'Informações sobre Terminais de Integração',
    description: 'Consulte informações sobre terminais de integração',
    icon: 'Building2',
    category: 'Integração Modal',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'terminal', type: 'select', label: 'Terminal', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'tarifa-transporte',
    name: 'Consulta de Tarifas de Transporte',
    description: 'Consulte valores de tarifas de transporte público',
    icon: 'DollarSign',
    category: 'Transporte Público',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_tarifa', type: 'select', label: 'Tipo de Tarifa', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 5,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'meia-tarifa',
    name: 'Solicitação de Meia-Tarifa',
    description: 'Solicite cadastro para meia-tarifa no transporte',
    icon: 'Percent',
    category: 'Transporte Público',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'categoria', type: 'select', label: 'Categoria', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 4,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'recarga-cartao',
    name: 'Consulta de Pontos de Recarga',
    description: 'Consulte locais para recarga de cartão de transporte',
    icon: 'MapPin',
    category: 'Transporte Público',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'regiao', type: 'select', label: 'Região', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 5,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'bike-compartilhada',
    name: 'Cadastro em Sistema de Bike Compartilhada',
    description: 'Cadastre-se no sistema de bicicletas compartilhadas',
    icon: 'Bike',
    category: 'Ciclovia',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'telefone', type: 'tel', label: 'Telefone Celular', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'estacao-bike',
    name: 'Solicitação de Estação de Bike',
    description: 'Solicite instalação de estação de bicicletas',
    icon: 'MapPinned',
    category: 'Ciclovia',
    estimatedDays: 60,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_local', type: 'select', label: 'Tipo de Local', required: true },
      { name: 'demanda_estimada', type: 'select', label: 'Demanda Estimada', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'corredor-onibus',
    name: 'Sugestão de Corredor de Ônibus',
    description: 'Sugira implantação de corredor exclusivo',
    icon: 'Route',
    category: 'Transporte Público',
    estimatedDays: 90,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'via', type: 'text', label: 'Via', required: true },
      { name: 'extensao', type: 'text', label: 'Extensão', required: false },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
      { name: 'linhas_beneficiadas', type: 'text', label: 'Linhas Beneficiadas', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'travessia-segura',
    name: 'Solicitação de Travessia Segura',
    description: 'Solicite melhorias para travessia de pedestres',
    icon: 'User',
    category: 'Acessibilidade',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_melhoria', type: 'select', label: 'Tipo de Melhoria', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
      { name: 'proximidade_escola', type: 'checkbox', label: 'Próximo a Escola', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'onibus-demanda',
    name: 'Transporte sob Demanda',
    description: 'Solicite transporte público sob demanda',
    icon: 'Smartphone',
    category: 'Transporte Público',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'origem', type: 'text', label: 'Origem', required: true },
      { name: 'destino', type: 'text', label: 'Destino', required: true },
      { name: 'data_desejada', type: 'date', label: 'Data Desejada', required: true },
      { name: 'horario_desejado', type: 'text', label: 'Horário Desejado', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'iluminacao-ponto',
    name: 'Solicitação de Iluminação em Ponto',
    description: 'Solicite iluminação em ponto de ônibus',
    icon: 'Lightbulb',
    category: 'Transporte Público',
    estimatedDays: 20,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco_ponto', type: 'text', label: 'Endereço do Ponto', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'piso-tatil',
    name: 'Solicitação de Piso Tátil',
    description: 'Solicite instalação de piso tátil',
    icon: 'Grid3x3',
    category: 'Acessibilidade',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_local', type: 'select', label: 'Tipo de Local', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'vlt-consulta',
    name: 'Consulta sobre VLT/Metrô',
    description: 'Consulte informações sobre VLT ou metrô',
    icon: 'Train',
    category: 'Integração Modal',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_informacao', type: 'select', label: 'Tipo de Informação', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'aplicativo-transporte',
    name: 'Suporte ao App de Transporte',
    description: 'Obtenha suporte para o aplicativo de transporte',
    icon: 'HelpCircle',
    category: 'Transporte Público',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_problema', type: 'select', label: 'Tipo de Problema', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 4,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'zona-compartilhada',
    name: 'Sugestão de Zona Compartilhada',
    description: 'Sugira criação de zona compartilhada entre pedestres e veículos',
    icon: 'Users',
    category: 'Acessibilidade',
    estimatedDays: 60,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_area', type: 'select', label: 'Tipo de Área', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'estacionamento-bike',
    name: 'Solicitação de Estacionamento para Bikes',
    description: 'Solicite instalação de paraciclo',
    icon: 'ParkingSquare',
    category: 'Ciclovia',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_local', type: 'select', label: 'Tipo de Local', required: true },
      { name: 'capacidade_desejada', type: 'number', label: 'Capacidade Desejada', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'pesquisa-satisfacao-transporte',
    name: 'Pesquisa de Satisfação do Transporte',
    description: 'Responda pesquisa sobre transporte público',
    icon: 'Star',
    category: 'Transporte Público',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'linhas_utilizadas', type: 'text', label: 'Linhas Utilizadas', required: true },
      { name: 'frequencia_uso', type: 'select', label: 'Frequência de Uso', required: true },
      { name: 'nota_geral', type: 'number', label: 'Nota Geral (0-10)', required: true },
      { name: 'comentarios', type: 'textarea', label: 'Comentários', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'horario-especial',
    name: 'Solicitação de Horário Especial',
    description: 'Solicite horário especial de ônibus para eventos',
    icon: 'Clock',
    category: 'Transporte Público',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'tipo_evento', type: 'select', label: 'Tipo de Evento', required: true },
      { name: 'data_evento', type: 'date', label: 'Data do Evento', required: true },
      { name: 'local_evento', type: 'text', label: 'Local do Evento', required: true },
      { name: 'publico_estimado', type: 'number', label: 'Público Estimado', required: true },
      { name: 'horario_necessario', type: 'text', label: 'Horário Necessário', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'acesso-universal',
    name: 'Projeto de Acesso Universal',
    description: 'Sugira projeto de acesso universal em área específica',
    icon: 'Heart',
    category: 'Acessibilidade',
    estimatedDays: 90,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'area', type: 'text', label: 'Área', required: true },
      { name: 'problemas_identificados', type: 'textarea', label: 'Problemas Identificados', required: true },
      { name: 'melhorias_sugeridas', type: 'textarea', label: 'Melhorias Sugeridas', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 2,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'onibus-ar-condicionado',
    name: 'Solicitação de Ônibus com Ar-Condicionado',
    description: 'Solicite ônibus com ar-condicionado em linha específica',
    icon: 'Wind',
    category: 'Transporte Público',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_linha', type: 'text', label: 'Número da Linha', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'rua-completa',
    name: 'Projeto de Rua Completa',
    description: 'Sugira implantação de conceito de rua completa',
    icon: 'LayoutGrid',
    category: 'Acessibilidade',
    estimatedDays: 120,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'via', type: 'text', label: 'Via', required: true },
      { name: 'extensao', type: 'text', label: 'Extensão', required: false },
      { name: 'elementos_desejados', type: 'textarea', label: 'Elementos Desejados', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 2,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'perdidos-achados',
    name: 'Objetos Perdidos no Transporte',
    description: 'Registre ou consulte objetos perdidos no transporte público',
    icon: 'Package',
    category: 'Transporte Público',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_solicitacao', type: 'select', label: 'Tipo de Solicitação', required: true },
      { name: 'descricao_objeto', type: 'textarea', label: 'Descrição do Objeto', required: true },
      { name: 'data_perda', type: 'date', label: 'Data da Perda', required: true },
      { name: 'linha_veiculo', type: 'text', label: 'Linha/Veículo', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'calcada-compartilhada',
    name: 'Sugestão de Calçada Compartilhada',
    description: 'Sugira calçada compartilhada com ciclovia',
    icon: 'Share2',
    category: 'Ciclovia',
    estimatedDays: 60,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'via', type: 'text', label: 'Via', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'mobiliario-urbano',
    name: 'Solicitação de Mobiliário Urbano',
    description: 'Solicite instalação de banco, lixeira ou outros',
    icon: 'Armchair',
    category: 'Acessibilidade',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_mobiliario', type: 'select', label: 'Tipo de Mobiliário', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'tempo-real-onibus',
    name: 'Consulta de Ônibus em Tempo Real',
    description: 'Consulte localização de ônibus em tempo real',
    icon: 'Radio',
    category: 'Transporte Público',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_linha', type: 'text', label: 'Número da Linha', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 5,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'plano-mobilidade',
    name: 'Participação no Plano de Mobilidade',
    description: 'Participe da construção do plano de mobilidade urbana',
    icon: 'FileText',
    category: 'Integração Modal',
    estimatedDays: 60,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tema_interesse', type: 'select', label: 'Tema de Interesse', required: true },
      { name: 'sugestoes', type: 'textarea', label: 'Sugestões', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'MOBILIDADE_URBANA',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
];
