import { ServiceSuggestion, ServiceType, ServiceSubtype } from './types';

export const politicasMulheresSuggestions: ServiceSuggestion[] = [
  {
    id: 'atendimento-mulher',
    name: 'Atendimento Especializado à Mulher',
    description: 'Agende atendimento na Casa da Mulher',
    icon: 'Heart',
    category: 'Atendimento à Mulher',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_atendimento', type: 'select', label: 'Tipo de Atendimento', required: true },
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'anonimo', type: 'checkbox', label: 'Atendimento Anônimo', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 5,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'violencia-denuncia',
    name: 'Denúncia de Violência contra Mulher',
    description: 'Registre denúncia de violência',
    icon: 'ShieldAlert',
    category: 'Violência',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_violencia', type: 'select', label: 'Tipo de Violência', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'situacao_urgente', type: 'checkbox', label: 'Situação Urgente', required: false },
      { name: 'telefone_contato', type: 'tel', label: 'Telefone de Contato', required: false },
      { name: 'anonimo', type: 'checkbox', label: 'Denúncia Anônima', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 5,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'acolhimento-emergencia',
    name: 'Solicitação de Acolhimento Emergencial',
    description: 'Solicite acolhimento em situação de risco',
    icon: 'Home',
    category: 'Casa da Mulher',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'situacao_risco', type: 'select', label: 'Situação de Risco', required: true },
      { name: 'quantidade_dependentes', type: 'number', label: 'Quantidade de Dependentes', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 5,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'atendimento-psicologico',
    name: 'Atendimento Psicológico',
    description: 'Solicite atendimento psicológico gratuito',
    icon: 'Brain',
    category: 'Atendimento à Mulher',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_demanda', type: 'select', label: 'Tipo de Demanda', required: true },
      { name: 'urgencia', type: 'select', label: 'Urgência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'orientacao-juridica',
    name: 'Orientação Jurídica Gratuita',
    description: 'Receba orientação jurídica especializada',
    icon: 'Scale',
    category: 'Atendimento à Mulher',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'area_juridica', type: 'select', label: 'Área Jurídica', required: true },
      { name: 'descricao_caso', type: 'textarea', label: 'Descrição do Caso', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'assistencia-social',
    name: 'Assistência Social',
    description: 'Solicite assistência social especializada',
    icon: 'HandHeart',
    category: 'Atendimento à Mulher',
    estimatedDays: 5,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'tipo_assistencia', type: 'select', label: 'Tipo de Assistência', required: true },
      { name: 'situacao_familiar', type: 'textarea', label: 'Situação Familiar', required: true },
      { name: 'renda_familiar', type: 'number', label: 'Renda Familiar', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'curso-qualificacao-mulher',
    name: 'Curso de Qualificação Profissional',
    description: 'Inscreva-se em cursos para mulheres',
    icon: 'GraduationCap',
    category: 'Qualificação',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'curso', type: 'select', label: 'Curso', required: true },
      { name: 'turno_preferencia', type: 'select', label: 'Turno de Preferência', required: true },
      { name: 'necessita_creche', type: 'checkbox', label: 'Necessita Creche', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'empreendedorismo-feminino',
    name: 'Programa de Empreendedorismo Feminino',
    description: 'Participe de programa de empreendedorismo',
    icon: 'Briefcase',
    category: 'Empoderamento',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_negocio', type: 'text', label: 'Tipo de Negócio', required: true },
      { name: 'estagio_negocio', type: 'select', label: 'Estágio do Negócio', required: true },
      { name: 'necessidades', type: 'textarea', label: 'Necessidades', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'saude-mulher',
    name: 'Programa de Saúde da Mulher',
    description: 'Cadastre-se em programas de saúde feminina',
    icon: 'Heart',
    category: 'Saúde da Mulher',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'programa', type: 'select', label: 'Programa', required: true },
      { name: 'faixa_etaria', type: 'select', label: 'Faixa Etária', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'prevencao-cancer',
    name: 'Programa de Prevenção ao Câncer',
    description: 'Agende exames preventivos de câncer',
    icon: 'Activity',
    category: 'Saúde da Mulher',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_exame', type: 'select', label: 'Tipo de Exame', required: true },
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
      { name: 'unidade_saude', type: 'select', label: 'Unidade de Saúde', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'planejamento-familiar',
    name: 'Atendimento em Planejamento Familiar',
    description: 'Receba orientação sobre planejamento familiar',
    icon: 'Users',
    category: 'Saúde da Mulher',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_atendimento', type: 'select', label: 'Tipo de Atendimento', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'roda-conversa',
    name: 'Inscrição em Roda de Conversa',
    description: 'Participe de rodas de conversa temáticas',
    icon: 'MessageCircle',
    category: 'Empoderamento',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tema', type: 'select', label: 'Tema', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'oficina-autoestima',
    name: 'Oficina de Autoestima',
    description: 'Participe de oficinas de fortalecimento',
    icon: 'Sparkles',
    category: 'Empoderamento',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'turma', type: 'select', label: 'Turma', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'grupo-apoio',
    name: 'Grupo de Apoio',
    description: 'Participe de grupos de apoio mútuo',
    icon: 'Users2',
    category: 'Atendimento à Mulher',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_grupo', type: 'select', label: 'Tipo de Grupo', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'medida-protetiva',
    name: 'Orientação sobre Medida Protetiva',
    description: 'Receba orientação sobre medidas protetivas',
    icon: 'ShieldCheck',
    category: 'Violência',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'situacao', type: 'textarea', label: 'Descrição da Situação', required: true },
      { name: 'urgente', type: 'checkbox', label: 'Situação Urgente', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 5,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'patrulha-maria-penha',
    name: 'Acionamento da Patrulha Maria da Penha',
    description: 'Acione a patrulha especializada',
    icon: 'Shield',
    category: 'Violência',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'descricao_situacao', type: 'textarea', label: 'Descrição da Situação', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 5,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'creche-acolhimento',
    name: 'Solicitação de Vaga em Creche',
    description: 'Solicite vaga em creche emergencial',
    icon: 'Baby',
    category: 'Casa da Mulher',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'quantidade_criancas', type: 'number', label: 'Quantidade de Crianças', required: true },
      { name: 'idades', type: 'text', label: 'Idades', required: true },
      { name: 'motivo', type: 'textarea', label: 'Motivo', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'cesta-basica',
    name: 'Solicitação de Cesta Básica',
    description: 'Solicite auxílio alimentação emergencial',
    icon: 'ShoppingBasket',
    category: 'Casa da Mulher',
    estimatedDays: 7,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'situacao_vulnerabilidade', type: 'textarea', label: 'Situação de Vulnerabilidade', required: true },
      { name: 'quantidade_moradores', type: 'number', label: 'Quantidade de Moradores', required: true },
      { name: 'renda_familiar', type: 'number', label: 'Renda Familiar', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'auxilio-moradia',
    name: 'Auxílio Moradia Temporário',
    description: 'Solicite auxílio moradia em situação de vulnerabilidade',
    icon: 'Home',
    category: 'Casa da Mulher',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'motivo', type: 'textarea', label: 'Motivo', required: true },
      { name: 'quantidade_dependentes', type: 'number', label: 'Quantidade de Dependentes', required: true },
      { name: 'renda_familiar', type: 'number', label: 'Renda Familiar', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'defensoria-agendamento',
    name: 'Agendamento na Defensoria Pública',
    description: 'Agende atendimento na defensoria',
    icon: 'CalendarCheck',
    category: 'Atendimento à Mulher',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'area_direito', type: 'select', label: 'Área do Direito', required: true },
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'cadastro-rede-apoio',
    name: 'Cadastro na Rede de Apoio',
    description: 'Cadastre-se na rede de apoio à mulher',
    icon: 'Network',
    category: 'Atendimento à Mulher',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_apoio', type: 'select', label: 'Tipo de Apoio Necessário', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'curso-direitos-mulher',
    name: 'Curso sobre Direitos da Mulher',
    description: 'Participe de curso sobre direitos femininos',
    icon: 'BookOpen',
    category: 'Empoderamento',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'turma', type: 'select', label: 'Turma', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'palestra-violencia',
    name: 'Palestra sobre Prevenção à Violência',
    description: 'Solicite palestra sobre prevenção',
    icon: 'Presentation',
    category: 'Violência',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'instituicao', type: 'text', label: 'Instituição', required: true },
      { name: 'publico_estimado', type: 'number', label: 'Público Estimado', required: true },
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'artesanato-mulher',
    name: 'Curso de Artesanato',
    description: 'Aprenda artesanato para geração de renda',
    icon: 'Palette',
    category: 'Qualificação',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_artesanato', type: 'select', label: 'Tipo de Artesanato', required: true },
      { name: 'turno_preferencia', type: 'select', label: 'Turno de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'feira-empreendedoras',
    name: 'Inscrição em Feira de Empreendedoras',
    description: 'Participe de feiras exclusivas para mulheres',
    icon: 'Store',
    category: 'Empoderamento',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_produto', type: 'select', label: 'Tipo de Produto', required: true },
      { name: 'descricao_negocio', type: 'textarea', label: 'Descrição do Negócio', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'microcredito-mulher',
    name: 'Microcrédito para Mulheres',
    description: 'Solicite microcrédito para empreendedoras',
    icon: 'Coins',
    category: 'Empoderamento',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'valor_solicitado', type: 'number', label: 'Valor Solicitado', required: true },
      { name: 'finalidade', type: 'textarea', label: 'Finalidade', required: true },
      { name: 'ramo_atividade', type: 'select', label: 'Ramo de Atividade', required: true },
      { name: 'renda_mensal', type: 'number', label: 'Renda Mensal', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'consulta-ginecologica',
    name: 'Agendamento de Consulta Ginecológica',
    description: 'Agende consulta ginecológica especializada',
    icon: 'Stethoscope',
    category: 'Saúde da Mulher',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_consulta', type: 'select', label: 'Tipo de Consulta', required: true },
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
      { name: 'unidade_saude', type: 'select', label: 'Unidade de Saúde', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'menopausa-atendimento',
    name: 'Programa de Atenção à Menopausa',
    description: 'Participe de programa especializado',
    icon: 'Heart',
    category: 'Saúde da Mulher',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'faixa_etaria', type: 'select', label: 'Faixa Etária', required: true },
      { name: 'sintomas', type: 'textarea', label: 'Sintomas', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'pre-natal-especializado',
    name: 'Pré-Natal Especializado',
    description: 'Cadastre-se em pré-natal de alto risco',
    icon: 'Baby',
    category: 'Saúde da Mulher',
    estimatedDays: 7,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'data_ultima_menstruacao', type: 'date', label: 'Data da Última Menstruação', required: true },
      { name: 'condicao_especial', type: 'select', label: 'Condição Especial', required: true },
      { name: 'unidade_saude', type: 'select', label: 'Unidade de Saúde', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'doula-social',
    name: 'Programa Doula Social',
    description: 'Solicite acompanhamento de doula social',
    icon: 'UserHeart',
    category: 'Saúde da Mulher',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'semanas_gestacao', type: 'number', label: 'Semanas de Gestação', required: true },
      { name: 'primeira_gestacao', type: 'checkbox', label: 'Primeira Gestação', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'mutirao-mamografia',
    name: 'Inscrição em Mutirão de Mamografia',
    description: 'Inscreva-se em mutirão de exames',
    icon: 'Activity',
    category: 'Saúde da Mulher',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'faixa_etaria', type: 'select', label: 'Faixa Etária', required: true },
      { name: 'local_preferencia', type: 'select', label: 'Local de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'lideranca-feminina',
    name: 'Programa de Liderança Feminina',
    description: 'Desenvolva habilidades de liderança',
    icon: 'Award',
    category: 'Empoderamento',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'area_atuacao', type: 'select', label: 'Área de Atuação', required: true },
      { name: 'experiencia_lideranca', type: 'textarea', label: 'Experiência em Liderança', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'informatica-mulher',
    name: 'Curso de Informática para Mulheres',
    description: 'Aprenda informática básica',
    icon: 'Monitor',
    category: 'Qualificação',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nivel', type: 'select', label: 'Nível', required: true },
      { name: 'turno_preferencia', type: 'select', label: 'Turno de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'lingua-estrangeira',
    name: 'Curso de Língua Estrangeira',
    description: 'Aprenda idiomas gratuitamente',
    icon: 'Globe',
    category: 'Qualificação',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'idioma', type: 'select', label: 'Idioma', required: true },
      { name: 'nivel', type: 'select', label: 'Nível', required: true },
      { name: 'turno_preferencia', type: 'select', label: 'Turno de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'beleza-autoestima',
    name: 'Oficina de Beleza e Autoestima',
    description: 'Participe de oficinas de cuidados pessoais',
    icon: 'Sparkles',
    category: 'Empoderamento',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_oficina', type: 'select', label: 'Tipo de Oficina', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'emprego-mulher',
    name: 'Encaminhamento para Emprego',
    description: 'Receba apoio na busca por emprego',
    icon: 'Briefcase',
    category: 'Empoderamento',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'area_interesse', type: 'select', label: 'Área de Interesse', required: true },
      { name: 'experiencia', type: 'textarea', label: 'Experiência Profissional', required: true },
      { name: 'escolaridade', type: 'select', label: 'Escolaridade', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'educacao-financeira',
    name: 'Curso de Educação Financeira',
    description: 'Aprenda a gerir suas finanças',
    icon: 'DollarSign',
    category: 'Empoderamento',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'turma', type: 'select', label: 'Turma', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'campanha-conscientizacao',
    name: 'Solicitação de Campanha de Conscientização',
    description: 'Solicite campanha em sua comunidade',
    icon: 'Megaphone',
    category: 'Violência',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tema', type: 'select', label: 'Tema', required: true },
      { name: 'local', type: 'text', label: 'Local', required: true },
      { name: 'publico_alvo', type: 'select', label: 'Público-Alvo', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'conselho-mulher',
    name: 'Participação no Conselho da Mulher',
    description: 'Cadastre-se para participar do conselho',
    icon: 'Users',
    category: 'Empoderamento',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'area_atuacao', type: 'select', label: 'Área de Atuação', required: true },
      { name: 'experiencia_conselhos', type: 'textarea', label: 'Experiência em Conselhos', required: false },
      { name: 'motivacao', type: 'textarea', label: 'Motivação', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'violencia-digital',
    name: 'Orientação sobre Violência Digital',
    description: 'Receba orientação sobre cyberbullying e crimes virtuais',
    icon: 'Smartphone',
    category: 'Violência',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_violencia_digital', type: 'select', label: 'Tipo de Violência Digital', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'pensao-alimenticia',
    name: 'Orientação sobre Pensão Alimentícia',
    description: 'Receba orientação jurídica sobre pensão',
    icon: 'Scale',
    category: 'Atendimento à Mulher',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'situacao', type: 'textarea', label: 'Descrição da Situação', required: true },
      { name: 'quantidade_filhos', type: 'number', label: 'Quantidade de Filhos', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'guarda-filhos',
    name: 'Orientação sobre Guarda de Filhos',
    description: 'Receba orientação sobre questões de guarda',
    icon: 'Baby',
    category: 'Atendimento à Mulher',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'situacao', type: 'textarea', label: 'Descrição da Situação', required: true },
      { name: 'quantidade_filhos', type: 'number', label: 'Quantidade de Filhos', required: true },
      { name: 'idades_filhos', type: 'text', label: 'Idades dos Filhos', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'divorcio-orientacao',
    name: 'Orientação sobre Divórcio',
    description: 'Receba orientação jurídica sobre divórcio',
    icon: 'Scale',
    category: 'Atendimento à Mulher',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'situacao_conjugal', type: 'select', label: 'Situação Conjugal', required: true },
      { name: 'tempo_casamento', type: 'text', label: 'Tempo de Casamento', required: true },
      { name: 'possui_filhos', type: 'checkbox', label: 'Possui Filhos', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'certificado-participacao',
    name: 'Solicitação de Certificado de Participação',
    description: 'Solicite certificado de curso ou atividade',
    icon: 'Award',
    category: 'Empoderamento',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_atividade', type: 'select', label: 'Tipo de Atividade', required: true },
      { name: 'nome_atividade', type: 'text', label: 'Nome da Atividade', required: true },
      { name: 'data_conclusao', type: 'date', label: 'Data de Conclusão', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'consulta-servicos',
    name: 'Consulta de Serviços Disponíveis',
    description: 'Consulte todos os serviços oferecidos',
    icon: 'Info',
    category: 'Atendimento à Mulher',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'categoria', type: 'select', label: 'Categoria', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'telefone-emergencia',
    name: 'Consulta de Telefones de Emergência',
    description: 'Consulte telefones de atendimento emergencial',
    icon: 'Phone',
    category: 'Violência',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_servico', type: 'select', label: 'Tipo de Serviço', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'POLITICAS_MULHERES',
    priority: 5,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
];
