import { ServiceSuggestion } from './types';

export const segurancapublicaSuggestions: ServiceSuggestion[] = [
  {
    id: 'boletim-ocorrencia',
    name: 'Boletim de Ocorrência Online',
    description: 'Registro de ocorrências não criminais pela internet',
    icon: 'FileText',
    category: 'Ocorrências',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_ocorrencia', type: 'select', label: 'Tipo de Ocorrência', required: true },
      { name: 'data_ocorrencia', type: 'date', label: 'Data da Ocorrência', required: true },
      { name: 'hora_ocorrencia', type: 'text', label: 'Hora da Ocorrência', required: true },
      { name: 'local_ocorrencia', type: 'text', label: 'Local da Ocorrência', required: true },
      { name: 'relato_fatos', type: 'textarea', label: 'Relato dos Fatos', required: true },
    ]
  },
  {
    id: 'ronda-gm',
    name: 'Solicitação de Ronda da Guarda Municipal',
    description: 'Pedido de rondas preventivas em bairros e estabelecimentos',
    icon: 'Shield',
    category: 'Rondas',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco_ronda', type: 'text', label: 'Endereço para Ronda', required: true },
      { name: 'tipo_local', type: 'select', label: 'Tipo de Local', required: true },
      { name: 'periodo_preferencial', type: 'select', label: 'Período Preferencial', required: true },
      { name: 'motivo_solicitacao', type: 'textarea', label: 'Motivo da Solicitação', required: true },
    ]
  },
  {
    id: 'videomonitoramento',
    name: 'Solicitação de Imagens de Videomonitoramento',
    description: 'Acesso a imagens de câmeras de segurança municipais',
    icon: 'Camera',
    category: 'Videomonitoramento',
    estimatedDays: 7,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'local_camera', type: 'text', label: 'Local da Câmera', required: true },
      { name: 'data_solicitada', type: 'date', label: 'Data da Gravação', required: true },
      { name: 'horario_inicio', type: 'text', label: 'Horário Inicial', required: true },
      { name: 'horario_fim', type: 'text', label: 'Horário Final', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ]
  },
  {
    id: 'denuncia-sossego',
    name: 'Denúncia de Perturbação do Sossego',
    description: 'Reclamação sobre barulho, som alto e perturbação do sossego público',
    icon: 'Volume2',
    category: 'Denúncias',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco_ocorrencia', type: 'text', label: 'Endereço da Ocorrência', required: true },
      { name: 'tipo_barulho', type: 'select', label: 'Tipo de Barulho', required: true },
      { name: 'esta_ocorrendo', type: 'select', label: 'Está Ocorrendo Agora?', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição da Situação', required: true },
    ]
  },
  {
    id: 'denuncia-comercio-irregular',
    name: 'Denúncia de Comércio Irregular',
    description: 'Denúncia de comércio ambulante irregular e ocupação indevida do espaço público',
    icon: 'ShoppingCart',
    category: 'Denúncias',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco_ocorrencia', type: 'text', label: 'Local da Irregularidade', required: true },
      { name: 'tipo_comercio', type: 'select', label: 'Tipo de Comércio', required: true },
      { name: 'periodo_funcionamento', type: 'text', label: 'Período de Funcionamento', required: false },
      { name: 'descricao', type: 'textarea', label: 'Descrição Detalhada', required: true },
    ]
  },
  {
    id: 'cadastro-alarme',
    name: 'Cadastro de Alarme Monitorado',
    description: 'Registro de sistemas de alarme para atendimento prioritário',
    icon: 'Bell',
    category: 'Cadastro',
    estimatedDays: 5,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'endereco_imovel', type: 'text', label: 'Endereço do Imóvel', required: true },
      { name: 'tipo_imovel', type: 'select', label: 'Tipo de Imóvel', required: true },
      { name: 'empresa_monitoramento', type: 'text', label: 'Empresa de Monitoramento', required: true },
      { name: 'telefone_central', type: 'tel', label: 'Telefone da Central', required: true },
      { name: 'responsavel_chaves', type: 'text', label: 'Responsável pelas Chaves', required: true },
      { name: 'telefone_responsavel', type: 'tel', label: 'Telefone do Responsável', required: true },
    ]
  },
  {
    id: 'seguranca-evento',
    name: 'Plano de Segurança para Eventos',
    description: 'Análise e aprovação de plano de segurança para eventos públicos e privados',
    icon: 'Calendar',
    category: 'Eventos',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'local_evento', type: 'text', label: 'Local do Evento', required: true },
      { name: 'data_evento', type: 'date', label: 'Data do Evento', required: true },
      { name: 'horario_inicio', type: 'text', label: 'Horário de Início', required: true },
      { name: 'horario_termino', type: 'text', label: 'Horário de Término', required: true },
      { name: 'publico_estimado', type: 'number', label: 'Público Estimado', required: true },
      { name: 'tipo_evento', type: 'select', label: 'Tipo de Evento', required: true },
    ]
  },
  {
    id: 'credencial-estacionamento-deficiente',
    name: 'Credencial de Estacionamento para Deficientes',
    description: 'Emissão de credencial para uso de vagas exclusivas para pessoas com deficiência',
    icon: 'Car',
    category: 'Credenciais',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'tipo_deficiencia', type: 'select', label: 'Tipo de Deficiência', required: true },
      { name: 'grau_mobilidade', type: 'select', label: 'Grau de Mobilidade', required: true },
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'condutor_principal', type: 'text', label: 'Condutor Principal', required: true },
    ]
  },
  {
    id: 'ronda-escolar',
    name: 'Solicitação de Ronda Escolar',
    description: 'Pedido de rondas preventivas em escolas municipais',
    icon: 'School',
    category: 'Rondas',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco_escola', type: 'text', label: 'Endereço da Escola', required: true },
      { name: 'periodo_atendimento', type: 'select', label: 'Período de Funcionamento', required: true },
      { name: 'motivo_solicitacao', type: 'textarea', label: 'Motivo da Solicitação', required: true },
    ]
  },
  {
    id: 'vizinhanca-solidaria',
    name: 'Programa Vizinhança Solidária',
    description: 'Cadastro em programa comunitário de segurança e prevenção',
    icon: 'Users',
    category: 'Programas Comunitários',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'num_residencias', type: 'number', label: 'Número de Residências Participantes', required: true },
      { name: 'objetivos', type: 'textarea', label: 'Objetivos do Grupo', required: true },
    ]
  },
  {
    id: 'achados-perdidos',
    name: 'Achados e Perdidos',
    description: 'Registro de objetos perdidos ou encontrados',
    icon: 'Search',
    category: 'Achados',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_registro', type: 'select', label: 'Tipo de Registro', required: true },
      { name: 'descricao_objeto', type: 'textarea', label: 'Descrição do Objeto', required: true },
      { name: 'local_perda', type: 'text', label: 'Local onde Perdeu/Achou', required: true },
      { name: 'data_ocorrencia', type: 'date', label: 'Data da Ocorrência', required: true },
    ]
  },
  {
    id: 'fiscalizacao-transito',
    name: 'Solicitação de Fiscalização de Trânsito',
    description: 'Pedido de fiscalização de infrações de trânsito',
    icon: 'TrafficCone',
    category: 'Trânsito',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'local_fiscalizacao', type: 'text', label: 'Local para Fiscalização', required: true },
      { name: 'tipo_infracao', type: 'select', label: 'Tipo de Infração', required: true },
      { name: 'periodo_ocorrencia', type: 'text', label: 'Período de Ocorrência', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição da Situação', required: true },
    ]
  },
  {
    id: 'denuncia-violencia-domestica',
    name: 'Denúncia de Violência Doméstica',
    description: 'Canal de denúncias de violência doméstica e familiar',
    icon: 'AlertTriangle',
    category: 'Denúncias',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco_ocorrencia', type: 'text', label: 'Endereço da Ocorrência', required: true },
      { name: 'tipo_violencia', type: 'select', label: 'Tipo de Violência', required: true },
      { name: 'vitima_menor', type: 'select', label: 'Vítima é Menor de Idade?', required: true },
      { name: 'situacao_urgente', type: 'select', label: 'Situação de Urgência?', required: true },
      { name: 'relato', type: 'textarea', label: 'Relato da Situação', required: true },
    ]
  },
  {
    id: 'cadastro-veiculo-gm',
    name: 'Cadastro de Veículo na Guarda Municipal',
    description: 'Registro de veículos para controle de acesso e segurança',
    icon: 'Car',
    category: 'Cadastro',
    estimatedDays: 5,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'marca_modelo', type: 'text', label: 'Marca/Modelo', required: true },
      { name: 'cor_veiculo', type: 'text', label: 'Cor do Veículo', required: true },
      { name: 'ano_fabricacao', type: 'number', label: 'Ano de Fabricação', required: true },
      { name: 'finalidade', type: 'select', label: 'Finalidade do Cadastro', required: true },
    ]
  },
  {
    id: 'balada-segura',
    name: 'Programa Balada Segura',
    description: 'Cadastro de estabelecimentos no programa de segurança noturna',
    icon: 'Music',
    category: 'Programas Comunitários',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável Legal', required: true },
      { name: 'tipo_estabelecimento', type: 'select', label: 'Tipo de Estabelecimento', required: true },
      { name: 'capacidade_publico', type: 'number', label: 'Capacidade de Público', required: true },
      { name: 'horario_funcionamento', type: 'text', label: 'Horário de Funcionamento', required: true },
    ]
  },
  {
    id: 'denuncia-drogas',
    name: 'Denúncia de Tráfico de Drogas',
    description: 'Canal de denúncias sobre tráfico e uso de drogas',
    icon: 'AlertCircle',
    category: 'Denúncias',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco_ocorrencia', type: 'text', label: 'Local da Ocorrência', required: true },
      { name: 'ponto_referencia', type: 'text', label: 'Ponto de Referência', required: false },
      { name: 'tipo_denuncia', type: 'select', label: 'Tipo de Denúncia', required: true },
      { name: 'periodo_atividade', type: 'text', label: 'Período de Atividade', required: false },
      { name: 'descricao', type: 'textarea', label: 'Descrição Detalhada', required: true },
    ]
  },
  {
    id: 'credencial-acesso-vip',
    name: 'Credencial de Acesso VIP',
    description: 'Emissão de credenciais para acesso a áreas restritas em eventos',
    icon: 'IdCard',
    category: 'Credenciais',
    estimatedDays: 7,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'data_evento', type: 'date', label: 'Data do Evento', required: true },
      { name: 'funcao_evento', type: 'text', label: 'Função no Evento', required: true },
      { name: 'area_acesso', type: 'select', label: 'Área de Acesso', required: true },
    ]
  },
  {
    id: 'patrulha-rural',
    name: 'Patrulha Rural',
    description: 'Solicitação de patrulhamento em áreas rurais',
    icon: 'Tractor',
    category: 'Rondas',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'localizacao_propriedade', type: 'text', label: 'Localização da Propriedade', required: true },
      { name: 'area_propriedade', type: 'number', label: 'Área da Propriedade (hectares)', required: true },
      { name: 'motivo_solicitacao', type: 'textarea', label: 'Motivo da Solicitação', required: true },
      { name: 'possui_caseiro', type: 'select', label: 'Possui Caseiro?', required: true },
    ]
  },
  {
    id: 'denuncia-maus-tratos-animais',
    name: 'Denúncia de Maus-Tratos a Animais',
    description: 'Canal de denúncias sobre maus-tratos e abandono de animais',
    icon: 'Dog',
    category: 'Denúncias',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco_ocorrencia', type: 'text', label: 'Local da Ocorrência', required: true },
      { name: 'tipo_animal', type: 'select', label: 'Tipo de Animal', required: true },
      { name: 'tipo_mausTrato', type: 'select', label: 'Tipo de Maus-Tratos', required: true },
      { name: 'situacao_urgente', type: 'select', label: 'Situação Urgente?', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição da Situação', required: true },
    ]
  },
  {
    id: 'botao-panico-idoso',
    name: 'Botão do Pânico para Idosos',
    description: 'Cadastro no programa de botão do pânico para idosos em situação de risco',
    icon: 'AlertOctagon',
    category: 'Programas Comunitários',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'data_nascimento', type: 'date', label: 'Data de Nascimento', required: true },
      { name: 'mora_sozinho', type: 'select', label: 'Mora Sozinho?', required: true },
      { name: 'contato_emergencia', type: 'text', label: 'Contato de Emergência', required: true },
      { name: 'telefone_emergencia', type: 'tel', label: 'Telefone de Emergência', required: true },
      { name: 'condicao_saude', type: 'textarea', label: 'Condições de Saúde Relevantes', required: false },
    ]
  },
  {
    id: 'denuncia-trabalho-infantil',
    name: 'Denúncia de Trabalho Infantil',
    description: 'Canal de denúncias sobre exploração de trabalho infantil',
    icon: 'UserX',
    category: 'Denúncias',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco_ocorrencia', type: 'text', label: 'Local da Ocorrência', required: true },
      { name: 'tipo_trabalho', type: 'select', label: 'Tipo de Trabalho', required: true },
      { name: 'idade_estimada_crianca', type: 'text', label: 'Idade Estimada da Criança', required: true },
      { name: 'periodo_trabalho', type: 'text', label: 'Período de Trabalho', required: false },
      { name: 'descricao', type: 'textarea', label: 'Descrição da Situação', required: true },
    ]
  },
  {
    id: 'escolta-valores',
    name: 'Solicitação de Escolta de Valores',
    description: 'Escolta de transporte de valores e cargas valiosas',
    icon: 'Lock',
    category: 'Escoltas',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'tipo_carga', type: 'select', label: 'Tipo de Carga', required: true },
      { name: 'data_transporte', type: 'date', label: 'Data do Transporte', required: true },
      { name: 'horario_previsto', type: 'text', label: 'Horário Previsto', required: true },
      { name: 'origem', type: 'text', label: 'Origem', required: true },
      { name: 'destino', type: 'text', label: 'Destino', required: true },
      { name: 'valor_estimado', type: 'text', label: 'Valor Estimado da Carga', required: false },
    ]
  },
  {
    id: 'vistoria-seguranca',
    name: 'Vistoria de Segurança em Estabelecimentos',
    description: 'Solicitação de vistoria de segurança para licenciamento',
    icon: 'ClipboardCheck',
    category: 'Vistorias',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'tipo_estabelecimento', type: 'select', label: 'Tipo de Estabelecimento', required: true },
      { name: 'area_total', type: 'number', label: 'Área Total (m²)', required: true },
      { name: 'finalidade_vistoria', type: 'select', label: 'Finalidade da Vistoria', required: true },
    ]
  },
  {
    id: 'registro-arma-fogo',
    name: 'Registro de Porte de Arma de Fogo (Vigilante)',
    description: 'Registro municipal para vigilantes com porte de arma',
    icon: 'Shield',
    category: 'Cadastro',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'empresa_empregadora', type: 'text', label: 'Empresa Empregadora', required: true },
      { name: 'cnpj_empresa', type: 'cnpj', label: 'CNPJ da Empresa', required: true },
      { name: 'numero_porte_pf', type: 'text', label: 'Número do Porte da Polícia Federal', required: true },
      { name: 'validade_porte', type: 'date', label: 'Validade do Porte', required: true },
      { name: 'calibre_arma', type: 'text', label: 'Calibre da Arma', required: true },
      { name: 'numero_serie', type: 'text', label: 'Número de Série', required: true },
    ]
  },
  {
    id: 'autorizacao-filme',
    name: 'Autorização para Filmagens',
    description: 'Autorização de segurança para filmagens em vias públicas',
    icon: 'Video',
    category: 'Autorizações',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'local_filmagem', type: 'text', label: 'Local da Filmagem', required: true },
      { name: 'data_filmagem', type: 'date', label: 'Data da Filmagem', required: true },
      { name: 'horario_inicio', type: 'text', label: 'Horário de Início', required: true },
      { name: 'horario_termino', type: 'text', label: 'Horário de Término', required: true },
      { name: 'num_pessoas_envolvidas', type: 'number', label: 'Número de Pessoas Envolvidas', required: true },
    ]
  },
  {
    id: 'denuncia-pichacao',
    name: 'Denúncia de Pichação e Vandalismo',
    description: 'Denúncia de pichações e atos de vandalismo no patrimônio público',
    icon: 'Spray',
    category: 'Denúncias',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'local_ocorrencia', type: 'text', label: 'Local da Ocorrência', required: true },
      { name: 'tipo_patrimonio', type: 'select', label: 'Tipo de Patrimônio', required: true },
      { name: 'extensao_dano', type: 'select', label: 'Extensão do Dano', required: true },
      { name: 'data_ocorrencia', type: 'date', label: 'Data Aproximada', required: false },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
    ]
  },
  {
    id: 'cadastro-mototaxi',
    name: 'Cadastro de Mototáxi',
    description: 'Registro de mototaxistas na Guarda Municipal',
    icon: 'Bike',
    category: 'Cadastro',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'num_cnh', type: 'text', label: 'Número da CNH', required: true },
      { name: 'categoria_cnh', type: 'text', label: 'Categoria da CNH', required: true },
      { name: 'placa_moto', type: 'text', label: 'Placa da Moto', required: true },
      { name: 'ano_moto', type: 'number', label: 'Ano da Moto', required: true },
      { name: 'cor_moto', type: 'text', label: 'Cor da Moto', required: true },
      { name: 'ponto_trabalho', type: 'text', label: 'Ponto de Trabalho', required: true },
    ]
  },
  {
    id: 'ocorrencia-animal-solto',
    name: 'Ocorrência de Animal Solto em Via Pública',
    description: 'Registro de animais soltos representando risco',
    icon: 'AlertTriangle',
    category: 'Ocorrências',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'local_ocorrencia', type: 'text', label: 'Local da Ocorrência', required: true },
      { name: 'tipo_animal', type: 'select', label: 'Tipo de Animal', required: true },
      { name: 'porte_animal', type: 'select', label: 'Porte do Animal', required: true },
      { name: 'comportamento', type: 'select', label: 'Comportamento do Animal', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: false },
    ]
  },
  {
    id: 'ronda-comercial',
    name: 'Ronda em Áreas Comerciais',
    description: 'Solicitação de patrulhamento em centros comerciais',
    icon: 'Store',
    category: 'Rondas',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_representacao', type: 'select', label: 'Tipo de Representação', required: true },
      { name: 'num_estabelecimentos', type: 'number', label: 'Número de Estabelecimentos', required: true },
      { name: 'periodo_preferencial', type: 'select', label: 'Período Preferencial', required: true },
      { name: 'motivo_solicitacao', type: 'textarea', label: 'Motivo da Solicitação', required: true },
    ]
  },
  {
    id: 'autorizacao-passeata',
    name: 'Autorização para Passeatas e Manifestações',
    description: 'Autorização de segurança para passeatas e manifestações públicas',
    icon: 'Users',
    category: 'Autorizações',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'tipo_manifestacao', type: 'select', label: 'Tipo de Manifestação', required: true },
      { name: 'motivo', type: 'textarea', label: 'Motivo/Tema', required: true },
      { name: 'data_prevista', type: 'date', label: 'Data Prevista', required: true },
      { name: 'horario_inicio', type: 'text', label: 'Horário de Início', required: true },
      { name: 'local_concentracao', type: 'text', label: 'Local de Concentração', required: true },
      { name: 'percurso', type: 'textarea', label: 'Percurso Pretendido', required: true },
      { name: 'publico_estimado', type: 'number', label: 'Público Estimado', required: true },
    ]
  },
  {
    id: 'denuncia-queimada',
    name: 'Denúncia de Queimadas',
    description: 'Denúncia de queimadas urbanas e rurais',
    icon: 'Flame',
    category: 'Denúncias',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'local_queimada', type: 'text', label: 'Local da Queimada', required: true },
      { name: 'tipo_area', type: 'select', label: 'Tipo de Área', required: true },
      { name: 'esta_ativa', type: 'select', label: 'Queimada Está Ativa?', required: true },
      { name: 'extensao_estimada', type: 'text', label: 'Extensão Estimada', required: false },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
    ]
  },
  {
    id: 'cadastro-seguranca-privada',
    name: 'Cadastro de Empresa de Segurança Privada',
    description: 'Registro de empresas de segurança privada atuantes no município',
    icon: 'Building2',
    category: 'Cadastro',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'razao_social', type: 'text', label: 'Razão Social', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável Legal', required: true },
      { name: 'endereco_sede', type: 'text', label: 'Endereço da Sede', required: true },
      { name: 'num_autorizacao_pf', type: 'text', label: 'Número de Autorização da PF', required: true },
      { name: 'validade_autorizacao', type: 'date', label: 'Validade da Autorização', required: true },
      { name: 'num_vigilantes', type: 'number', label: 'Número de Vigilantes', required: true },
      { name: 'areas_atuacao', type: 'textarea', label: 'Áreas de Atuação no Município', required: true },
    ]
  },
  {
    id: 'operacao-transito',
    name: 'Solicitação de Operação de Trânsito',
    description: 'Pedido de operações de trânsito para eventos e obras',
    icon: 'AlertCircle',
    category: 'Trânsito',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'tipo_solicitacao', type: 'select', label: 'Tipo de Solicitação', required: true },
      { name: 'local_operacao', type: 'text', label: 'Local da Operação', required: true },
      { name: 'data_inicio', type: 'date', label: 'Data de Início', required: true },
      { name: 'data_termino', type: 'date', label: 'Data de Término', required: true },
      { name: 'horario_operacao', type: 'text', label: 'Horário da Operação', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ]
  },
  {
    id: 'monitoramento-tornozeira',
    name: 'Monitoramento por Tornozeleira Eletrônica Municipal',
    description: 'Programa de monitoramento eletrônico de medidas socioeducativas',
    icon: 'Radio',
    category: 'Programas Comunitários',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'data_nascimento', type: 'date', label: 'Data de Nascimento', required: true },
      { name: 'endereco_residencia', type: 'text', label: 'Endereço de Residência', required: true },
      { name: 'responsavel_legal', type: 'text', label: 'Responsável Legal', required: false },
      { name: 'num_processo', type: 'text', label: 'Número do Processo', required: true },
      { name: 'vara_origem', type: 'text', label: 'Vara de Origem', required: true },
      { name: 'tipo_medida', type: 'select', label: 'Tipo de Medida', required: true },
      { name: 'prazo_monitoramento', type: 'number', label: 'Prazo de Monitoramento (meses)', required: true },
    ]
  },
  {
    id: 'busca-pessoa-desaparecida',
    name: 'Registro de Pessoa Desaparecida',
    description: 'Registro e busca de pessoas desaparecidas',
    icon: 'Search',
    category: 'Ocorrências',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'cpf_comunicante', type: 'cpf', label: 'CPF do Comunicante', required: true },
      { name: 'telefone_comunicante', type: 'tel', label: 'Telefone do Comunicante', required: true },
      { name: 'parentesco', type: 'text', label: 'Parentesco com Desaparecido', required: true },
      { name: 'idade_desaparecido', type: 'number', label: 'Idade', required: true },
      { name: 'data_desaparecimento', type: 'date', label: 'Data do Desaparecimento', required: true },
      { name: 'local_desaparecimento', type: 'text', label: 'Local do Desaparecimento', required: true },
      { name: 'caracteristicas', type: 'textarea', label: 'Características Físicas', required: true },
      { name: 'roupas', type: 'text', label: 'Roupas que Vestia', required: false },
      { name: 'condicao_saude', type: 'textarea', label: 'Condições de Saúde', required: false },
    ]
  },
  {
    id: 'denuncia-violacao-medida-protetiva',
    name: 'Denúncia de Violação de Medida Protetiva',
    description: 'Denúncia de descumprimento de medidas protetivas de urgência',
    icon: 'ShieldAlert',
    category: 'Denúncias',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'telefone_vitima', type: 'tel', label: 'Telefone da Vítima', required: true },
      { name: 'num_processo_medida', type: 'text', label: 'Número do Processo da Medida Protetiva', required: false },
      { name: 'tipo_violacao', type: 'select', label: 'Tipo de Violação', required: true },
      { name: 'data_violacao', type: 'date', label: 'Data da Violação', required: true },
      { name: 'local_violacao', type: 'text', label: 'Local da Violação', required: true },
      { name: 'situacao_urgente', type: 'select', label: 'Situação de Urgência?', required: true },
      { name: 'relato', type: 'textarea', label: 'Relato da Violação', required: true },
    ]
  },
  {
    id: 'credencial-estacionamento-idoso',
    name: 'Credencial de Estacionamento Preferencial para Idosos',
    description: 'Emissão de credencial para uso de vagas preferenciais para idosos',
    icon: 'Car',
    category: 'Credenciais',
    estimatedDays: 7,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'data_nascimento', type: 'date', label: 'Data de Nascimento', required: true },
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'condutor_principal', type: 'text', label: 'Condutor Principal', required: true },
      { name: 'possui_mobilidade_reduzida', type: 'select', label: 'Possui Mobilidade Reduzida?', required: true },
    ]
  },
  {
    id: 'curso-defesa-pessoal',
    name: 'Inscrição em Curso de Defesa Pessoal',
    description: 'Cadastro em cursos gratuitos de defesa pessoal oferecidos pela GM',
    icon: 'Users',
    category: 'Programas Comunitários',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'data_nascimento', type: 'date', label: 'Data de Nascimento', required: true },
      { name: 'genero', type: 'select', label: 'Gênero', required: true },
      { name: 'turma_preferencial', type: 'select', label: 'Turma Preferencial', required: true },
      { name: 'experiencia_previa', type: 'select', label: 'Possui Experiência Prévia?', required: false },
    ]
  },
  {
    id: 'denuncia-aglomeracao',
    name: 'Denúncia de Aglomeração Irregular',
    description: 'Denúncia de aglomerações em desacordo com normas sanitárias',
    icon: 'Users',
    category: 'Denúncias',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'local_aglomeracao', type: 'text', label: 'Local da Aglomeração', required: true },
      { name: 'tipo_local', type: 'select', label: 'Tipo de Local', required: true },
      { name: 'num_estimado_pessoas', type: 'text', label: 'Número Estimado de Pessoas', required: false },
      { name: 'esta_ocorrendo', type: 'select', label: 'Está Ocorrendo Agora?', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
    ]
  },
  {
    id: 'escolta-autoridade',
    name: 'Solicitação de Escolta de Autoridade',
    description: 'Escolta de segurança para autoridades em visita ao município',
    icon: 'ShieldCheck',
    category: 'Escoltas',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'orgao_solicitante', type: 'text', label: 'Órgão Solicitante', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável pela Solicitação', required: true },
      { name: 'cargo_autoridade', type: 'text', label: 'Cargo', required: true },
      { name: 'data_visita', type: 'date', label: 'Data da Visita', required: true },
      { name: 'horario_chegada', type: 'text', label: 'Horário de Chegada', required: true },
      { name: 'horario_saida', type: 'text', label: 'Horário de Saída', required: true },
      { name: 'locais_visita', type: 'textarea', label: 'Locais que Visitará', required: true },
      { name: 'nivel_seguranca', type: 'select', label: 'Nível de Segurança Requerido', required: true },
    ]
  },
  {
    id: 'cadastro-guarda-patrimonio',
    name: 'Cadastro de Guardador de Patrimônio Público',
    description: 'Registro de zeladores e guardiões voluntários de patrimônio público',
    icon: 'Eye',
    category: 'Cadastro',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'patrimonio_interesse', type: 'text', label: 'Patrimônio de Interesse', required: true },
      { name: 'localizacao_patrimonio', type: 'text', label: 'Localização do Patrimônio', required: true },
      { name: 'tipo_patrimonio', type: 'select', label: 'Tipo de Patrimônio', required: true },
      { name: 'disponibilidade', type: 'textarea', label: 'Disponibilidade de Horários', required: true },
      { name: 'motivacao', type: 'textarea', label: 'Motivação para Participar', required: true },
    ]
  },
  {
    id: 'denuncia-perturbacao-fauna',
    name: 'Denúncia de Perturbação da Fauna',
    description: 'Denúncia de caça, aprisionamento ou perturbação de animais silvestres',
    icon: 'Bird',
    category: 'Denúncias',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'local_ocorrencia', type: 'text', label: 'Local da Ocorrência', required: true },
      { name: 'tipo_animal', type: 'text', label: 'Tipo de Animal', required: true },
      { name: 'tipo_perturbacao', type: 'select', label: 'Tipo de Perturbação', required: true },
      { name: 'frequencia', type: 'select', label: 'Frequência', required: false },
      { name: 'descricao', type: 'textarea', label: 'Descrição Detalhada', required: true },
    ]
  },
  {
    id: 'autorizacao-manifestacao-religiosa',
    name: 'Autorização para Manifestação Religiosa',
    description: 'Autorização de segurança para procissões e eventos religiosos',
    icon: 'Church',
    category: 'Autorizações',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'instituicao_religiosa', type: 'text', label: 'Instituição Religiosa', required: true },
      { name: 'tipo_evento', type: 'select', label: 'Tipo de Evento', required: true },
      { name: 'data_evento', type: 'date', label: 'Data do Evento', required: true },
      { name: 'horario_inicio', type: 'text', label: 'Horário de Início', required: true },
      { name: 'horario_termino', type: 'text', label: 'Horário de Término', required: true },
      { name: 'local_concentracao', type: 'text', label: 'Local de Concentração', required: true },
      { name: 'percurso', type: 'textarea', label: 'Percurso (se aplicável)', required: false },
      { name: 'publico_estimado', type: 'number', label: 'Público Estimado', required: true },
    ]
  },
  {
    id: 'denuncia-ocupacao-irregular',
    name: 'Denúncia de Ocupação Irregular de Terreno',
    description: 'Denúncia de invasões e ocupações irregulares',
    icon: 'Home',
    category: 'Denúncias',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'local_ocupacao', type: 'text', label: 'Local da Ocupação', required: true },
      { name: 'tipo_terreno', type: 'select', label: 'Tipo de Terreno', required: true },
      { name: 'data_inicio_ocupacao', type: 'date', label: 'Data Aproximada do Início', required: false },
      { name: 'num_familias_estimado', type: 'text', label: 'Número Estimado de Famílias', required: false },
      { name: 'descricao', type: 'textarea', label: 'Descrição da Situação', required: true },
    ]
  },
  {
    id: 'cadastro-porteiro',
    name: 'Cadastro de Porteiro/Zelador',
    description: 'Registro de porteiros e zeladores para controle de acesso',
    icon: 'DoorOpen',
    category: 'Cadastro',
    estimatedDays: 7,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'endereco_residencia', type: 'text', label: 'Endereço de Residência', required: true },
      { name: 'local_trabalho', type: 'text', label: 'Local de Trabalho', required: true },
      { name: 'tipo_estabelecimento', type: 'select', label: 'Tipo de Estabelecimento', required: true },
      { name: 'empresa_empregadora', type: 'text', label: 'Empresa Empregadora', required: false },
      { name: 'cnpj_empresa', type: 'cnpj', label: 'CNPJ da Empresa', required: false },
      { name: 'horario_trabalho', type: 'text', label: 'Horário de Trabalho', required: true },
    ]
  },
  {
    id: 'patrulha-parques',
    name: 'Patrulha em Parques e Praças',
    description: 'Solicitação de patrulhamento preventivo em parques e praças',
    icon: 'Trees',
    category: 'Rondas',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_representacao', type: 'select', label: 'Tipo de Representação', required: true },
      { name: 'periodo_preferencial', type: 'select', label: 'Período Preferencial', required: true },
      { name: 'motivo_solicitacao', type: 'textarea', label: 'Motivo da Solicitação', required: true },
    ]
  },
  {
    id: 'denuncia-crimes-ambientais',
    name: 'Denúncia de Crimes Ambientais',
    description: 'Denúncia de crimes contra o meio ambiente urbano',
    icon: 'Leaf',
    category: 'Denúncias',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'local_crime', type: 'text', label: 'Local do Crime', required: true },
      { name: 'tipo_crime_ambiental', type: 'select', label: 'Tipo de Crime Ambiental', required: true },
      { name: 'data_ocorrencia', type: 'date', label: 'Data da Ocorrência', required: false },
      { name: 'responsavel_conhecido', type: 'select', label: 'Responsável é Conhecido?', required: false },
      { name: 'descricao', type: 'textarea', label: 'Descrição Detalhada', required: true },
    ]
  },
];
