import { ServiceSuggestion, ServiceType, ServiceSubtype } from './types';

export const tecnologiaInovacaoSuggestions: ServiceSuggestion[] = [
  {
    id: 'inclusao-digital-inscricao',
    name: 'Inscrição em Curso de Inclusão Digital',
    description: 'Inscreva-se em cursos gratuitos de informática básica',
    icon: 'Monitor',
    category: 'Inclusão Digital',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'curso', type: 'select', label: 'Curso', required: true },
      { name: 'turno_preferencia', type: 'select', label: 'Turno de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Comprovante de Inscrição']
  },
  {
    id: 'wifi-publico-cadastro',
    name: 'Cadastro em Wi-Fi Público',
    description: 'Cadastre-se para usar internet pública gratuita',
    icon: 'Wifi',
    category: 'Wi-Fi Público',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'telefone', type: 'tel', label: 'Telefone Celular', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'local_uso', type: 'select', label: 'Local de Uso Principal', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 4,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Credencial de Acesso']
  },
  {
    id: 'dados-abertos-consulta',
    name: 'Consulta de Dados Abertos',
    description: 'Acesse dados públicos municipais',
    icon: 'Database',
    category: 'Dados Abertos',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'categoria_dados', type: 'select', label: 'Categoria de Dados', required: false },
      { name: 'formato_desejado', type: 'select', label: 'Formato', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'api-publica-cadastro',
    name: 'Cadastro para Uso de API Pública',
    description: 'Cadastre-se para usar APIs de dados municipais',
    icon: 'Code',
    category: 'Dados Abertos',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_aplicacao', type: 'text', label: 'Nome da Aplicação', required: true },
      { name: 'finalidade', type: 'textarea', label: 'Finalidade', required: true },
      { name: 'tipo_desenvolvedor', type: 'select', label: 'Tipo de Desenvolvedor', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Credencial de Acesso']
  },
  {
    id: 'hackathon-inscricao',
    name: 'Inscrição em Hackathon',
    description: 'Inscreva-se em maratona de programação municipal',
    icon: 'Trophy',
    category: 'Inovação',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_equipe', type: 'text', label: 'Nome da Equipe', required: true },
      { name: 'tema_interesse', type: 'select', label: 'Tema de Interesse', required: true },
      { name: 'numero_membros', type: 'number', label: 'Número de Membros', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Comprovante de Inscrição']
  },
  {
    id: 'laboratorio-fabricacao',
    name: 'Agendamento no Lab de Fabricação Digital',
    description: 'Agende uso de impressora 3D e equipamentos',
    icon: 'Printer',
    category: 'Laboratórios',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'equipamento', type: 'select', label: 'Equipamento', required: true },
      { name: 'data_uso', type: 'date', label: 'Data do Uso', required: true },
      { name: 'periodo', type: 'select', label: 'Período', required: true },
      { name: 'projeto', type: 'textarea', label: 'Descrição do Projeto', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Protocolo de Solicitação']
  },
  {
    id: 'startup-cadastro',
    name: 'Cadastro de Startup',
    description: 'Cadastre sua startup no ecossistema de inovação',
    icon: 'Rocket',
    category: 'Startups',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_startup', type: 'text', label: 'Nome da Startup', required: true },
      { name: 'area_atuacao', type: 'select', label: 'Área de Atuação', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'estagio', type: 'select', label: 'Estágio', required: true },
      { name: 'numero_fundadores', type: 'number', label: 'Número de Fundadores', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Comprovante de Cadastro']
  },
  {
    id: 'aceleradora-inscricao',
    name: 'Inscrição em Programa de Aceleração',
    description: 'Inscreva-se em programa de aceleração de startups',
    icon: 'Zap',
    category: 'Startups',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_startup', type: 'text', label: 'Nome da Startup', required: true },
      { name: 'pitch', type: 'textarea', label: 'Pitch da Ideia', required: true },
      { name: 'problema_solucao', type: 'textarea', label: 'Problema e Solução', required: true },
      { name: 'mercado_alvo', type: 'text', label: 'Mercado-Alvo', required: true },
      { name: 'faturamento_atual', type: 'number', label: 'Faturamento Atual', required: false },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Comprovante de Inscrição']
  },
  {
    id: 'sistema-sugestao',
    name: 'Sugestão de Melhoria em Sistema',
    description: 'Sugira melhorias nos sistemas municipais',
    icon: 'Lightbulb',
    category: 'Sistemas',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'sistema', type: 'select', label: 'Sistema', required: true },
      { name: 'tipo_sugestao', type: 'select', label: 'Tipo de Sugestão', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Protocolo de Solicitação']
  },
  {
    id: 'problema-sistema',
    name: 'Reporte de Problema em Sistema',
    description: 'Reporte problemas técnicos nos sistemas',
    icon: 'Bug',
    category: 'Sistemas',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'sistema', type: 'select', label: 'Sistema', required: true },
      { name: 'tipo_problema', type: 'select', label: 'Tipo de Problema', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição do Problema', required: true },
      { name: 'gravidade', type: 'select', label: 'Gravidade', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 4,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Protocolo de Solicitação']
  },
  {
    id: 'certificado-digital',
    name: 'Orientação sobre Certificado Digital',
    description: 'Receba orientação sobre certificado digital',
    icon: 'KeyRound',
    category: 'Inclusão Digital',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'finalidade', type: 'select', label: 'Finalidade', required: true },
      { name: 'tipo_certificado', type: 'select', label: 'Tipo de Certificado', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Protocolo de Solicitação']
  },
  {
    id: 'curso-programacao',
    name: 'Inscrição em Curso de Programação',
    description: 'Inscreva-se em cursos de programação',
    icon: 'Code2',
    category: 'Inclusão Digital',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'linguagem', type: 'select', label: 'Linguagem de Programação', required: true },
      { name: 'nivel', type: 'select', label: 'Nível', required: true },
      { name: 'turno_preferencia', type: 'select', label: 'Turno de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Comprovante de Inscrição']
  },
  {
    id: 'robotica-inscricao',
    name: 'Inscrição em Curso de Robótica',
    description: 'Inscreva-se em oficinas de robótica',
    icon: 'Bot',
    category: 'Laboratórios',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'faixa_etaria', type: 'select', label: 'Faixa Etária', required: true },
      { name: 'nivel', type: 'select', label: 'Nível', required: true },
      { name: 'turno_preferencia', type: 'select', label: 'Turno de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Comprovante de Inscrição']
  },
  {
    id: 'ponto-wifi-solicitacao',
    name: 'Solicitação de Ponto Wi-Fi Público',
    description: 'Solicite instalação de ponto Wi-Fi público',
    icon: 'WifiOff',
    category: 'Wi-Fi Público',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'local_solicitado', type: 'text', label: 'Local Solicitado', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
      { name: 'publico_estimado', type: 'number', label: 'Público Estimado', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Protocolo de Solicitação']
  },
  {
    id: 'wifi-mapa-cobertura',
    name: 'Consulta de Mapa de Cobertura Wi-Fi',
    description: 'Consulte mapa de pontos Wi-Fi públicos',
    icon: 'MapPin',
    category: 'Wi-Fi Público',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'regiao', type: 'select', label: 'Região', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'inovacao-desafio',
    name: 'Inscrição em Desafio de Inovação',
    description: 'Inscreva-se em desafios de inovação aberta',
    icon: 'Target',
    category: 'Inovação',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'desafio', type: 'select', label: 'Desafio', required: true },
      { name: 'nome_solucao', type: 'text', label: 'Nome da Solução', required: true },
      { name: 'descricao_proposta', type: 'textarea', label: 'Descrição da Proposta', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Comprovante de Inscrição']
  },
  {
    id: 'cidade-inteligente',
    name: 'Sugestão para Cidade Inteligente',
    description: 'Sugira iniciativas de smart city',
    icon: 'Building2',
    category: 'Inovação',
    estimatedDays: 20,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'area_atuacao', type: 'select', label: 'Área de Atuação', required: true },
      { name: 'titulo_proposta', type: 'text', label: 'Título da Proposta', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'beneficios_esperados', type: 'textarea', label: 'Benefícios Esperados', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Protocolo de Solicitação']
  },
  {
    id: 'telecentro-cadastro',
    name: 'Cadastro em Telecentro',
    description: 'Cadastre-se para usar telecentros comunitários',
    icon: 'Computer',
    category: 'Inclusão Digital',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'telecentro', type: 'select', label: 'Telecentro', required: true },
      { name: 'finalidade_uso', type: 'select', label: 'Finalidade do Uso', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Credencial de Acesso']
  },
  {
    id: 'curso-seguranca-digital',
    name: 'Curso de Segurança Digital',
    description: 'Inscreva-se em curso de segurança na internet',
    icon: 'ShieldCheck',
    category: 'Inclusão Digital',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'turma', type: 'select', label: 'Turma', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Comprovante de Inscrição']
  },
  {
    id: 'mentoria-tecnologia',
    name: 'Solicitação de Mentoria em Tecnologia',
    description: 'Solicite mentoria com profissionais de tecnologia',
    icon: 'UserCheck',
    category: 'Inovação',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'area_interesse', type: 'select', label: 'Área de Interesse', required: true },
      { name: 'nivel_conhecimento', type: 'select', label: 'Nível de Conhecimento', required: true },
      { name: 'objetivos', type: 'textarea', label: 'Objetivos', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Protocolo de Solicitação']
  },
  {
    id: 'aplicativo-cidadao',
    name: 'Sugestão de Funcionalidade para App',
    description: 'Sugira novas funcionalidades para o app do cidadão',
    icon: 'Smartphone',
    category: 'Sistemas',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'titulo_funcionalidade', type: 'text', label: 'Título da Funcionalidade', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'problema_resolve', type: 'textarea', label: 'Problema que Resolve', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Protocolo de Solicitação']
  },
  {
    id: 'dados-estatisticas',
    name: 'Solicitação de Dados Estatísticos',
    description: 'Solicite dados estatísticos específicos',
    icon: 'BarChart3',
    category: 'Dados Abertos',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tema', type: 'select', label: 'Tema', required: true },
      { name: 'periodo_interesse', type: 'text', label: 'Período de Interesse', required: true },
      { name: 'finalidade', type: 'textarea', label: 'Finalidade', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Protocolo de Solicitação']
  },
  {
    id: 'blockchain-workshop',
    name: 'Inscrição em Workshop de Blockchain',
    description: 'Participe de workshops sobre blockchain',
    icon: 'Link',
    category: 'Inovação',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nivel_conhecimento', type: 'select', label: 'Nível de Conhecimento', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Comprovante de Inscrição']
  },
  {
    id: 'ia-workshop',
    name: 'Workshop de Inteligência Artificial',
    description: 'Inscreva-se em workshops de IA',
    icon: 'Brain',
    category: 'Inovação',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'area_interesse', type: 'select', label: 'Área de Interesse', required: true },
      { name: 'nivel', type: 'select', label: 'Nível', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Comprovante de Inscrição']
  },
  {
    id: 'iot-demonstracao',
    name: 'Demonstração de IoT',
    description: 'Agende demonstração de Internet das Coisas',
    icon: 'Cpu',
    category: 'Inovação',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_demonstracao', type: 'select', label: 'Tipo de Demonstração', required: true },
      { name: 'aplicacao_interesse', type: 'text', label: 'Aplicação de Interesse', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Protocolo de Solicitação']
  },
  {
    id: 'portal-transparencia',
    name: 'Consulta ao Portal de Transparência',
    description: 'Acesse informações sobre gestão pública',
    icon: 'Eye',
    category: 'Dados Abertos',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_informacao', type: 'select', label: 'Tipo de Informação', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'game-dev-curso',
    name: 'Curso de Desenvolvimento de Jogos',
    description: 'Inscreva-se em curso de criação de jogos',
    icon: 'Gamepad2',
    category: 'Inclusão Digital',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'plataforma', type: 'select', label: 'Plataforma', required: true },
      { name: 'nivel', type: 'select', label: 'Nível', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Comprovante de Inscrição']
  },
  {
    id: 'design-thinking',
    name: 'Workshop de Design Thinking',
    description: 'Participe de workshops de design thinking',
    icon: 'Palette',
    category: 'Inovação',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'area_aplicacao', type: 'select', label: 'Área de Aplicação', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Comprovante de Inscrição']
  },
  {
    id: 'parceria-tecnologica',
    name: 'Proposta de Parceria Tecnológica',
    description: 'Proponha parceria tecnológica com a prefeitura',
    icon: 'Handshake',
    category: 'Inovação',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_empresa', type: 'text', label: 'Nome da Empresa', required: true },
      { name: 'tipo_solucao', type: 'text', label: 'Tipo de Solução', required: true },
      { name: 'descricao_proposta', type: 'textarea', label: 'Descrição da Proposta', required: true },
      { name: 'beneficios', type: 'textarea', label: 'Benefícios', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Protocolo de Solicitação']
  },
  {
    id: 'estagio-tecnologia',
    name: 'Cadastro para Estágio em TI',
    description: 'Cadastre-se para vagas de estágio em tecnologia',
    icon: 'Briefcase',
    category: 'Inclusão Digital',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'curso', type: 'text', label: 'Curso', required: true },
      { name: 'instituicao', type: 'text', label: 'Instituição de Ensino', required: true },
      { name: 'periodo_curso', type: 'text', label: 'Período do Curso', required: true },
      { name: 'area_interesse', type: 'select', label: 'Área de Interesse', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Comprovante de Cadastro']
  },
  {
    id: 'licenca-software-livre',
    name: 'Consultoria em Software Livre',
    description: 'Receba consultoria sobre migração para software livre',
    icon: 'FileCode',
    category: 'Sistemas',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_organizacao', type: 'select', label: 'Tipo de Organização', required: true },
      { name: 'softwares_atuais', type: 'textarea', label: 'Softwares Atuais', required: true },
      { name: 'objetivo', type: 'textarea', label: 'Objetivo da Migração', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Protocolo de Solicitação']
  },
  {
    id: 'youtuber-mirim',
    name: 'Curso de Criação de Conteúdo Digital',
    description: 'Curso para jovens criadores de conteúdo',
    icon: 'Video',
    category: 'Inclusão Digital',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'faixa_etaria', type: 'select', label: 'Faixa Etária', required: true },
      { name: 'plataforma_interesse', type: 'select', label: 'Plataforma de Interesse', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Comprovante de Inscrição']
  },
  {
    id: 'cyber-seguranca',
    name: 'Denúncia de Incidente de Segurança',
    description: 'Reporte incidentes de segurança cibernética',
    icon: 'ShieldAlert',
    category: 'Sistemas',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_incidente', type: 'select', label: 'Tipo de Incidente', required: true },
      { name: 'sistema_afetado', type: 'select', label: 'Sistema Afetado', required: false },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 5,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Protocolo de Solicitação']
  },
  {
    id: 'dashboard-visualizacao',
    name: 'Solicitação de Dashboard Personalizado',
    description: 'Solicite criação de dashboard de dados',
    icon: 'LayoutDashboard',
    category: 'Dados Abertos',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tema_dashboard', type: 'text', label: 'Tema do Dashboard', required: true },
      { name: 'dados_necessarios', type: 'textarea', label: 'Dados Necessários', required: true },
      { name: 'finalidade', type: 'textarea', label: 'Finalidade', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Protocolo de Solicitação']
  },
  {
    id: 'makerspace-uso',
    name: 'Agendamento de Makerspace',
    description: 'Agende uso do espaço maker',
    icon: 'Wrench',
    category: 'Laboratórios',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'data_uso', type: 'date', label: 'Data do Uso', required: true },
      { name: 'periodo', type: 'select', label: 'Período', required: true },
      { name: 'projeto', type: 'textarea', label: 'Descrição do Projeto', required: true },
      { name: 'equipamentos_necessarios', type: 'textarea', label: 'Equipamentos Necessários', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z',
    generatesDocuments: ['Protocolo de Solicitação']
  },
  {
    id: 'tech-talk',
    name: 'Inscrição em Tech Talk',
    description: 'Participe de palestras sobre tecnologia',
    icon: 'Mic',
    category: 'Inovação',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'evento', type: 'select', label: 'Evento', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'competicao-coding',
    name: 'Inscrição em Competição de Programação',
    description: 'Participe de competições de código',
    icon: 'Medal',
    category: 'Inovação',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'competicao', type: 'select', label: 'Competição', required: true },
      { name: 'categoria', type: 'select', label: 'Categoria', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'certificado-curso-tech',
    name: 'Solicitação de Certificado de Curso',
    description: 'Solicite certificado de curso de tecnologia realizado',
    icon: 'Award',
    category: 'Inclusão Digital',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_curso', type: 'select', label: 'Nome do Curso', required: true },
      { name: 'turma', type: 'text', label: 'Turma', required: true },
      { name: 'ano_conclusao', type: 'select', label: 'Ano de Conclusão', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'consultoria-transformacao-digital',
    name: 'Consultoria em Transformação Digital',
    description: 'Receba consultoria sobre transformação digital',
    icon: 'RefreshCw',
    category: 'Inovação',
    estimatedDays: 20,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_organizacao', type: 'select', label: 'Tipo de Organização', required: true },
      { name: 'desafios', type: 'textarea', label: 'Principais Desafios', required: true },
      { name: 'objetivos', type: 'textarea', label: 'Objetivos', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'sandbox-regulatorio',
    name: 'Inscrição em Sandbox Regulatório',
    description: 'Inscreva projeto em ambiente regulatório controlado',
    icon: 'TestTube',
    category: 'Startups',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_projeto', type: 'text', label: 'Nome do Projeto', required: true },
      { name: 'area_regulada', type: 'select', label: 'Área Regulada', required: true },
      { name: 'descricao_inovacao', type: 'textarea', label: 'Descrição da Inovação', required: true },
      { name: 'impacto_esperado', type: 'textarea', label: 'Impacto Esperado', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 2,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'lgpd-orientacao',
    name: 'Orientação sobre LGPD',
    description: 'Receba orientação sobre Lei Geral de Proteção de Dados',
    icon: 'Lock',
    category: 'Sistemas',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_organizacao', type: 'select', label: 'Tipo de Organização', required: true },
      { name: 'duvida_especifica', type: 'textarea', label: 'Dúvida Específica', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TECNOLOGIA_INOVACAO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
];
