import { ServiceSuggestion, ServiceType, ServiceSubtype } from './types';

export const transporteTransitoSuggestions: ServiceSuggestion[] = [
  {
    id: 'carteira-habilitacao-primeira',
    name: 'Primeira Habilitação',
    description: 'Informações sobre primeira habilitação',
    icon: 'IdCard',
    category: 'Habilitação',
    estimatedDays: 90,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'categoria_pretendida', type: 'select', label: 'Categoria Pretendida', required: true },
      { name: 'auto_escola', type: 'select', label: 'Auto Escola', required: false },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'renovacao-cnh',
    name: 'Renovação de CNH',
    description: 'Solicite renovação de carteira de habilitação',
    icon: 'RefreshCcw',
    category: 'Habilitação',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'numero_cnh', type: 'text', label: 'Número da CNH', required: true },
      { name: 'data_vencimento', type: 'date', label: 'Data de Vencimento', required: true },
      { name: 'clinica_medica', type: 'select', label: 'Clínica Médica', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'adicao-categoria',
    name: 'Adição de Categoria na CNH',
    description: 'Solicite adição de categoria na habilitação',
    icon: 'PlusCircle',
    category: 'Habilitação',
    estimatedDays: 60,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'numero_cnh', type: 'text', label: 'Número da CNH', required: true },
      { name: 'categoria_atual', type: 'select', label: 'Categoria Atual', required: true },
      { name: 'categoria_adicionar', type: 'select', label: 'Categoria a Adicionar', required: true },
      { name: 'auto_escola', type: 'select', label: 'Auto Escola', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'segunda-via-cnh',
    name: 'Segunda Via de CNH',
    description: 'Solicite segunda via da habilitação',
    icon: 'Copy',
    category: 'Habilitação',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'numero_cnh', type: 'text', label: 'Número da CNH', required: true },
      { name: 'motivo', type: 'select', label: 'Motivo', required: true },
      { name: 'boletim_ocorrencia', type: 'text', label: 'Número do B.O.', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 4,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'consulta-multas',
    name: 'Consulta de Multas de Trânsito',
    description: 'Consulte multas de trânsito',
    icon: 'Search',
    category: 'Multas',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 5,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'recurso-multa',
    name: 'Recurso de Multa de Trânsito',
    description: 'Interponha recurso contra multa de trânsito',
    icon: 'Scale',
    category: 'Multas',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'numero_auto', type: 'text', label: 'Número do Auto de Infração', required: true },
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'tipo_recurso', type: 'select', label: 'Tipo de Recurso', required: true },
      { name: 'fundamentacao', type: 'textarea', label: 'Fundamentação', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 4,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'parcelamento-multas',
    name: 'Parcelamento de Multas',
    description: 'Solicite parcelamento de multas de trânsito',
    icon: 'CreditCard',
    category: 'Multas',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'valor_total', type: 'number', label: 'Valor Total', required: true },
      { name: 'numero_parcelas', type: 'select', label: 'Número de Parcelas', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.PAGAMENTO,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 4,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'indicacao-condutor',
    name: 'Indicação de Condutor',
    description: 'Indique o condutor responsável pela infração',
    icon: 'UserCog',
    category: 'Multas',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'numero_auto', type: 'text', label: 'Número do Auto de Infração', required: true },
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'cpf_condutor', type: 'cpf', label: 'CPF do Condutor', required: true },
      { name: 'cnh_condutor', type: 'text', label: 'CNH do Condutor', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 4,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'pontuacao-cnh',
    name: 'Consulta de Pontuação na CNH',
    description: 'Consulte pontuação acumulada na habilitação',
    icon: 'BarChart',
    category: 'Habilitação',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_cnh', type: 'text', label: 'Número da CNH', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 5,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'estacionamento-rotativo',
    name: 'Cadastro em Estacionamento Rotativo',
    description: 'Cadastre-se no sistema de zona azul',
    icon: 'ParkingCircle',
    category: 'Estacionamento',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone Celular', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'vaga-especial',
    name: 'Solicitação de Vaga Especial',
    description: 'Solicite vaga de estacionamento para pessoa com deficiência',
    icon: 'Accessibility',
    category: 'Estacionamento',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'tipo_deficiencia', type: 'select', label: 'Tipo de Deficiência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'sinalizacao-solicitacao',
    name: 'Solicitação de Sinalização de Trânsito',
    description: 'Solicite instalação ou reparo de sinalização',
    icon: 'TriangleAlert',
    category: 'Sinalização',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_sinalizacao', type: 'select', label: 'Tipo de Sinalização', required: true },
      { name: 'tipo_solicitacao', type: 'select', label: 'Tipo de Solicitação', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'semaforo-solicitacao',
    name: 'Solicitação de Semáforo',
    description: 'Solicite instalação de semáforo',
    icon: 'CircleDot',
    category: 'Semáforos',
    estimatedDays: 90,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco_cruzamento', type: 'text', label: 'Endereço do Cruzamento', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
      { name: 'historico_acidentes', type: 'textarea', label: 'Histórico de Acidentes', required: false },
      { name: 'fluxo_veiculos', type: 'select', label: 'Fluxo de Veículos', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'semaforo-defeito',
    name: 'Reporte de Defeito em Semáforo',
    description: 'Reporte semáforo com defeito',
    icon: 'AlertCircle',
    category: 'Semáforos',
    estimatedDays: 2,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco_semaforo', type: 'text', label: 'Endereço do Semáforo', required: true },
      { name: 'tipo_defeito', type: 'select', label: 'Tipo de Defeito', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 5,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'lombada-solicitacao',
    name: 'Solicitação de Lombada',
    description: 'Solicite instalação de lombada ou redutor de velocidade',
    icon: 'MoveVertical',
    category: 'Sinalização',
    estimatedDays: 45,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_redutor', type: 'select', label: 'Tipo de Redutor', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
      { name: 'proximidade_escola', type: 'checkbox', label: 'Próximo a Escola', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'transporte-escolar-cadastro',
    name: 'Cadastro em Transporte Escolar',
    description: 'Cadastre estudante no transporte escolar',
    icon: 'Bus',
    category: 'Transporte Escolar',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_estudante', type: 'text', label: 'Nome do Estudante', required: true },
      { name: 'escola', type: 'select', label: 'Escola', required: true },
      { name: 'serie', type: 'select', label: 'Série', required: true },
      { name: 'turno', type: 'select', label: 'Turno', required: true },
      { name: 'endereco_residencia', type: 'text', label: 'Endereço de Residência', required: true },
      { name: 'telefone_responsavel', type: 'tel', label: 'Telefone do Responsável', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 4,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'transporte-escolar-rota',
    name: 'Consulta de Rotas de Transporte Escolar',
    description: 'Consulte rotas e horários do transporte escolar',
    icon: 'Route',
    category: 'Transporte Escolar',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'escola', type: 'select', label: 'Escola', required: false },
      { name: 'regiao', type: 'select', label: 'Região', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'autorizacao-especial-transito',
    name: 'Autorização Especial de Trânsito (AET)',
    description: 'Solicite AET para veículos com excesso de peso ou dimensão',
    icon: 'FileCheck',
    category: 'Veículos',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'tipo_excesso', type: 'select', label: 'Tipo de Excesso', required: true },
      { name: 'rota_pretendida', type: 'textarea', label: 'Rota Pretendida', required: true },
      { name: 'data_transito', type: 'date', label: 'Data do Trânsito', required: true },
      { name: 'carga_descricao', type: 'textarea', label: 'Descrição da Carga', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'bloqueio-via',
    name: 'Solicitação de Bloqueio de Via',
    description: 'Solicite bloqueio temporário de via para evento',
    icon: 'Ban',
    category: 'Sinalização',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'data_evento', type: 'date', label: 'Data do Evento', required: true },
      { name: 'horario_inicio', type: 'text', label: 'Horário de Início', required: true },
      { name: 'horario_fim', type: 'text', label: 'Horário de Término', required: true },
      { name: 'tipo_evento', type: 'select', label: 'Tipo de Evento', required: true },
      { name: 'publico_estimado', type: 'number', label: 'Público Estimado', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'bicicletario-localizacao',
    name: 'Consulta de Bicicletários',
    description: 'Consulte localização de bicicletários públicos',
    icon: 'Bike',
    category: 'Estacionamento',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'regiao', type: 'select', label: 'Região', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'bicicletario-solicitacao',
    name: 'Solicitação de Bicicletário',
    description: 'Solicite instalação de bicicletário',
    icon: 'ParkingSquare',
    category: 'Estacionamento',
    estimatedDays: 60,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_local', type: 'select', label: 'Tipo de Local', required: true },
      { name: 'demanda_estimada', type: 'number', label: 'Demanda Estimada', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'curso-reciclagem',
    name: 'Inscrição em Curso de Reciclagem',
    description: 'Inscreva-se em curso de reciclagem de condutores',
    icon: 'GraduationCap',
    category: 'Habilitação',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'numero_cnh', type: 'text', label: 'Número da CNH', required: true },
      { name: 'motivo', type: 'select', label: 'Motivo', required: true },
      { name: 'turma_preferencia', type: 'select', label: 'Turma de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 4,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'credencial-taxi',
    name: 'Solicitação de Credencial de Taxi',
    description: 'Solicite credencial para trabalhar como taxista',
    icon: 'Car',
    category: 'Veículos',
    estimatedDays: 45,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'numero_cnh', type: 'text', label: 'Número da CNH', required: true },
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'tempo_habilitacao', type: 'number', label: 'Tempo de Habilitação (anos)', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'vistoria-taxi',
    name: 'Agendamento de Vistoria de Táxi',
    description: 'Agende vistoria para veículo de táxi',
    icon: 'ClipboardCheck',
    category: 'Veículos',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'numero_permissao', type: 'text', label: 'Número da Permissão', required: true },
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 4,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'carga-descarga',
    name: 'Autorização de Carga e Descarga',
    description: 'Solicite autorização para operação de carga/descarga',
    icon: 'PackageOpen',
    category: 'Veículos',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'endereco_operacao', type: 'text', label: 'Endereço da Operação', required: true },
      { name: 'horario_operacao', type: 'text', label: 'Horário de Operação', required: true },
      { name: 'tipo_carga', type: 'select', label: 'Tipo de Carga', required: true },
      { name: 'frequencia', type: 'select', label: 'Frequência', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'alteracao-caracteristica',
    name: 'Autorização para Alteração de Veículo',
    description: 'Solicite autorização para alteração de características',
    icon: 'Settings',
    category: 'Veículos',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'tipo_alteracao', type: 'select', label: 'Tipo de Alteração', required: true },
      { name: 'descricao_alteracao', type: 'textarea', label: 'Descrição da Alteração', required: true },
      { name: 'oficina_responsavel', type: 'text', label: 'Oficina Responsável', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'faixa-exclusiva',
    name: 'Solicitação de Faixa Exclusiva Temporária',
    description: 'Solicite faixa exclusiva para mudança ou obra',
    icon: 'Construction',
    category: 'Sinalização',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'data_inicio', type: 'date', label: 'Data de Início', required: true },
      { name: 'data_fim', type: 'date', label: 'Data de Término', required: true },
      { name: 'finalidade', type: 'select', label: 'Finalidade', required: true },
      { name: 'horario', type: 'text', label: 'Horário', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'denuncia-transito',
    name: 'Denúncia de Infração de Trânsito',
    description: 'Denuncie infrações de trânsito',
    icon: 'AlertOctagon',
    category: 'Multas',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_infracao', type: 'select', label: 'Tipo de Infração', required: true },
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: false },
      { name: 'local', type: 'text', label: 'Local', required: true },
      { name: 'data_hora', type: 'date', label: 'Data e Hora', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'anonimo', type: 'checkbox', label: 'Denúncia Anônima', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'velocidade-maxima',
    name: 'Consulta de Velocidade Máxima',
    description: 'Consulte velocidade máxima permitida em vias',
    icon: 'Gauge',
    category: 'Sinalização',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'jari-recurso',
    name: 'Recurso ao JARI',
    description: 'Interponha recurso à Junta Administrativa de Recursos',
    icon: 'FileWarning',
    category: 'Multas',
    estimatedDays: 45,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'numero_processo', type: 'text', label: 'Número do Processo', required: true },
      { name: 'numero_auto', type: 'text', label: 'Número do Auto de Infração', required: true },
      { name: 'fundamentacao', type: 'textarea', label: 'Fundamentação', required: true },
      { name: 'pedido', type: 'textarea', label: 'Pedido', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'radar-localizacao',
    name: 'Consulta de Localização de Radares',
    description: 'Consulte localização de radares de velocidade',
    icon: 'MapPinned',
    category: 'Sinalização',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'regiao', type: 'select', label: 'Região', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'faixa-pedestres',
    name: 'Solicitação de Faixa de Pedestres',
    description: 'Solicite instalação de faixa de pedestres',
    icon: 'User',
    category: 'Sinalização',
    estimatedDays: 30,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
      { name: 'proximidade_escola', type: 'checkbox', label: 'Próximo a Escola', required: false },
      { name: 'proximidade_hospital', type: 'checkbox', label: 'Próximo a Hospital', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'passarela-solicitacao',
    name: 'Solicitação de Passarela',
    description: 'Solicite construção de passarela para pedestres',
    icon: 'Bridge',
    category: 'Sinalização',
    estimatedDays: 180,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_via', type: 'select', label: 'Tipo de Via', required: true },
      { name: 'fluxo_pedestres', type: 'select', label: 'Fluxo de Pedestres', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
      { name: 'historico_acidentes', type: 'textarea', label: 'Histórico de Acidentes', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 2,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'mao-direcao',
    name: 'Solicitação de Mudança de Mão de Direção',
    description: 'Solicite mudança de sentido de via',
    icon: 'ArrowRightLeft',
    category: 'Sinalização',
    estimatedDays: 60,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'sentido_atual', type: 'select', label: 'Sentido Atual', required: true },
      { name: 'sentido_pretendido', type: 'select', label: 'Sentido Pretendido', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'rotatoria-solicitacao',
    name: 'Solicitação de Rotatória',
    description: 'Solicite instalação de rotatória',
    icon: 'CircleDashed',
    category: 'Sinalização',
    estimatedDays: 90,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco_cruzamento', type: 'text', label: 'Endereço do Cruzamento', required: true },
      { name: 'numero_vias', type: 'number', label: 'Número de Vias', required: true },
      { name: 'fluxo_veiculos', type: 'select', label: 'Fluxo de Veículos', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.CAPTURA_COMPLETA,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 2,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'educacao-transito',
    name: 'Solicitação de Palestra de Educação no Trânsito',
    description: 'Solicite palestra educativa sobre trânsito',
    icon: 'Presentation',
    category: 'Habilitação',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'instituicao', type: 'text', label: 'Instituição', required: true },
      { name: 'publico_alvo', type: 'select', label: 'Público-Alvo', required: true },
      { name: 'tema', type: 'select', label: 'Tema', required: true },
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
      { name: 'numero_participantes', type: 'number', label: 'Número de Participantes', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#ec4899',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'certidao-nada-consta',
    name: 'Certidão Nada Consta de Multas',
    description: 'Emita certidão de inexistência de multas',
    icon: 'FileCheck',
    category: 'Multas',
    estimatedDays: 3,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'placa_veiculo', type: 'text', label: 'Placa do Veículo', required: true },
      { name: 'finalidade', type: 'select', label: 'Finalidade', required: true },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 4,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'agente-transito',
    name: 'Solicitação de Agente de Trânsito',
    description: 'Solicite presença de agente de trânsito',
    icon: 'ShieldCheck',
    category: 'Sinalização',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'local', type: 'text', label: 'Local', required: true },
      { name: 'data', type: 'date', label: 'Data', required: true },
      { name: 'horario', type: 'text', label: 'Horário', required: true },
      { name: 'motivo', type: 'textarea', label: 'Motivo', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#3b82f6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'fiscalizacao-estacionamento',
    name: 'Solicitação de Fiscalização de Estacionamento',
    description: 'Solicite fiscalização de estacionamento irregular',
    icon: 'Eye',
    category: 'Estacionamento',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_irregularidade', type: 'select', label: 'Tipo de Irregularidade', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'horario_problema', type: 'text', label: 'Horário do Problema', required: false },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#f59e0b',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'transporte-escolar-reclamacao',
    name: 'Reclamação sobre Transporte Escolar',
    description: 'Registre reclamação sobre transporte escolar',
    icon: 'MessageSquareWarning',
    category: 'Transporte Escolar',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'linha_rota', type: 'select', label: 'Linha/Rota', required: true },
      { name: 'tipo_reclamacao', type: 'select', label: 'Tipo de Reclamação', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 4,
    color: '#ef4444',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'placa-rua-solicitacao',
    name: 'Solicitação de Placa de Rua',
    description: 'Solicite instalação ou troca de placa de rua',
    icon: 'Signpost',
    category: 'Sinalização',
    estimatedDays: 20,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_solicitacao', type: 'select', label: 'Tipo de Solicitação', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#06b6d4',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'municipalizacao-transito',
    name: 'Consulta sobre Municipalização do Trânsito',
    description: 'Consulte informações sobre serviços municipalizados',
    icon: 'Info',
    category: 'Habilitação',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'servico', type: 'select', label: 'Serviço', required: false },
    ],
    serviceType: ServiceType.SEM_DADOS,
    serviceSubtype: ServiceSubtype.CONSULTIVO,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 3,
    color: '#10b981',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
  {
    id: 'exame-medico-psicologico',
    name: 'Agendamento de Exame Médico e Psicológico',
    description: 'Agende exame médico e psicológico para CNH',
    icon: 'Stethoscope',
    category: 'Habilitação',
    estimatedDays: 7,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'tipo_exame', type: 'select', label: 'Tipo de Exame', required: true },
      { name: 'clinica', type: 'select', label: 'Clínica', required: true },
      { name: 'data_preferencia', type: 'date', label: 'Data de Preferência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
    ],
    serviceType: ServiceType.COM_DADOS,
    serviceSubtype: ServiceSubtype.SOLICITACAO_SIMPLES,
    departmentCode: 'TRANSPORTE_TRANSITO',
    priority: 4,
    color: '#8b5cf6',
    moduleType: null,
    status: 'ACTIVE' as const,
    createdAt: '2026-01-26T18:30:00.000Z'
  },
];
