import { ServiceSuggestion } from './types';

export const turismoSuggestions: ServiceSuggestion[] = [
  {
    id: 'cadastro-guia',
    name: 'Cadastro de Guia Turístico',
    description: 'Registro oficial de guias turísticos municipais',
    icon: 'MapPin',
    category: 'Cadastro Profissional',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_completo', type: 'text', label: 'Nome Completo', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'num_cadastur', type: 'text', label: 'Número CADASTUR (se possuir)', required: false },
      { name: 'idiomas', type: 'text', label: 'Idiomas que Fala', required: true },
      { name: 'especializacao', type: 'select', label: 'Especialização', required: true },
      { name: 'formacao', type: 'text', label: 'Formação', required: true },
      { name: 'experiencia_anos', type: 'number', label: 'Anos de Experiência', required: true },
    ]
  },
  {
    id: 'cadastro-estabelecimento',
    name: 'Cadastro de Estabelecimento Turístico',
    description: 'Registro de hotéis, pousadas, restaurantes e agências',
    icon: 'Building',
    category: 'Cadastro Comercial',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_estabelecimento', type: 'text', label: 'Nome do Estabelecimento', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'responsavel', type: 'text', label: 'Nome do Responsável', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_estabelecimento', type: 'select', label: 'Tipo de Estabelecimento', required: true },
      { name: 'capacidade', type: 'number', label: 'Capacidade de Atendimento', required: true },
      { name: 'num_cadastur', type: 'text', label: 'Número CADASTUR (se possuir)', required: false },
      { name: 'classificacao', type: 'select', label: 'Classificação', required: false },
    ]
  },
  {
    id: 'autorizacao-evento-turistico',
    name: 'Autorização para Evento Turístico',
    description: 'Licença para realização de eventos turísticos e culturais',
    icon: 'Calendar',
    category: 'Eventos',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_organizador', type: 'text', label: 'Nome do Organizador', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'nome_evento', type: 'text', label: 'Nome do Evento', required: true },
      { name: 'tipo_evento', type: 'select', label: 'Tipo de Evento', required: true },
      { name: 'local_evento', type: 'text', label: 'Local do Evento', required: true },
      { name: 'data_inicio', type: 'date', label: 'Data de Início', required: true },
      { name: 'data_termino', type: 'date', label: 'Data de Término', required: true },
      { name: 'publico_estimado', type: 'number', label: 'Público Estimado', required: true },
      { name: 'descricao_evento', type: 'textarea', label: 'Descrição do Evento', required: true },
    ]
  },
  {
    id: 'roteiro-turistico',
    name: 'Inclusão em Roteiro Turístico Oficial',
    description: 'Solicite a inclusão de seu atrativo nos roteiros oficiais',
    icon: 'Route',
    category: 'Roteiros',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_responsavel', type: 'text', label: 'Nome do Responsável', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'nome_atrativo', type: 'text', label: 'Nome do Atrativo', required: true },
      { name: 'tipo_atrativo', type: 'select', label: 'Tipo de Atrativo', required: true },
      { name: 'endereco_atrativo', type: 'text', label: 'Endereço/Localização', required: true },
      { name: 'descricao_atrativo', type: 'textarea', label: 'Descrição do Atrativo', required: true },
      { name: 'horario_funcionamento', type: 'text', label: 'Horário de Funcionamento', required: true },
      { name: 'valor_entrada', type: 'text', label: 'Valor de Entrada (se houver)', required: false },
      { name: 'acessibilidade', type: 'select', label: 'Possui Acessibilidade?', required: true },
    ]
  },
  {
    id: 'selo-turismo',
    name: 'Selo de Qualidade Turística',
    description: 'Certificação de qualidade em serviços turísticos',
    icon: 'Award',
    category: 'Certificação',
    estimatedDays: 45,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_estabelecimento', type: 'text', label: 'Nome do Estabelecimento', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'tipo_estabelecimento', type: 'select', label: 'Tipo de Estabelecimento', required: true },
      { name: 'tempo_atividade', type: 'text', label: 'Tempo de Atividade (anos)', required: true },
      { name: 'num_funcionarios', type: 'number', label: 'Número de Funcionários', required: true },
      { name: 'certificacoes_existentes', type: 'text', label: 'Certificações Existentes', required: false },
    ]
  },
  {
    id: 'material-promocional',
    name: 'Solicitação de Material Promocional',
    description: 'Folders, mapas e materiais promocionais do município',
    icon: 'FileText',
    category: 'Divulgação',
    estimatedDays: 5,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'tipo_material', type: 'select', label: 'Tipo de Material', required: true },
      { name: 'quantidade', type: 'number', label: 'Quantidade Solicitada', required: true },
      { name: 'finalidade', type: 'textarea', label: 'Finalidade do Material', required: true },
    ]
  },
  {
    id: 'capacitacao-turismo',
    name: 'Inscrição em Curso de Capacitação',
    description: 'Cursos gratuitos de capacitação para profissionais do turismo',
    icon: 'BookOpen',
    category: 'Capacitação',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_completo', type: 'text', label: 'Nome Completo', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'curso_interesse', type: 'select', label: 'Curso de Interesse', required: true },
      { name: 'atua_turismo', type: 'select', label: 'Já Atua no Turismo?', required: true },
      { name: 'area_atuacao', type: 'text', label: 'Área de Atuação', required: false },
      { name: 'escolaridade', type: 'select', label: 'Escolaridade', required: true },
    ]
  },
  {
    id: 'cadastro-artesao',
    name: 'Cadastro de Artesão Local',
    description: 'Registro de artesãos para divulgação e participação em eventos',
    icon: 'Palette',
    category: 'Cadastro Profissional',
    estimatedDays: 10,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_completo', type: 'text', label: 'Nome Completo', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: false },
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_artesanato', type: 'text', label: 'Tipo de Artesanato', required: true },
      { name: 'tecnicas_utilizadas', type: 'textarea', label: 'Técnicas Utilizadas', required: true },
      { name: 'tempo_experiencia', type: 'text', label: 'Tempo de Experiência', required: true },
      { name: 'possui_certificacao', type: 'select', label: 'Possui Certificação de Artesão?', required: false },
    ]
  },
  {
    id: 'feira-artesanato',
    name: 'Participação em Feiras de Artesanato',
    description: 'Inscrição para participar de feiras e eventos de artesanato',
    icon: 'Store',
    category: 'Eventos',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_artesao', type: 'text', label: 'Nome do Artesão', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: false },
      { name: 'nome_feira', type: 'select', label: 'Feira Pretendida', required: true },
      { name: 'tipo_produto', type: 'text', label: 'Tipo de Produto', required: true },
      { name: 'necessita_energia', type: 'select', label: 'Necessita Energia Elétrica?', required: true },
      { name: 'tamanho_barraca', type: 'select', label: 'Tamanho da Barraca', required: true },
    ]
  },
  {
    id: 'apoio-evento-cultural',
    name: 'Apoio Municipal a Eventos Culturais',
    description: 'Solicite apoio da secretaria para realização de eventos',
    icon: 'Users',
    category: 'Apoio',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_proponente', type: 'text', label: 'Nome do Proponente', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'nome_evento', type: 'text', label: 'Nome do Evento', required: true },
      { name: 'tipo_evento', type: 'select', label: 'Tipo de Evento', required: true },
      { name: 'data_evento', type: 'date', label: 'Data do Evento', required: true },
      { name: 'publico_estimado', type: 'number', label: 'Público Estimado', required: true },
      { name: 'tipo_apoio_solicitado', type: 'select', label: 'Tipo de Apoio Solicitado', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ]
  },
  {
    id: 'visita-tecnica-turismo',
    name: 'Agendamento de Visita Técnica',
    description: 'Agendamento de visitas técnicas a atrativos turísticos',
    icon: 'Users',
    category: 'Visitas',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_responsavel', type: 'text', label: 'Nome do Responsável', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'instituicao', type: 'text', label: 'Instituição/Empresa', required: true },
      { name: 'num_participantes', type: 'number', label: 'Número de Participantes', required: true },
      { name: 'data_pretendida', type: 'date', label: 'Data Pretendida', required: true },
      { name: 'atrativos_interesse', type: 'textarea', label: 'Atrativos de Interesse', required: true },
      { name: 'objetivo_visita', type: 'textarea', label: 'Objetivo da Visita', required: true },
    ]
  },
  {
    id: 'hospedagem-familiar',
    name: 'Cadastro de Hospedagem Familiar',
    description: 'Registro de residências para hospedagem domiciliar',
    icon: 'Home',
    category: 'Cadastro Comercial',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_proprietario', type: 'text', label: 'Nome do Proprietário', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: false },
      { name: 'endereco_imovel', type: 'text', label: 'Endereço do Imóvel', required: true },
      { name: 'num_quartos_disponiveis', type: 'number', label: 'Número de Quartos Disponíveis', required: true },
      { name: 'capacidade_hospedes', type: 'number', label: 'Capacidade de Hóspedes', required: true },
      { name: 'oferece_cafe_manha', type: 'select', label: 'Oferece Café da Manhã?', required: true },
      { name: 'idiomas_falados', type: 'text', label: 'Idiomas Falados', required: false },
    ]
  },
  {
    id: 'restaurante-tipico',
    name: 'Certificação de Restaurante Típico',
    description: 'Certificação para restaurantes com culinária regional',
    icon: 'UtensilsCrossed',
    category: 'Certificação',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_restaurante', type: 'text', label: 'Nome do Restaurante', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'especialidade_culinaria', type: 'textarea', label: 'Especialidade Culinária', required: true },
      { name: 'pratos_tipicos', type: 'textarea', label: 'Principais Pratos Típicos', required: true },
      { name: 'tempo_atividade', type: 'text', label: 'Tempo de Atividade (anos)', required: true },
    ]
  },
  {
    id: 'cadastro-condutor',
    name: 'Cadastro de Condutor de Turismo de Aventura',
    description: 'Registro de condutores para atividades de ecoturismo e aventura',
    icon: 'Mountain',
    category: 'Cadastro Profissional',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_completo', type: 'text', label: 'Nome Completo', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'especialidade', type: 'select', label: 'Especialidade', required: true },
      { name: 'certificacoes', type: 'textarea', label: 'Certificações e Cursos', required: true },
      { name: 'tempo_experiencia', type: 'number', label: 'Anos de Experiência', required: true },
      { name: 'possui_seguro', type: 'select', label: 'Possui Seguro de Responsabilidade Civil?', required: true },
    ]
  },
  {
    id: 'patrimonio-historico',
    name: 'Inclusão no Inventário do Patrimônio Histórico',
    description: 'Solicitação de tombamento ou registro de patrimônio histórico',
    icon: 'Landmark',
    category: 'Patrimônio',
    estimatedDays: 60,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'nome_bem', type: 'text', label: 'Nome do Bem', required: true },
      { name: 'tipo_patrimonio', type: 'select', label: 'Tipo de Patrimônio', required: true },
      { name: 'localizacao', type: 'text', label: 'Localização', required: true },
      { name: 'periodo_construcao', type: 'text', label: 'Período de Construção', required: false },
      { name: 'relevancia_historica', type: 'textarea', label: 'Relevância Histórica/Cultural', required: true },
    ]
  },
  {
    id: 'autorizacao-filmagem',
    name: 'Autorização para Filmagem em Atrativos',
    description: 'Licença para filmagens e produções em atrativos turísticos',
    icon: 'Video',
    category: 'Autorizações',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_produtora', type: 'text', label: 'Nome da Produtora', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'tipo_producao', type: 'select', label: 'Tipo de Produção', required: true },
      { name: 'locais_filmagem', type: 'textarea', label: 'Locais para Filmagem', required: true },
      { name: 'data_inicio', type: 'date', label: 'Data de Início', required: true },
      { name: 'data_termino', type: 'date', label: 'Data de Término', required: true },
      { name: 'num_equipe', type: 'number', label: 'Tamanho da Equipe', required: true },
    ]
  },
  {
    id: 'transporte-turistico',
    name: 'Licença para Transporte Turístico',
    description: 'Autorização para operação de transporte turístico',
    icon: 'Bus',
    category: 'Licenciamento',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_empresa', type: 'text', label: 'Nome da Empresa', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'tipo_transporte', type: 'select', label: 'Tipo de Transporte', required: true },
      { name: 'num_veiculos', type: 'number', label: 'Número de Veículos', required: true },
      { name: 'capacidade_total', type: 'number', label: 'Capacidade Total de Passageiros', required: true },
      { name: 'roteiros_atendidos', type: 'textarea', label: 'Roteiros Atendidos', required: true },
    ]
  },
  {
    id: 'mirante-observacao',
    name: 'Autorização para Instalação de Mirante',
    description: 'Licença para construção de mirantes e pontos de observação',
    icon: 'Eye',
    category: 'Infraestrutura',
    estimatedDays: 45,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'localizacao_pretendida', type: 'text', label: 'Localização Pretendida', required: true },
      { name: 'tipo_estrutura', type: 'select', label: 'Tipo de Estrutura', required: true },
      { name: 'dimensoes', type: 'text', label: 'Dimensões (m²)', required: true },
      { name: 'capacidade_pessoas', type: 'number', label: 'Capacidade de Pessoas', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa e Objetivo', required: true },
    ]
  },
  {
    id: 'festival-gastronomico',
    name: 'Inscrição para Festival Gastronômico',
    description: 'Participação em festivais de gastronomia do município',
    icon: 'ChefHat',
    category: 'Eventos',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_participante', type: 'text', label: 'Nome do Participante/Estabelecimento', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'prato_inscrito', type: 'text', label: 'Prato Inscrito', required: true },
      { name: 'categoria', type: 'select', label: 'Categoria', required: true },
      { name: 'ingredientes_principais', type: 'textarea', label: 'Ingredientes Principais', required: true },
      { name: 'historia_prato', type: 'textarea', label: 'História do Prato', required: false },
    ]
  },
  {
    id: 'rota-gastronomica',
    name: 'Inclusão em Rota Gastronômica',
    description: 'Cadastro para participar da rota gastronômica oficial',
    icon: 'MapTrifold',
    category: 'Roteiros',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_estabelecimento', type: 'text', label: 'Nome do Estabelecimento', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_culinaria', type: 'select', label: 'Tipo de Culinária', required: true },
      { name: 'especialidades', type: 'textarea', label: 'Especialidades da Casa', required: true },
      { name: 'horario_funcionamento', type: 'text', label: 'Horário de Funcionamento', required: true },
    ]
  },
  {
    id: 'centro-informacoes',
    name: 'Solicitação de Instalação de Centro de Informações',
    description: 'Pedido de instalação de posto de informações turísticas',
    icon: 'Info',
    category: 'Infraestrutura',
    estimatedDays: 60,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'local_proposto', type: 'text', label: 'Local Proposto', required: true },
      { name: 'tipo_representacao', type: 'select', label: 'Tipo de Representação', required: true },
      { name: 'fluxo_turistas_estimado', type: 'text', label: 'Fluxo de Turistas Estimado', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ]
  },
  {
    id: 'sinalizacao-turistica',
    name: 'Solicitação de Sinalização Turística',
    description: 'Pedido de instalação de placas e sinalizações',
    icon: 'SignPost',
    category: 'Infraestrutura',
    estimatedDays: 45,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'local_sinalizacao', type: 'text', label: 'Local para Sinalização', required: true },
      { name: 'tipo_atrativo', type: 'select', label: 'Tipo de Atrativo', required: true },
      { name: 'distancia_aproximada', type: 'text', label: 'Distância do Centro (km)', required: false },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ]
  },
  {
    id: 'camping-autorizado',
    name: 'Licenciamento de Área de Camping',
    description: 'Autorização para operação de camping e áreas de acampamento',
    icon: 'Tent',
    category: 'Licenciamento',
    estimatedDays: 40,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_proprietario', type: 'text', label: 'Nome do Proprietário', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'localizacao_area', type: 'text', label: 'Localização da Área', required: true },
      { name: 'area_total', type: 'number', label: 'Área Total (m²)', required: true },
      { name: 'capacidade_barracas', type: 'number', label: 'Capacidade de Barracas', required: true },
      { name: 'infraestrutura_disponivel', type: 'textarea', label: 'Infraestrutura Disponível', required: true },
    ]
  },
  {
    id: 'turismo-rural',
    name: 'Cadastro de Propriedade para Turismo Rural',
    description: 'Registro de fazendas e sítios para turismo rural',
    icon: 'Tractor',
    category: 'Cadastro Comercial',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_proprietario', type: 'text', label: 'Nome do Proprietário', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: false },
      { name: 'nome_propriedade', type: 'text', label: 'Nome da Propriedade', required: true },
      { name: 'localizacao', type: 'text', label: 'Localização', required: true },
      { name: 'area_propriedade', type: 'number', label: 'Área da Propriedade (hectares)', required: true },
      { name: 'atividades_oferecidas', type: 'textarea', label: 'Atividades Oferecidas', required: true },
      { name: 'capacidade_hospedagem', type: 'number', label: 'Capacidade de Hospedagem', required: false },
    ]
  },
  {
    id: 'passeio-nautico',
    name: 'Autorização para Passeio Náutico',
    description: 'Licença para operação de passeios de barco e atividades náuticas',
    icon: 'Sailboat',
    category: 'Licenciamento',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_operador', type: 'text', label: 'Nome do Operador', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'tipo_embarcacao', type: 'select', label: 'Tipo de Embarcação', required: true },
      { name: 'capacidade_passageiros', type: 'number', label: 'Capacidade de Passageiros', required: true },
      { name: 'roteiro_passeio', type: 'textarea', label: 'Roteiro do Passeio', required: true },
      { name: 'possui_habilitacao', type: 'select', label: 'Possui Habilitação Náutica?', required: true },
      { name: 'possui_seguro', type: 'select', label: 'Possui Seguro?', required: true },
    ]
  },
  {
    id: 'tour-bicicleta',
    name: 'Cadastro de Tour de Bicicleta',
    description: 'Registro de operadores de passeios ciclísticos',
    icon: 'Bike',
    category: 'Cadastro Profissional',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_operador', type: 'text', label: 'Nome do Operador', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'roteiros_oferecidos', type: 'textarea', label: 'Roteiros Oferecidos', required: true },
      { name: 'num_bicicletas', type: 'number', label: 'Número de Bicicletas Disponíveis', required: true },
      { name: 'nivel_dificuldade', type: 'select', label: 'Nível de Dificuldade', required: true },
      { name: 'equipamentos_seguranca', type: 'textarea', label: 'Equipamentos de Segurança', required: true },
    ]
  },
  {
    id: 'observacao-fauna',
    name: 'Autorização para Observação de Fauna',
    description: 'Licença para atividades de observação de aves e fauna silvestre',
    icon: 'Binoculars',
    category: 'Licenciamento',
    estimatedDays: 25,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_guia', type: 'text', label: 'Nome do Guia/Operador', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'area_atuacao', type: 'text', label: 'Área de Atuação', required: true },
      { name: 'especialidade', type: 'select', label: 'Especialidade', required: true },
      { name: 'tamanho_grupo_maximo', type: 'number', label: 'Tamanho Máximo do Grupo', required: true },
      { name: 'formacao_especifica', type: 'textarea', label: 'Formação Específica', required: true },
    ]
  },
  {
    id: 'fam-tour',
    name: 'Solicitação de FAM Tour',
    description: 'Participação em viagens de familiarização para agentes de turismo',
    icon: 'Plane',
    category: 'Promoção',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_agente', type: 'text', label: 'Nome do Agente', required: true },
      { name: 'empresa', type: 'text', label: 'Empresa/Agência', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'cargo', type: 'text', label: 'Cargo', required: true },
      { name: 'area_atuacao', type: 'select', label: 'Área de Atuação', required: true },
      { name: 'periodo_disponivel', type: 'text', label: 'Período Disponível', required: true },
      { name: 'interesse_roteiros', type: 'textarea', label: 'Interesse em Roteiros', required: true },
    ]
  },
  {
    id: 'feira-turismo',
    name: 'Participação em Feira de Turismo',
    description: 'Inscrição para participar de feiras e eventos de turismo',
    icon: 'Presentation',
    category: 'Eventos',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_empresa', type: 'text', label: 'Nome da Empresa/Estabelecimento', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'tipo_servico', type: 'select', label: 'Tipo de Serviço Turístico', required: true },
      { name: 'interesse_feira', type: 'select', label: 'Feira de Interesse', required: true },
      { name: 'tamanho_stand', type: 'select', label: 'Tamanho de Stand Desejado', required: true },
    ]
  },
  {
    id: 'museu-comunitario',
    name: 'Cadastro de Museu ou Espaço Cultural',
    description: 'Registro de museus, centros culturais e memoriais',
    icon: 'Building2',
    category: 'Patrimônio',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_espaco', type: 'text', label: 'Nome do Espaço', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'tipo_acervo', type: 'textarea', label: 'Tipo de Acervo', required: true },
      { name: 'horario_visitacao', type: 'text', label: 'Horário de Visitação', required: true },
      { name: 'cobra_entrada', type: 'select', label: 'Cobra Entrada?', required: true },
    ]
  },
  {
    id: 'trilha-ecologica',
    name: 'Autorização para Operação de Trilha Ecológica',
    description: 'Licença para condução de trilhas e caminhadas ecológicas',
    icon: 'Route',
    category: 'Licenciamento',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_operador', type: 'text', label: 'Nome do Operador', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'nome_trilha', type: 'text', label: 'Nome da Trilha', required: true },
      { name: 'localizacao_inicio', type: 'text', label: 'Localização do Início', required: true },
      { name: 'extensao_km', type: 'number', label: 'Extensão (km)', required: true },
      { name: 'nivel_dificuldade', type: 'select', label: 'Nível de Dificuldade', required: true },
      { name: 'tempo_percurso', type: 'text', label: 'Tempo Médio de Percurso', required: true },
      { name: 'capacidade_grupo', type: 'number', label: 'Capacidade do Grupo', required: true },
    ]
  },
  {
    id: 'festa-tradicional',
    name: 'Registro de Festa Tradicional',
    description: 'Cadastro de festas e celebrações tradicionais do município',
    icon: 'PartyPopper',
    category: 'Patrimônio',
    estimatedDays: 25,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_festa', type: 'text', label: 'Nome da Festa', required: true },
      { name: 'organizador', type: 'text', label: 'Organizador', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: false },
      { name: 'periodo_realizacao', type: 'text', label: 'Período de Realização', required: true },
      { name: 'origem_historica', type: 'textarea', label: 'Origem Histórica', required: true },
      { name: 'manifestacoes_culturais', type: 'textarea', label: 'Manifestações Culturais Envolvidas', required: true },
      { name: 'tempo_tradicao', type: 'text', label: 'Tempo de Tradição (anos)', required: true },
    ]
  },
  {
    id: 'produtor-local',
    name: 'Cadastro de Produtor Local',
    description: 'Registro de produtores de alimentos e produtos típicos',
    icon: 'ShoppingBasket',
    category: 'Cadastro Comercial',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_produtor', type: 'text', label: 'Nome do Produtor', required: true },
      { name: 'cpf_cnpj', type: 'text', label: 'CPF/CNPJ', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: false },
      { name: 'produtos_produzidos', type: 'textarea', label: 'Produtos Produzidos', required: true },
      { name: 'tipo_producao', type: 'select', label: 'Tipo de Produção', required: true },
      { name: 'possui_selo_certificacao', type: 'select', label: 'Possui Selo/Certificação?', required: false },
      { name: 'capacidade_producao', type: 'text', label: 'Capacidade de Produção Mensal', required: true },
    ]
  },
  {
    id: 'loja-souvenirs',
    name: 'Cadastro de Loja de Souvenirs',
    description: 'Registro de estabelecimentos de venda de souvenirs e produtos locais',
    icon: 'Store',
    category: 'Cadastro Comercial',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_loja', type: 'text', label: 'Nome da Loja', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: false },
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'produtos_vendidos', type: 'textarea', label: 'Principais Produtos Vendidos', required: true },
      { name: 'produtos_locais_percentual', type: 'text', label: 'Percentual de Produtos Locais', required: true },
    ]
  },
  {
    id: 'wifi-turistico',
    name: 'Solicitação de Ponto Wi-Fi Turístico',
    description: 'Pedido de instalação de ponto de internet gratuita',
    icon: 'Wifi',
    category: 'Infraestrutura',
    estimatedDays: 40,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_solicitante', type: 'text', label: 'Nome do Solicitante', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'local_proposto', type: 'text', label: 'Local Proposto', required: true },
      { name: 'tipo_local', type: 'select', label: 'Tipo de Local', required: true },
      { name: 'fluxo_pessoas_estimado', type: 'text', label: 'Fluxo Estimado de Pessoas', required: true },
      { name: 'justificativa', type: 'textarea', label: 'Justificativa', required: true },
    ]
  },
  {
    id: 'calendario-eventos',
    name: 'Inclusão no Calendário Oficial de Eventos',
    description: 'Cadastro de evento no calendário turístico municipal',
    icon: 'CalendarDays',
    category: 'Eventos',
    estimatedDays: 15,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_evento', type: 'text', label: 'Nome do Evento', required: true },
      { name: 'organizador', type: 'text', label: 'Organizador', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'tipo_evento', type: 'select', label: 'Tipo de Evento', required: true },
      { name: 'data_inicio', type: 'date', label: 'Data de Início', required: true },
      { name: 'data_termino', type: 'date', label: 'Data de Término', required: true },
      { name: 'local', type: 'text', label: 'Local', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição do Evento', required: true },
      { name: 'publico_alvo', type: 'select', label: 'Público-Alvo', required: true },
    ]
  },
  {
    id: 'programa-voluntario',
    name: 'Cadastro de Voluntário em Turismo',
    description: 'Registro de voluntários para apoio a eventos e atividades turísticas',
    icon: 'Heart',
    category: 'Voluntariado',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_completo', type: 'text', label: 'Nome Completo', required: true },
      { name: 'cpf', type: 'cpf', label: 'CPF', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'idiomas', type: 'text', label: 'Idiomas que Fala', required: false },
      { name: 'areas_interesse', type: 'textarea', label: 'Áreas de Interesse', required: true },
      { name: 'disponibilidade', type: 'text', label: 'Disponibilidade (dias/horários)', required: true },
      { name: 'experiencia_turismo', type: 'select', label: 'Possui Experiência em Turismo?', required: false },
    ]
  },
  {
    id: 'pesquisa-satisfacao',
    name: 'Responder Pesquisa de Satisfação Turística',
    description: 'Contribua com a melhoria do turismo no município',
    icon: 'ClipboardList',
    category: 'Pesquisa',
    estimatedDays: 1,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome', type: 'text', label: 'Nome (Opcional)', required: false },
      { name: 'email', type: 'email', label: 'E-mail (Opcional)', required: false },
      { name: 'origem', type: 'text', label: 'Cidade/País de Origem', required: true },
      { name: 'motivo_visita', type: 'select', label: 'Motivo da Visita', required: true },
      { name: 'tempo_permanencia', type: 'select', label: 'Tempo de Permanência', required: true },
      { name: 'atrativos_visitados', type: 'textarea', label: 'Atrativos Visitados', required: true },
      { name: 'avaliacao_geral', type: 'select', label: 'Avaliação Geral', required: true },
      { name: 'sugestoes', type: 'textarea', label: 'Sugestões e Comentários', required: false },
    ]
  },
  {
    id: 'aplicativo-turistico',
    name: 'Inclusão em Aplicativo Turístico',
    description: 'Cadastro de estabelecimento ou atrativo no app turístico oficial',
    icon: 'Smartphone',
    category: 'Divulgação',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_estabelecimento', type: 'text', label: 'Nome do Estabelecimento/Atrativo', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'categoria', type: 'select', label: 'Categoria', required: true },
      { name: 'descricao_breve', type: 'textarea', label: 'Descrição Breve (máx. 200 caracteres)', required: true },
      { name: 'site', type: 'text', label: 'Website', required: false },
      { name: 'redes_sociais', type: 'text', label: 'Redes Sociais', required: false },
    ]
  },
  {
    id: 'reclamacao-servico-turistico',
    name: 'Reclamação sobre Serviço Turístico',
    description: 'Registre reclamações sobre serviços turísticos do município',
    icon: 'AlertTriangle',
    category: 'Ouvidoria',
    estimatedDays: 10,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_reclamante', type: 'text', label: 'Nome do Reclamante', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'estabelecimento_reclamado', type: 'text', label: 'Estabelecimento/Serviço Reclamado', required: true },
      { name: 'tipo_servico', type: 'select', label: 'Tipo de Serviço', required: true },
      { name: 'data_ocorrencia', type: 'date', label: 'Data da Ocorrência', required: true },
      { name: 'descricao_reclamacao', type: 'textarea', label: 'Descrição da Reclamação', required: true },
    ]
  },
  {
    id: 'indicacao-turistica',
    name: 'Indicação de Novo Atrativo Turístico',
    description: 'Sugira novos atrativos para serem divulgados',
    icon: 'Lightbulb',
    category: 'Sugestões',
    estimatedDays: 15,
    requiresDocuments: false,
    suggestedFields: [
      { name: 'nome_indicador', type: 'text', label: 'Seu Nome', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: false },
      { name: 'nome_atrativo', type: 'text', label: 'Nome do Atrativo Sugerido', required: true },
      { name: 'localizacao', type: 'text', label: 'Localização', required: true },
      { name: 'tipo_atrativo', type: 'select', label: 'Tipo de Atrativo', required: true },
      { name: 'descricao', type: 'textarea', label: 'Descrição e Relevância', required: true },
      { name: 'fotos_disponiveis', type: 'select', label: 'Possui Fotos para Compartilhar?', required: false },
    ]
  },
  {
    id: 'parceria-institucional',
    name: 'Proposta de Parceria Institucional',
    description: 'Formalize parcerias para desenvolvimento do turismo',
    icon: 'Handshake',
    category: 'Parcerias',
    estimatedDays: 30,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_instituicao', type: 'text', label: 'Nome da Instituição', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'tipo_instituicao', type: 'select', label: 'Tipo de Instituição', required: true },
      { name: 'area_atuacao', type: 'text', label: 'Área de Atuação', required: true },
      { name: 'proposta_parceria', type: 'textarea', label: 'Proposta de Parceria', required: true },
      { name: 'beneficios_esperados', type: 'textarea', label: 'Benefícios Esperados', required: true },
    ]
  },
  {
    id: 'receptivo-turismo',
    name: 'Cadastro de Empresa de Receptivo',
    description: 'Registro de operadoras de receptivo turístico',
    icon: 'UserCheck',
    category: 'Cadastro Comercial',
    estimatedDays: 20,
    requiresDocuments: true,
    suggestedFields: [
      { name: 'nome_empresa', type: 'text', label: 'Nome da Empresa', required: true },
      { name: 'cnpj', type: 'cnpj', label: 'CNPJ', required: true },
      { name: 'responsavel', type: 'text', label: 'Responsável', required: true },
      { name: 'telefone', type: 'tel', label: 'Telefone', required: true },
      { name: 'email', type: 'email', label: 'E-mail', required: true },
      { name: 'endereco', type: 'text', label: 'Endereço', required: true },
      { name: 'servicos_oferecidos', type: 'textarea', label: 'Serviços Oferecidos', required: true },
      { name: 'idiomas_atendimento', type: 'text', label: 'Idiomas de Atendimento', required: true },
      { name: 'num_cadastur', type: 'text', label: 'Número CADASTUR', required: false },
      { name: 'capacidade_atendimento', type: 'number', label: 'Capacidade de Atendimento Diário', required: true },
    ]
  },
];
