/**
 * Serviço de Templates de Workflows
 * Gera workflows padrão para novos serviços COM_DADOS
 */

import type { CreateWorkflowData } from './module-workflow.service'

export interface GenerateWorkflowFromServiceInput {
  moduleType: string
  serviceName: string
  serviceDescription?: string | null
  estimatedDays?: number | null
  departmentName?: string
}

/**
 * Gera workflow padrão baseado nos dados do serviço
 */
export function generateDefaultWorkflow(
  input: GenerateWorkflowFromServiceInput
): CreateWorkflowData {
  const {
    moduleType,
    serviceName,
    serviceDescription,
    estimatedDays,
    departmentName
  } = input

  // Calcular SLA total (padrão: estimatedDays ou 10 dias)
  const totalSLA = estimatedDays || 10

  // Distribuir SLA entre etapas
  const analysisTime = Math.ceil(totalSLA * 0.4) // 40% do tempo em análise
  const pendingTime = Math.ceil(totalSLA * 0.2) // 20% para pendências
  const approvalTime = Math.ceil(totalSLA * 0.3) // 30% para aprovação

  return {
    moduleType,
    name: serviceName,
    description: serviceDescription || `Workflow automático para ${serviceName}`,
    defaultSLA: totalSLA,
    stages: [
      {
        name: 'Novo',
        order: 1,
        slaDays: 1,
        requiredDocuments: [],
        requiredActions: [],
        canSkip: false
      },
      {
        name: 'Em Análise',
        order: 2,
        slaDays: analysisTime,
        requiredDocuments: [],
        requiredActions: ['analisar_documentacao'],
        canSkip: false
      },
      {
        name: 'Pendente',
        order: 3,
        slaDays: pendingTime,
        requiredDocuments: [],
        requiredActions: [],
        canSkip: true,
        skipCondition: 'Documentação completa'
      },
      {
        name: 'Aprovado',
        order: 4,
        slaDays: approvalTime,
        requiredDocuments: [],
        requiredActions: ['emitir_parecer'],
        canSkip: false
      },
      {
        name: 'Concluído',
        order: 5,
        slaDays: 1,
        requiredDocuments: [],
        requiredActions: [],
        canSkip: false
      }
    ],
    rules: {
      autoGenerated: true,
      generatedAt: new Date().toISOString(),
      source: 'service_creation',
      department: departmentName,
      canBeDeleted: true,
      needsReview: true,
      version: '1.0'
    }
  }
}

/**
 * Valida se workflow gerado está correto
 */
export function validateGeneratedWorkflow(workflow: CreateWorkflowData): boolean {
  // Verificar campos obrigatórios
  if (!workflow.moduleType || !workflow.name || !workflow.stages) {
    return false
  }

  // Verificar se tem pelo menos 3 etapas
  if (workflow.stages.length < 3) {
    return false
  }

  // Verificar se etapas estão ordenadas
  const orders = workflow.stages.map(s => s.order)
  const sortedOrders = [...orders].sort((a, b) => a - b)
  if (JSON.stringify(orders) !== JSON.stringify(sortedOrders)) {
    return false
  }

  // Verificar se não há ordens duplicadas
  const uniqueOrders = new Set(orders)
  if (uniqueOrders.size !== orders.length) {
    return false
  }

  return true
}
