-- Migration: Add moduleType field to all module models
-- This adds the moduleType field to all 95 models that are part of the MODULE_MAPPING

-- SAÚDE (11 modelos)
ALTER TABLE health_attendances ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ATENDIMENTOS_SAUDE';
ALTER TABLE health_appointments ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'AGENDAMENTOS_MEDICOS';
ALTER TABLE medication_dispenses ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CONTROLE_MEDICAMENTOS';
ALTER TABLE health_campaigns ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CAMPANHAS_SAUDE';
ALTER TABLE health_programs ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'PROGRAMAS_SAUDE';
ALTER TABLE health_transports ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ENCAMINHAMENTOS_TFD';
ALTER TABLE health_exams ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'EXAMES';
ALTER TABLE health_transport_requests ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'TRANSPORTE_PACIENTES';
ALTER TABLE vaccinations ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'VACINACAO';
ALTER TABLE patients ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_PACIENTE';
ALTER TABLE community_health_agents ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'GESTAO_ACS';

-- EDUCAÇÃO (10 modelos - um já tem)
ALTER TABLE education_attendances ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ATENDIMENTOS_EDUCACAO';
ALTER TABLE students ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'MATRICULA_ALUNO';
ALTER TABLE student_transports ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'TRANSPORTE_ESCOLAR';
ALTER TABLE disciplinary_records ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'REGISTRO_OCORRENCIA_ESCOLAR';
ALTER TABLE school_documents ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'SOLICITACAO_DOCUMENTO_ESCOLAR';
ALTER TABLE student_transfers ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'TRANSFERENCIA_ESCOLAR';
ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CONSULTA_FREQUENCIA';
ALTER TABLE grade_records ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CONSULTA_NOTAS';
ALTER TABLE school_managements ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'GESTAO_ESCOLAR';
ALTER TABLE school_meals ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'GESTAO_MERENDA';

-- ASSISTÊNCIA SOCIAL (9 modelos)
ALTER TABLE social_assistance_attendances ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ATENDIMENTOS_ASSISTENCIA_SOCIAL';
ALTER TABLE vulnerable_families ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_UNICO';
ALTER TABLE benefit_requests ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'SOLICITACAO_BENEFICIO';
ALTER TABLE emergency_deliveries ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ENTREGA_EMERGENCIAL';
ALTER TABLE social_group_enrollments ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'INSCRICAO_GRUPO_OFICINA';
ALTER TABLE home_visits ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'VISITAS_DOMICILIARES';
ALTER TABLE social_program_enrollments ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'INSCRICAO_PROGRAMA_SOCIAL';
ALTER TABLE social_appointments ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'AGENDAMENTO_ATENDIMENTO_SOCIAL';
ALTER TABLE social_equipments ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'GESTAO_CRAS_CREAS';

-- AGRICULTURA (6 modelos)
ALTER TABLE agriculture_attendances ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ATENDIMENTOS_AGRICULTURA';
ALTER TABLE rural_producers ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_PRODUTOR';
ALTER TABLE technical_assistances ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ASSISTENCIA_TECNICA';
ALTER TABLE rural_trainings ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'INSCRICAO_CURSO_RURAL';
ALTER TABLE rural_programs ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'INSCRICAO_PROGRAMA_RURAL';
ALTER TABLE rural_properties ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_PROPRIEDADE_RURAL';

-- CULTURA (8 modelos)
ALTER TABLE cultural_attendances ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ATENDIMENTOS_CULTURA';
ALTER TABLE cultural_space_reservations ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'RESERVA_ESPACO_CULTURAL';
ALTER TABLE cultural_workshop_enrollments ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'INSCRICAO_OFICINA_CULTURAL';
ALTER TABLE artistic_groups ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_GRUPO_ARTISTICO';
ALTER TABLE cultural_projects ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'PROJETO_CULTURAL';
ALTER TABLE cultural_project_submissions ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'SUBMISSAO_PROJETO_CULTURAL';
ALTER TABLE cultural_events ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_EVENTO_CULTURAL';
ALTER TABLE cultural_manifestations ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'REGISTRO_MANIFESTACAO_CULTURAL';

-- ESPORTES (9 modelos)
ALTER TABLE sports_attendances ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ATENDIMENTOS_ESPORTES';
ALTER TABLE sports_school_enrollments ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'INSCRICAO_ESCOLINHA';
ALTER TABLE athletes ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_ATLETA';
ALTER TABLE sports_infrastructure_reservations ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'RESERVA_ESPACO_ESPORTIVO';
ALTER TABLE competition_enrollments ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'INSCRICAO_COMPETICAO';
ALTER TABLE sports_teams ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_EQUIPE_ESPORTIVA';
ALTER TABLE tournament_enrollments ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'INSCRICAO_TORNEIO';
ALTER TABLE sports_modalities ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_MODALIDADE';
ALTER TABLE competitions ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'INSCRICAO_COMPETICAO';

-- HABITAÇÃO (6 modelos)
ALTER TABLE housing_attendances ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ATENDIMENTOS_HABITACAO';
ALTER TABLE housing_applications ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'INSCRICAO_PROGRAMA_HABITACIONAL';
ALTER TABLE land_regularizations ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'REGULARIZACAO_FUNDIARIA';
ALTER TABLE rent_assistances ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'SOLICITACAO_AUXILIO_ALUGUEL';
ALTER TABLE housing_units ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_UNIDADE_HABITACIONAL';
ALTER TABLE housing_registrations ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'INSCRICAO_FILA_HABITACAO';

-- MEIO AMBIENTE (7 modelos)
ALTER TABLE environmental_attendances ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ATENDIMENTOS_MEIO_AMBIENTE';
ALTER TABLE environmental_licenses ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'LICENCA_AMBIENTAL';
ALTER TABLE environmental_complaints ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'DENUNCIA_AMBIENTAL';
ALTER TABLE environmental_programs ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'PROGRAMA_AMBIENTAL';
ALTER TABLE tree_cutting_authorizations ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'AUTORIZACAO_PODA_CORTE';
ALTER TABLE environmental_inspections ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'VISTORIA_AMBIENTAL';
ALTER TABLE protected_areas ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'GESTAO_AREAS_PROTEGIDAS';

-- OBRAS PÚBLICAS (5 modelos)
ALTER TABLE public_works_attendances ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ATENDIMENTOS_OBRAS';
ALTER TABLE road_repair_requests ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'SOLICITACAO_REPARO_VIA';
ALTER TABLE technical_inspections ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'VISTORIA_TECNICA_OBRAS';
ALTER TABLE public_works ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_OBRA_PUBLICA';
ALTER TABLE work_inspections ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'INSPECAO_OBRA';

-- PLANEJAMENTO URBANO (7 modelos)
ALTER TABLE urban_planning_attendances ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ATENDIMENTOS_PLANEJAMENTO';
ALTER TABLE project_approvals ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'APROVACAO_PROJETO';
ALTER TABLE building_permits ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ALVARA_CONSTRUCAO';
ALTER TABLE business_licenses ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ALVARA_FUNCIONAMENTO';
ALTER TABLE certificate_requests ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'SOLICITACAO_CERTIDAO';
ALTER TABLE urban_infractions ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'DENUNCIA_CONSTRUCAO_IRREGULAR';
ALTER TABLE urban_zonings ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_LOTEAMENTO';

-- SEGURANÇA PÚBLICA (10 modelos)
ALTER TABLE security_attendances ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ATENDIMENTOS_SEGURANCA';
ALTER TABLE security_occurrences ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'REGISTRO_OCORRENCIA';
ALTER TABLE patrol_requests ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'SOLICITACAO_RONDA';
ALTER TABLE security_camera_requests ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'SOLICITACAO_CAMERA_SEGURANCA';
ALTER TABLE anonymous_tips ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'DENUNCIA_ANONIMA';
ALTER TABLE critical_points ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_PONTO_CRITICO';
ALTER TABLE security_alerts ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ALERTA_SEGURANCA';
ALTER TABLE security_patrols ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'REGISTRO_PATRULHA';
ALTER TABLE municipal_guards ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'GESTAO_GUARDA_MUNICIPAL';
ALTER TABLE surveillance_systems ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'GESTAO_VIGILANCIA';

-- SERVIÇOS PÚBLICOS (8 modelos)
ALTER TABLE public_service_attendances ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ATENDIMENTOS_SERVICOS_PUBLICOS';
ALTER TABLE street_lightings ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ILUMINACAO_PUBLICA';
ALTER TABLE urban_cleanings ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'LIMPEZA_URBANA';
ALTER TABLE special_collections ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'COLETA_ESPECIAL';
ALTER TABLE weeding_requests ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'SOLICITACAO_CAPINA';
ALTER TABLE drainage_requests ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'SOLICITACAO_DESOBSTRUCAO';
ALTER TABLE tree_pruning_requests ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'SOLICITACAO_PODA';
ALTER TABLE service_teams ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'GESTAO_EQUIPES_SERVICOS';

-- TURISMO (7 modelos)
ALTER TABLE tourism_attendances ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'ATENDIMENTOS_TURISMO';
ALTER TABLE local_businesses ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_ESTABELECIMENTO_TURISTICO';
ALTER TABLE tourism_guides ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_GUIA_TURISTICO';
ALTER TABLE tourism_programs ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'INSCRICAO_PROGRAMA_TURISTICO';
ALTER TABLE tourist_attractions ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'REGISTRO_ATRATIVO_TURISTICO';
ALTER TABLE tourism_routes ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_ROTEIRO_TURISTICO';
ALTER TABLE tourism_events ADD COLUMN IF NOT EXISTS "moduleType" TEXT DEFAULT 'CADASTRO_EVENTO_TURISTICO';

-- Criar índices para melhorar performance das queries por moduleType
CREATE INDEX IF NOT EXISTS idx_health_attendances_moduletype ON health_attendances("tenantId", "moduleType");
CREATE INDEX IF NOT EXISTS idx_education_attendances_moduletype ON education_attendances("tenantId", "moduleType");
CREATE INDEX IF NOT EXISTS idx_social_attendances_moduletype ON social_assistance_attendances("tenantId", "moduleType");
CREATE INDEX IF NOT EXISTS idx_agriculture_attendances_moduletype ON agriculture_attendances("tenantId", "moduleType");
CREATE INDEX IF NOT EXISTS idx_cultural_attendances_moduletype ON cultural_attendances("tenantId", "moduleType");
CREATE INDEX IF NOT EXISTS idx_sports_attendances_moduletype ON sports_attendances("tenantId", "moduleType");
CREATE INDEX IF NOT EXISTS idx_housing_attendances_moduletype ON housing_attendances("tenantId", "moduleType");
CREATE INDEX IF NOT EXISTS idx_environmental_attendances_moduletype ON environmental_attendances("tenantId", "moduleType");
CREATE INDEX IF NOT EXISTS idx_public_works_attendances_moduletype ON public_works_attendances("tenantId", "moduleType");
CREATE INDEX IF NOT EXISTS idx_urban_planning_attendances_moduletype ON urban_planning_attendances("tenantId", "moduleType");
CREATE INDEX IF NOT EXISTS idx_security_attendances_moduletype ON security_attendances("tenantId", "moduleType");
CREATE INDEX IF NOT EXISTS idx_public_service_attendances_moduletype ON public_service_attendances("tenantId", "moduleType");
CREATE INDEX IF NOT EXISTS idx_tourism_attendances_moduletype ON tourism_attendances("tenantId", "moduleType");
