-- ============================================================================
-- FASE 3 MULTI-TENANT - ROW LEVEL SECURITY (segunda camada / defesa em profundidade)
-- ============================================================================
-- Cobre o residuo que a Prisma extension nao ve: $queryRaw, jobs sem contexto,
-- ferramentas externas. Politica PERMISSIVA por design:
--   - GUC app.tenant_id vazio  -> passa tudo (migrations/seeds/admin do banco)
--   - setado                   -> so tenant atual, NULLs de plataforma, ou '__platform__'
-- Sem FORCE: owner (migrations) enxerga tudo. Em runtime a app seta o GUC por
-- transacao. Idempotente (DROP POLICY IF EXISTS).

CREATE OR REPLACE FUNCTION current_tenant_id() RETURNS TEXT AS $BODY$
  SELECT NULLIF(current_setting('app.tenant_id', true), '');
$BODY$ LANGUAGE sql STABLE;

DO $OUTER$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'users',
    'user_departments',
    'departments',
    'citizens',
    'citizen_documents',
    'protocol_citizen_links',
    'services_simplified',
    'protocols_simplified',
    'protocol_history_simplified',
    'protocol_evaluations_simplified',
    'admin_tickets',
    'protocol_interactions',
    'protocol_documents',
    'protocol_pendings',
    'protocol_data_fields',
    'protocol_stages',
    'protocol_sla',
    'notifications',
    'notification_logs',
    'citizen_transfer_requests',
    'department_metrics',
    'server_performance',
    'emails',
    'email_auth_attempts',
    'email_drafts',
    'audit_logs',
    'specialized_pages',
    'agenda_events',
    'central_calendars',
    'central_calendar_events',
    'unidades_saude',
    'unidades_educacao',
    'unidades_cras',
    'programas_sociais',
    'professores',
    'agendas_medicas',
    'consultas_agendadas',
    'atendimentos_medicos',
    'consultas_medicas',
    'problemas_condicoes',
    'alergias_reacoes',
    'atendimentos_odontologicos',
    'acompanhamento_pre_natal',
    'consultas_pre_natal',
    'exames_pre_natal',
    'visitas_domiciliares',
    'prescricoes',
    'exames_solicitados',
    'atestados',
    'encaminhamentos',
    'medicamentos',
    'estoque_medicamentos',
    'dispensacao_medicamentos',
    'solicitacoes_tfd',
    'viagens_tfd',
    'veiculos_tfd',
    'motoristas_tfd',
    'inscricoes_matricula',
    'matriculas',
    'turmas',
    'veiculos_escolares',
    'rotas_escolares',
    'cadunico_familias',
    'membros_familia',
    'inscricoes_programas_sociais',
    'acompanhamentos_beneficio',
    'pagamentos_beneficio',
    'conversations',
    'messages',
    'official_channels',
    'channel_subscriptions',
    'channel_deliveries',
    'message_logs',
    'document_templates',
    'generated_documents',
    'citizen_categories',
    'citizen_category_assignments',
    'citizen_category_protocol_history',
    'citizen_category_audit_log',
    'citizen_category_badges',
    'digital_certificates',
    'certificate_requests',
    'bot_conversations',
    'bot_messages',
    'proactive_notifications',
    'bot_uploads',
    'flow_executions',
    'external_documents',
    'chamada_painel',
    'alergias_cidadao',
    'comorbidades_cidadao',
    'anexo_prontuario',
    'imunizacao_cidadao',
    'lote_medicamento',
    'transferencia_estoque',
    'alerta_estoque',
    'documento_tfd',
    'parecer_regulacao_tfd',
    'aprovacao_gestao_tfd',
    'agendamento_externo_tfd',
    'passageiro_viagem_tfd',
    'prestacao_contas_tfd',
    'salas_consultorios',
    'turnos_trabalho',
    'configuracoes_atendimento',
    'equipes_saude',
    'microareas',
    'fila_atendimento',
    'escutas_iniciais',
    'triagens_enfermagem',
    'atividades_coletivas',
    'participantes_atividades',
    'configuracoes_agenda',
    'organizational_units',
    'positions',
    'functions',
    'employee_assignments',
    'teams',
    'face_recognition_identities'
  ] LOOP
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = t AND table_schema='public') THEN
      EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
      EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', t);
      EXECUTE format($f$CREATE POLICY tenant_isolation ON %I USING (current_tenant_id() IS NULL OR current_tenant_id() = '__platform__' OR "tenantId" IS NULL OR "tenantId" = current_tenant_id()) WITH CHECK (current_tenant_id() IS NULL OR current_tenant_id() = '__platform__' OR "tenantId" IS NULL OR "tenantId" = current_tenant_id())$f$, t);
    END IF;
  END LOOP;
END $OUTER$;
