/**
 * ============================================================================
 * MÓDULOS DE EDUCAÇÃO - CONFIGURAÇÃO COMPLETA (11 MÓDULOS)
 * ============================================================================
 */

import { ModuleConfig } from './types';

// ============================================================================
// 1. EDUCATION ATTENDANCE - Atendimentos Educacionais
// ============================================================================

export const educationAttendanceConfig: ModuleConfig = {
  key: 'education-attendance',
  departmentType: 'education',
  entityName: 'EducationAttendance',
  displayName: 'Atendimentos Educacionais',
  displayNameSingular: 'Atendimento Educacional',
  description: 'Atendimentos e solicitações na área de educação',
  icon: 'FileText',
  color: 'blue',

  fields: [
    {
      name: 'citizenName',
      label: 'Nome do Solicitante',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'citizenCpf',
      label: 'CPF',
      type: 'text',
      required: true,
      placeholder: '000.000.000-00',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'citizenPhone',
      label: 'Telefone',
      type: 'phone',
      placeholder: '(00) 00000-0000',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'citizenEmail',
      label: 'E-mail',
      type: 'email',
      placeholder: 'email@exemplo.com',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'serviceType',
      label: 'Tipo de Serviço',
      type: 'select',
      required: true,
      options: [
        { value: 'MATRICULA', label: 'Matrícula' },
        { value: 'TRANSFERENCIA', label: 'Transferência' },
        { value: 'DOCUMENTO', label: 'Documento Escolar' },
        { value: 'TRANSPORTE', label: 'Transporte Escolar' },
        { value: 'MERENDA', label: 'Merenda Escolar' },
        { value: 'OUTROS', label: 'Outros' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'COMPLETED', label: 'Concluído' },
        { value: 'CANCELLED', label: 'Cancelado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'priority',
      label: 'Prioridade',
      type: 'select',
      options: [
        { value: 'LOW', label: 'Baixa' },
        { value: 'NORMAL', label: 'Normal' },
        { value: 'HIGH', label: 'Alta' },
        { value: 'URGENT', label: 'Urgente' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'scheduledDate',
      label: 'Data Agendada',
      type: 'date',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'observations',
      label: 'Observações',
      type: 'textarea',
      showInForm: true,
      showInDetails: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Atendimentos',
      icon: 'FileText',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'pending',
      label: 'Pendentes',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'inProgress',
      label: 'Em Andamento',
      icon: 'Activity',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'completed',
      label: 'Concluídos',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PENDING', label: 'Pendente' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'COMPLETED', label: 'Concluído' },
        { value: 'CANCELLED', label: 'Cancelado' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'priority',
      label: 'Prioridade',
      type: 'select',
      options: [
        { value: 'all', label: 'Todas' },
        { value: 'URGENT', label: 'Urgente' },
        { value: 'HIGH', label: 'Alta' },
        { value: 'NORMAL', label: 'Normal' },
        { value: 'LOW', label: 'Baixa' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'serviceType',
      label: 'Tipo de Serviço',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'MATRICULA', label: 'Matrícula' },
        { value: 'TRANSFERENCIA', label: 'Transferência' },
        { value: 'DOCUMENTO', label: 'Documento Escolar' },
        { value: 'TRANSPORTE', label: 'Transporte Escolar' },
        { value: 'MERENDA', label: 'Merenda Escolar' },
      ],
      defaultValue: 'all',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/educacao/education-attendances',
};

// ============================================================================
// 2. STUDENT - Matrícula de Alunos
// ============================================================================

export const studentConfig: ModuleConfig = {
  key: 'students',
  departmentType: 'education',
  entityName: 'Student',
  displayName: 'Matrículas de Alunos',
  displayNameSingular: 'Aluno',
  description: 'Cadastro e gestão de matrículas de alunos',
  icon: 'GraduationCap',
  color: 'green',

  fields: [
    {
      name: 'name',
      label: 'Nome Completo',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'birthDate',
      label: 'Data de Nascimento',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'cpf',
      label: 'CPF',
      type: 'text',
      placeholder: '000.000.000-00',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'rg',
      label: 'RG',
      type: 'text',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'parentName',
      label: 'Nome do Responsável',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'parentPhone',
      label: 'Telefone do Responsável',
      type: 'phone',
      required: true,
      placeholder: '(00) 00000-0000',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'parentEmail',
      label: 'E-mail do Responsável',
      type: 'email',
      placeholder: 'email@exemplo.com',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'address',
      label: 'Endereço',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'schoolId',
      label: 'Escola',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
      options: [], // Será preenchido dinamicamente
    },
    {
      name: 'medicalInfo',
      label: 'Informações Médicas',
      type: 'textarea',
      placeholder: 'Alergias, medicamentos, condições especiais...',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'isActive',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'true', label: 'Ativo' },
        { value: 'false', label: 'Inativo' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Alunos',
      icon: 'Users',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'active',
      label: 'Alunos Ativos',
      icon: 'UserCheck',
      color: 'green',
      format: 'number',
    },
    {
      key: 'inactive',
      label: 'Inativos',
      icon: 'UserX',
      color: 'red',
      format: 'number',
    },
    {
      key: 'thisMonth',
      label: 'Matrículas este Mês',
      icon: 'TrendingUp',
      color: 'amber',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'isActive',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'true', label: 'Ativos' },
        { value: 'false', label: 'Inativos' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'schoolId',
      label: 'Escola',
      type: 'select',
      options: [
        { value: 'all', label: 'Todas' },
      ],
      defaultValue: 'all',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/educacao/students',
};

// ============================================================================
// 3. SCHOOL TRANSPORT - Transporte Escolar
// ============================================================================

export const schoolTransportConfig: ModuleConfig = {
  key: 'school-transports',
  departmentType: 'education',
  entityName: 'SchoolTransport',
  displayName: 'Transporte Escolar',
  displayNameSingular: 'Rota de Transporte',
  description: 'Gestão de rotas e transporte escolar',
  icon: 'Bus',
  color: 'yellow',

  fields: [
    {
      name: 'route',
      label: 'Rota',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'driver',
      label: 'Motorista',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'vehicle',
      label: 'Veículo',
      type: 'text',
      required: true,
      placeholder: 'Placa ou identificação',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'capacity',
      label: 'Capacidade',
      type: 'number',
      required: true,
      placeholder: 'Número de passageiros',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'shift',
      label: 'Turno',
      type: 'select',
      required: true,
      options: [
        { value: 'MATUTINO', label: 'Matutino' },
        { value: 'VESPERTINO', label: 'Vespertino' },
        { value: 'NOTURNO', label: 'Noturno' },
        { value: 'INTEGRAL', label: 'Integral' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'stops',
      label: 'Paradas',
      type: 'textarea',
      placeholder: 'Lista de paradas da rota',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'isActive',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'true', label: 'Ativa' },
        { value: 'false', label: 'Inativa' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Rotas',
      icon: 'Bus',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'active',
      label: 'Rotas Ativas',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'morning',
      label: 'Turno Matutino',
      icon: 'Sun',
      color: 'amber',
      format: 'number',
    },
    {
      key: 'afternoon',
      label: 'Turno Vespertino',
      icon: 'Sunset',
      color: 'orange',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'isActive',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todas' },
        { value: 'true', label: 'Ativas' },
        { value: 'false', label: 'Inativas' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'shift',
      label: 'Turno',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'MATUTINO', label: 'Matutino' },
        { value: 'VESPERTINO', label: 'Vespertino' },
        { value: 'NOTURNO', label: 'Noturno' },
      ],
      defaultValue: 'all',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/educacao/school-transports',
};

// ============================================================================
// 4. DISCIPLINARY RECORD - Ocorrências Disciplinares
// ============================================================================

export const disciplinaryRecordConfig: ModuleConfig = {
  key: 'disciplinary-records',
  departmentType: 'education',
  entityName: 'DisciplinaryRecord',
  displayName: 'Ocorrências Disciplinares',
  displayNameSingular: 'Ocorrência Disciplinar',
  description: 'Registro de ocorrências e questões disciplinares',
  icon: 'AlertTriangle',
  color: 'red',

  fields: [
    {
      name: 'studentId',
      label: 'Aluno',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
      options: [], // Será preenchido dinamicamente
    },
    {
      name: 'schoolId',
      label: 'Escola',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
      options: [], // Será preenchido dinamicamente
    },
    {
      name: 'incidentType',
      label: 'Tipo de Ocorrência',
      type: 'select',
      required: true,
      options: [
        { value: 'INDISCIPLINA', label: 'Indisciplina' },
        { value: 'BRIGA', label: 'Briga' },
        { value: 'DESRESPEITO', label: 'Desrespeito' },
        { value: 'VANDALISMO', label: 'Vandalismo' },
        { value: 'BULLING', label: 'Bullying' },
        { value: 'OUTROS', label: 'Outros' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'severity',
      label: 'Gravidade',
      type: 'select',
      options: [
        { value: 'LEVE', label: 'Leve' },
        { value: 'MODERADA', label: 'Moderada' },
        { value: 'GRAVE', label: 'Grave' },
        { value: 'GRAVISSIMA', label: 'Gravíssima' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'incidentDate',
      label: 'Data da Ocorrência',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'time',
      label: 'Horário',
      type: 'text',
      placeholder: '00:00',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'location',
      label: 'Local',
      type: 'text',
      placeholder: 'Sala de aula, pátio, etc.',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'witnesses',
      label: 'Testemunhas',
      type: 'textarea',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'measures',
      label: 'Medidas Tomadas',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'responsibleTeacher',
      label: 'Professor Responsável',
      type: 'text',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'parentNotified',
      label: 'Responsável Notificado',
      type: 'select',
      options: [
        { value: 'true', label: 'Sim' },
        { value: 'false', label: 'Não' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'resolved',
      label: 'Resolvido',
      type: 'select',
      options: [
        { value: 'true', label: 'Sim' },
        { value: 'false', label: 'Não' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'RESOLVED', label: 'Resolvido' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'observations',
      label: 'Observações',
      type: 'textarea',
      showInForm: true,
      showInDetails: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Ocorrências',
      icon: 'AlertTriangle',
      color: 'red',
      format: 'number',
    },
    {
      key: 'pending',
      label: 'Pendentes',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'resolved',
      label: 'Resolvidas',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'thisMonth',
      label: 'Este Mês',
      icon: 'Calendar',
      color: 'blue',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'resolved',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todas' },
        { value: 'false', label: 'Pendentes' },
        { value: 'true', label: 'Resolvidas' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'severity',
      label: 'Gravidade',
      type: 'select',
      options: [
        { value: 'all', label: 'Todas' },
        { value: 'LEVE', label: 'Leve' },
        { value: 'MODERADA', label: 'Moderada' },
        { value: 'GRAVE', label: 'Grave' },
        { value: 'GRAVISSIMA', label: 'Gravíssima' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'incidentType',
      label: 'Tipo',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'INDISCIPLINA', label: 'Indisciplina' },
        { value: 'BRIGA', label: 'Briga' },
        { value: 'DESRESPEITO', label: 'Desrespeito' },
        { value: 'BULLING', label: 'Bullying' },
      ],
      defaultValue: 'all',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/educacao/disciplinary-records',
};

// ============================================================================
// 5. SCHOOL DOCUMENT - Documentos Escolares
// ============================================================================

export const schoolDocumentConfig: ModuleConfig = {
  key: 'school-documents',
  departmentType: 'education',
  entityName: 'SchoolDocument',
  displayName: 'Documentos Escolares',
  displayNameSingular: 'Documento Escolar',
  description: 'Emissão e gestão de documentos escolares',
  icon: 'FileText',
  color: 'purple',

  fields: [
    {
      name: 'studentId',
      label: 'Aluno',
      type: 'select',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
      options: [], // Será preenchido dinamicamente
    },
    {
      name: 'studentName',
      label: 'Nome do Aluno',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'documentType',
      label: 'Tipo de Documento',
      type: 'select',
      required: true,
      options: [
        { value: 'HISTORICO', label: 'Histórico Escolar' },
        { value: 'DECLARACAO', label: 'Declaração' },
        { value: 'BOLETIM', label: 'Boletim' },
        { value: 'CERTIFICADO', label: 'Certificado' },
        { value: 'ATESTADO', label: 'Atestado de Matrícula' },
        { value: 'TRANSFERENCIA', label: 'Documento de Transferência' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'issueDate',
      label: 'Data de Emissão',
      type: 'date',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'validUntil',
      label: 'Válido Até',
      type: 'date',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'ISSUED', label: 'Emitido' },
        { value: 'DELIVERED', label: 'Entregue' },
        { value: 'CANCELLED', label: 'Cancelado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'observations',
      label: 'Observações',
      type: 'textarea',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'fileUrl',
      label: 'Arquivo',
      type: 'text',
      placeholder: 'URL do documento',
      showInForm: true,
      showInDetails: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Documentos',
      icon: 'FileText',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'pending',
      label: 'Pendentes',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'issued',
      label: 'Emitidos',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'thisMonth',
      label: 'Este Mês',
      icon: 'Calendar',
      color: 'purple',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PENDING', label: 'Pendente' },
        { value: 'ISSUED', label: 'Emitido' },
        { value: 'DELIVERED', label: 'Entregue' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'documentType',
      label: 'Tipo',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'HISTORICO', label: 'Histórico Escolar' },
        { value: 'DECLARACAO', label: 'Declaração' },
        { value: 'BOLETIM', label: 'Boletim' },
        { value: 'CERTIFICADO', label: 'Certificado' },
      ],
      defaultValue: 'all',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/educacao/school-documents',
};

// ============================================================================
// 6. STUDENT TRANSFER - Transferências de Alunos
// ============================================================================

export const studentTransferConfig: ModuleConfig = {
  key: 'student-transfers',
  departmentType: 'education',
  entityName: 'StudentTransfer',
  displayName: 'Transferências de Alunos',
  displayNameSingular: 'Transferência',
  description: 'Gestão de transferências entre escolas',
  icon: 'ArrowRightLeft',
  color: 'indigo',

  fields: [
    {
      name: 'studentId',
      label: 'Aluno',
      type: 'select',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      options: [], // Será preenchido dinamicamente
    },
    {
      name: 'studentName',
      label: 'Nome do Aluno',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'currentSchool',
      label: 'Escola Atual',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'targetSchool',
      label: 'Escola Destino',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'grade',
      label: 'Série/Ano',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'transferReason',
      label: 'Motivo da Transferência',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'requestDate',
      label: 'Data da Solicitação',
      type: 'date',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'transferDate',
      label: 'Data da Transferência',
      type: 'date',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'APPROVED', label: 'Aprovada' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'COMPLETED', label: 'Concluída' },
        { value: 'CANCELLED', label: 'Cancelada' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'documents',
      label: 'Documentos',
      type: 'textarea',
      placeholder: 'Lista de documentos necessários',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'observations',
      label: 'Observações',
      type: 'textarea',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'approvedBy',
      label: 'Aprovado Por',
      type: 'text',
      showInDetails: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Transferências',
      icon: 'ArrowRightLeft',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'pending',
      label: 'Pendentes',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'completed',
      label: 'Concluídas',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'thisMonth',
      label: 'Este Mês',
      icon: 'Calendar',
      color: 'indigo',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todas' },
        { value: 'PENDING', label: 'Pendente' },
        { value: 'APPROVED', label: 'Aprovada' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'COMPLETED', label: 'Concluída' },
      ],
      defaultValue: 'all',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/educacao/student-transfers',
};

// ============================================================================
// 7. ATTENDANCE RECORD - Registros de Frequência
// ============================================================================

export const attendanceRecordConfig: ModuleConfig = {
  key: 'attendance-records',
  departmentType: 'education',
  entityName: 'AttendanceRecord',
  displayName: 'Registros de Frequência',
  displayNameSingular: 'Registro de Frequência',
  description: 'Controle de frequência mensal de alunos',
  icon: 'Calendar',
  color: 'cyan',

  fields: [
    {
      name: 'studentId',
      label: 'Aluno',
      type: 'select',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
      options: [], // Será preenchido dinamicamente
    },
    {
      name: 'studentName',
      label: 'Nome do Aluno',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'schoolId',
      label: 'Escola',
      type: 'select',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
      options: [], // Será preenchido dinamicamente
    },
    {
      name: 'classId',
      label: 'Turma',
      type: 'select',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      options: [], // Será preenchido dinamicamente
    },
    {
      name: 'month',
      label: 'Mês',
      type: 'number',
      required: true,
      placeholder: '1-12',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'year',
      label: 'Ano',
      type: 'number',
      required: true,
      placeholder: '2024',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'totalDays',
      label: 'Total de Dias',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'presentDays',
      label: 'Dias Presentes',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'absentDays',
      label: 'Dias Ausentes',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'percentage',
      label: 'Percentual de Presença',
      type: 'number',
      required: true,
      placeholder: '0-100',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'ACTIVE', label: 'Ativo' },
        { value: 'INACTIVE', label: 'Inativo' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'observations',
      label: 'Observações',
      type: 'textarea',
      showInForm: true,
      showInDetails: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Registros',
      icon: 'Calendar',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'highAttendance',
      label: 'Frequência Alta (>90%)',
      icon: 'TrendingUp',
      color: 'green',
      format: 'number',
    },
    {
      key: 'lowAttendance',
      label: 'Frequência Baixa (<75%)',
      icon: 'TrendingDown',
      color: 'red',
      format: 'number',
    },
    {
      key: 'thisMonth',
      label: 'Este Mês',
      icon: 'Clock',
      color: 'cyan',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'month',
      label: 'Mês',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: '1', label: 'Janeiro' },
        { value: '2', label: 'Fevereiro' },
        { value: '3', label: 'Março' },
        { value: '4', label: 'Abril' },
        { value: '5', label: 'Maio' },
        { value: '6', label: 'Junho' },
        { value: '7', label: 'Julho' },
        { value: '8', label: 'Agosto' },
        { value: '9', label: 'Setembro' },
        { value: '10', label: 'Outubro' },
        { value: '11', label: 'Novembro' },
        { value: '12', label: 'Dezembro' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'ACTIVE', label: 'Ativo' },
        { value: 'INACTIVE', label: 'Inativo' },
      ],
      defaultValue: 'all',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/educacao/attendance-records',
};

// ============================================================================
// 8. GRADE RECORD - Registros de Notas
// ============================================================================

export const gradeRecordConfig: ModuleConfig = {
  key: 'grade-records',
  departmentType: 'education',
  entityName: 'GradeRecord',
  displayName: 'Registros de Notas',
  displayNameSingular: 'Registro de Nota',
  description: 'Controle de notas e desempenho acadêmico',
  icon: 'BarChart',
  color: 'emerald',

  fields: [
    {
      name: 'studentId',
      label: 'Aluno',
      type: 'select',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
      options: [], // Será preenchido dinamicamente
    },
    {
      name: 'studentName',
      label: 'Nome do Aluno',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'schoolId',
      label: 'Escola',
      type: 'select',
      showInForm: true,
      showInDetails: true,
      options: [], // Será preenchido dinamicamente
    },
    {
      name: 'classId',
      label: 'Turma',
      type: 'select',
      showInForm: true,
      showInDetails: true,
      options: [], // Será preenchido dinamicamente
    },
    {
      name: 'subject',
      label: 'Disciplina',
      type: 'select',
      required: true,
      options: [
        { value: 'PORTUGUES', label: 'Português' },
        { value: 'MATEMATICA', label: 'Matemática' },
        { value: 'CIENCIAS', label: 'Ciências' },
        { value: 'HISTORIA', label: 'História' },
        { value: 'GEOGRAFIA', label: 'Geografia' },
        { value: 'INGLES', label: 'Inglês' },
        { value: 'EDUCACAO_FISICA', label: 'Educação Física' },
        { value: 'ARTES', label: 'Artes' },
        { value: 'FILOSOFIA', label: 'Filosofia' },
        { value: 'SOCIOLOGIA', label: 'Sociologia' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'period',
      label: 'Período',
      type: 'select',
      required: true,
      options: [
        { value: 'BIMESTRE_1', label: '1º Bimestre' },
        { value: 'BIMESTRE_2', label: '2º Bimestre' },
        { value: 'BIMESTRE_3', label: '3º Bimestre' },
        { value: 'BIMESTRE_4', label: '4º Bimestre' },
        { value: 'FINAL', label: 'Final' },
        { value: 'RECUPERACAO', label: 'Recuperação' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'grade',
      label: 'Nota',
      type: 'number',
      required: true,
      placeholder: '0.0',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'maxGrade',
      label: 'Nota Máxima',
      type: 'number',
      placeholder: '10.0',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'APPROVED', label: 'Aprovado' },
        { value: 'FAILED', label: 'Reprovado' },
        { value: 'RECOVERY', label: 'Recuperação' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'teacherName',
      label: 'Professor',
      type: 'text',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'observations',
      label: 'Observações',
      type: 'textarea',
      showInForm: true,
      showInDetails: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Notas',
      icon: 'BarChart',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'approved',
      label: 'Aprovados',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'failed',
      label: 'Reprovados',
      icon: 'XCircle',
      color: 'red',
      format: 'number',
    },
    {
      key: 'average',
      label: 'Média Geral',
      icon: 'TrendingUp',
      color: 'emerald',
      format: 'decimal',
    },
  ],

  filters: [
    {
      key: 'subject',
      label: 'Disciplina',
      type: 'select',
      options: [
        { value: 'all', label: 'Todas' },
        { value: 'PORTUGUES', label: 'Português' },
        { value: 'MATEMATICA', label: 'Matemática' },
        { value: 'CIENCIAS', label: 'Ciências' },
        { value: 'HISTORIA', label: 'História' },
        { value: 'GEOGRAFIA', label: 'Geografia' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'APPROVED', label: 'Aprovado' },
        { value: 'FAILED', label: 'Reprovado' },
        { value: 'RECOVERY', label: 'Recuperação' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'period',
      label: 'Período',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'BIMESTRE_1', label: '1º Bimestre' },
        { value: 'BIMESTRE_2', label: '2º Bimestre' },
        { value: 'BIMESTRE_3', label: '3º Bimestre' },
        { value: 'BIMESTRE_4', label: '4º Bimestre' },
      ],
      defaultValue: 'all',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/educacao/grade-records',
};

// ============================================================================
// 9. SCHOOL MANAGEMENT - Gestão Escolar
// ============================================================================

export const schoolManagementConfig: ModuleConfig = {
  key: 'school-management',
  departmentType: 'education',
  entityName: 'SchoolManagement',
  displayName: 'Gestão Escolar',
  displayNameSingular: 'Solicitação de Gestão',
  description: 'Gestão administrativa e operacional das escolas',
  icon: 'Building',
  color: 'slate',

  fields: [
    {
      name: 'schoolId',
      label: 'Escola',
      type: 'select',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
      options: [], // Será preenchido dinamicamente
    },
    {
      name: 'schoolName',
      label: 'Nome da Escola',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'managementType',
      label: 'Tipo de Gestão',
      type: 'select',
      required: true,
      options: [
        { value: 'MANUTENCAO', label: 'Manutenção' },
        { value: 'INFRAESTRUTURA', label: 'Infraestrutura' },
        { value: 'MATERIAL', label: 'Material Escolar' },
        { value: 'PESSOAL', label: 'Gestão de Pessoal' },
        { value: 'PEDAGOGICO', label: 'Pedagógico' },
        { value: 'FINANCEIRO', label: 'Financeiro' },
        { value: 'OUTROS', label: 'Outros' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'requestDate',
      label: 'Data da Solicitação',
      type: 'date',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'COMPLETED', label: 'Concluído' },
        { value: 'CANCELLED', label: 'Cancelado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'priority',
      label: 'Prioridade',
      type: 'select',
      options: [
        { value: 'LOW', label: 'Baixa' },
        { value: 'NORMAL', label: 'Normal' },
        { value: 'HIGH', label: 'Alta' },
        { value: 'URGENT', label: 'Urgente' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'assignedTo',
      label: 'Responsável',
      type: 'text',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'completedDate',
      label: 'Data de Conclusão',
      type: 'date',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'observations',
      label: 'Observações',
      type: 'textarea',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'documents',
      label: 'Documentos',
      type: 'textarea',
      placeholder: 'Lista de documentos relacionados',
      showInForm: true,
      showInDetails: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Solicitações',
      icon: 'Building',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'pending',
      label: 'Pendentes',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'inProgress',
      label: 'Em Andamento',
      icon: 'Activity',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'completed',
      label: 'Concluídas',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PENDING', label: 'Pendente' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'COMPLETED', label: 'Concluído' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'managementType',
      label: 'Tipo',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'MANUTENCAO', label: 'Manutenção' },
        { value: 'INFRAESTRUTURA', label: 'Infraestrutura' },
        { value: 'MATERIAL', label: 'Material Escolar' },
        { value: 'PEDAGOGICO', label: 'Pedagógico' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'priority',
      label: 'Prioridade',
      type: 'select',
      options: [
        { value: 'all', label: 'Todas' },
        { value: 'URGENT', label: 'Urgente' },
        { value: 'HIGH', label: 'Alta' },
        { value: 'NORMAL', label: 'Normal' },
        { value: 'LOW', label: 'Baixa' },
      ],
      defaultValue: 'all',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/educacao/school-management',
};

// ============================================================================
// 10. SCHOOL MEAL - Merenda Escolar
// ============================================================================

export const schoolMealConfig: ModuleConfig = {
  key: 'school-meals',
  departmentType: 'education',
  entityName: 'SchoolMeal',
  displayName: 'Merenda Escolar',
  displayNameSingular: 'Cardápio de Merenda',
  description: 'Gestão de cardápios e merenda escolar',
  icon: 'Utensils',
  color: 'orange',

  fields: [
    {
      name: 'schoolId',
      label: 'Escola',
      type: 'select',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
      options: [], // Será preenchido dinamicamente
    },
    {
      name: 'date',
      label: 'Data',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'shift',
      label: 'Turno',
      type: 'select',
      required: true,
      options: [
        { value: 'MATUTINO', label: 'Matutino' },
        { value: 'VESPERTINO', label: 'Vespertino' },
        { value: 'NOTURNO', label: 'Noturno' },
        { value: 'INTEGRAL', label: 'Integral' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'menu',
      label: 'Cardápio',
      type: 'textarea',
      required: true,
      placeholder: 'Descrição do cardápio do dia',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'studentsServed',
      label: 'Alunos Atendidos',
      type: 'number',
      placeholder: 'Quantidade de alunos',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'cost',
      label: 'Custo (R$)',
      type: 'number',
      placeholder: '0.00',
      showInForm: true,
      showInDetails: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Cardápios',
      icon: 'Utensils',
      color: 'orange',
      format: 'number',
    },
    {
      key: 'thisWeek',
      label: 'Esta Semana',
      icon: 'Calendar',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'studentsServed',
      label: 'Alunos Atendidos',
      icon: 'Users',
      color: 'green',
      format: 'number',
    },
    {
      key: 'totalCost',
      label: 'Custo Total',
      icon: 'DollarSign',
      color: 'amber',
      format: 'currency',
    },
  ],

  filters: [
    {
      key: 'shift',
      label: 'Turno',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'MATUTINO', label: 'Matutino' },
        { value: 'VESPERTINO', label: 'Vespertino' },
        { value: 'NOTURNO', label: 'Noturno' },
        { value: 'INTEGRAL', label: 'Integral' },
      ],
      defaultValue: 'all',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/educacao/school-meals',
};

// ============================================================================
// EXPORTAÇÃO DE TODAS AS CONFIGURAÇÕES
// ============================================================================

export const educacaoModuleConfigs = {
  educationAttendance: educationAttendanceConfig,
  students: studentConfig,
  schoolTransports: schoolTransportConfig,
  disciplinaryRecords: disciplinaryRecordConfig,
  schoolDocuments: schoolDocumentConfig,
  studentTransfers: studentTransferConfig,
  attendanceRecords: attendanceRecordConfig,
  gradeRecords: gradeRecordConfig,
  schoolManagement: schoolManagementConfig,
  schoolMeals: schoolMealConfig,
};

export default educacaoModuleConfigs;
