/**
 * ============================================================================
 * MÓDULOS DE HABITAÇÃO - CONFIGURAÇÃO
 * ============================================================================
 */

import { ModuleConfig } from './types';

export const programasHabitacionaisConfig: ModuleConfig = {
  key: 'programas-habitacionais',
  departmentType: 'housing',
  entityName: 'HousingApplication',
  displayName: 'Programas Habitacionais',
  displayNameSingular: 'Inscrição em Programa',
  description: 'Inscrições em programas habitacionais (MCMV, Casa Verde e Amarela, etc)',
  icon: 'Home',
  color: 'blue',

  fields: [
    {
      name: 'applicantName',
      label: 'Nome do Requerente',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'applicantCpf',
      label: 'CPF',
      type: 'text',
      required: true,
      placeholder: '000.000.000-00',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'protocol',
      label: 'Protocolo',
      type: 'text',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'programType',
      label: 'Tipo de Programa',
      type: 'select',
      options: [
        { value: 'MCMV', label: 'Minha Casa Minha Vida' },
        { value: 'CASA_VERDE_AMARELA', label: 'Casa Verde e Amarela' },
        { value: 'REGULARIZACAO', label: 'Regularização Fundiária' },
        { value: 'AUXILIO_ALUGUEL', label: 'Auxílio Aluguel' },
        { value: 'OUTROS', label: 'Outros' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'address',
      label: 'Endereço Atual',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'familyIncome',
      label: 'Renda Familiar (R$)',
      type: 'currency',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'familySize',
      label: 'Membros da Família',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'housingType',
      label: 'Tipo de Moradia Desejada',
      type: 'select',
      options: [
        { value: 'CASA', label: 'Casa' },
        { value: 'APARTAMENTO', label: 'Apartamento' },
        { value: 'SOBRADO', label: 'Sobrado' },
      ],
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'hasProperty',
      label: 'Possui Imóvel',
      type: 'checkbox',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'isFirstHome',
      label: 'Primeira Moradia',
      type: 'checkbox',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'priorityScore',
      label: 'Pontuação de Prioridade',
      type: 'number',
      showInList: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'UNDER_ANALYSIS', label: 'Em Análise' },
        { value: 'APPROVED', label: 'Aprovado' },
        { value: 'REJECTED', label: 'Rejeitado' },
        { value: 'PENDING_DOCS', label: 'Documentação Pendente' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'applicationDate',
      label: 'Data de Inscrição',
      type: 'date',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Inscrições',
      icon: 'FileText',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'underAnalysis',
      label: 'Em Análise',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'approved',
      label: 'Aprovadas',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'rejected',
      label: 'Rejeitadas',
      icon: 'XCircle',
      color: 'red',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'UNDER_ANALYSIS', label: 'Em Análise' },
        { value: 'APPROVED', label: 'Aprovado' },
        { value: 'REJECTED', label: 'Rejeitado' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'programType',
      label: 'Tipo de Programa',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'MCMV', label: 'Minha Casa Minha Vida' },
        { value: 'CASA_VERDE_AMARELA', label: 'Casa Verde e Amarela' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/habitacao/programas-habitacionais',

  features: {
    hasProtocol: true,
    hasSource: true,
    hasStatus: true,
    exportable: true,
    importable: false,
  },
};

export const regularizacaoFundiariaConfig: ModuleConfig = {
  key: 'regularizacao-fundiaria',
  departmentType: 'habitacao',
  entityName: 'LandRegularization',
  displayName: 'Regularização Fundiária',
  displayNameSingular: 'Regularização',
  description: 'Processos de regularização de terrenos e imóveis',
  icon: 'FileCheck',
  color: 'green',

  fields: [
    {
      name: 'applicantName',
      label: 'Nome do Requerente',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'applicantCpf',
      label: 'CPF',
      type: 'text',
      required: true,
      placeholder: '000.000.000-00',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'protocol',
      label: 'Protocolo',
      type: 'text',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'propertyAddress',
      label: 'Endereço do Imóvel',
      type: 'textarea',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'propertyArea',
      label: 'Área do Terreno (m²)',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'occupationType',
      label: 'Tipo de Ocupação',
      type: 'select',
      options: [
        { value: 'RESIDENCIAL', label: 'Residencial' },
        { value: 'COMERCIAL', label: 'Comercial' },
        { value: 'MISTA', label: 'Mista' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'hasBuilding',
      label: 'Possui Edificação',
      type: 'checkbox',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'buildingArea',
      label: 'Área Construída (m²)',
      type: 'number',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'occupationDate',
      label: 'Data de Ocupação',
      type: 'date',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'landValue',
      label: 'Valor do Terreno (R$)',
      type: 'currency',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'UNDER_ANALYSIS', label: 'Em Análise' },
        { value: 'FIELD_VISIT', label: 'Aguardando Vistoria' },
        { value: 'IN_PUBLICATION', label: 'Em Publicação' },
        { value: 'APPROVED', label: 'Aprovado' },
        { value: 'TITLE_ISSUED', label: 'Título Emitido' },
        { value: 'REJECTED', label: 'Rejeitado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'applicationDate',
      label: 'Data de Solicitação',
      type: 'date',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Processos',
      icon: 'FileText',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'underAnalysis',
      label: 'Em Análise',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'approved',
      label: 'Aprovados',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'titleIssued',
      label: 'Títulos Emitidos',
      icon: 'Award',
      color: 'purple',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'UNDER_ANALYSIS', label: 'Em Análise' },
        { value: 'APPROVED', label: 'Aprovado' },
        { value: 'TITLE_ISSUED', label: 'Título Emitido' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'occupationType',
      label: 'Tipo de Ocupação',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'RESIDENCIAL', label: 'Residencial' },
        { value: 'COMERCIAL', label: 'Comercial' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/habitacao/regularizacao-fundiaria',

  features: {
    hasProtocol: true,
    hasSource: true,
    hasStatus: true,
    exportable: true,
    importable: false,
  },
};

export const auxilioAluguelConfig: ModuleConfig = {
  key: 'auxilio-aluguel',
  departmentType: 'habitacao',
  entityName: 'RentAssistance',
  displayName: 'Auxílio Aluguel',
  displayNameSingular: 'Auxílio',
  description: 'Programa de auxílio aluguel para famílias em vulnerabilidade',
  icon: 'DollarSign',
  color: 'emerald',

  fields: [
    {
      name: 'applicantName',
      label: 'Nome do Requerente',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'applicantCpf',
      label: 'CPF',
      type: 'text',
      required: true,
      placeholder: '000.000.000-00',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'protocol',
      label: 'Protocolo',
      type: 'text',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'currentAddress',
      label: 'Endereço Atual',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'monthlyRent',
      label: 'Valor do Aluguel (R$)',
      type: 'currency',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'landlordName',
      label: 'Nome do Proprietário',
      type: 'text',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'familyIncome',
      label: 'Renda Familiar (R$)',
      type: 'currency',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'familySize',
      label: 'Membros da Família',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'hasEmployment',
      label: 'Possui Emprego',
      type: 'checkbox',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'vulnerabilityReason',
      label: 'Motivo da Vulnerabilidade',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'requestedAmount',
      label: 'Valor Solicitado (R$)',
      type: 'currency',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'requestedPeriod',
      label: 'Período Solicitado (meses)',
      type: 'number',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'UNDER_ANALYSIS', label: 'Em Análise' },
        { value: 'APPROVED', label: 'Aprovado' },
        { value: 'REJECTED', label: 'Rejeitado' },
        { value: 'ACTIVE', label: 'Ativo' },
        { value: 'SUSPENDED', label: 'Suspenso' },
        { value: 'FINISHED', label: 'Finalizado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'applicationDate',
      label: 'Data de Solicitação',
      type: 'date',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'totalPaid',
      label: 'Total Pago (R$)',
      type: 'currency',
      showInList: true,
      showInDetails: true,
    },
    {
      name: 'paymentsCount',
      label: 'Nº de Pagamentos',
      type: 'number',
      showInList: true,
      showInDetails: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Auxílios',
      icon: 'FileText',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'active',
      label: 'Ativos',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'underAnalysis',
      label: 'Em Análise',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'totalPaid',
      label: 'Total Desembolsado',
      icon: 'DollarSign',
      color: 'emerald',
      format: 'currency',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'UNDER_ANALYSIS', label: 'Em Análise' },
        { value: 'APPROVED', label: 'Aprovado' },
        { value: 'ACTIVE', label: 'Ativo' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/habitacao/auxilio-aluguel',

  features: {
    hasProtocol: true,
    hasSource: true,
    hasStatus: true,
    exportable: true,
    importable: false,
  },
};

export const unidadesHabitacionaisConfig: ModuleConfig = {
  key: 'unidades-habitacionais',
  departmentType: 'habitacao',
  entityName: 'HousingUnit',
  displayName: 'Unidades Habitacionais',
  displayNameSingular: 'Unidade Habitacional',
  description: 'Gestão de unidades habitacionais públicas',
  icon: 'Building',
  color: 'indigo',

  fields: [
    {
      name: 'unitCode',
      label: 'Código da Unidade',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'unitType',
      label: 'Tipo de Unidade',
      type: 'select',
      options: [
        { value: 'APARTAMENTO', label: 'Apartamento' },
        { value: 'CASA', label: 'Casa' },
        { value: 'SOBRADO', label: 'Sobrado' },
        { value: 'KITNET', label: 'Kitnet' },
      ],
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'address',
      label: 'Endereço',
      type: 'textarea',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'neighborhood',
      label: 'Bairro',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'area',
      label: 'Área (m²)',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'bedrooms',
      label: 'Quartos',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'bathrooms',
      label: 'Banheiros',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'constructionYear',
      label: 'Ano de Construção',
      type: 'number',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'propertyValue',
      label: 'Valor do Imóvel (R$)',
      type: 'currency',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'monthlyRent',
      label: 'Aluguel Mensal (R$)',
      type: 'currency',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'isOccupied',
      label: 'Ocupado',
      type: 'checkbox',
      showInList: true,
      showInDetails: true,
    },
    {
      name: 'occupantName',
      label: 'Nome do Ocupante',
      type: 'text',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'occupantCpf',
      label: 'CPF do Ocupante',
      type: 'text',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'needsMaintenance',
      label: 'Precisa de Manutenção',
      type: 'checkbox',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'AVAILABLE', label: 'Disponível' },
        { value: 'OCCUPIED', label: 'Ocupado' },
        { value: 'MAINTENANCE', label: 'Em Manutenção' },
        { value: 'RESERVED', label: 'Reservado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Unidades',
      icon: 'Building',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'available',
      label: 'Disponíveis',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'occupied',
      label: 'Ocupadas',
      icon: 'Users',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'maintenance',
      label: 'Em Manutenção',
      icon: 'Wrench',
      color: 'red',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'AVAILABLE', label: 'Disponível' },
        { value: 'OCCUPIED', label: 'Ocupado' },
        { value: 'MAINTENANCE', label: 'Em Manutenção' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'unitType',
      label: 'Tipo de Unidade',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'APARTAMENTO', label: 'Apartamento' },
        { value: 'CASA', label: 'Casa' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/habitacao/unidades-habitacionais',

  features: {
    hasProtocol: true,
    hasSource: true,
    hasStatus: true,
    exportable: true,
    importable: true,
  },
};

export const filaHabitacaoConfig: ModuleConfig = {
  key: 'fila-habitacao',
  departmentType: 'habitacao',
  entityName: 'HousingRegistration',
  displayName: 'Fila de Habitação',
  displayNameSingular: 'Inscrição na Fila',
  description: 'Gestão da fila de espera para moradia popular',
  icon: 'List',
  color: 'orange',

  fields: [
    {
      name: 'familyHeadName',
      label: 'Chefe da Família',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'familyHeadCPF',
      label: 'CPF',
      type: 'text',
      required: true,
      placeholder: '000.000.000-00',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'contact',
      label: 'Telefone',
      type: 'phone',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'address',
      label: 'Endereço Atual',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'familyIncome',
      label: 'Renda Familiar (R$)',
      type: 'currency',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'familySize',
      label: 'Membros da Família',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'score',
      label: 'Pontuação',
      type: 'number',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'registrationDate',
      label: 'Data de Cadastro',
      type: 'date',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'selectedDate',
      label: 'Data de Seleção',
      type: 'date',
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'REGISTERED', label: 'Cadastrado' },
        { value: 'IN_QUEUE', label: 'Na Fila' },
        { value: 'SELECTED', label: 'Selecionado' },
        { value: 'CONTEMPLATED', label: 'Contemplado' },
        { value: 'INACTIVE', label: 'Inativo' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'observations',
      label: 'Observações',
      type: 'textarea',
      showInForm: true,
      showInDetails: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total na Fila',
      icon: 'List',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'registered',
      label: 'Cadastrados',
      icon: 'FileText',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'selected',
      label: 'Selecionados',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'contemplated',
      label: 'Contemplados',
      icon: 'Award',
      color: 'purple',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'REGISTERED', label: 'Cadastrado' },
        { value: 'IN_QUEUE', label: 'Na Fila' },
        { value: 'SELECTED', label: 'Selecionado' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/habitacao/fila-habitacao',

  features: {
    hasProtocol: true,
    hasSource: true,
    hasStatus: true,
    exportable: true,
    importable: false,
  },
};

export const atendimentosHabitacaoConfig: ModuleConfig = {
  key: 'atendimentos',
  departmentType: 'habitacao',
  entityName: 'HousingAttendance',
  displayName: 'Atendimentos',
  displayNameSingular: 'Atendimento',
  description: 'Atendimentos gerais da secretaria de habitação',
  icon: 'MessageSquare',
  color: 'slate',

  fields: [
    {
      name: 'citizenName',
      label: 'Nome do Cidadão',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'citizenCPF',
      label: 'CPF',
      type: 'text',
      required: true,
      placeholder: '000.000.000-00',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'protocol',
      label: 'Protocolo',
      type: 'text',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'contact',
      label: 'Telefone',
      type: 'phone',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'type',
      label: 'Tipo de Atendimento',
      type: 'select',
      options: [
        { value: 'PROGRAM_INFO', label: 'Informação sobre Programas' },
        { value: 'REGISTRATION', label: 'Cadastramento' },
        { value: 'DOCUMENTATION', label: 'Documentação' },
        { value: 'COMPLAINT', label: 'Reclamação' },
        { value: 'OTHER', label: 'Outros' },
      ],
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'program',
      label: 'Programa de Interesse',
      type: 'text',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'propertyAddress',
      label: 'Endereço do Imóvel',
      type: 'textarea',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'familyIncome',
      label: 'Renda Familiar (R$)',
      type: 'currency',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'familySize',
      label: 'Membros da Família',
      type: 'number',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'currentHousing',
      label: 'Situação Habitacional Atual',
      type: 'textarea',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'IN_PROGRESS', label: 'Em Atendimento' },
        { value: 'RESOLVED', label: 'Resolvido' },
        { value: 'CANCELLED', label: 'Cancelado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'priority',
      label: 'Prioridade',
      type: 'select',
      options: [
        { value: 'LOW', label: 'Baixa' },
        { value: 'MEDIUM', label: 'Média' },
        { value: 'HIGH', label: 'Alta' },
        { value: 'URGENT', label: 'Urgente' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'observations',
      label: 'Observações',
      type: 'textarea',
      showInForm: true,
      showInDetails: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Atendimentos',
      icon: 'MessageSquare',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'pending',
      label: 'Pendentes',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'inProgress',
      label: 'Em Atendimento',
      icon: 'Activity',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'resolved',
      label: 'Resolvidos',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PENDING', label: 'Pendente' },
        { value: 'IN_PROGRESS', label: 'Em Atendimento' },
        { value: 'RESOLVED', label: 'Resolvido' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'type',
      label: 'Tipo',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PROGRAM_INFO', label: 'Informação' },
        { value: 'REGISTRATION', label: 'Cadastramento' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/habitacao/atendimentos',

  features: {
    hasProtocol: true,
    hasSource: true,
    hasStatus: true,
    exportable: true,
    importable: false,
  },
};

// ============================================================================
// EXPORTAR TODOS OS CONFIGS
// ============================================================================

export const habitacaoModuleConfigs = {
  'programas-habitacionais': programasHabitacionaisConfig,
  'regularizacao-fundiaria': regularizacaoFundiariaConfig,
  'auxilio-aluguel': auxilioAluguelConfig,
  'unidades-habitacionais': unidadesHabitacionaisConfig,
  'fila-habitacao': filaHabitacaoConfig,
  'atendimentos': atendimentosHabitacaoConfig,
};
