/**
 * ============================================================================
 * MÓDULOS DE OBRAS PÚBLICAS - CONFIGURAÇÃO
 * ============================================================================
 */

import { ModuleConfig } from './types';

export const atendimentosObrasPublicasConfig: ModuleConfig = {
  key: 'atendimentos-obras-publicas',
  entityName: 'PublicWorksAttendance',
  departmentType: 'public-works',
  displayName: 'Atendimentos de Obras Públicas',
  displayNameSingular: 'Atendimento de Obras Públicas',
  description: 'Solicitações e atendimentos gerais da Secretaria de Obras Públicas',
  icon: 'Headset',
  color: 'amber',

  fields: [
    {
      name: 'protocol',
      label: 'Protocolo',
      type: 'text',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'citizenName',
      label: 'Nome do Cidadão',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'citizenCpf',
      label: 'CPF',
      type: 'text',
      placeholder: '000.000.000-00',
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'contact',
      label: 'Contato',
      type: 'json',
      subfields: [
        { name: 'phone', label: 'Telefone', type: 'text', required: true },
        { name: 'email', label: 'E-mail', type: 'email' },
      ],
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'serviceType',
      label: 'Tipo de Serviço',
      type: 'select',
      required: true,
      options: [
        { value: 'SOLICITACAO', label: 'Solicitação de Serviço' },
        { value: 'RECLAMACAO', label: 'Reclamação' },
        { value: 'INFORMACAO', label: 'Pedido de Informação' },
        { value: 'SUGESTAO', label: 'Sugestão' },
        { value: 'ELOGIO', label: 'Elogio' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'subject',
      label: 'Assunto',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'workType',
      label: 'Tipo de Obra',
      type: 'select',
      options: [
        { value: 'PAVIMENTACAO', label: 'Pavimentação' },
        { value: 'DRENAGEM', label: 'Drenagem' },
        { value: 'ILUMINACAO', label: 'Iluminação Pública' },
        { value: 'PREDIOS', label: 'Prédios Públicos' },
        { value: 'PRACAS', label: 'Praças e Parques' },
        { value: 'OUTROS', label: 'Outros' },
      ],
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'location',
      label: 'Localização',
      type: 'text',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'coordinates',
      label: 'Coordenadas',
      type: 'json',
      showInDetails: true,
    },
    {
      name: 'urgency',
      label: 'Urgência',
      type: 'select',
      options: [
        { value: 'NORMAL', label: 'Normal' },
        { value: 'URGENTE', label: 'Urgente' },
        { value: 'EMERGENCIA', label: 'Emergência' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'priority',
      label: 'Prioridade',
      type: 'select',
      options: [
        { value: 'LOW', label: 'Baixa' },
        { value: 'MEDIUM', label: 'Média' },
        { value: 'HIGH', label: 'Alta' },
        { value: 'CRITICAL', label: 'Crítica' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'IN_ANALYSIS', label: 'Em Análise' },
        { value: 'APPROVED', label: 'Aprovado' },
        { value: 'IN_EXECUTION', label: 'Em Execução' },
        { value: 'COMPLETED', label: 'Concluído' },
        { value: 'REJECTED', label: 'Rejeitado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'photos',
      label: 'Fotos',
      type: 'json',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'estimatedCost',
      label: 'Custo Estimado (R$)',
      type: 'currency',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'engineer',
      label: 'Engenheiro Responsável',
      type: 'text',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'scheduledDate',
      label: 'Data Agendada',
      type: 'date',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'completionDate',
      label: 'Data de Conclusão',
      type: 'date',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'createdAt',
      label: 'Data de Criação',
      type: 'date',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
  ],

  stats: [
    { key: 'total', label: 'Total de Atendimentos', color: 'blue' },
    { key: 'pending', label: 'Pendentes', color: 'yellow' },
    { key: 'inProgress', label: 'Em Andamento', color: 'orange' },
    { key: 'completed', label: 'Concluídos', color: 'green' },
  ],
};

export const reparosDeViasConfig: ModuleConfig = {
  key: 'reparos-de-vias',
  departmentType: 'obrasPublicas',
  entityName: 'RoadRepairRequest',
  displayName: 'Reparos de Vias',
  displayNameSingular: 'Reparo de Via',
  description: 'Solicitações de reparos em vias públicas (buracos, pavimentação, etc)',
  icon: 'Construction',
  color: 'orange',

  fields: [
    {
      name: 'protocol',
      label: 'Protocolo',
      type: 'text',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'citizenName',
      label: 'Nome do Solicitante',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'citizenCpf',
      label: 'CPF',
      type: 'text',
      placeholder: '000.000.000-00',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'contact',
      label: 'Contato',
      type: 'json',
      subfields: [
        { name: 'phone', label: 'Telefone', type: 'text', required: true },
        { name: 'email', label: 'E-mail', type: 'email' },
      ],
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'roadName',
      label: 'Nome da Via',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'location',
      label: 'Localização Detalhada',
      type: 'text',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'problemType',
      label: 'Tipo de Problema',
      type: 'select',
      required: true,
      options: [
        { value: 'BURACO', label: 'Buraco' },
        { value: 'PAVIMENTO_DANIFICADO', label: 'Pavimento Danificado' },
        { value: 'CRATERA', label: 'Cratera' },
        { value: 'AFUNDAMENTO', label: 'Afundamento' },
        { value: 'RACHADURA', label: 'Rachadura' },
        { value: 'EROSAO', label: 'Erosão' },
        { value: 'OUTROS', label: 'Outros' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'severity',
      label: 'Gravidade',
      type: 'select',
      options: [
        { value: 'LOW', label: 'Baixa' },
        { value: 'MEDIUM', label: 'Média' },
        { value: 'HIGH', label: 'Alta' },
        { value: 'CRITICAL', label: 'Crítica' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'affectedArea',
      label: 'Área Afetada (m²)',
      type: 'number',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'trafficImpact',
      label: 'Impacto no Tráfego',
      type: 'select',
      options: [
        { value: 'SEM_IMPACTO', label: 'Sem Impacto' },
        { value: 'LEVE', label: 'Leve' },
        { value: 'MODERADO', label: 'Moderado' },
        { value: 'SEVERO', label: 'Severo' },
        { value: 'BLOQUEIO_TOTAL', label: 'Bloqueio Total' },
      ],
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'urgency',
      label: 'Urgência',
      type: 'select',
      options: [
        { value: 'NORMAL', label: 'Normal' },
        { value: 'URGENTE', label: 'Urgente' },
        { value: 'EMERGENCIA', label: 'Emergência' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'priority',
      label: 'Prioridade',
      type: 'select',
      options: [
        { value: 'LOW', label: 'Baixa' },
        { value: 'MEDIUM', label: 'Média' },
        { value: 'HIGH', label: 'Alta' },
        { value: 'CRITICAL', label: 'Crítica' },
      ],
      showInList: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'IN_ANALYSIS', label: 'Em Análise' },
        { value: 'APPROVED', label: 'Aprovado' },
        { value: 'SCHEDULED', label: 'Agendado' },
        { value: 'IN_EXECUTION', label: 'Em Execução' },
        { value: 'COMPLETED', label: 'Concluído' },
        { value: 'REJECTED', label: 'Rejeitado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'photos',
      label: 'Fotos',
      type: 'json',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'estimatedCost',
      label: 'Custo Estimado (R$)',
      type: 'currency',
      showInDetails: true,
    },
    {
      name: 'assignedTeam',
      label: 'Equipe Designada',
      type: 'text',
      showInDetails: true,
    },
    {
      name: 'scheduledDate',
      label: 'Data Agendada',
      type: 'date',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'completionDate',
      label: 'Data de Conclusão',
      type: 'date',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'createdAt',
      label: 'Data de Solicitação',
      type: 'date',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
  ],

  stats: [
    { key: 'total', label: 'Total de Solicitações', color: 'blue' },
    { key: 'pending', label: 'Pendentes', color: 'yellow' },
    { key: 'inProgress', label: 'Em Execução', color: 'orange' },
    { key: 'completed', label: 'Concluídos', color: 'green' },
  ],
};

export const vistoriasTecnicasConfig: ModuleConfig = {
  key: 'vistorias-tecnicas',
  departmentType: 'obrasPublicas',
  entityName: 'TechnicalInspection',
  displayName: 'Vistorias Técnicas',
  displayNameSingular: 'Vistoria Técnica',
  description: 'Solicitações de vistorias técnicas em imóveis e obras',
  icon: 'ClipboardCheck',
  color: 'purple',

  fields: [
    {
      name: 'protocol',
      label: 'Protocolo',
      type: 'text',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'requestorName',
      label: 'Nome do Solicitante',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'requestorCpf',
      label: 'CPF',
      type: 'text',
      placeholder: '000.000.000-00',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'contact',
      label: 'Contato',
      type: 'json',
      subfields: [
        { name: 'phone', label: 'Telefone', type: 'text', required: true },
        { name: 'email', label: 'E-mail', type: 'email' },
      ],
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'inspectionType',
      label: 'Tipo de Vistoria',
      type: 'select',
      required: true,
      options: [
        { value: 'ESTRUTURAL', label: 'Estrutural' },
        { value: 'ELETRICA', label: 'Elétrica' },
        { value: 'HIDRAULICA', label: 'Hidráulica' },
        { value: 'INCENDIO', label: 'Prevenção de Incêndio' },
        { value: 'ACESSIBILIDADE', label: 'Acessibilidade' },
        { value: 'AMBIENTAL', label: 'Ambiental' },
        { value: 'COMPLETA', label: 'Completa' },
        { value: 'OUTROS', label: 'Outros' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'subject',
      label: 'Assunto',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'location',
      label: 'Localização',
      type: 'text',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'propertyType',
      label: 'Tipo de Imóvel',
      type: 'select',
      options: [
        { value: 'RESIDENCIAL', label: 'Residencial' },
        { value: 'COMERCIAL', label: 'Comercial' },
        { value: 'INDUSTRIAL', label: 'Industrial' },
        { value: 'PUBLICO', label: 'Público' },
        { value: 'MISTO', label: 'Misto' },
      ],
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'constructionStage',
      label: 'Estágio da Construção',
      type: 'select',
      options: [
        { value: 'PROJETO', label: 'Projeto' },
        { value: 'FUNDACAO', label: 'Fundação' },
        { value: 'ESTRUTURA', label: 'Estrutura' },
        { value: 'ACABAMENTO', label: 'Acabamento' },
        { value: 'CONCLUIDO', label: 'Concluído' },
      ],
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'urgency',
      label: 'Urgência',
      type: 'select',
      options: [
        { value: 'NORMAL', label: 'Normal' },
        { value: 'URGENTE', label: 'Urgente' },
        { value: 'EMERGENCIA', label: 'Emergência' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'SCHEDULED', label: 'Agendado' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'COMPLETED', label: 'Concluído' },
        { value: 'APPROVED', label: 'Aprovado' },
        { value: 'REJECTED', label: 'Rejeitado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'documents',
      label: 'Documentos',
      type: 'json',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'photos',
      label: 'Fotos',
      type: 'json',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'inspector',
      label: 'Inspetor',
      type: 'text',
      showInDetails: true,
    },
    {
      name: 'scheduledDate',
      label: 'Data Agendada',
      type: 'date',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'inspectionDate',
      label: 'Data da Vistoria',
      type: 'date',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'approved',
      label: 'Aprovado',
      type: 'checkbox',
      showInList: true,
      showInDetails: true,
    },
    {
      name: 'validUntil',
      label: 'Válido Até',
      type: 'date',
      showInDetails: true,
    },
    {
      name: 'createdAt',
      label: 'Data de Solicitação',
      type: 'date',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
  ],

  stats: [
    { key: 'total', label: 'Total de Vistorias', color: 'blue' },
    { key: 'pending', label: 'Pendentes', color: 'yellow' },
    { key: 'scheduled', label: 'Agendadas', color: 'purple' },
    { key: 'completed', label: 'Concluídas', color: 'green' },
  ],
};

export const cadastroDeObrasConfig: ModuleConfig = {
  key: 'cadastro-de-obras',
  departmentType: 'obrasPublicas',
  entityName: 'PublicWork',
  displayName: 'Cadastro de Obras',
  displayNameSingular: 'Obra Pública',
  description: 'Cadastro e acompanhamento de obras públicas',
  icon: 'Building2',
  color: 'blue',

  fields: [
    {
      name: 'title',
      label: 'Título da Obra',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'workType',
      label: 'Tipo de Obra',
      type: 'select',
      required: true,
      options: [
        { value: 'PAVIMENTACAO', label: 'Pavimentação' },
        { value: 'DRENAGEM', label: 'Drenagem' },
        { value: 'EDIFICACAO', label: 'Edificação' },
        { value: 'REFORMA', label: 'Reforma' },
        { value: 'PRACA', label: 'Praça/Parque' },
        { value: 'PONTE', label: 'Ponte/Viaduto' },
        { value: 'REDE_AGUA', label: 'Rede de Água' },
        { value: 'REDE_ESGOTO', label: 'Rede de Esgoto' },
        { value: 'ILUMINACAO', label: 'Iluminação Pública' },
        { value: 'OUTROS', label: 'Outros' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'location',
      label: 'Localização',
      type: 'text',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'contractor',
      label: 'Empresa Contratada',
      type: 'text',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'startDate',
      label: 'Data de Início',
      type: 'date',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'endDate',
      label: 'Data de Término Prevista',
      type: 'date',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'plannedBudget',
      label: 'Orçamento Planejado (R$)',
      type: 'currency',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'actualBudget',
      label: 'Orçamento Executado (R$)',
      type: 'currency',
      showInList: true,
      showInDetails: true,
    },
    {
      name: 'progressPercent',
      label: 'Progresso (%)',
      type: 'number',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PLANNED', label: 'Planejada' },
        { value: 'APPROVED', label: 'Aprovada' },
        { value: 'IN_BIDDING', label: 'Em Licitação' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'PAUSED', label: 'Paralisada' },
        { value: 'COMPLETED', label: 'Concluída' },
        { value: 'CANCELLED', label: 'Cancelada' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'priority',
      label: 'Prioridade',
      type: 'select',
      options: [
        { value: 'LOW', label: 'Baixa' },
        { value: 'MEDIUM', label: 'Média' },
        { value: 'HIGH', label: 'Alta' },
        { value: 'CRITICAL', label: 'Crítica' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'beneficiaries',
      label: 'Beneficiários (estimativa)',
      type: 'number',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'photos',
      label: 'Fotos',
      type: 'json',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'documents',
      label: 'Documentos',
      type: 'json',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'createdAt',
      label: 'Data de Cadastro',
      type: 'date',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
  ],

  stats: [
    { key: 'total', label: 'Total de Obras', color: 'blue' },
    { key: 'planned', label: 'Planejadas', color: 'gray' },
    { key: 'inProgress', label: 'Em Andamento', color: 'orange' },
    { key: 'completed', label: 'Concluídas', color: 'green' },
  ],
};

export const inspecaoDeObrasConfig: ModuleConfig = {
  key: 'inspecao-de-obras',
  departmentType: 'obrasPublicas',
  entityName: 'WorkInspection',
  displayName: 'Inspeção de Obras',
  displayNameSingular: 'Inspeção de Obra',
  description: 'Inspeções e fiscalizações de obras em andamento',
  icon: 'Shield',
  color: 'red',

  fields: [
    {
      name: 'protocol',
      label: 'Protocolo',
      type: 'text',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'workName',
      label: 'Nome da Obra',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'workType',
      label: 'Tipo de Obra',
      type: 'select',
      required: true,
      options: [
        { value: 'PAVIMENTACAO', label: 'Pavimentação' },
        { value: 'DRENAGEM', label: 'Drenagem' },
        { value: 'EDIFICACAO', label: 'Edificação' },
        { value: 'REFORMA', label: 'Reforma' },
        { value: 'PRACA', label: 'Praça/Parque' },
        { value: 'PONTE', label: 'Ponte/Viaduto' },
        { value: 'OUTROS', label: 'Outros' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'contractor',
      label: 'Empresa Contratada',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'location',
      label: 'Localização',
      type: 'text',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'inspectionDate',
      label: 'Data da Inspeção',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'inspector',
      label: 'Inspetor',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'inspectionType',
      label: 'Tipo de Inspeção',
      type: 'select',
      required: true,
      options: [
        { value: 'ROTINA', label: 'Rotina' },
        { value: 'FISCAL', label: 'Fiscal' },
        { value: 'DENUNCIA', label: 'Denúncia' },
        { value: 'EMERGENCIA', label: 'Emergência' },
        { value: 'FINAL', label: 'Final/Recebimento' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'compliance',
      label: 'Conformidade',
      type: 'select',
      required: true,
      options: [
        { value: 'CONFORME', label: 'Conforme' },
        { value: 'NAO_CONFORME', label: 'Não Conforme' },
        { value: 'PARCIALMENTE_CONFORME', label: 'Parcialmente Conforme' },
        { value: 'EM_ANALISE', label: 'Em Análise' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'findings',
      label: 'Constatações',
      type: 'json',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'violations',
      label: 'Infrações',
      type: 'json',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'recommendations',
      label: 'Recomendações',
      type: 'json',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'SCHEDULED', label: 'Agendada' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'COMPLETED', label: 'Concluída' },
        { value: 'PENDING_ACTION', label: 'Ação Pendente' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'photos',
      label: 'Fotos',
      type: 'json',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'documents',
      label: 'Documentos',
      type: 'json',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'deadline',
      label: 'Prazo para Correções',
      type: 'date',
      showInDetails: true,
    },
    {
      name: 'nextInspection',
      label: 'Próxima Inspeção',
      type: 'date',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'createdAt',
      label: 'Data de Registro',
      type: 'date',
      showInList: true,
      showInDetails: true,
      sortable: true,
    },
  ],

  stats: [
    { key: 'total', label: 'Total de Inspeções', color: 'blue' },
    { key: 'scheduled', label: 'Agendadas', color: 'purple' },
    { key: 'completed', label: 'Concluídas', color: 'green' },
    { key: 'nonCompliant', label: 'Não Conformes', color: 'red' },
  ],
};

// ============================================================================
// MÓDULOS INFORMATIVOS (SEM DADOS)
// ============================================================================

export const consultaContratosConfig: ModuleConfig = {
  key: 'consulta-contratos',
  departmentType: 'obrasPublicas',
  entityName: 'InformativeModule',
  displayName: 'Consulta de Contratos e Licitações',
  displayNameSingular: 'Consulta de Contratos',
  description: 'Módulo informativo para consulta de contratos e processos licitatórios',
  icon: 'FileText',
  color: 'yellow',
  fields: [],
  stats: [],
  canCreate: false,
};

export const consultaMapaObrasConfig: ModuleConfig = {
  key: 'consulta-mapa-obras',
  departmentType: 'obrasPublicas',
  entityName: 'InformativeModule',
  displayName: 'Consulta de Mapa de Obras',
  displayNameSingular: 'Mapa de Obras',
  description: 'Módulo informativo para visualização geográfica de obras públicas',
  icon: 'Map',
  color: 'green',
  fields: [],
  stats: [],
  canCreate: false,
};
