/**
 * ============================================================================
 * MÓDULOS DE SERVIÇOS PÚBLICOS - CONFIGURAÇÃO
 * ============================================================================
 */

import { ModuleConfig } from './types';

export const publicServiceAttendanceConfig: ModuleConfig = {
  key: 'atendimentos-gerais',
  entityName: 'PublicServiceAttendance',
  departmentType: 'public-services',
  displayName: 'Atendimentos Gerais',
  displayNameSingular: 'Atendimento Geral',
  description: 'Atendimentos gerais de serviços públicos ao cidadão',
  icon: 'ClipboardList',
  color: 'blue',

  fields: [
    {
      name: 'citizenName',
      label: 'Nome do Cidadão',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'citizenCpf',
      label: 'CPF',
      type: 'text',
      required: false,
      placeholder: '000.000.000-00',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'citizenPhone',
      label: 'Telefone',
      type: 'phone',
      required: false,
      placeholder: '(00) 00000-0000',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'citizenEmail',
      label: 'E-mail',
      type: 'email',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'serviceType',
      label: 'Tipo de Serviço',
      type: 'select',
      required: true,
      options: [
        { value: 'LIMPEZA', label: 'Limpeza Urbana' },
        { value: 'ILUMINACAO', label: 'Iluminação Pública' },
        { value: 'COLETA', label: 'Coleta de Resíduos' },
        { value: 'MANUTENCAO', label: 'Manutenção Urbana' },
        { value: 'CAPINA', label: 'Capina e Roçada' },
        { value: 'DRENAGEM', label: 'Drenagem e Limpeza' },
        { value: 'PODA', label: 'Poda de Árvores' },
        { value: 'OUTROS', label: 'Outros Serviços' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'requestType',
      label: 'Tipo de Solicitação',
      type: 'select',
      required: true,
      options: [
        { value: 'RECLAMACAO', label: 'Reclamação' },
        { value: 'SOLICITACAO', label: 'Solicitação' },
        { value: 'SUGESTAO', label: 'Sugestão' },
        { value: 'ELOGIO', label: 'Elogio' },
        { value: 'DENUNCIA', label: 'Denúncia' },
        { value: 'INFORMACAO', label: 'Pedido de Informação' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInList: false,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'location',
      label: 'Localização',
      type: 'text',
      required: false,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'address',
      label: 'Endereço Completo',
      type: 'text',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'urgency',
      label: 'Urgência',
      type: 'select',
      required: false,
      options: [
        { value: 'BAIXA', label: 'Baixa' },
        { value: 'NORMAL', label: 'Normal' },
        { value: 'ALTA', label: 'Alta' },
        { value: 'URGENTE', label: 'Urgente' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'priority',
      label: 'Prioridade',
      type: 'select',
      required: false,
      options: [
        { value: 'BAIXA', label: 'Baixa' },
        { value: 'MEDIA', label: 'Média' },
        { value: 'ALTA', label: 'Alta' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      required: false,
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'RESOLVED', label: 'Resolvido' },
        { value: 'CANCELLED', label: 'Cancelado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'requestDate',
      label: 'Data da Solicitação',
      type: 'date',
      required: false,
      showInList: true,
      showInForm: false,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'scheduledDate',
      label: 'Data Agendada',
      type: 'date',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'completionDate',
      label: 'Data de Conclusão',
      type: 'date',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'assignedTeam',
      label: 'Equipe Responsável',
      type: 'text',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'assignedTo',
      label: 'Responsável',
      type: 'text',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'resolution',
      label: 'Resolução',
      type: 'textarea',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'observations',
      label: 'Observações',
      type: 'textarea',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetails: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Atendimentos',
      description: 'Total de atendimentos registrados',
      icon: 'ClipboardList',
      color: 'blue',
    },
    {
      key: 'pending',
      label: 'Pendentes',
      description: 'Atendimentos aguardando processamento',
      icon: 'Clock',
      color: 'yellow',
    },
    {
      key: 'inProgress',
      label: 'Em Andamento',
      description: 'Atendimentos em execução',
      icon: 'Activity',
      color: 'blue',
    },
    {
      key: 'resolved',
      label: 'Resolvidos',
      description: 'Atendimentos concluídos',
      icon: 'CheckCircle',
      color: 'green',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PENDING', label: 'Pendente' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'RESOLVED', label: 'Resolvido' },
        { value: 'CANCELLED', label: 'Cancelado' },
      ],
    },
    {
      key: 'serviceType',
      label: 'Tipo de Serviço',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'LIMPEZA', label: 'Limpeza Urbana' },
        { value: 'ILUMINACAO', label: 'Iluminação Pública' },
        { value: 'COLETA', label: 'Coleta de Resíduos' },
        { value: 'MANUTENCAO', label: 'Manutenção Urbana' },
        { value: 'CAPINA', label: 'Capina e Roçada' },
        { value: 'DRENAGEM', label: 'Drenagem e Limpeza' },
        { value: 'PODA', label: 'Poda de Árvores' },
        { value: 'OUTROS', label: 'Outros Serviços' },
      ],
    },
    {
      key: 'urgency',
      label: 'Urgência',
      type: 'select',
      options: [
        { value: 'all', label: 'Todas' },
        { value: 'BAIXA', label: 'Baixa' },
        { value: 'NORMAL', label: 'Normal' },
        { value: 'ALTA', label: 'Alta' },
        { value: 'URGENTE', label: 'Urgente' },
      ],
    },
  ],

  apiEndpoint: '/api/admin/secretarias/servicos-publicos/PublicServiceAttendance',
};

export const publicServiceRequestConfig: ModuleConfig = {
  key: 'public-service-requests',
  departmentType: 'servicos-publicos',
  entityName: 'PublicServiceRequest',
  displayName: 'Atendimentos de Serviços Públicos',
  displayNameSingular: 'Atendimento de Serviço Público',
  description: 'Solicitações e atendimentos de serviços públicos',
  icon: 'ClipboardList',
  color: 'blue',

  fields: [
    {
      name: 'requestorName',
      label: 'Nome do Solicitante',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'requestorCpf',
      label: 'CPF',
      type: 'text',
      required: true,
      placeholder: '000.000.000-00',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'contact',
      label: 'Contato',
      type: 'phone',
      required: true,
      placeholder: '(00) 00000-0000',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'serviceType',
      label: 'Tipo de Serviço',
      type: 'select',
      required: true,
      options: [
        { value: 'cleaning', label: 'Limpeza' },
        { value: 'lighting', label: 'Iluminação' },
        { value: 'weeding', label: 'Capina' },
        { value: 'drainage', label: 'Desobstrução' },
        { value: 'pruning', label: 'Poda' },
        { value: 'collection', label: 'Coleta Especial' },
        { value: 'other', label: 'Outros' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'category',
      label: 'Categoria',
      type: 'select',
      required: true,
      options: [
        { value: 'request', label: 'Solicitação' },
        { value: 'complaint', label: 'Reclamação' },
        { value: 'suggestion', label: 'Sugestão' },
        { value: 'information', label: 'Informação' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'location',
      label: 'Localização',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'urgency',
      label: 'Urgência',
      type: 'select',
      required: true,
      options: [
        { value: 'low', label: 'Baixa' },
        { value: 'medium', label: 'Média' },
        { value: 'high', label: 'Alta' },
        { value: 'critical', label: 'Crítica' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'COMPLETED', label: 'Concluído' },
        { value: 'CANCELLED', label: 'Cancelado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'photos',
      label: 'Fotos',
      type: 'file',
      showInForm: true,
      showInDetails: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Atendimentos',
      icon: 'ClipboardList',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'pending',
      label: 'Pendentes',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'inProgress',
      label: 'Em Andamento',
      icon: 'Activity',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'completed',
      label: 'Concluídos',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'thisMonth',
      label: 'Atendimentos este Mês',
      icon: 'TrendingUp',
      color: 'purple',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PENDING', label: 'Pendentes' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'COMPLETED', label: 'Concluídos' },
        { value: 'CANCELLED', label: 'Cancelados' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'serviceType',
      label: 'Tipo de Serviço',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'cleaning', label: 'Limpeza' },
        { value: 'lighting', label: 'Iluminação' },
        { value: 'weeding', label: 'Capina' },
        { value: 'drainage', label: 'Desobstrução' },
        { value: 'pruning', label: 'Poda' },
        { value: 'collection', label: 'Coleta Especial' },
        { value: 'other', label: 'Outros' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'urgency',
      label: 'Urgência',
      type: 'select',
      options: [
        { value: 'all', label: 'Todas' },
        { value: 'low', label: 'Baixa' },
        { value: 'medium', label: 'Média' },
        { value: 'high', label: 'Alta' },
        { value: 'critical', label: 'Crítica' },
      ],
      defaultValue: 'all',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/servicos-publicos/atendimentos',

  features: {
    hasProtocol: true,
    hasSource: true,
    hasStatus: true,
    exportable: true,
    importable: true,
  },
};

export const streetLightingConfig: ModuleConfig = {
  key: 'street-lighting',
  departmentType: 'servicos-publicos',
  entityName: 'StreetLighting',
  displayName: 'Iluminação Pública',
  displayNameSingular: 'Ponto de Iluminação',
  description: 'Gestão e manutenção de iluminação pública',
  icon: 'Lightbulb',
  color: 'yellow',

  fields: [
    {
      name: 'pointCode',
      label: 'Código do Ponto',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'streetName',
      label: 'Rua/Avenida',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'neighborhood',
      label: 'Bairro',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'coordinates',
      label: 'Coordenadas',
      type: 'text',
      placeholder: 'Latitude, Longitude',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'poleType',
      label: 'Tipo de Poste',
      type: 'select',
      required: true,
      options: [
        { value: 'concrete', label: 'Concreto' },
        { value: 'metal', label: 'Metálico' },
        { value: 'wood', label: 'Madeira' },
        { value: 'fiberglass', label: 'Fibra de Vidro' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'lampType',
      label: 'Tipo de Lâmpada',
      type: 'select',
      required: true,
      options: [
        { value: 'led', label: 'LED' },
        { value: 'sodium', label: 'Vapor de Sódio' },
        { value: 'mercury', label: 'Vapor de Mercúrio' },
        { value: 'fluorescent', label: 'Fluorescente' },
        { value: 'halogen', label: 'Halógena' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'power',
      label: 'Potência (W)',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'height',
      label: 'Altura (m)',
      type: 'number',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'condition',
      label: 'Condição',
      type: 'select',
      required: true,
      options: [
        { value: 'good', label: 'Boa' },
        { value: 'regular', label: 'Regular' },
        { value: 'poor', label: 'Ruim' },
        { value: 'critical', label: 'Crítica' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'ACTIVE', label: 'Ativo' },
        { value: 'INACTIVE', label: 'Inativo' },
        { value: 'MAINTENANCE', label: 'Em Manutenção' },
        { value: 'BROKEN', label: 'Quebrado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Pontos',
      icon: 'Lightbulb',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'active',
      label: 'Ativos',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'inactive',
      label: 'Inativos',
      icon: 'XCircle',
      color: 'red',
      format: 'number',
    },
    {
      key: 'maintenance',
      label: 'Em Manutenção',
      icon: 'Wrench',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'led',
      label: 'LED',
      icon: 'Zap',
      color: 'purple',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'ACTIVE', label: 'Ativos' },
        { value: 'INACTIVE', label: 'Inativos' },
        { value: 'MAINTENANCE', label: 'Em Manutenção' },
        { value: 'BROKEN', label: 'Quebrados' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'lampType',
      label: 'Tipo de Lâmpada',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'led', label: 'LED' },
        { value: 'sodium', label: 'Vapor de Sódio' },
        { value: 'mercury', label: 'Vapor de Mercúrio' },
        { value: 'fluorescent', label: 'Fluorescente' },
        { value: 'halogen', label: 'Halógena' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/servicos-publicos/iluminacao',

  features: {
    hasStatus: true,
    exportable: true,
    importable: true,
  },
};

export const specialCollectionConfig: ModuleConfig = {
  key: 'special-collection',
  departmentType: 'servicos-publicos',
  entityName: 'SpecialCollection',
  displayName: 'Coleta Especial',
  displayNameSingular: 'Coleta Especial',
  description: 'Solicitações de coleta de resíduos especiais',
  icon: 'Trash2',
  color: 'orange',

  fields: [
    {
      name: 'collectionType',
      label: 'Tipo de Coleta',
      type: 'select',
      required: true,
      options: [
        { value: 'furniture', label: 'Móveis' },
        { value: 'electronics', label: 'Eletrônicos' },
        { value: 'construction', label: 'Entulho' },
        { value: 'garden', label: 'Resíduos de Jardim' },
        { value: 'hazardous', label: 'Resíduos Perigosos' },
        { value: 'other', label: 'Outros' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'requestorName',
      label: 'Nome do Solicitante',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'requestorCpf',
      label: 'CPF',
      type: 'text',
      required: true,
      placeholder: '000.000.000-00',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'address',
      label: 'Endereço',
      type: 'textarea',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'description',
      label: 'Descrição dos Resíduos',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'estimatedVolume',
      label: 'Volume Estimado (m³)',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'quantity',
      label: 'Quantidade de Itens',
      type: 'number',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'preferredDate',
      label: 'Data Preferencial',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'SCHEDULED', label: 'Agendado' },
        { value: 'COLLECTED', label: 'Coletado' },
        { value: 'CANCELLED', label: 'Cancelado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Solicitações',
      icon: 'Trash2',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'pending',
      label: 'Pendentes',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'scheduled',
      label: 'Agendadas',
      icon: 'Calendar',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'collected',
      label: 'Coletadas',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'totalVolume',
      label: 'Volume Total (m³)',
      icon: 'Package',
      color: 'orange',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PENDING', label: 'Pendentes' },
        { value: 'SCHEDULED', label: 'Agendadas' },
        { value: 'COLLECTED', label: 'Coletadas' },
        { value: 'CANCELLED', label: 'Canceladas' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'collectionType',
      label: 'Tipo de Coleta',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'furniture', label: 'Móveis' },
        { value: 'electronics', label: 'Eletrônicos' },
        { value: 'construction', label: 'Entulho' },
        { value: 'garden', label: 'Resíduos de Jardim' },
        { value: 'hazardous', label: 'Resíduos Perigosos' },
        { value: 'other', label: 'Outros' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/servicos-publicos/coleta-especial',

  features: {
    hasProtocol: true,
    hasStatus: true,
    exportable: true,
  },
};

export const cleaningScheduleConfig: ModuleConfig = {
  key: 'cleaning-schedule',
  departmentType: 'servicos-publicos',
  entityName: 'CleaningSchedule',
  displayName: 'Limpeza Urbana',
  displayNameSingular: 'Programação de Limpeza',
  description: 'Programação e gestão de limpeza urbana',
  icon: 'Sparkles',
  color: 'cyan',

  fields: [
    {
      name: 'area',
      label: 'Área/Região',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'cleaningType',
      label: 'Tipo de Limpeza',
      type: 'select',
      required: true,
      options: [
        { value: 'street', label: 'Varrição' },
        { value: 'washing', label: 'Lavagem' },
        { value: 'desilting', label: 'Desassoreamento' },
        { value: 'weeding', label: 'Capina' },
        { value: 'collection', label: 'Coleta' },
        { value: 'general', label: 'Limpeza Geral' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'frequency',
      label: 'Frequência',
      type: 'select',
      required: true,
      options: [
        { value: 'daily', label: 'Diária' },
        { value: 'weekly', label: 'Semanal' },
        { value: 'biweekly', label: 'Quinzenal' },
        { value: 'monthly', label: 'Mensal' },
        { value: 'sporadic', label: 'Esporádica' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'startTime',
      label: 'Horário de Início',
      type: 'time',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'duration',
      label: 'Duração (horas)',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'teamSize',
      label: 'Tamanho da Equipe',
      type: 'number',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'responsibleTeam',
      label: 'Equipe Responsável',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'nextExecution',
      label: 'Próxima Execução',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'isActive',
      label: 'Ativo',
      type: 'boolean',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Programações',
      icon: 'Calendar',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'active',
      label: 'Ativas',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'today',
      label: 'Programadas Hoje',
      icon: 'Clock',
      color: 'cyan',
      format: 'number',
    },
    {
      key: 'thisWeek',
      label: 'Esta Semana',
      icon: 'CalendarDays',
      color: 'purple',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'isActive',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todas' },
        { value: 'true', label: 'Ativas' },
        { value: 'false', label: 'Inativas' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'cleaningType',
      label: 'Tipo de Limpeza',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'street', label: 'Varrição' },
        { value: 'washing', label: 'Lavagem' },
        { value: 'desilting', label: 'Desassoreamento' },
        { value: 'weeding', label: 'Capina' },
        { value: 'collection', label: 'Coleta' },
        { value: 'general', label: 'Limpeza Geral' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/servicos-publicos/limpeza',

  features: {
    hasStatus: true,
    exportable: true,
  },
};

export const teamScheduleConfig: ModuleConfig = {
  key: 'team-schedule',
  departmentType: 'servicos-publicos',
  entityName: 'TeamSchedule',
  displayName: 'Gestão de Equipes',
  displayNameSingular: 'Equipe',
  description: 'Gestão e escala de equipes de serviço',
  icon: 'Users',
  color: 'indigo',

  fields: [
    {
      name: 'teamName',
      label: 'Nome da Equipe',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'teamType',
      label: 'Tipo de Equipe',
      type: 'select',
      required: true,
      options: [
        { value: 'cleaning', label: 'Limpeza' },
        { value: 'lighting', label: 'Iluminação' },
        { value: 'collection', label: 'Coleta' },
        { value: 'maintenance', label: 'Manutenção' },
        { value: 'weeding', label: 'Capina' },
        { value: 'pruning', label: 'Poda' },
        { value: 'general', label: 'Geral' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'shift',
      label: 'Turno',
      type: 'select',
      required: true,
      options: [
        { value: 'morning', label: 'Manhã' },
        { value: 'afternoon', label: 'Tarde' },
        { value: 'night', label: 'Noite' },
        { value: 'full', label: 'Integral' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'workDays',
      label: 'Dias de Trabalho',
      type: 'text',
      required: true,
      placeholder: 'Ex: Seg-Sex, Seg-Sab',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'startTime',
      label: 'Horário de Início',
      type: 'time',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'endTime',
      label: 'Horário de Término',
      type: 'time',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'teamLead',
      label: 'Responsável',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'members',
      label: 'Membros',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'workAreas',
      label: 'Áreas de Atuação',
      type: 'textarea',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'isActive',
      label: 'Ativa',
      type: 'boolean',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Equipes',
      icon: 'Users',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'active',
      label: 'Ativas',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'totalMembers',
      label: 'Total de Membros',
      icon: 'UserCheck',
      color: 'indigo',
      format: 'number',
    },
    {
      key: 'workingToday',
      label: 'Trabalhando Hoje',
      icon: 'Briefcase',
      color: 'purple',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'isActive',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todas' },
        { value: 'true', label: 'Ativas' },
        { value: 'false', label: 'Inativas' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'teamType',
      label: 'Tipo de Equipe',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'cleaning', label: 'Limpeza' },
        { value: 'lighting', label: 'Iluminação' },
        { value: 'collection', label: 'Coleta' },
        { value: 'maintenance', label: 'Manutenção' },
        { value: 'weeding', label: 'Capina' },
        { value: 'pruning', label: 'Poda' },
        { value: 'general', label: 'Geral' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/servicos-publicos/equipes',

  features: {
    hasStatus: true,
    exportable: true,
  },
};

export const publicProblemReportConfig: ModuleConfig = {
  key: 'public-problem-report',
  departmentType: 'servicos-publicos',
  entityName: 'PublicProblemReport',
  displayName: 'Registro de Problemas com Foto',
  displayNameSingular: 'Registro de Problema',
  description: 'Registro de problemas urbanos com documentação fotográfica',
  icon: 'Camera',
  color: 'red',

  fields: [
    {
      name: 'reporterName',
      label: 'Nome do Denunciante',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'reporterPhone',
      label: 'Telefone',
      type: 'phone',
      required: true,
      placeholder: '(00) 00000-0000',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'problemType',
      label: 'Tipo de Problema',
      type: 'select',
      required: true,
      options: [
        { value: 'pothole', label: 'Buraco na Via' },
        { value: 'lighting', label: 'Iluminação Defeituosa' },
        { value: 'drainage', label: 'Drenagem Entupida' },
        { value: 'trash', label: 'Lixo Acumulado' },
        { value: 'vegetation', label: 'Mato Alto' },
        { value: 'sidewalk', label: 'Calçada Danificada' },
        { value: 'signage', label: 'Sinalização Danificada' },
        { value: 'other', label: 'Outro' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'title',
      label: 'Título',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
    },
    {
      name: 'severity',
      label: 'Gravidade',
      type: 'select',
      required: true,
      options: [
        { value: 'low', label: 'Baixa' },
        { value: 'medium', label: 'Média' },
        { value: 'high', label: 'Alta' },
        { value: 'critical', label: 'Crítica' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'location',
      label: 'Localização',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'photos',
      label: 'Fotos',
      type: 'file',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'IN_ANALYSIS', label: 'Em Análise' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'RESOLVED', label: 'Resolvido' },
        { value: 'REJECTED', label: 'Rejeitado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'priority',
      label: 'Prioridade',
      type: 'select',
      options: [
        { value: 'low', label: 'Baixa' },
        { value: 'medium', label: 'Média' },
        { value: 'high', label: 'Alta' },
        { value: 'urgent', label: 'Urgente' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Registros',
      icon: 'Camera',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'pending',
      label: 'Pendentes',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'inProgress',
      label: 'Em Andamento',
      icon: 'Activity',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'resolved',
      label: 'Resolvidos',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'critical',
      label: 'Críticos',
      icon: 'AlertTriangle',
      color: 'red',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PENDING', label: 'Pendentes' },
        { value: 'IN_ANALYSIS', label: 'Em Análise' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'RESOLVED', label: 'Resolvidos' },
        { value: 'REJECTED', label: 'Rejeitados' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'problemType',
      label: 'Tipo de Problema',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'pothole', label: 'Buraco na Via' },
        { value: 'lighting', label: 'Iluminação Defeituosa' },
        { value: 'drainage', label: 'Drenagem Entupida' },
        { value: 'trash', label: 'Lixo Acumulado' },
        { value: 'vegetation', label: 'Mato Alto' },
        { value: 'sidewalk', label: 'Calçada Danificada' },
        { value: 'signage', label: 'Sinalização Danificada' },
        { value: 'other', label: 'Outro' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'severity',
      label: 'Gravidade',
      type: 'select',
      options: [
        { value: 'all', label: 'Todas' },
        { value: 'low', label: 'Baixa' },
        { value: 'medium', label: 'Média' },
        { value: 'high', label: 'Alta' },
        { value: 'critical', label: 'Crítica' },
      ],
      defaultValue: 'all',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/servicos-publicos/registro-problemas',

  features: {
    hasProtocol: true,
    hasStatus: true,
    exportable: true,
  },
};

export const weedingRequestConfig: ModuleConfig = {
  key: 'weeding-request',
  departmentType: 'servicos-publicos',
  entityName: 'WeedingRequest',
  displayName: 'Capina',
  displayNameSingular: 'Solicitação de Capina',
  description: 'Solicitações de serviço de capina',
  icon: 'Leaf',
  color: 'green',

  fields: [
    {
      name: 'requestorName',
      label: 'Nome do Solicitante',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'requestorCpf',
      label: 'CPF',
      type: 'text',
      required: true,
      placeholder: '000.000.000-00',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'location',
      label: 'Localização',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'address',
      label: 'Endereço Completo',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'areaSize',
      label: 'Tamanho da Área (m²)',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'terrainType',
      label: 'Tipo de Terreno',
      type: 'select',
      required: true,
      options: [
        { value: 'lot', label: 'Lote Vago' },
        { value: 'sidewalk', label: 'Calçada' },
        { value: 'street', label: 'Rua' },
        { value: 'square', label: 'Praça' },
        { value: 'other', label: 'Outro' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'accessType',
      label: 'Tipo de Acesso',
      type: 'select',
      required: true,
      options: [
        { value: 'easy', label: 'Fácil' },
        { value: 'moderate', label: 'Moderado' },
        { value: 'difficult', label: 'Difícil' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'urgency',
      label: 'Urgência',
      type: 'select',
      required: true,
      options: [
        { value: 'low', label: 'Baixa' },
        { value: 'medium', label: 'Média' },
        { value: 'high', label: 'Alta' },
        { value: 'critical', label: 'Crítica' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'SCHEDULED', label: 'Agendado' },
        { value: 'IN_PROGRESS', label: 'Em Execução' },
        { value: 'COMPLETED', label: 'Concluído' },
        { value: 'CANCELLED', label: 'Cancelado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Solicitações',
      icon: 'Leaf',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'pending',
      label: 'Pendentes',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'inProgress',
      label: 'Em Execução',
      icon: 'Activity',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'completed',
      label: 'Concluídos',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'totalArea',
      label: 'Área Total (m²)',
      icon: 'Maximize',
      color: 'emerald',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PENDING', label: 'Pendentes' },
        { value: 'SCHEDULED', label: 'Agendados' },
        { value: 'IN_PROGRESS', label: 'Em Execução' },
        { value: 'COMPLETED', label: 'Concluídos' },
        { value: 'CANCELLED', label: 'Cancelados' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'urgency',
      label: 'Urgência',
      type: 'select',
      options: [
        { value: 'all', label: 'Todas' },
        { value: 'low', label: 'Baixa' },
        { value: 'medium', label: 'Média' },
        { value: 'high', label: 'Alta' },
        { value: 'critical', label: 'Crítica' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/servicos-publicos/capina',

  features: {
    hasProtocol: true,
    hasStatus: true,
    exportable: true,
  },
};

export const drainageRequestConfig: ModuleConfig = {
  key: 'drainage-request',
  departmentType: 'servicos-publicos',
  entityName: 'DrainageRequest',
  displayName: 'Desobstrução',
  displayNameSingular: 'Solicitação de Desobstrução',
  description: 'Solicitações de desobstrução de galerias e bueiros',
  icon: 'Droplet',
  color: 'blue',

  fields: [
    {
      name: 'requestorName',
      label: 'Nome do Solicitante',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'requestorCpf',
      label: 'CPF',
      type: 'text',
      required: true,
      placeholder: '000.000.000-00',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'location',
      label: 'Localização',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'address',
      label: 'Endereço Completo',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'problemType',
      label: 'Tipo de Problema',
      type: 'select',
      required: true,
      options: [
        { value: 'manhole', label: 'Bueiro Entupido' },
        { value: 'drain', label: 'Galeria Obstruída' },
        { value: 'gutter', label: 'Sarjeta Entupida' },
        { value: 'culvert', label: 'Canaleta Obstruída' },
        { value: 'other', label: 'Outro' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'severity',
      label: 'Gravidade',
      type: 'select',
      required: true,
      options: [
        { value: 'low', label: 'Baixa' },
        { value: 'medium', label: 'Média' },
        { value: 'high', label: 'Alta' },
        { value: 'critical', label: 'Crítica' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'waterLevel',
      label: 'Nível de Água',
      type: 'select',
      options: [
        { value: 'dry', label: 'Seco' },
        { value: 'low', label: 'Baixo' },
        { value: 'medium', label: 'Médio' },
        { value: 'high', label: 'Alto' },
        { value: 'flooding', label: 'Alagado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'affectedArea',
      label: 'Área Afetada (m²)',
      type: 'number',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'urgency',
      label: 'Urgência',
      type: 'select',
      required: true,
      options: [
        { value: 'low', label: 'Baixa' },
        { value: 'medium', label: 'Média' },
        { value: 'high', label: 'Alta' },
        { value: 'critical', label: 'Crítica' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'SCHEDULED', label: 'Agendado' },
        { value: 'IN_PROGRESS', label: 'Em Execução' },
        { value: 'COMPLETED', label: 'Concluído' },
        { value: 'CANCELLED', label: 'Cancelado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Solicitações',
      icon: 'Droplet',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'pending',
      label: 'Pendentes',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'inProgress',
      label: 'Em Execução',
      icon: 'Activity',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'completed',
      label: 'Concluídos',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'critical',
      label: 'Críticos',
      icon: 'AlertTriangle',
      color: 'red',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PENDING', label: 'Pendentes' },
        { value: 'SCHEDULED', label: 'Agendados' },
        { value: 'IN_PROGRESS', label: 'Em Execução' },
        { value: 'COMPLETED', label: 'Concluídos' },
        { value: 'CANCELLED', label: 'Cancelados' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'problemType',
      label: 'Tipo de Problema',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'manhole', label: 'Bueiro Entupido' },
        { value: 'drain', label: 'Galeria Obstruída' },
        { value: 'gutter', label: 'Sarjeta Entupida' },
        { value: 'culvert', label: 'Canaleta Obstruída' },
        { value: 'other', label: 'Outro' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/servicos-publicos/desobstrucao',

  features: {
    hasProtocol: true,
    hasStatus: true,
    exportable: true,
  },
};

export const treePruningRequestConfig: ModuleConfig = {
  key: 'tree-pruning-request',
  departmentType: 'servicos-publicos',
  entityName: 'TreePruningRequest',
  displayName: 'Poda de Árvores',
  displayNameSingular: 'Solicitação de Poda',
  description: 'Solicitações de poda e manejo de árvores',
  icon: 'TreePine',
  color: 'emerald',

  fields: [
    {
      name: 'requestorName',
      label: 'Nome do Solicitante',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'requestorCpf',
      label: 'CPF',
      type: 'text',
      required: true,
      placeholder: '000.000.000-00',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'location',
      label: 'Localização',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'address',
      label: 'Endereço Completo',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'treeSpecies',
      label: 'Espécie da Árvore',
      type: 'text',
      placeholder: 'Ex: Ipê, Jacarandá, Mangueira',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'treeHeight',
      label: 'Altura Aproximada (m)',
      type: 'number',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'pruningType',
      label: 'Tipo de Poda',
      type: 'select',
      required: true,
      options: [
        { value: 'light', label: 'Poda Leve' },
        { value: 'medium', label: 'Poda Média' },
        { value: 'heavy', label: 'Poda Pesada' },
        { value: 'removal', label: 'Remoção Total' },
        { value: 'emergency', label: 'Emergencial' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'reason',
      label: 'Motivo',
      type: 'select',
      required: true,
      options: [
        { value: 'wires', label: 'Interferência com Fios' },
        { value: 'building', label: 'Proximidade de Edificação' },
        { value: 'sick', label: 'Árvore Doente' },
        { value: 'risk', label: 'Risco de Queda' },
        { value: 'visibility', label: 'Obstrução de Visibilidade' },
        { value: 'other', label: 'Outro' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'riskLevel',
      label: 'Nível de Risco',
      type: 'select',
      required: true,
      options: [
        { value: 'low', label: 'Baixo' },
        { value: 'medium', label: 'Médio' },
        { value: 'high', label: 'Alto' },
        { value: 'critical', label: 'Crítico' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'EVALUATION', label: 'Em Avaliação' },
        { value: 'APPROVED', label: 'Aprovado' },
        { value: 'SCHEDULED', label: 'Agendado' },
        { value: 'IN_PROGRESS', label: 'Em Execução' },
        { value: 'COMPLETED', label: 'Concluído' },
        { value: 'REJECTED', label: 'Rejeitado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Solicitações',
      icon: 'TreePine',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'pending',
      label: 'Pendentes',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'inProgress',
      label: 'Em Execução',
      icon: 'Activity',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'completed',
      label: 'Concluídos',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'highRisk',
      label: 'Alto Risco',
      icon: 'AlertTriangle',
      color: 'red',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PENDING', label: 'Pendentes' },
        { value: 'EVALUATION', label: 'Em Avaliação' },
        { value: 'APPROVED', label: 'Aprovados' },
        { value: 'SCHEDULED', label: 'Agendados' },
        { value: 'IN_PROGRESS', label: 'Em Execução' },
        { value: 'COMPLETED', label: 'Concluídos' },
        { value: 'REJECTED', label: 'Rejeitados' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'riskLevel',
      label: 'Nível de Risco',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'low', label: 'Baixo' },
        { value: 'medium', label: 'Médio' },
        { value: 'high', label: 'Alto' },
        { value: 'critical', label: 'Crítico' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/servicos-publicos/poda',

  features: {
    hasProtocol: true,
    hasStatus: true,
    exportable: true,
  },
};

// Exportar todas as configurações de serviços públicos
export const servicosPublicosConfigs = {
  'public-service-requests': publicServiceRequestConfig,
  'street-lighting': streetLightingConfig,
  'special-collection': specialCollectionConfig,
  'cleaning-schedule': cleaningScheduleConfig,
  'team-schedule': teamScheduleConfig,
  'public-problem-report': publicProblemReportConfig,
  'weeding-request': weedingRequestConfig,
  'drainage-request': drainageRequestConfig,
  'tree-pruning-request': treePruningRequestConfig,
};
