/**
 * ============================================================================
 * MÓDULOS DE TURISMO - CONFIGURAÇÃO
 * ============================================================================
 */

import { ModuleConfig } from './types';

// 1. ATENDIMENTOS DE TURISMO
export const tourismAttendanceConfig: ModuleConfig = {
  key: 'tourism-attendance',
  entityName: 'TourismAttendance',
  departmentType: 'tourism',
  displayName: 'Atendimentos de Turismo',
  displayNameSingular: 'Atendimento',
  description: 'Atendimento e informações turísticas',
  icon: 'HeadphonesIcon',
  color: 'blue',

  fields: [
    {
      name: 'visitorName',
      label: 'Nome do Visitante',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'visitorEmail',
      label: 'E-mail',
      type: 'email',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'visitorPhone',
      label: 'Telefone',
      type: 'phone',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'origin',
      label: 'Origem',
      type: 'text',
      placeholder: 'Cidade/Estado/País',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'serviceType',
      label: 'Tipo de Serviço',
      type: 'select',
      required: true,
      options: [
        { value: 'INFORMATION', label: 'Informação Turística' },
        { value: 'COMPLAINT', label: 'Reclamação' },
        { value: 'SUGGESTION', label: 'Sugestão' },
        { value: 'GUIDE_REQUEST', label: 'Solicitação de Guia' },
        { value: 'EVENT_INFO', label: 'Informação de Evento' },
        { value: 'OTHER', label: 'Outro' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'subject',
      label: 'Assunto',
      type: 'text',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PENDING', label: 'Pendente' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'RESOLVED', label: 'Resolvido' },
        { value: 'CANCELLED', label: 'Cancelado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Atendimentos',
      icon: 'Users',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'pending',
      label: 'Pendentes',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'resolved',
      label: 'Resolvidos',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'thisMonth',
      label: 'Este Mês',
      icon: 'TrendingUp',
      color: 'purple',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PENDING', label: 'Pendentes' },
        { value: 'IN_PROGRESS', label: 'Em Andamento' },
        { value: 'RESOLVED', label: 'Resolvidos' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'serviceType',
      label: 'Tipo de Serviço',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'INFORMATION', label: 'Informação' },
        { value: 'COMPLAINT', label: 'Reclamação' },
        { value: 'SUGGESTION', label: 'Sugestão' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/turismo/atendimentos',

  features: {
    hasProtocol: true,
    hasSource: true,
    hasStatus: true,
    exportable: true,
    importable: false,
  },
};

// 2. ATRATIVOS TURÍSTICOS
export const touristAttractionConfig: ModuleConfig = {
  key: 'tourist-attractions',
  departmentType: 'turismo',
  entityName: 'TouristAttraction',
  displayName: 'Atrativos Turísticos',
  displayNameSingular: 'Atrativo Turístico',
  description: 'Pontos turísticos e atrativos da cidade',
  icon: 'MapPin',
  color: 'teal',

  fields: [
    {
      name: 'name',
      label: 'Nome do Atrativo',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'type',
      label: 'Tipo',
      type: 'select',
      required: true,
      options: [
        { value: 'CULTURAL', label: 'Cultural' },
        { value: 'NATURAL', label: 'Natural' },
        { value: 'HISTORICAL', label: 'Histórico' },
        { value: 'RELIGIOUS', label: 'Religioso' },
        { value: 'ENTERTAINMENT', label: 'Entretenimento' },
        { value: 'GASTRONOMIC', label: 'Gastronômico' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'category',
      label: 'Categoria',
      type: 'text',
      placeholder: 'Ex: Museu, Praça, Parque',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'address',
      label: 'Endereço',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'neighborhood',
      label: 'Bairro',
      type: 'text',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'openingHours',
      label: 'Horário de Funcionamento',
      type: 'text',
      placeholder: 'Ex: Seg-Sex 9h-17h',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'ticketPrice',
      label: 'Preço do Ingresso',
      type: 'number',
      placeholder: 'R$ 0,00',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'freeEntry',
      label: 'Entrada Gratuita',
      type: 'checkbox',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'isActive',
      label: 'Ativo',
      type: 'checkbox',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Atrativos',
      icon: 'MapPin',
      color: 'teal',
      format: 'number',
    },
    {
      key: 'active',
      label: 'Ativos',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'featured',
      label: 'Em Destaque',
      icon: 'Star',
      color: 'yellow',
      format: 'number',
    },
    {
      key: 'freeEntry',
      label: 'Entrada Gratuita',
      icon: 'DollarSign',
      color: 'blue',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'type',
      label: 'Tipo',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'CULTURAL', label: 'Cultural' },
        { value: 'NATURAL', label: 'Natural' },
        { value: 'HISTORICAL', label: 'Histórico' },
        { value: 'RELIGIOUS', label: 'Religioso' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'isActive',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'true', label: 'Ativos' },
        { value: 'false', label: 'Inativos' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/turismo/atrativos',

  features: {
    hasProtocol: true,
    hasSource: false,
    hasStatus: false,
    exportable: true,
    importable: true,
  },
};

// 3. ESTABELECIMENTOS TURÍSTICOS
export const localBusinessConfig: ModuleConfig = {
  key: 'local-businesses',
  departmentType: 'turismo',
  entityName: 'LocalBusiness',
  displayName: 'Estabelecimentos Turísticos',
  displayNameSingular: 'Estabelecimento',
  description: 'Hotéis, pousadas, restaurantes e comércio turístico',
  icon: 'Building',
  color: 'orange',

  fields: [
    {
      name: 'name',
      label: 'Nome do Estabelecimento',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'businessType',
      label: 'Tipo de Estabelecimento',
      type: 'select',
      required: true,
      options: [
        { value: 'HOTEL', label: 'Hotel' },
        { value: 'POUSADA', label: 'Pousada' },
        { value: 'RESTAURANT', label: 'Restaurante' },
        { value: 'BAR', label: 'Bar/Café' },
        { value: 'SHOP', label: 'Loja/Comércio' },
        { value: 'AGENCY', label: 'Agência de Turismo' },
        { value: 'OTHER', label: 'Outro' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'category',
      label: 'Categoria',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'address',
      label: 'Endereço',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'owner',
      label: 'Proprietário',
      type: 'text',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'ownerCpf',
      label: 'CPF do Proprietário',
      type: 'text',
      placeholder: '000.000.000-00',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'priceRange',
      label: 'Faixa de Preço',
      type: 'select',
      options: [
        { value: '$', label: '$ - Econômico' },
        { value: '$$', label: '$$ - Moderado' },
        { value: '$$$', label: '$$$ - Alto' },
        { value: '$$$$', label: '$$$$ - Premium' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'isTourismPartner',
      label: 'Parceiro de Turismo',
      type: 'checkbox',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'isActive',
      label: 'Ativo',
      type: 'checkbox',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Estabelecimentos',
      icon: 'Building',
      color: 'orange',
      format: 'number',
    },
    {
      key: 'partners',
      label: 'Parceiros',
      icon: 'Handshake',
      color: 'green',
      format: 'number',
    },
    {
      key: 'hotels',
      label: 'Hotéis/Pousadas',
      icon: 'Bed',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'restaurants',
      label: 'Restaurantes',
      icon: 'Utensils',
      color: 'red',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'businessType',
      label: 'Tipo',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'HOTEL', label: 'Hotel' },
        { value: 'POUSADA', label: 'Pousada' },
        { value: 'RESTAURANT', label: 'Restaurante' },
        { value: 'SHOP', label: 'Loja' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'isActive',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'true', label: 'Ativos' },
        { value: 'false', label: 'Inativos' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/turismo/estabelecimentos',

  features: {
    hasProtocol: true,
    hasSource: false,
    hasStatus: false,
    exportable: true,
    importable: true,
  },
};

// 4. GUIAS TURÍSTICOS
export const tourismGuideConfig: ModuleConfig = {
  key: 'tourism-guides',
  departmentType: 'turismo',
  entityName: 'TourismGuide',
  displayName: 'Guias Turísticos',
  displayNameSingular: 'Guia Turístico',
  description: 'Cadastro de guias turísticos credenciados',
  icon: 'User',
  color: 'indigo',

  fields: [
    {
      name: 'name',
      label: 'Nome Completo',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'cpf',
      label: 'CPF',
      type: 'text',
      required: true,
      placeholder: '000.000.000-00',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'email',
      label: 'E-mail',
      type: 'email',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'phone',
      label: 'Telefone',
      type: 'phone',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'licenseNumber',
      label: 'Número da Licença',
      type: 'text',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'licenseExpiry',
      label: 'Validade da Licença',
      type: 'date',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'experienceYears',
      label: 'Anos de Experiência',
      type: 'number',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'bio',
      label: 'Biografia',
      type: 'textarea',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'ACTIVE', label: 'Ativo' },
        { value: 'INACTIVE', label: 'Inativo' },
        { value: 'SUSPENDED', label: 'Suspenso' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'isActive',
      label: 'Ativo',
      type: 'checkbox',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Guias',
      icon: 'Users',
      color: 'indigo',
      format: 'number',
    },
    {
      key: 'active',
      label: 'Ativos',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'certified',
      label: 'Certificados',
      icon: 'Award',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'thisMonth',
      label: 'Cadastrados este Mês',
      icon: 'TrendingUp',
      color: 'purple',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'ACTIVE', label: 'Ativos' },
        { value: 'INACTIVE', label: 'Inativos' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/turismo/guias',

  features: {
    hasProtocol: true,
    hasSource: false,
    hasStatus: true,
    exportable: true,
    importable: true,
  },
};

// 5. PROGRAMAS TURÍSTICOS
export const tourismProgramConfig: ModuleConfig = {
  key: 'tourism-programs',
  departmentType: 'turismo',
  entityName: 'TourismProgram',
  displayName: 'Programas Turísticos',
  displayNameSingular: 'Programa Turístico',
  description: 'Programas e iniciativas de fomento ao turismo',
  icon: 'Calendar',
  color: 'violet',

  fields: [
    {
      name: 'name',
      label: 'Nome do Programa',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'programType',
      label: 'Tipo de Programa',
      type: 'select',
      required: true,
      options: [
        { value: 'PROMOTION', label: 'Promoção Turística' },
        { value: 'TRAINING', label: 'Capacitação' },
        { value: 'INFRASTRUCTURE', label: 'Infraestrutura' },
        { value: 'EVENT', label: 'Evento' },
        { value: 'PARTNERSHIP', label: 'Parceria' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'targetAudience',
      label: 'Público-Alvo',
      type: 'text',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'startDate',
      label: 'Data de Início',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'endDate',
      label: 'Data de Término',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'budget',
      label: 'Orçamento',
      type: 'number',
      placeholder: 'R$ 0,00',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'coordinator',
      label: 'Coordenador',
      type: 'text',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PLANNED', label: 'Planejado' },
        { value: 'ACTIVE', label: 'Em Andamento' },
        { value: 'COMPLETED', label: 'Concluído' },
        { value: 'CANCELLED', label: 'Cancelado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'isActive',
      label: 'Ativo',
      type: 'checkbox',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Programas',
      icon: 'Calendar',
      color: 'violet',
      format: 'number',
    },
    {
      key: 'active',
      label: 'Em Andamento',
      icon: 'Play',
      color: 'green',
      format: 'number',
    },
    {
      key: 'completed',
      label: 'Concluídos',
      icon: 'CheckCircle',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'planned',
      label: 'Planejados',
      icon: 'Clock',
      color: 'yellow',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'programType',
      label: 'Tipo',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PROMOTION', label: 'Promoção' },
        { value: 'TRAINING', label: 'Capacitação' },
        { value: 'EVENT', label: 'Evento' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PLANNED', label: 'Planejado' },
        { value: 'ACTIVE', label: 'Em Andamento' },
        { value: 'COMPLETED', label: 'Concluído' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/turismo/programas',

  features: {
    hasProtocol: true,
    hasSource: false,
    hasStatus: true,
    exportable: true,
    importable: false,
  },
};

// 6. ROTEIROS TURÍSTICOS
export const tourismRouteConfig: ModuleConfig = {
  key: 'tourism-routes',
  departmentType: 'turismo',
  entityName: 'TourismRoute',
  displayName: 'Roteiros Turísticos',
  displayNameSingular: 'Roteiro Turístico',
  description: 'Roteiros e circuitos turísticos',
  icon: 'Route',
  color: 'cyan',

  fields: [
    {
      name: 'name',
      label: 'Nome do Roteiro',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'routeType',
      label: 'Tipo de Roteiro',
      type: 'select',
      required: true,
      options: [
        { value: 'HISTORICAL', label: 'Histórico' },
        { value: 'CULTURAL', label: 'Cultural' },
        { value: 'NATURAL', label: 'Natural' },
        { value: 'RELIGIOUS', label: 'Religioso' },
        { value: 'GASTRONOMIC', label: 'Gastronômico' },
        { value: 'ADVENTURE', label: 'Aventura' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'duration',
      label: 'Duração',
      type: 'text',
      required: true,
      placeholder: 'Ex: 4 horas, 1 dia',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'difficulty',
      label: 'Dificuldade',
      type: 'select',
      required: true,
      options: [
        { value: 'EASY', label: 'Fácil' },
        { value: 'MODERATE', label: 'Moderado' },
        { value: 'HARD', label: 'Difícil' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'distance',
      label: 'Distância (km)',
      type: 'number',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'startPoint',
      label: 'Ponto de Partida',
      type: 'text',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'endPoint',
      label: 'Ponto de Chegada',
      type: 'text',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'estimatedCost',
      label: 'Custo Estimado',
      type: 'number',
      placeholder: 'R$ 0,00',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'guideRequired',
      label: 'Requer Guia',
      type: 'checkbox',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'isActive',
      label: 'Ativo',
      type: 'checkbox',
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Roteiros',
      icon: 'Route',
      color: 'cyan',
      format: 'number',
    },
    {
      key: 'active',
      label: 'Ativos',
      icon: 'CheckCircle',
      color: 'green',
      format: 'number',
    },
    {
      key: 'withGuide',
      label: 'Com Guia',
      icon: 'User',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'featured',
      label: 'Em Destaque',
      icon: 'Star',
      color: 'yellow',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'routeType',
      label: 'Tipo',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'HISTORICAL', label: 'Histórico' },
        { value: 'CULTURAL', label: 'Cultural' },
        { value: 'NATURAL', label: 'Natural' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'difficulty',
      label: 'Dificuldade',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'EASY', label: 'Fácil' },
        { value: 'MODERATE', label: 'Moderado' },
        { value: 'HARD', label: 'Difícil' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/turismo/roteiros',

  features: {
    hasProtocol: true,
    hasSource: false,
    hasStatus: false,
    exportable: true,
    importable: true,
  },
};

// 7. EVENTOS TURÍSTICOS
export const tourismEventConfig: ModuleConfig = {
  key: 'tourism-events',
  departmentType: 'turismo',
  entityName: 'TourismEvent',
  displayName: 'Eventos Turísticos',
  displayNameSingular: 'Evento Turístico',
  description: 'Eventos, festivais e atividades turísticas',
  icon: 'PartyPopper',
  color: 'pink',

  fields: [
    {
      name: 'name',
      label: 'Nome do Evento',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
      sortable: true,
      filterable: true,
    },
    {
      name: 'eventType',
      label: 'Tipo de Evento',
      type: 'select',
      required: true,
      options: [
        { value: 'FESTIVAL', label: 'Festival' },
        { value: 'FAIR', label: 'Feira' },
        { value: 'EXHIBITION', label: 'Exposição' },
        { value: 'CONCERT', label: 'Show/Concerto' },
        { value: 'SPORTS', label: 'Esportivo' },
        { value: 'CULTURAL', label: 'Cultural' },
        { value: 'RELIGIOUS', label: 'Religioso' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'venue',
      label: 'Local',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'address',
      label: 'Endereço',
      type: 'text',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'startDate',
      label: 'Data de Início',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'endDate',
      label: 'Data de Término',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'startTime',
      label: 'Hora de Início',
      type: 'time',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'organizer',
      label: 'Organizador',
      type: 'text',
      required: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'capacity',
      label: 'Capacidade',
      type: 'number',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'ticketPrice',
      label: 'Valor do Ingresso',
      type: 'number',
      placeholder: 'R$ 0,00',
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'freeEntry',
      label: 'Entrada Gratuita',
      type: 'checkbox',
      showInList: true,
      showInForm: true,
      showInDetails: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'PLANNED', label: 'Planejado' },
        { value: 'CONFIRMED', label: 'Confirmado' },
        { value: 'ONGOING', label: 'Em Andamento' },
        { value: 'COMPLETED', label: 'Concluído' },
        { value: 'CANCELLED', label: 'Cancelado' },
      ],
      showInList: true,
      showInForm: true,
      showInDetails: true,
      filterable: true,
    },
  ],

  stats: [
    {
      key: 'total',
      label: 'Total de Eventos',
      icon: 'Calendar',
      color: 'pink',
      format: 'number',
    },
    {
      key: 'upcoming',
      label: 'Próximos',
      icon: 'Clock',
      color: 'blue',
      format: 'number',
    },
    {
      key: 'ongoing',
      label: 'Em Andamento',
      icon: 'Play',
      color: 'green',
      format: 'number',
    },
    {
      key: 'thisMonth',
      label: 'Este Mês',
      icon: 'TrendingUp',
      color: 'purple',
      format: 'number',
    },
  ],

  filters: [
    {
      key: 'eventType',
      label: 'Tipo',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'FESTIVAL', label: 'Festival' },
        { value: 'FAIR', label: 'Feira' },
        { value: 'CULTURAL', label: 'Cultural' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'all', label: 'Todos' },
        { value: 'PLANNED', label: 'Planejado' },
        { value: 'CONFIRMED', label: 'Confirmado' },
        { value: 'COMPLETED', label: 'Concluído' },
      ],
      defaultValue: 'all',
    },
    {
      key: 'search',
      label: 'Buscar',
      type: 'text',
    },
  ],

  apiEndpoint: '/api/admin/secretarias/turismo/eventos',

  features: {
    hasProtocol: true,
    hasSource: false,
    hasStatus: true,
    exportable: true,
    importable: true,
  },
};

// EXPORT ALL CONFIGS
export const configsTurismo = {
  attendance: tourismAttendanceConfig,
  attractions: touristAttractionConfig,
  businesses: localBusinessConfig,
  guides: tourismGuideConfig,
  programs: tourismProgramConfig,
  routes: tourismRouteConfig,
  events: tourismEventConfig,
};
